### ISSUE TITLE
add logic to restart excavator if OC memory issue

### ISSUE THREAD

**Issue by Dreunit1986** [nicehash/NiceHashQuickMiner#1]
add logic to restart excavator if OC memory issue

currently a message appears saying DAG memory issue is OC too high... it would be good to get a user alert if this occurs...

**Comment by nicehashdev** [comment]
Restart should happen, because then device does not mine and speed falls to zero which is trigger for action.

Check this out: https://github.com/nicehash/NiceHashQuickMiner/wiki/Tips-&-tricks#3-define-what-happens-when-something-goes-wrong

You need to define what QuickMiner should do.

**Comment by violinmaker** [comment]
![image](https://user-images.githubusercontent.com/63171683/107845074-f929b600-6de9-11eb-93f8-99fc100bccfb.jpeg) 

Hi I recive core I  Decive #0-0 error! 

1080ti help please

**Comment by newshate** [comment]
аналогично ,1080
