### ISSUE TITLE
Cannot connect: /cuda_devices     - Can anyone help, tell me what is the problem?

### ISSUE THREAD

**Issue by dictatore** [nicehash/NiceHashQuickMiner#10]
Excavator crashes, turns on every 3-5 seconds and turns off immediately,in Octune shows this - Cannot connect: / cuda_devices.
[log_2021-02-12_23-40-00.000.log](https://github.com/nicehash/NiceHashQuickMiner/files/5974420/log_2021-02-12_23-40-00.000.log)
[log_2021-02-12_23-41-14.000.log](https://github.com/nicehash/NiceHashQuickMiner/files/5974421/log_2021-02-12_23-41-14.000.log)
[log_2021-02-12_23-41-20.000.log](https://github.com/nicehash/NiceHashQuickMiner/files/5974422/log_2021-02-12_23-41-20.000.log)
[log_2021-02-12_23-41-26.000.log](https://github.com/nicehash/NiceHashQuickMiner/files/5974423/log_2021-02-12_23-41-26.000.log)
[log_2021-02-12_23-41-32.000.log](https://github.com/nicehash/NiceHashQuickMiner/files/5974424/log_2021-02-12_23-41-32.000.log)
[log_2021-02-12_23-41-38.000.log](https://github.com/nicehash/NiceHashQuickMiner/files/5974425/log_2021-02-12_23-41-38.000.log)
[log_2021-02-12_23-41-44.000.log](https://github.com/nicehash/NiceHashQuickMiner/files/5974426/log_2021-02-12_23-41-44.000.log)
[log_2021-02-12_23-41-50.000.log](https://github.com/nicehash/NiceHashQuickMiner/files/5974427/log_2021-02-12_23-41-50.000.log)
[log_2021-02-12_23-41-56.000.log](https://github.com/nicehash/NiceHashQuickMiner/files/5974428/log_2021-02-12_23-41-56.000.log)
[log_2021-02-12_23-42-03.000.log](https://github.com/nicehash/NiceHashQuickMiner/files/5974429/log_2021-02-12_23-42-03.000.log)
[log_2021-02-12_23-42-09.000.log](https://github.com/nicehash/NiceHashQuickMiner/files/5974430/log_2021-02-12_23-42-09.000.log)
[log_2021-02-12_23-42-15.000.log](https://github.com/nicehash/NiceHashQuickMiner/files/5974431/log_2021-02-12_23-42-15.000.log)
[log_2021-02-12_23-42-21.000.log](https://github.com/nicehash/NiceHashQuickMiner/files/5974433/log_2021-02-12_23-42-21.000.log)

**Comment by nicehashdev** [comment]
Looks like you have issue with Excavator crashing after method `quickminer.devices` is called. Can you provide me:

- Your hardware (detailed, motherboard, CPU, GPUs)
- Your OS and version
- NVIDIA drivers version installed

**Comment by dictatore** [comment]
Intel Core i7-7700K 
 Asus PCI-Ex GeForce GTX 1080 ROG Strix 8GB GDDR5X (256bit) - 1
 Asus Strix Z270H Gaming
 HyperX DDR4-3000 16384MB
 Samsung 960 Evo series 250GB M.2 PCIe 3.0
 Western Digital Green SSD 120GB M.2 2280 SATAIII TLC
 Windows 10 pro 64 bit

 NVIDIA driver version installed - 461.40

**Comment by nicehashdev** [comment]
Is this working for you: http://www.nicehash.com/quick-miner ?

**Comment by nicehashdev** [comment]
And another question; perhaps you had an AMD GPU before and you did not reinstall Windows after upgrading to NVIDIA card?

**Comment by dictatore** [comment]
> Is this working for you: http://www.nicehash.com/quick-miner ?

unfortunately not - the frequency of starting and stopping the excavator has increased

**Comment by dictatore** [comment]
> And another question; perhaps you had an AMD GPU before and you did not reinstall Windows after upgrading to NVIDIA card?

No.I assembled a PC from new components, initially this assembly was assembled from such components and nothing has changed. Perhaps reinstalling Windows will help, I hope. Since there are two more users on this PC, and perhaps they installed something that interferes with the work.

**Comment by stepobiz** [comment]
I have same problem
3 X Nvidia 1050 ti
