### ISSUE TITLE
Hiden two Console automatic

### ISSUE THREAD

**Issue by Riones** [nicehash/NiceHashQuickMiner#100]
Hi.
I put Hiden mining console, true.
But, When start, just hidden the excavator. 
Its possible to Hide the Console " Nice hash quick miner 0.3.2.6" too?
In resume, Hiden two console, and not just One.

Thanks you.
Best regards.

**Comment by nicehashdev** [comment]
No. Why would you like that? This feature will never be available because then botnetters would use NiceHash QuickMiner.

**Comment by Riones** [comment]
But if I close this console, they are minning normaly? Or its not a good idea to do that?

I ask hidden two console, because, on my PC, my wife works sometimes on PC. So If Don't see nothing Opened, they Don't close for mystake... Or something like that...

**Comment by jameslmoser** [comment]
I would prefer to have the ability to show the consoles through the tray icon/menu but hide them when minimized again.  Right now it seems like its one option to hide them and that is it, unless you edit the config and restart.

**Comment by nicehashdev** [comment]
Like I said, there is no intention to hide everything because it would just make it simple to use on botnets, which WE DO NOT ALLOW! Closing.
