### ISSUE TITLE
3 Fan Control?

### ISSUE THREAD

**Issue by DroptheHammer** [nicehash/NiceHashQuickMiner#102]
I have an EVGA FTW3 card and OC Tuner seems to only affect 2 of the fans (similar to MSI Afterburner).  Is there any way it can alter all 3 fans and display all 3 fans to the UI?  That way I dont need to start mining and then go put the 3rd fan at the desired RPM in EVGA Precision.

Thanks.

**Comment by nicehashdev** [comment]
I am in fact developing with various EVGA cards. The method for adjusting and measuring fans is different than what Precision X1 uses and it in fact adjusts speed of all fans not only one or two. Check and you will see that all of your fans are spinning with the same speed.

**Comment by nicehashdev** [comment]
Issue fixed. Closing.
