### ISSUE TITLE
Separate fan & temp control while in Game Mode

### ISSUE THREAD

**Issue by Jaksonas** [nicehash/NiceHashQuickMiner#103]
Hello,

Would it be possible to add separate fan & temp control in Game Mode, because mining temps are totally different and while gaming the fans spin at unreasonably high speeds, because core clock temps, which are set with OCTune for mining, are quickly reached. So right now the solution is to open MSI afterburner, reconfigure fans before gaming, then, after finishing gaming, close afterburner, reenable OCTune fans. It is tedious work to do everytime.

Or am I missing something and there is a way to do all this fan control more smoothly?

I hope I have explained my request understandably. 

Thanks

**Comment by nicehashdev** [comment]
I will think about some good solution for that.

**Comment by nicehashdev** [comment]
You can manually adjust many parameters. It is true that Optimize modes in Rig Manager have fixed values, but you can copy them and modify for yourself to suits your needs. Additionally, you can also tune advanced parameters of SmartFan algorithm (you should modify commands.json file and call this method at the beginning, when Excavator starts up): https://github.com/nicehash/excavator/tree/master/api#device-smartfan-set-advanced

Is perhaps there something more that would be needed?

**Comment by Jaksonas** [comment]
> 
> 
> You can manually adjust many parameters. It is true that Optimize modes in Rig Manager have fixed values, but you can copy them and modify for yourself to suits your needs. Additionally, you can also tune advanced parameters of SmartFan algorithm (you should modify commands.json file and call this method at the beginning, when Excavator starts up): https://github.com/nicehash/excavator/tree/master/api#device-smartfan-set-advanced
> 
> Is perhaps there something more that would be needed?

**Comment by Jaksonas** [comment]
I must say, that I have zero knowledge in programming, so this is not a solution for me... I understand very little of what I've read, when I've opened the commands.json file.

How would I copy and modify the optimization modes in Rig Manager?

Sorry for my incompetence in this field.:)

A setting to control this, like in Game Mode, would be much appreciated!

**Comment by yosoyalguien** [comment]
Hi, I did something similar to this so I hope it works for you.
in nicehash.com go to rig manager and leave it on high or medium, then go to the quickmine folder in the commands file and look for the event "on_quickminer.start", in where it says "commands" paste the following " 
[{
				"id": 1,
				"method": "device.smartfan.set",
				"params": ["0", "1", "50"]
			}]"
(1 means fixed speed and the 50 means the speed in %, when it starts to mine the fans spin at 50%, you can change this to your liking)
and in the "on_quickminer.stop" event paste this:
 [{
				"id": 1,
				"method": "devices.smartfan.reset",
				"params": []
			}]
this resets the settings when you stop mining, it will leave it default which should be the automatic fan mode
It should look something like this:
![image](https://user-images.githubusercontent.com/79892442/109600993-e3600480-7afc-11eb-900d-86f7424e6256.png)

I hope it works for you

**Comment by Swiftnc** [comment]
If QuickMiner is not resetting to the default fan curve on starting game mode, it should.

**Comment by nicehashdev** [comment]
Version 0.4.0.1 has option to set default/automatic fan curve when you activate Game Mode. This should help you a bit at least.

**Comment by Swiftnc** [comment]
That appears to work great!  Thanks!

**Comment by Jaksonas** [comment]
Yes, default/ automatic fan curve is great, but I do not use a default fan curve for my GPU. I'd still like to see a custom fan control setting in Game Mode, one like in Afterburner, where you pinpoint dots on certain values of X and Y - temperature and fan speed. It does need to be like a graph necessarily, it would just be enough and very convenient to insert certain fan speed values in spaces named 'at temp. X, fan speed will be Y'.

Thank you!

**Comment by renzska** [comment]
I'd like to see something similar as @Jaksonas mentioned. My EVGA XC3 Ultra default fan curve is bad and would prefer to set something like the X1 Precision Quiet or Stealth Fan Curve options when enabling Game Mode with NiceHash QuickMiner. Thanks for your work on this!

**Comment by renzska** [comment]
Honestly, when gaming, I can guarantee my temps at a certain fan speed so, I'd take an option for setting the fan speed in gaming mode.
