### ISSUE TITLE
v0.3.2.6 miner reports ~0.5-1mhs less vs v0.3.0.2

### ISSUE THREAD

**Issue by T5-R** [nicehash/NiceHashQuickMiner#104]
I have issues with version v0.3.0.2 where it crashes my system most of the time when I try to exit the Program. Stop->exit more often than not freezes the system
Updated to v0.3.2.6, but here excavator reports about 0.5-1mhs less per card with the exact same settings as used in v0.3.0.2
I was able to stop and exit the new version, but when I tried to start it up again the system froze again.

I am using an amd 2400g win10 (and have disabled the igpu and reinstalled nv drivers since I thought that might be causing issues)
2x 1660s

Just thought I report it in case it is helpful. Probably just a difference in how it is displayed in excavator?

**Comment by Vithujap** [comment]
My systems have also been freezing lately after i updated the software. Also the hashpower is less compared to before

**Comment by nicehashdev** [comment]
Let me know exactly what hardware you use regarding speed.

When it comes to freezes, I need more information. Enable logs and provide full logging.

**Comment by nicehashdev** [comment]
No response. Closing.
