### ISSUE TITLE
Power consumption back to factory default

### ISSUE THREAD

**Issue by richardcool** [nicehash/NiceHashQuickMiner#105]
I have a EVGA ftw3 3080 and and GTX 1060 and use the recommended OC settings from https://www.nicehash.com/blog/post/nvidia-and-amd-graphics-card-oc-settings-for-mining

Power limit for 3080 & 1060 was set to 220w and 80w respectively. 

Upgraded to 0.3.2.6 stable release last night and everything was fine until this morning when excavator windows showed the GPUs are using 380w & 120w instead

Somehow In Octune the setting are back to 380/120w too (the actual command line file says 220/80w though). Tried to set the value to 220/80w but the GPUs are still running at 380/120w.

Downgraded to 0.3.2.5 and everything is back to normal.

**Comment by nicehashdev** [comment]
Either your driver crashed or you had another tool messing with OC settings. It is very recommended to not use any other OC tool because the results are unpredictable.

**Comment by richardcool** [comment]
No I don't have any other OC tool.

**Comment by fw88** [comment]
I'm not sure if my problem is related. Using 0.3.2.6, woke up this morning and my mem OC dropped from 1250 to 1150 and fan curve went from fixed to dynamic. This didn't happen with the previous stable version. I'm not using any other OC tools.

**Comment by nicehashdev** [comment]
Version 0.3.2.5 is not different from 0.3.2.6 regarding that. I would really suggest you to double check for other OC tools which may modify your clocks. Alternative you can enable full logging and provide me the logs of Excavator.

**Comment by richardcool** [comment]
Thanks a lot for the suggestion.

I went back to 0.3.2.6 stable because the same problem occurred even with 0.3.2.5 RC.

My PC is Alienware and thus there might be some Alienware service in the background messing with the Power Setting from time to time. With full logging enabled I will disable some of these services one by one to see if it helps.

**Comment by richardcool** [comment]
Ok it turns out the GPU Power Setting is reset to factory default whenever someone else logon windows...

I suspect this might be something done by the Nvidia driver/Control Panel etc..

**Comment by nicehashdev** [comment]
Okay, issue fixed. Closing.
