### ISSUE TITLE
I deleted the software, due to some reasons. Then when i tried to download it again, it wont let me. 

### ISSUE THREAD

**Issue by Vithujap** [nicehash/NiceHashQuickMiner#106]
Even though i deleted all files from my computer in regards to nicehash quick miner. Later on i decided to redownload the software, but then i get an error message like u can see in the picture down below. 

![image](https://user-images.githubusercontent.com/73892808/109041088-f4f57680-76ce-11eb-8805-66bd8f9558f7.png)

**Comment by Vithujap** [comment]
Looks like even though i uninstalled it, it remained on my system. And i cant press uninstall

![image](https://user-images.githubusercontent.com/73892808/109041576-7947f980-76cf-11eb-8860-ebcc188fc947.png)

**Comment by nicehashdev** [comment]
If you delete files manually then you have to also delete registry keys manually. If you do not know how to do that, I suggest to simply download .zip package of the miner and put it in the same folder. Then the uninstall will work correctly and you can remove it through Windows Uninstall.

**Comment by nicehashdev** [comment]
I will make improvement regarding this issue in the next version. It is on TODO list.
