### ISSUE TITLE
Running AutoOC on Water Cooled 3080 - No fans connected

### ISSUE THREAD

**Issue by DustoMan** [nicehash/NiceHashQuickMiner#107]
My brother's computer is having a problem running the AutoOC tool on this latest stable version (0.3.2.6). We both have the same video card, EVGA 3080 FTW3. Mine still has the stock air cooler but his has a water block on it with no fans connected to the fan headers.  Latest Standard Nvidia driver (ver 461.40), freshly re-installed with DDU, same version of Windows 10. I can run the tool and I get a core clock speed around 1200Mhz and normal power consumption around 200W. When he runs it, his card's clocks won't go much higher than 480-500Mhz and the power is only 90W. We tried a couple different experiments seeing if it would make any difference. Tried resetting the overclock settings on the AutoOC page. Didn't seem to make any difference. The only way to get the system to run at decent speeds is to have EVGA precision X (ver1.1.7) open and set the power limit to what we would want it. My question is does the AutoOC tool take fan speed into account when trying clocks and setting power? I'm wondering if since the tool isn't getting feedback from the fans, it's assuming there's no cooling at all and only low powering the card to protect it. 

![AutoOC Settings](https://user-images.githubusercontent.com/24239025/109058264-666dfe80-76a8-11eb-89f2-e38d0ca8a13c.jpg)
[AutoOC Log.txt](https://github.com/nicehash/NiceHashQuickMiner/files/6038534/AutoOC.Log.txt)

**Comment by nicehashdev** [comment]
It looks like you the miner was not mining? When you perform Autotune, your card must be in mining state.

**Comment by DustoMan** [comment]
The miner is running. So he retested some more and found that if he sets the radio button to SPEED then the power usage ramps up like normal. When the radio button is set to EFFECIENT then the power usage is way low.
[OC Autotune - SPEED  - log.txt](https://github.com/nicehash/NiceHashQuickMiner/files/6046541/OC.Autotune.-.SPEED.-.log.txt)
[OC Autotune - EFFICIENCY  - log.txt](https://github.com/nicehash/NiceHashQuickMiner/files/6046542/OC.Autotune.-.EFFICIENCY.-.log.txt)

**Comment by nicehashdev** [comment]
The logs you've just shown are completely normal. It is visible that the logs you provided before - miner was not working and thus the results were not correct. What exactly is the issue here now?

The algorithm has detected, that the most efficient mining mode is at clock 510 because of this:
> 25/2021, 5:40:40 PM] kt.umed: 79290 us,  clock: 480MHz,  pwr: 117.18W,  eff: 0.10763115 ke/J,  heff: 539.61kH/J

You can try it on your own and see what kind of efficiency you get. If it is not good, then set high starting core clock limit so the algorithm will ignore this low value.

**Comment by DustoMan** [comment]
Ok we'll adjust the starting clock so it doesn't start out so low.
