### ISSUE TITLE
Erro Drivers

### ISSUE THREAD

**Issue by derekchsantos** [nicehash/NiceHashQuickMiner#109]
Hi!

When executing the .exe it gives an error, follow the evidence below;

![drivers](https://user-images.githubusercontent.com/48655103/109161497-e30ae680-7755-11eb-9098-30d177360fc2.PNG)

Help me?

**Comment by nicehashdev** [comment]
Do you have NVIDIA card? If you do, then you can run it only on Windows 10 x64.

**Comment by nicehashdev** [comment]
Issue fixed. Closing.

**Comment by derekchsantos** [comment]
I don't have the NVIDIA card but I get it. Thanks!
