### ISSUE TITLE
status of mining rig is ''unknown''

### ISSUE THREAD

**Issue by daimonkori** [nicehash/NiceHashQuickMiner#111]
Good day. I cannot see my rig status from the website or from my android app . It shows me the H\S rate but says Rig Status Unknown . From the log files I found this error

[[2021-02-26 02:29:34.110822] [thread=0x000029e0] [trace]]

	Response: {"id":1,"error":null}

How can I fix it ?out of 26 workers, the problem periodically appears only on 2. Thanks in advance

**Comment by nicehashdev** [comment]
Which version are you using? Please, activate full logging and provide me logs from folder `nhqm_logs` (edit out your BTC address).

**Comment by daimonkori** [comment]
NHQM_v0.3.2.6
Excavator_v1.6.3g_Build_642
[log_2021-02-26_02-28-17.001.log](https://github.com/nicehash/NiceHashQuickMiner/files/6046011/log_2021-02-26_02-28-17.001.log)

**Comment by nicehashdev** [comment]
You have supplied wrong logs, I need logs that you can find in folder `nhqm_logs`.

**Comment by daimonkori** [comment]
sorry, but I don't have such a folder .. there is only "archived_logs"

**Comment by nicehashdev** [comment]
Make sure you fully enable logging. After you make a change, you need to restart NiceHash QuickMiner.

**Comment by daimonkori** [comment]
[log.txt](https://github.com/nicehash/NiceHashQuickMiner/files/6046159/log.txt)

**Comment by daimonkori** [comment]
[log.txt](https://github.com/nicehash/NiceHashQuickMiner/files/6046161/log.txt)

**Comment by nicehashdev** [comment]
It looks like Excavator crashes right after it is launched. Can you check what is the status of Excavator? What is happening with it?

**Comment by daimonkori** [comment]
[log.txt](https://github.com/nicehash/NiceHashQuickMiner/files/6046193/log.txt)
![Безымянный](https://user-images.githubusercontent.com/79622605/109230417-ad620e00-77e6-11eb-9783-7a5be5dc718f.jpg)

**Comment by nicehashdev** [comment]
Use this:
[NHQM_test.zip](https://github.com/nicehash/NiceHashQuickMiner/files/6046321/NHQM_test.zip)

And then set following value in nhqm.conf
"watchDogAPITimeout":2000

To something higher, like 5000 for example. What happens then?

**Comment by daimonkori** [comment]
it only got worse
[log.txt](https://github.com/nicehash/NiceHashQuickMiner/files/6047485/log.txt)

**Comment by daimonkori** [comment]
it only got worse
[log.txt](https://github.com/nicehash/NiceHashQuickMiner/files/6047505/log.txt)

**Comment by daimonkori** [comment]
I used various "watchDogAPITimeout" parameters such as 1000, 2000, 10000, run with administrative privileges, changed network settings (gateway) and also added a route to 172.65.216.96 - nothing helped

**Comment by AnimaUmbra** [comment]
Have the same issue, with this in the logs, in loop:

[2021-02-27 09:58:45:784] [INFO] [watchdog] Starting/stopping with: /quickstart?id=3BGLmoh755smdAhnum9Q9cjPDsfnib3co8$0-evEyWWIIMEOQuHWpPJ7iLg&loc=usa-east&ip=172.65.202.202
[2021-02-27 09:58:47:808] [WARNING] [watchdog] Quick start/stop err: Object reference not set to an instance of an object.

**Comment by daimonkori** [comment]
please ignore this, this error occurs when I restart the miner to enable the log.

**Comment by nicehashdev** [comment]
> Have the same issue, with this in the logs, in loop:
> 
> [2021-02-27 09:58:45:784] [INFO] [watchdog] Starting/stopping with: /quickstart?id=3BGLmoh755smdAhnum9Q9cjPDsfnib3co8$0-evEyWWIIMEOQuHWpPJ7iLg&loc=usa-east&ip=172.65.202.202
> [2021-02-27 09:58:47:808] [WARNING] [watchdog] Quick start/stop err: Object reference not set to an instance of an object.

This is not the same problem, but completely different, please, open a new ticket regarding this issue.

**Comment by daimonkori** [comment]
my problem is still active, can you recommend something else or should I close the request?

**Comment by nicehashdev** [comment]
Looks like you have issues with stability when memory is high - you cannot use Medium optimisation. You can either use Lite or make your own OC using OCTune.
