### ISSUE TITLE
Ошибка DLL Cabinet.dll

### ISSUE THREAD

**Issue by stopbtc** [nicehash/NiceHashQuickMiner#113]
При запуске ошибка excavator.exe ПОярдковый номер 40 не найден в библиотеке DLL Cabinet.dll

**Comment by daimonkori** [comment]
use windows 10 x64

**Comment by stopbtc** [comment]
жаль. У меня Windows 7

**Comment by nicehashdev** [comment]
NiceHash QuickMiner only works on Windows 10 x64.
