### ISSUE TITLE
Add accepted/min and rejected/overall

### ISSUE THREAD

**Issue by ben1628** [nicehash/NiceHashQuickMiner#114]
Some of the mining program provides 

accepted shares/min
rejected shares/min
rejected shares/overall

Those are very helpful to help us to manage our mining better, and give us a sense of how well it has been performed.  If we get too many rejected, we may want to adjust our settings etc.

Overall, it's been great.

**Comment by nicehashdev** [comment]
There is no need that, because you have full detailed charts on NiceHash Rig Manager which contain all the important information you need. Please, read this: https://github.com/nicehash/NiceHashQuickMiner/wiki/Hashing-speed,-accepted-rejected-speed-and-shares
