### ISSUE TITLE
feature request: minimum fan speed

### ISSUE THREAD

**Issue by bredita** [nicehash/NiceHashQuickMiner#117]
When doing automatic fan speed based on temps the fan speed varies a lot. This is a bit unpleasant to listen to when I am using my computer.

The "problem" is that it ramps down to a too low fan speed when it has "cooled down" the card and the temps are OK, and then it gets hot again and ramps back up, and then this repeats forever.

If you add a minimum fan speed option it would be possible to set the minimum fan speed to a "comfortable" noise level that usually keeps temps reasonable, and not having it ramp up/down as much.

**Comment by nicehashdev** [comment]
This issue has already been fixed: https://github.com/nicehash/NiceHashQuickMiner/issues/89
