### ISSUE TITLE
Quick Miner stops running

### ISSUE THREAD

**Issue by mefe-tr** [nicehash/NiceHashQuickMiner#118]
I start quickMiner and it starts to minning. After about an hour, it stops to minning and a start button is showed on the quickminer screen. Also CPU minning stops too after during sometimes half sometimes an hour later.
I use CPU - Ryzen9-3900 and GPU - GTX 1660Ti. 
Please help me,

**Comment by nicehashdev** [comment]
You will have to provide me detailed logs to figure that one out. Please enable full logging and then upload them here with your BTC information removed.

**Comment by mefe-tr** [comment]
OK. I opened it now. When the quickMiner stop, I will upload here.

**Comment by mefe-tr** [comment]
[archived_logs.zip](https://github.com/nicehash/NiceHashQuickMiner/files/6054609/archived_logs.zip)
there is log files about quickMiner stops to run

**Comment by mefe-tr** [comment]
[archived_logs_1853.zip](https://github.com/nicehash/NiceHashQuickMiner/files/6054848/archived_logs_1853.zip)
This is the second error about quickMiner stopping

**Comment by mefe-tr** [comment]
[log_2021-02-27_18-45-41.009.log](https://github.com/nicehash/NiceHashQuickMiner/files/6054881/log_2021-02-27_18-45-41.009.log)
this is the third

**Comment by nicehashdev** [comment]
Please, do NOT use www.nicehash.com/quick-miner

The source of your issues is that you use this webpage, which will close/stop your miner if you close that webpage. Just use Rig manager and manage your rig from there.
