### ISSUE TITLE
AutoTune fan speed issue

### ISSUE THREAD

**Issue by Anatharias** [nicehash/NiceHashQuickMiner#12]
Hello, while Autotune in version 3.0.6 (OCTune RC2) sets the fans at 100% at the beginning of the test, then for no reason, fans are set to auto, so during the test memory junction was at 104° on my EVGA 3080 FTW3
I had - mid test, to launch Afterburner to set fans to 100%

**Comment by nicehashdev** [comment]
Did you update OCTune to the latest version that was posted after 3.0.6 RC?

https://github.com/nicehash/NiceHashQuickMiner/releases/download/v0.3.0.6_RC/octune_0.3.0.6_RC_fix2.zip

**Comment by TerryFrench** [comment]
With 3.0.7, should we re-run octune? I have the same problem. 
Also the documentation to use the USA vs Europe region was missing. 

`"serviceLocation":1,`
is what is needed to use USA.

**Comment by nicehashdev** [comment]
You have it here: https://github.com/nicehash/NiceHashQuickMiner/wiki/Tips-&-tricks#1-choose-your-service-location-to-improve-your-latency-and-reduce-number-of-stale-shares

What exactly is your issue now? Because a lot has changed regarding fan adjusting fan speeds.

**Comment by TerryFrench** [comment]
octune from 3.0.7let me get the fan settings I want. So I'm good with that. 
Same for the service location (I did find it but somehow missed in the tips and tricks)
thanks
