### ISSUE TITLE
I get error 

### ISSUE THREAD

**Issue by LudoviKush** [nicehash/NiceHashQuickMiner#120]
I already updated the drivers in GeForce Experience.

I've read here that all the hardware that supports cuda 5.0 should work.
https://www.nicehash.com/support/mining-help/general-help/is-my-hardware-supported

Do you have any idea?

**Comment by nicehashdev** [comment]
Supported hardware for NiceHash QuickMiner is listed here: https://github.com/nicehash/NiceHashQuickMiner/wiki/Supported-hardware
