### ISSUE TITLE
CPU Performance Is Different Between Rig Manager And Quick Miner

### ISSUE THREAD

**Issue by mefe-tr** [nicehash/NiceHashQuickMiner#122]
Hi,
When I start CPU mining on https://www.nicehash.com/quick-miner site, the CPU performance is 100%. But when I start CPU mining on https://www.nicehash.com/my/mining/rigs/ site, the CPU performance is 50%. 

How can I increase CPU performance on rig maneger site? Is there any settings for this?

**Comment by nicehashdev** [comment]
Answer is here: https://github.com/nicehash/NiceHashQuickMiner/wiki/FAQ#-6-how-can-i-limit-cpu-mining-to-less-coresload
