### ISSUE TITLE
Moving to QM from NH Miner Generates a new Rig in Rig Manager

### ISSUE THREAD

**Issue by uniqueacid** [nicehash/NiceHashQuickMiner#123]
While not necessarily a bug, changing mining setups generates "new" Rigs in Rig Manager. It would be appreciated to be able to "link" a rigs existing ID to a fresh install in QM. This allows for a preserved history and continuity of log data, without having to delete a depreciated "rig". And / Or the ability to merge "offline" depreciated rigs history with the "new" online Rig. Alternatively, the ability to hide or archive a rig, without loosing data history, could also solve the issue of offline rigs in Rig Manager.

**Comment by nicehashdev** [comment]
This is an known issue that was already opened. There is no fix and it is a low priority bug.
