### ISSUE TITLE
Unable to find an entry point name 'nvmllnitWithFlags' in DLL 'nvml'.

### ISSUE THREAD

**Issue by JacobWardCoding** [nicehash/NiceHashQuickMiner#124]
Hi All,

I have just installed NiceHashQuickMiner, and keep on getting this error when I open it.

"_Unable to find an entry point name 'nvmllnitWithFlags' in DLL 'nvml'._"

Note: I have tried running both the installer and the source code, both of the yield the same results.

Help would be appreciated ASAP. Thanks

**Comment by nicehashdev** [comment]
Please, reinstall your NVIDIA drivers the latest version.

**Comment by Guti1989** [comment]
![Captura de pantalla 2021-03-03 002606](https://user-images.githubusercontent.com/78506615/109728731-123ab100-7bb7-11eb-8732-4a442f2363d7.png)

A mi no me deja proceder abrirla. He descargado la ultima version y me da el siguiente error al abrirla , como pueden ver en la imagen que adjunto.

**Comment by nicehashdev** [comment]
I do not speak Spanish? is it? Sorry.

When you get this error, you need to update drivers. If your drivers are latest version, then your GPU is not supported, check list of supported hardware here: https://github.com/nicehash/NiceHashQuickMiner/wiki/Supported-hardware
