### ISSUE TITLE
Reinstallation error

### ISSUE THREAD

**Issue by C64S** [nicehash/NiceHashQuickMiner#126]
After Norton LifeLock removed the program and I deleted the application folder, the installer still says QuickMiner is installed.
![QuickMiner Error](https://user-images.githubusercontent.com/58891228/109589505-6884f280-7ad8-11eb-8cd8-789ba97c3bf7.png)

**Comment by Slundar** [comment]
I'm experiencing the same issue.

**Comment by nicehashdev** [comment]
This is fixed in next version already but it is not stable version yet. For now, you can bypass this issue by downloading .zip file.
