### ISSUE TITLE
Command line controls?

### ISSUE THREAD

**Issue by mwmoseley** [nicehash/NiceHashQuickMiner#127]
Would it be possible to get some command line controls set up for quick miner? Specifically, I'm looking to enable/disable game mode via script. Assuming this can be done, I'd also like to suggest that the popup that shows whenever game mode is enabled and disabled *not* be shown when using the command line controls so they don't have to be cleared manually.

**Comment by nicehashdev** [comment]
Suggest you to check out https://github.com/nicehash/excavator

QuickMiner is nothing but wrapper around Excavator, which has many commanding options (command file, TCP API, HTTP API). I haven't had time to keep up with all the latest documentation regarding API, but you can figure a lot of parts out if you analyze logs and inspect OCTune js code.

**Comment by mwmoseley** [comment]
This ended up working for me, thanks for the tip!
