### ISSUE TITLE
Fan ramp from idle to setpoints not aggressive enough

### ISSUE THREAD

**Issue by Turd89Ferguson** [nicehash/NiceHashQuickMiner#128]
I currently use QM on a 3080 with the Medium optimization preset. However, when I went into OCTune to check (My VRAM was up around 95C) the setpoint was 94. I adjusted down to 90 and things have been going great.

However, when ramping up from idle/cold boot, the fan profile is not aggressive enough to prevent the vram temperature from overshooting (in my case, topping out at 96+) before settling into the 90 setpoint.

Is it possible to make the fan profile ramp more aggressively, or monitor rate of temperature change and adjust the profile accordingly?

Thank you.

**Comment by nicehashdev** [comment]
Yes, you need to use this method (put it into commands.json): https://github.com/nicehash/excavator/tree/master/api#device-smartfan-set-advanced
