### ISSUE TITLE
NiceHash Task Scheduler Autostart option delay for 1 minute

### ISSUE THREAD

**Issue by Swiftnc** [nicehash/NiceHashQuickMiner#130]
Due to the black screen issue found with the v.0.4.0.0 RC (as well as if anyone changes voltage poorly), can you please change the task scheduler autostart to delay start by 1 minute (or 30 seconds) after login.  This will allow recovery in case of a system issue caused by NiceHashQuickMiner.

**Comment by nicehashdev** [comment]
Currently, there is delay 5 seconds. You can manually increase this delay after entry in Task Scheduler is made (you can use Windows UI to do it, it is simple: go to triggers and edit Login trigger - there is option to delay it for as long as you want).

**Comment by Swiftnc** [comment]
The new 15 seconds delay is great.  Thanks!

**Comment by nicehashdev** [comment]
Also added instructions how to choose any delay you want: https://github.com/nicehash/NiceHashQuickMiner/wiki/Troubleshooting#nicehash-quickminer-starts-with-windows-too-quickly-can-i-delay-it

Closing this issue.
