### ISSUE TITLE
Nvidia driver 461.72 Issue

### ISSUE THREAD

**Issue by moops44** [nicehash/NiceHashQuickMiner#132]
When i try to set the Powerlimit with OCTune on Nvidia driver 461.72
Excavator says " device #0 | Failed to get power limits (issue with NVIDIA drivers!) "

**Comment by nicehashdev** [comment]
What kind of hardware do you have? Are you using laptop? Not all laptops support power management functions. You may try to install different variants of drivers, experiment around, but generally, this is an issue of NVIDIA's libraries and nothing I can do about it.

**Comment by moops44** [comment]
I use a Desktop Rig , with a Rtx 3080 FE
But i manage to solve the issue , i deleted everything from Nvidia with DDU and did a fresh install , and now it works again
