### ISSUE TITLE
Radeon RX 6800 Gaming OC

### ISSUE THREAD

**Issue by ben1628** [nicehash/NiceHashQuickMiner#133]
I know it isn't supported in quick miner.

So what should one do, if he has

RTX 3060 TI
Gigabtye Radeon RX 6800 gaming OC.

Can I run 3060 ti using quick miner and use RX 6800 with NiceHash.

Or am i forced to use them only in Nicehash.  OR DON"T DO IT

Any help would be appreciated.

**Comment by nicehashdev** [comment]
When you start NiceHash QuickMiner, only NVIDIA cards (with 6GB+ VRAM) are detected. It does not matter what kind of other hardware you have. You can use another miner that would utilize AMD GPU. There would be no conflict with QuickMiner. It is also possible to run QuickMiner and NiceHash Miner on same PC at the same time if you wish to do that, but you have to make sure to properly assign GPUs to each miner so there are no fights over resources.
