### ISSUE TITLE
false positive Windows Defender Win32/Wacapew.C!ml

### ISSUE THREAD

**Issue by phi0x** [nicehash/NiceHashQuickMiner#136]
Today I received my first notification from Windows defender (I do have exclusions setup but WD found this.)

Program:Win32/Wacapew.C!ml

file: C:\Program Files\NiceHash\NiceHashQuickMiner\excavator.exe

I downloaded nicehash quick miner via github and used the auto update feature going forward to upgrade to latest RC 4.0.1 which has caused this trigger.

Any concern?...

**Comment by nicehashdev** [comment]
We do not sign RC versions. For peace of mind, we suggest you to use latest Stable version which is signed and we fight with Microsoft and Google to get any false positive detection off.
