### ISSUE TITLE
Command line options to stop/start mining?

### ISSUE THREAD

**Issue by CorneliousJD** [nicehash/NiceHashQuickMiner#137]
I have a unique situation where I pay 4x as much for power between 3p-7p 

I would like to script a method to stop mining at 3p and start again at 7p 
To do this I would need some form of command line option to pass the "stop" and "start" commands to QuickMiner. 

I looked at API in Excavator but cannot get it to work for my needs. 

Is this possible with QuickMiner at all directly?
If not, perhaps some command line options could be implemented so users can schedule things like this?

Thank you in advance!

**Comment by CorneliousJD** [comment]
@mwmoseley - you ahd the same question I found - what did you end up doing exactly to get this to work?

**Comment by ben1628** [comment]
If you are using Windows 10, you should be able to setup scheduled tasks to skip mining between 3 p and 7

**Comment by nicehashdev** [comment]
Perhaps this will be available as a feature one day.

As explained now, You can play with Task Scheduler and using [Excavator API](https://github.com/nicehash/excavator/tree/master/api) to achieve this.

**Comment by Postal268** [comment]
n00b at this sort of thing here, I tried using a batch file to close the program to no avail and I have no idea what an Excavator API is so I figured I'd drop my solution here for any other n00bs looking for an easier method. I just used windows task scheduler to schedule the whole pc to reboot when peak hours start here, then I used the scheduler to schedule the miner to open at the end of peak hours. You should make sure your miner doesn't auto open with windows for this to work however.
