### ISSUE TITLE
Mining device does not get recognised as online.

### ISSUE THREAD

**Issue by keangurow** [nicehash/NiceHashQuickMiner#138]
Any ideas how to fix this?

**Comment by nicehashdev** [comment]
Some more information is needed. What exactly does not work?

**Comment by keangurow** [comment]
> Some more information is needed. What exactly does not work?

Altough my device is online it counts as offline.

**Comment by nicehashdev** [comment]
What kind of BTC address are you using? You have to use your Mining Address provided by NiceHash, which you can find in Rig Manager. If you use any other BTC addrress, various things are not going to work.

**Comment by nicehashdev** [comment]
Considering as solved - no reply.
