### ISSUE TITLE
Memory overclocks resetting when using afterburner (not in built)

### ISSUE THREAD

**Issue by insom1337** [nicehash/NiceHashQuickMiner#14]
I’m not sure if its when drags are being generated or not, but my memory overclock reduces (3070) after a certain amount of time.

I read that if using the build in OC tool this would happen while a drag is generated - but i’m not using the built in tool. I did try the auto OC thing once, but then hit reset all settings and reverted to my own afterburner settings.

Should this be happening? Is there a way to override?

Thanks

**Comment by lvn2007** [comment]
I heard Excavator will automatically set OC to default whenever DAG is being generated.

**Comment by nicehashdev** [comment]
QuickMiner OC tuning or Excavator OC profiles are not compatible with Afterburner and there are unpredictable results if trying to use both OC tools at the same time. You need to decide whether to use Afterburner OC or QuickMiner OC and stick to it solely.

**Comment by nicehashdev** [comment]
This might be related with another issue that was fixed in latest RC, get it here: https://github.com/nicehash/NiceHashQuickMiner/releases/tag/v0.3.1.2_RC

Closing as fixed.
