### ISSUE TITLE
Unable to power consumption

### ISSUE THREAD

**Issue by profucius** [nicehash/NiceHashQuickMiner#144]
I am running the miner on my laptop, and the Excavator is telling me that it cannot get the power consumption, even though GPU-Z is able to with no trouble.

Let me know if you want any other information or to test anything.

![image](https://user-images.githubusercontent.com/18254607/110158396-5399af00-7db7-11eb-8652-033297cacfa3.png)

**Comment by nicehashdev** [comment]
Laptops are not officially supported by NiceHash QuickMiner. Not all features may work correctly.

We might add official support for them, but it is not so trivial as there are quite some quirks - the one you are showing is one of them - obviously Laptops have different way of getting power related values.

**Comment by profucius** [comment]
Thank you for explaining.

**Comment by nicehashdev** [comment]
Please, try following excavator.exe and let me know if it is any better. Before you use it, update to 0.4.0.3 RC!
[excavator_b715.zip](https://github.com/nicehash/NiceHashQuickMiner/files/6095689/excavator_b715.zip)

**Comment by profucius** [comment]
I have updated to 0.4.0.3 RC and replaced the file you provided. I am still receiving the same error

![image](https://user-images.githubusercontent.com/18254607/110215319-1e549600-7e77-11eb-8968-a834d43864b7.png)

**Comment by nicehashdev** [comment]
What if you open GPU-Z, Advanced and then select NVIDIA BIOS?
Can you see these numbers that I have marked?
![gpuzbios](https://user-images.githubusercontent.com/10868174/110216634-71970a80-7eb0-11eb-99bc-df5e571c3208.png)

**Comment by profucius** [comment]
No it appears I do not have that section

![image](https://user-images.githubusercontent.com/18254607/110216698-92466c80-7e7e-11eb-9855-df83a4606136.png)

**Comment by nicehashdev** [comment]
Okay, so, it is not possible to get these limits for your card. This is it. I may improve display in the future, so it is not throwing warnings/errors out, but you will not have more functionality, because your GPU/driver does not support it.

**Comment by profucius** [comment]
That won't be a problem for me, at least it works the way it does now. Thanks for your time.

**Comment by nicehashdev** [comment]
I have made some improvements regarding this, please try following Excavator: https://github.com/nicehash/NiceHashQuickMiner/releases/download/v0.4.1.2_RC/excavator_b723.zip

**Comment by profucius** [comment]
![image](https://user-images.githubusercontent.com/18254607/110828488-12951500-8265-11eb-9e85-a167d17880c9.png)

![image](https://user-images.githubusercontent.com/18254607/110828513-188af600-8265-11eb-9a00-bb64700486ab.png)
