### ISSUE TITLE
[Suggestion] Add overvolting for gamemode

### ISSUE THREAD

**Issue by Someonewhoisaperson** [nicehash/NiceHashQuickMiner#145]
Some people for gaming overclock settings apply overvolts, please add this setting for game mode

**Comment by nicehashdev** [comment]
When it comes to modifying values that may damage hardware, we are very conservative - undervolting cannot damage your hardware, but overvolting can. Therefore, we have no plans to add this feature as of now. If you rely on this, you will have to find alternative solution for yourself. You may combine it using Excavator's API.
