### ISSUE TITLE
API temperature readings question

### ISSUE THREAD

**Issue by vaskivskyiI** [nicehash/NiceHashQuickMiner#146]
After updating the quickminer to the version, which shows VRAM temp, I have started getting some quite high "temperatures" in API responses. Like 
"temperature": 6029367 
At first this happened for my 3080, after the latest update, which shows hotspot temp, it has also occurred for 3070. How can I convert these to degrees?

**Comment by nicehashdev** [comment]
Where do you get these messages? Mobile APP? I suggest you to update your Mobile APP to the latest version and everything will be fine.

**Comment by vaskivskyiI** [comment]
No, I am getting it from API
![image](https://user-images.githubusercontent.com/10550384/110179372-3fca6900-7e08-11eb-9da1-f664f2fbf928.png)

**Comment by nicehashdev** [comment]
There are two temperatures packed into it: GPU temp and VRAM/HotSpot temp.

VRAM/HotSpot: temperature >> 16
GPU Temp: temperature & 0xffff

If you use some higher level lang that doesnt have easy access to bit manipulation, then you can get temps using simple math:
VRAM/HotSpot: temperature / 65536
GPU Temp: temperature % 65536

**Comment by vaskivskyiI** [comment]
Seems like after recent updates this way I am getting GPU and HotSpot temperatures for all 30xx graphics cards. Is there a way to obtain also VRAM temp?

**Comment by nfrankish** [comment]
@nicehashdev has there been changes to the temperature calculation now? In the app im seeing:
temp 42 degrees
vram 106 degrees.

Butt he api/v2/mining/rigs2 api is returning:
"temperature": 3735594,
which based on the math is
vram = (3735594 / 65536) = 57
and gpu = 3735594 % 65536) = 42.

**Comment by 3p3r** [comment]
temperature reporting is still broken at least for 30 series cards. I'm still getting the same range results as @nfrankish but the app is clearly showing some wildly other temperatures.

Also packing two numbers like this is a stupid API design decision. What are you trying to save? another integer worth of packet size? You could get rid of `server.getTime()` and save 50% bandwidth instead on singular API calls.

**Comment by jernejk** [comment]
Any solution for the VRAM temps?

At one point it showed correctly at 96C but then it dropped between 55 and 57C while real temps were unchanged at 96C.
I have RTX 3080 FHR.

**Comment by jernejk** [comment]
I found out that 55-57C is actually a GPU hotspot...
So on some GPUs we actually only get GPU core and GPU hotspot temps while on others we get VRAM temp instead.

On NiceHash we get all 3 temps depending on the view, which makes me believe this information is somewhere.

**Comment by sqftcoin** [comment]
might find something from https://www.nicehash.com/my/5069.638debcf9d020d33ede9.js
