### ISSUE TITLE
Update data_003.json how to change?

### ISSUE THREAD

**Issue by luminkhant12** [nicehash/NiceHashQuickMiner#147]
i have gtx 1660ti 3fan but octurn 2 fan.how to change and quick miner can destory gpu?

**Comment by nicehashdev** [comment]
You cannot change data_003 but you can make your own overclock and save it. Use OCTune to do it.

**Comment by luminkhant12** [comment]
quick miner destory gpu?

**Comment by nicehashdev** [comment]
No, why would it destroy GPU? It is not possible to destroy GPU.

**Comment by luminkhant12** [comment]
i read your device may not stable i dont understand

**Comment by nicehashdev** [comment]
I really do not understand what you are asking. Please, ask someone to translate your question or perhaps use Google translate: https://translate.google.com/

**Comment by kin6Kan** [comment]
How to use this update data_003.json ? My GTX 1660 Super is only 27mhs.
