### ISSUE TITLE
NiceHash QuickMiner Error installing! NiceHash QuickMiner was unable to continue with installation。

### ISSUE THREAD

**Issue by lsq864** [nicehash/NiceHashQuickMiner#148]
NiceHash QuickMiner
Error installing!
NiceHash QuickMiner was unable to continue with installation.Error:
未能解析此远程名称: 'raw.githubusercontent.com'

**Comment by nicehashdev** [comment]
Are you from China? Perhaps China is blocking some GitHub URLs.

You can always download package manually: https://github.com/nicehash/NiceHashQuickMiner/releases

Just choose whether you want Stable or RC and then download .ZIP file.

**Comment by Slundar** [comment]
Hey there.  I'm from the US and having the same issue.  I've tried to uninstall the program and do a clean install, and that's when I get a similar error message stating it's already installed.

**Comment by nicehashdev** [comment]
> Hey there. I'm from the US and having the same issue. I've tried to uninstall the program and do a clean install, and that's when I get a similar error message stating it's already installed.

That is not the same message but different - a bug that was fixed in later versions, but if you use 0.3.2.6 installer (which is signed) you will still get this message. To avoid this issue just download .ZIP package.

**Comment by Slundar** [comment]
Thank you, I'll give that a try.
