### ISSUE TITLE
Different actual profit from quick miner website and on rig manager

### ISSUE THREAD

**Issue by Vithujap** [nicehash/NiceHashQuickMiner#149]
Hello, i realized that on the quick miner website that the actual profit shows a different number then the actual profit shown on the rig manager on the nicehash website. Which of these is the correct profit? the one shown on the quick miner website or the one shown under rigs

Actual profit (24hrs) on the quickminer website: 
![image](https://user-images.githubusercontent.com/73892808/110212108-22de7600-7e9a-11eb-916f-8da7880fe386.png)
 
Actual profit (24hrs) under the rigs website for the quick miner.
![image](https://user-images.githubusercontent.com/73892808/110212134-3ee21780-7e9a-11eb-85f5-e191a2be5a60.png)

**Comment by nicehashdev** [comment]
Actual profitability is what you are getting paid.

Quick Miner tryout website only shows you a potential profitability (for all devices with max tuning enabled).
