### ISSUE TITLE
OCTune defaults

### ISSUE THREAD

**Issue by lotharmatheos** [nicehash/NiceHashQuickMiner#15]
RTX 3090 has default memory clock 9750MHz not 9500MHz

**Comment by nicehashdev** [comment]
Fixed, thanks for point that out.

**Comment by nicehashdev** [comment]
Actually, the default for CUDA apps is really only 9500, perhaps 9750 is for games. I have changed it back to 9500, which is default one for CUDA and therefore default one for mining.
