### ISSUE TITLE
Request: Allow installing even when previous installation detected

### ISSUE THREAD

**Issue by mprovenz** [nicehash/NiceHashQuickMiner#150]
I had a previous installation of the quick miner that was damaged. I cannot uninstall it because the uninstaller is gone, but I also cannot re-install because the installer refuses to launch and states "Already installed in:"

At the moment I am stuck in a state of not having the program actually installed, but being unable to install it. It would be nice to just make the detected previous installation a warning instead of an error during the install process.

Thanks!

**Comment by nicehashdev** [comment]
This is already fixed, but you have to use installer from RC version, which is not "Stable" and signed.

For now, you can bypass this issue by downloading and unpacking ZIP file.
