### ISSUE TITLE
Duel Address Support

### ISSUE THREAD

**Issue by Trustmeimtheninja** [nicehash/NiceHashQuickMiner#151]
Hello,

My friend and I run a mining rig that we split the cost on. I would like to have some cards payout to his NiceHash account and other cards pay to my NiceHash account. Right now we need to run different instances in order to make this happen. But more than one instance isn't working with the new software. We are using the old software for now. 

Is there a chance we can assign which cards pay to different addresses? 

Thank you!

**Comment by nicehashdev** [comment]
Hello!

We have no plans to support this for now. You will have to get around it somehow on your own.
