### ISSUE TITLE
Game mode not reverting fan settings

### ISSUE THREAD

**Issue by chakal** [nicehash/NiceHashQuickMiner#152]
When disabling Game Mode, my fan should switch back to Fixed speed as saved in the OC profile but it does not, it stays on the Default/Auto profile that is set when enabling Game Mode.

Expected behavior would be that the fan mode is set back to the OC profile

**Comment by nicehashdev** [comment]
Which version are you using?

**Comment by chakal** [comment]
Sorry, latest 4.0.3

**Comment by nicehashdev** [comment]
You are right - there is bug if you have fixed mode, but not if you have target (mode 2 or 3).

**Comment by nicehashdev** [comment]
Found bug, there was `=` missing in code ;)

Will be fixed in next version.
