### ISSUE TITLE
Cannot connect: /cuda_devices

### ISSUE THREAD

**Issue by Hotrod369** [nicehash/NiceHashQuickMiner#153]
I'm mining with a GTX 1660Ti  and mining at an avaerage rate of 29.46 MH/s which is better than with the nicehash miner. On the OCTune page I'm getting this error "Cannot connect: /cuda_devices". Everything seem to be normal and hash rate is good. Just need to know if this is an issue I need to correct and if so how do I fix it. Attache is screen shots of my health monitor and tuner.
![photo_2021-03-07_00-21-32](https://user-images.githubusercontent.com/72291352/110229982-6ad1bd00-7edb-11eb-80e0-68550b5d2703.jpg)
![photo_2021-03-07_00-24-13](https://user-images.githubusercontent.com/72291352/110229995-82a94100-7edb-11eb-825b-8cc562a684ff.jpg)

**Comment by nicehashdev** [comment]
Cannot connect happens when Excavator cannot be reached - it is off, stopped, crashed or whatever. This is only "event log" so you know what is happening.

**Comment by Hotrod369** [comment]
That's odd I get that event log every few minutes the entire time I'm mining. Could it be that it's trying to reach my GTX 1050Ti that is mining with the regular nicehash miner?

**Comment by nicehashdev** [comment]
Do you have many OCTune pages open at the same time? Close them and have only ONE page.

**Comment by Hotrod369** [comment]
No just the one page is all I have open. Here is just a few lines of this error.

[3/7/2021, 2:55:09 AM] Cannot connect: /cuda_devices
[3/7/2021, 2:52:33 AM] Cannot connect: /cuda_devices
[3/7/2021, 2:51:43 AM] Cannot connect: /cuda_devices
[3/7/2021, 2:51:24 AM] Cannot connect: /cuda_devices
[3/7/2021, 2:51:05 AM] Cannot connect: /cuda_devices
[3/7/2021, 2:50:00 AM] Cannot connect: /cuda_devices
[3/7/2021, 2:48:55 AM] Cannot connect: /cuda_devices
[3/7/2021, 2:48:41 AM] Cannot connect: /cuda_devices
[3/7/2021, 2:48:27 AM] Cannot connect: /cuda_devices
[3/7/2021, 2:48:16 AM] Cannot connect: /cuda_devices
[3/7/2021, 2:47:12 AM] Cannot connect: /cuda_devices
[3/7/2021, 2:47:03 AM] Cannot connect: /cuda_devices
[3/7/2021, 2:46:55 AM] Cannot connect: /cuda_devices
[3/7/2021, 2:46:26 AM] Cannot connect: /cuda_devices

This continues the entire time I'm mining. Here is my miner at the same time.

![image](https://user-images.githubusercontent.com/72291352/110234405-4c2def00-7ef8-11eb-9fb7-93625ba78165.png)

I can live with it if you don't think is effecting mining.

**Comment by nicehashdev** [comment]
If you have 31 MH/s in Rig Manager, then it does not affect mining. But I am really curious what could it be.

**Comment by nicehashdev** [comment]
> That's odd I get that event log every few minutes the entire time I'm mining. Could it be that it's trying to reach my GTX 1050Ti that is mining with the regular nicehash miner?

Do you have more than 1 Excavator opened?

**Comment by Hotrod369** [comment]
Nope sure don't but like I said ealier I do have a 1050Ti mining with the regular nicehasminer It' running T-rex Kapow.  I figured you might know if that was the cause.

**Comment by nicehashdev** [comment]
Does it help if you decrease update time in OCTune to 3 or 4 seconds or even 5 seconds?

**Comment by Hotrod369** [comment]
I moved the slider all the way to 5 seconds and get the same error.

**Comment by nicehashdev** [comment]
Are you still getting this issue with latest RC version?

**Comment by Hotrod369** [comment]
Just updated to the latest version 0.4.1.3 Stable release and am getting the same error.

**Comment by barret71691** [comment]
Hi! 

I am working on a buddies rig and he is also getting the same error. It happened in the previous release and also continuing to happen for this newer release. The difference here is that he is not actually able to mine at all, the quick miner doesn't actually load at all.

He can use the other nice hash manager to mine, though would prefer the safer, enhanced quick miner. I will drop the logs below to see if that helps. As a side note, we purchased the same exact laptop, spec by spec, both running a 2070. I don't have any issues so I am guessing there may be something he's downloaded? Any help would be appreciated!

![Log Error](https://user-images.githubusercontent.com/80551450/111005182-54eb4e80-8358-11eb-90ea-af01371d2af1.PNG)

[exported_logs.zip](https://github.com/nicehash/NiceHashQuickMiner/files/6133345/exported_logs.zip)

**Comment by nicehashdev** [comment]
`[2021-03-12 17:17:31:499] [INFO] [watchdog] Starting excavator.exe with cmdline: -c commands.json -qx -qm -wp 18000 -d 2 -f 0
[2021-03-12 17:17:31:507] [ERROR] [watchdog] Failed to start, reason: Access is denied`

This means that something is blocking excavator.exe from starting. Make sure that no AV or Microsoft Defender interferes with the process. Best to make exclusion for whole NiceHash QuickMiner folder.
