### ISSUE TITLE
Uninstaller deleted numerous personal files!

### ISSUE THREAD

**Issue by Zehpto** [nicehash/NiceHashQuickMiner#155]
When using the new installer, I had an "incident"  where the Nicehash files were extracted to my desktop instead of a nested folder. When I went to run the uninstall binary (in the hopes of cleaning up the scheduled task). It literally deleted every file on my desktop. Clearly there is no validation that the files are part of the application. This is really obnoxious because by 2021 you would think an application could tell it's own files apart from other files.

**Comment by nicehashdev** [comment]
I am terribly sorry about that. Will add check to allow installation into new empty folders only to prevent installation into desktop.

This bug also affects previous version.

**Comment by nicehashdev** [comment]
This bug is fixed in new upcoming version.

**Comment by Zehpto** [comment]
Thank you for resolving. Fortunately I had backups. 
I hope I was the only one who experienced this. Keep up the good work.
