### ISSUE TITLE
Newest QuickMiner Release v0.4.1.0_INST still pointing to v0.4.0.3_RC in exe

### ISSUE THREAD

**Issue by Briteguy** [nicehash/NiceHashQuickMiner#156]
Newest Nicehashquickminerintstaller.exe still points to previous version instead of the one just released. 

also zip package hyperlink in newest release pointing to previous version zip as well.

**Comment by nicehashdev** [comment]
There is no 0.4.1.0 yet, Just installer was updated to fix some issues.
