### ISSUE TITLE
core I Decive #0-0 error!

### ISSUE THREAD

**Issue by violinmaker** [nicehash/NiceHashQuickMiner#16]
![image](https://user-images.githubusercontent.com/63171683/107846704-c0dca480-6df6-11eb-99a1-8196772a0c95.jpeg)

Hi I recive core I Decive #0-0 error!

1080ti help please

**Comment by geanpp** [comment]
Same error with a GTX 1080 Ti Asus Strix

**Comment by nicehashdev** [comment]
Will take a look into this. Please, enable logging in Excavator and QuickMiner ([how to do it](https://github.com/nicehash/NiceHashQuickMiner/wiki/Tips-&-tricks#4-enable-logging-for-better-troubleshooting)) and submit your logs. Thanks!

**Comment by geanpp** [comment]
> Will take a look into this. Please, enable logging in Excavator and QuickMiner ([how to do it](https://github.com/nicehash/NiceHashQuickMiner/wiki/Tips-&-tricks#4-enable-logging-for-better-troubleshooting)) and submit your logs. Thanks!

Hello my friend!

This is the log file as requested.
Just two things I wish to add: the temperature on the GPU is getting too hot very fast, minutes to 84C, and the online NiceHash Rig Manager for the affected worker shows some error messages like in the screenshots here. 
Hope you can figure out what's wrong.

Anyway the new QuickMiner is very good indeed and working well in my other GPU (RTX 2080Ti)

Thank you!


[log.txt](https://github.com/nicehash/NiceHashQuickMiner/files/5978393/log.txt)
<img width="936" alt="01" src="https://user-images.githubusercontent.com/79029067/107887256-99afd100-6ee3-11eb-91b0-bb8191913982.png">
<img width="915" alt="02" src="https://user-images.githubusercontent.com/79029067/107887262-9c122b00-6ee3-11eb-88dc-942feed93c77.png">

**Comment by geanpp** [comment]
> > Will take a look into this. Please, enable logging in Excavator and QuickMiner ([how to do it](https://github.com/nicehash/NiceHashQuickMiner/wiki/Tips-&-tricks#4-enable-logging-for-better-troubleshooting)) and submit your logs. Thanks!
> 
> Hello my friend!
> 
> This is the log file as requested.
> Just two things I wish to add: the temperature on the GPU is getting too hot very fast, minutes to 84C, and the online NiceHash Rig Manager for the affected worker shows some error messages like in the screenshots here.
> Hope you can figure out what's wrong.
> 
> Anyway the new QuickMiner is very good indeed and working well in my other GPU (RTX 2080Ti)
> 
> Thank you!
> 
> [log.txt](https://github.com/nicehash/NiceHashQuickMiner/files/5978393/log.txt)
> <img alt="01" width="936" src="https://user-images.githubusercontent.com/79029067/107887256-99afd100-6ee3-11eb-91b0-bb8191913982.png">
> <img alt="02" width="915" src="https://user-images.githubusercontent.com/79029067/107887262-9c122b00-6ee3-11eb-88dc-942feed93c77.png">

Also forgot to mention... the OCTune is not working at all in this worker! Just don't retain the setting applied.

**Comment by nicehashdev** [comment]
I will need Excavator log as well. Please, check instructions how to activate logging for Excavator.

**Comment by nicehashdev** [comment]
Never mind, I have found the issue; looks like your GPU does not report power consumption for some reason.

Calling following NVML method fails

> nvmlDeviceGetPowerUsage

Can you see power consumption in other tools, like GPU-Z?

**Comment by nicehashdev** [comment]
Excavator will not report error next time anymore, but you will be without of many features, including ability to perform Autotune. I suggest you look into it, perhaps you can fix it by updating drivers?

**Comment by PEDemers** [comment]
![nice_Err1](https://user-images.githubusercontent.com/49821959/107893461-5c563e00-6ef9-11eb-896c-6b1ebf06eb29.jpg)
Hi I recive core I Decive #0-0 error!

Asus2080ti, Asus1080, Evga 2080ti end Evga 1080ti help please
[log1.txt](https://github.com/nicehash/NiceHashQuickMiner/files/5978850/log1.txt)

**Comment by promsorn** [comment]
[log_2021-02-15_08-23-35.000.log](https://github.com/nicehash/NiceHashQuickMiner/files/5979024/log_2021-02-15_08-23-35.000.log)
![NHQM_ERROR](https://user-images.githubusercontent.com/79067017/107895916-80506880-6f67-11eb-9caf-17a47a29d1d6.png)
My Quadro RTX4000 & GTX1660

**Comment by violinmaker** [comment]
![image](https://user-images.githubusercontent.com/63171683/107902925-e5e92880-6f58-11eb-962f-0ad174ad960e.jpeg)

I reinstalled the drivers.  problem solved.

**Comment by PEDemers** [comment]
[log_D.txt](https://github.com/nicehash/NiceHashQuickMiner/files/5980086/log_D.txt)
![Nice_Err1_D](https://user-images.githubusercontent.com/49821959/107917721-60548100-6f36-11eb-8f57-c34dbf95cd75.jpg)
Hi I recive core I Decive #0-0 error!
Asus2080ti, Asus1080, Evga 2080ti end Evga 1080ti help please

**Comment by nicehashdev** [comment]
You need to reinstall drivers. Apparently, this is something that helps.

**Comment by PEDemers** [comment]
I redid the installation of the DRIVER Nvidia 461.51 and downloaded the NiceQuickMiner 0.3.7_RC and Octune_v0.3.0.7_RC_fix1
I still see Device # 0-0 Could not Obtain power consumption!
               Device # 1-1 Could not Obtain power consumption!
               Device # 2-2 Could not Obtain power consumption!
               Device # 3-3 Could not Obtain power consumption!

**Comment by nicehashdev** [comment]
You need to do it properly - you must not let Windows install their own version first. So, use DDU and do it without internet.
