### ISSUE TITLE
NHQM is not working on my PC.

### ISSUE THREAD

**Issue by murillolarocca** [nicehash/NiceHashQuickMiner#161]
Everytime that I try to ope, it shows a message sayng:

![image](https://user-images.githubusercontent.com/80229809/110261586-8e563f80-7f8f-11eb-88f2-941d78189700.png)

GeForce Asus RTX3080 TUF
Driver Version: 461.72

Does anybody knows what to do here? Would appreciate a little help...

**Comment by murillolarocca** [comment]
Team, a quick update regarding my issue. I've noticed that the problem might be related to "NicehashQuickMinerv550". Every time that I try to run it the message show a problem. Like this one:

![image](https://user-images.githubusercontent.com/80229809/110362210-c311d780-801f-11eb-8bb3-929a3f5a6126.png)

Does anybody know how to solve this problem?

**Comment by nicehashdev** [comment]
Please, try to reinstall your NVIDIA drivers - the issue is that nvml cannot be located.

**Comment by nicehashdev** [comment]
And after you have done that, try 0.4.03 RC - there were some improvements regarding that.

**Comment by nicehashdev** [comment]
No response, closing.
