### ISSUE TITLE
optimization does not work, return com.nike.backstopper.exception.ApiException: (1): Not initialized yet

### ISSUE THREAD

**Issue by distdream** [nicehash/NiceHashQuickMiner#162]

**Comment by nicehashdev** [comment]
You will have to provide some more information. Your hardware, OS, NHQM version. Enable logs and attach them here.

**Comment by nicehashdev** [comment]
No extra info provided, closing.

**Comment by distdream** [comment]
win10,NiceHash_QuickMiner_v0.4.0.3_RC,
when i click this button 
![image](https://user-images.githubusercontent.com/24263456/110781233-9cae9f00-82a0-11eb-9959-6947a12eff71.png),
return 
![image](https://user-images.githubusercontent.com/24263456/110781336-bfd94e80-82a0-11eb-847c-e9e533f36e38.png)
