### ISSUE TITLE
Display driver requiring occassional restart

### ISSUE THREAD

**Issue by profucius** [nicehash/NiceHashQuickMiner#163]
Running NiceHash 0.4.0.3 RC, once a day or every other day, the monitor connected to the mining graphics card (3080) will turn off, and become unresponsive. If I remote into the machine using a remote connection app, the computer is not locked or unresponsive.

Using the fix from the NiceHash full miner ("**nvidiaInspector.exe -restartDisplayDriver**") I am able to regain responsiveness from the monitor again.

Is there a way to trigger this in the Quick Miner in a similar way to the Full Miner config?

**Comment by nicehashdev** [comment]
Using remove desktop apps can cause issues that we haven't tested yet. The only working remote desktop method that does not cause issues is TeamViewer and Parsec. Try to use these and report back if your problem is solved.

**Comment by profucius** [comment]
The issue stopped happening for the past couple of days. I'll keep my eyes on it, but I suspect that it may have been the clock rates being set too high and causing the card to become unresponsive until the driver was restarted.
