### ISSUE TITLE
Occasional MH/s degredation, fixed by setting overclock again

### ISSUE THREAD

**Issue by profucius** [nicehash/NiceHashQuickMiner#164]
The MH/s rate of my 3080 will occasionally from from ~95 MH/s down to ~70 or ~60 MH/s. I will be unaware of this change for some hours, and once I recognize it, I login to the Excavator OCTune page, click "All" within "Alternative method for overclocking", the correct values were already set in the fields, I simply click All, and immediately the MH/s rate climbs back up to 95/normal.

Rinse, repeat. Approx. a few times a day this will occur, I just need to click "All" and it will fix it.

Unsure what the cause is, I am usually not at the computer when it happens. Not playing any games during the time it happens.

The fan speed however stays constant, and never needs to be re applied.

**Comment by profucius** [comment]
If it is a bug, let me know what I can provide to you to assist in resolving. Otherwise, here are some ideas I have for solving this:

1. Scheduler for re-applying overclock settings.
2. External trigger for re-applying overclock settings, such as a .BAT file.
3. Menu option in the context menu of the taskbar icon.

**Comment by nicehashdev** [comment]
Do you have any other overclocking tools active? These may cause conflicts. Also make sure that your driver is not crashing. Enable full logging and attach logs here. We will see what is happening.

**Comment by profucius** [comment]
No other overclocking tools are active, I have double checked in Task Manager. I do not think my driver is crashing, how would I know that. Does the full logging show that? Also, does the full logging log MH/s rate? Because I will need that to show you when it dips down and requires manual apply overclock again.

**Comment by nicehashdev** [comment]
Yes, everything is logged. It will be visible exactly what is happening.

**Comment by profucius** [comment]
What is the prefix/suffix for the MH/s rate in the logs? 

I'm trying to find that myself. If I am going to provide the log to you, I want to pinpoint an example to share so we can reduce the amount of time hunting for the cause.

**Comment by nicehashdev** [comment]
There are excavator logs too, please check them.

If you use latest 0.4.1.1 RC version then all logs are in folder "logs".

**Comment by profucius** [comment]
Ah I see, is it this string within the excavator log?

"speed":92415590.4

**Comment by nicehashdev** [comment]
It would be still good to get to the bottom of this issue and figure out what exactly is causing it. Let me know if you figure it out.

**Comment by profucius** [comment]
I have two other rigs that are not my primary computers, and they never have the issue. So it could be something running on my computer that is taking GPU resources. I would need to investigate that more deeply using some tool I haven't found yet (since Task Manager is not great for telling you which apps are utilizing GPU like it does for CPU)

**Comment by Blackcol** [comment]
This happened to me, you need to use manual mode to avoid overwriting your OCtune values with the profiles of optimize.

![image](https://user-images.githubusercontent.com/32214170/110854377-e38d9c00-8282-11eb-82ce-ae3ddba95e08.png)

**Comment by profucius** [comment]
That's interesting, my rig hasn't even been triggered to Optimize at all. I do all mine manually within OCTune and haven't used that button at all.

![image](https://user-images.githubusercontent.com/18254607/110858808-84328a80-8288-11eb-9e02-14c4189b07b7.png)

**Comment by nicehashdev** [comment]
If you have manual OC, you should leave this at Manual and not apply any optimization. If you apply optimization and configure manual OC, then results are unexpected and you never know what would happen.

Regarding your issue, yes, if you add loop there, then every 30 seconds, those commands would be called. If that fixes your issue, you can do it that way - I recommend looping every 300 seconds then, because when applying OC, your GPU is "paused" for few milliseconds and does no work. The documentation for commands.json file is here: https://github.com/nicehash/excavator/tree/master/api (it is a bit outdated, will be fixed soon)

**Comment by nicehashdev** [comment]
Considering this resolved. Closing.
