### ISSUE TITLE
GTX750Ti Error

### ISSUE THREAD

**Issue by smileycracker91** [nicehash/NiceHashQuickMiner#166]
I got error to use GTC750Ti. I tried update the driver, and install using .exe installer, and .zip package. Both will have same issue with this GPU.
![GPU_GTX750Ti_Errors](https://user-images.githubusercontent.com/9147888/110310510-9967a900-803d-11eb-90c0-4571f21cf7c8.JPG)

**Comment by nicehashdev** [comment]
This is not NiceHash Miner. Please, open issue here: https://github.com/nicehash/NiceHashMiner/issues
