### ISSUE TITLE
Mining rig not found 0 - GTX 1650 ti

### ISSUE THREAD

**Issue by wouter-claassen** [nicehash/NiceHashQuickMiner#167]
Hi 

I have GTX 1650 ti and all initial checks for hardware done by the site suggested that it can be used for mining. After installation it does shows as a Mining rig under the Rig Manager with notification given that it was mining now, but with no details like temp power or other details as a dropdown, which suggests that it is running but not working.

When selecting the mining rig under Rig Manager however, it shows Mining rig not found: 0-BxCNQ7GBz0mIxxx.

Cannot seem to see anything that i have missed from the instructions provided to do the installation. 

Please assist.

**Comment by nicehashdev** [comment]
GTX 1650 is not supported. Please check list of supported hardware here: https://github.com/nicehash/NiceHashQuickMiner/wiki/Supported-hardware
