### ISSUE TITLE
My computer is the latest version of the driver, why does it display this

### ISSUE THREAD

**Issue by zxt2698** [nicehash/NiceHashQuickMiner#17]
![image](https://user-images.githubusercontent.com/79004446/107848485-bccc7900-6e2e-11eb-8a88-f85b02e133d5.png)

**Comment by nicehashdev** [comment]
Well, obviously it is not or you are trying to run it for hardware that isn't supported by QuickMiner. Please check whether your hardware is listed here: https://github.com/nicehash/NiceHashQuickMiner/wiki/Supported-hardware

**Comment by Disparatado** [comment]
and remember to uninstall driver using DDU from wagnar booting into safe mode. Then disconnect your wifi or LAN so windows wont auto-update, and run the nVidia installer, and try then.
