### ISSUE TITLE
How to Minimize NHQM to Tray

### ISSUE THREAD

**Issue by AlexDumoJM484** [nicehash/NiceHashQuickMiner#170]
What I love the most about the main miner is how you can minimize it to the tray and forget about it. Is there a way to do this with QuickMiner? I see a "hide mining console" option in the config file, but it doesn't seem to do anything differently if I set it to true.

**Comment by nicehashdev** [comment]
You can enable bHideMiningConsole and this will hide Excavator console window, leaving only NiceHash QuickMiner in the tray. Thats all.
