### ISSUE TITLE
How to use update data_003.json ?

### ISSUE THREAD

**Issue by kin6Kan** [nicehash/NiceHashQuickMiner#172]

**Comment by nicehashdev** [comment]
This is used automatically. You will need to specify your question in more details.

**Comment by lonelymyp** [comment]
Set the parameters manually, do not use ready-made overclocking profiles.
first find the operating frequency of the memory, then use OCTune -> autotune ->speed
TDP should not be done below ~70%, because there may be a performance drawdown.

**Comment by kin6Kan** [comment]
TDP 100%. MM -502. Still 27mhs

**Comment by lonelymyp** [comment]
-502 only for hunix. do not do this if you have a memory from another company.

**Comment by lonelymyp** [comment]
as I said, manually find the best memory frequency.
