### ISSUE TITLE
How to config Stop and exit Quick miner if internet is drop

### ISSUE THREAD

**Issue by Ar-Myn** [nicehash/NiceHashQuickMiner#173]
Is there any config to setup if internet is down stop and exit the miner?  if not typically it restart miner automatically and suddenly apply the overclocked settings and repeating same.  it may be not good to GPU I think.
So is there any way to config please explain here. if no way to do it i would be better to add it in config

**Comment by nicehashdev** [comment]
There are no dangers in applying overclocks. During no internet connection, there is no load on GPU so you are completely safe. You have nothing to worry about.

**Comment by Ar-Myn** [comment]
Thanks for your response. 
As my understanding, as soon as Excavator restart, in initial stage, it will apply overclocks to GPU and after it will identify mining value is 0(No internet) it will close and restart again within few seconds. so it will close and restart until found there is internet.
So each and every time restart Excavator, apply overclocks -->no load due to, no internet & Close-->restart-->apply overclocks.

So my concern is, this this circle loop due to no internet will affect to GPU or not.  Correct me if  i'm wrong

BTW is there any configuration we can setup as there is no internet detect, "Do nothing" and keep going until internet detect without restart the Excavator?

**Comment by nicehashdev** [comment]
No, it will not affect GPU. There is no load on GPU. Changing clocks does not harm to GPU. This is not V6 engine that would have mechanical parts which would wear out ;)

**Comment by Ar-Myn** [comment]
Okay got it :) 

BTW for just to know, is there any configuration we can setup as, if there is no internet detect, "Do nothing" and keep going until internet detect without restart the Excavator?

**Comment by nicehashdev** [comment]
Yes, you can set to not do anything when speed is 0: https://github.com/nicehash/NiceHashQuickMiner/wiki/Tips-&-tricks#3-define-what-happens-when-something-goes-wrong

But this will also make no reaction if there is an actual bug that causes your mining to stop. QuickMiner would not restart Excavator then to solve the issue and your mining would be dead until you manually do it.
