### ISSUE TITLE
How to setup fan speed permanently? Due to setup in OCTune is temporary and after restart settings will be back to default 

### ISSUE THREAD

**Issue by Ar-Myn** [nicehash/NiceHashQuickMiner#174]
According to topic i mentioned is there any way to change the fan speed permanently? Due to I would like to keep the fan speed as Auto/default mode because it will keep low temp in my GPU.

**Comment by Ar-Myn** [comment]
Okay.got it .Thanks

**Comment by Ar-Myn** [comment]
It seems with new update we can not set the fan speed what ever we want.
Can you please help to allow change the fan speed?

**Comment by Xalaxis** [comment]
To set the fan speed to default/auto whilst using an optimization profile, you must customize it by setting the `"fm"` (fan mode) value to 0.

More information is available in https://github.com/nicehash/NiceHashQuickMiner/wiki/One-click-Optimizations#is-it-possible-to-slightly-modify-optimization-profiles

**Comment by nicehashdev** [comment]
> It seems with new update we can not set the fan speed what ever we want.
> Can you please help to allow change the fan speed?

Yes, I will add this functionality in the next version.

**Comment by nicehashdev** [comment]
Here it is: https://github.com/nicehash/NiceHashQuickMiner/issues/411#issuecomment-823632051

**Comment by nicehashdev** [comment]
Closing as duplicate. Continue https://github.com/nicehash/NiceHashQuickMiner/issues/411#issuecomment-823632051
