### ISSUE TITLE
Please allow just CPU mining

### ISSUE THREAD

**Issue by allanstevens** [nicehash/NiceHashQuickMiner#176]
I currently only CPU mine at the moment as my Nvidea GPU is too out of date.  I have been using the standard nicehash miner due to the limitation of CPU only as additional.  Now with the Phoenix miner issue, I have removed and os reinstalled!!

I will not put the standard miner back and would like to use the 100% safe and digitally signed QuickMiner, but I can't for just CPU. Could you remove the Nvidia limitation, even if it's just a command-line switch or something?

I hope this is the correct place to raise this, sorry if not.

**Comment by nicehashdev** [comment]
If you plan to mine using your CPU only, I suggest you to use NiceHash Miner: https://github.com/nicehash/NiceHashMiner/releases

There are no plans to make NiceHash QuickMiner CPU mine only. CPU mining is only an extra feature that gives less work to miners who would like to enable CPU mining when they already do GPU mining.

**Comment by nicehashdev** [comment]
We are aware of this problem. We are also preparing NHM to be as safe as NHQM if you do not specifically allow 3rd party closed source miners with anonymous developers.

In the meantime, you can use XMRig as a standalone solution.
