### ISSUE TITLE
Feature Request: Auto Game Mode

### ISSUE THREAD

**Issue by jroselle** [nicehash/NiceHashQuickMiner#178]
Please have an option to auto start game mode when a process is running (like steam or PlayNite) and then turn game mode off when process disappears.  Most likely involve polling every few seconds.

Use case - I use my PC for remote game streaming and when remoting in, it's difficult to turn game mode on.  I realize I can use the mobile app to temporarily suspend mining, but then I may forget to turn it back on.  Having game mode turn on and off automatically would be very helpful.

**Comment by nicehashdev** [comment]
Added to the TODO list: https://github.com/nicehash/NiceHashQuickMiner/wiki/Planned-features
