### ISSUE TITLE
EVGA 3rd Fan control

### ISSUE THREAD

**Issue by UnPure** [nicehash/NiceHashQuickMiner#179]
This might be related to https://github.com/nicehash/NiceHashQuickMiner/issues/102 but it doesn't seem to be fixed for me. If I try to change the fan speed on my 3080 FTW3 or 3070 FTW3 it only changes the speed of the left and middle fan but ignores the right fan. I tested it on latest stable and on 0.4.0.3RC with the same result. I can change the speed of all 3 fans in PX1 without any problems. I tried it with and without PX1 running in the background. If you need any other information please let me know.

//edit: I just tried it again and it does in fact change all 3 fans on my 3070 FTW3 but not on my 3080.

**Comment by nicehashdev** [comment]
That is interesting because I have several FTW 3090 and one 3080 FTW and not one of them have this issue. Could you check if there is bios fix that addresses this issue? Or perhaps a change of drivers. Try DCH drivers.  DCH drivers are actually better because they offer more reliable control of your GPU.

**Comment by UnPure** [comment]
BIOS is up-to-date on the 3080 and I also tried the XOC bios but both have the same problem. I used DDU and installed the latest DCH driver instead but I still cant seem to control the right fan with OCTune.

**Comment by nicehashdev** [comment]
Is there another PC you could use to try this there?

**Comment by UnPure** [comment]
I don't have access to any other PC's at this point.

**Comment by nicehashdev** [comment]
Okay, then try following, when excavator is running, open browser and write this into address bar:
`http://localhost:18000/devices_cuda`

**Comment by UnPure** [comment]
https://pastebin.com/GEPLN6wq

**Comment by nicehashdev** [comment]
Yes, this shows that API does not report 3 fans, but rather only 2, so there is no possibility for NiceHash QuickMiner to change fan speed for all of them. Precision X works, because it uses proprietary settings and methods by EVGA.

**Comment by UnPure** [comment]
I'm not sure if this can be helpful but in HWiNFO64 the fans seem be under different names for the 3080 FTW3.

- GPU Fan1
- GPU Fan2
- GPU Right Fan

The 3070 FTW3 has the same naming for all 3 fans but the `GPU Right Fan` doesn't seem to be readable through HWiNFO64 which is a weird behavior because OCTune can in fact change the third fan on the 3070 FTW3, just not on the 3080.
