### ISSUE TITLE
Feature Request: Mine when Idle/Locked Screen or Keycombination to Start mining

### ISSUE THREAD

**Issue by c0deisme** [nicehash/NiceHashQuickMiner#18]
As the title states,
i'd find it super useful if there were an option to set a keybind to start mining or like in the normal miner to start mining when idle for XX seconds or when the computer is locked.

**Comment by nicehashdev** [comment]
Already on todo list: https://github.com/nicehash/NiceHashQuickMiner/wiki/Planned-features
