### ISSUE TITLE
[10/3/2021 9:30:32] Cannot connect: /cuda_devices [10/3/2021 9:30:28] Starting up...

### ISSUE THREAD

**Issue by bbnnyy23** [nicehash/NiceHashQuickMiner#181]
![prbnh](https://user-images.githubusercontent.com/80386333/110599931-ae4e5480-8183-11eb-9c48-98296314dfbd.jpg)
Hi, i keep getting this issue no matter what i do. i have a gtx 1060 6gb from asus. with nicehash worked without problems, with nhqm it doesnt even show up 👍 

Any ideas ?

Thanks

**Comment by nicehashdev** [comment]
You need to turn on NiceHash QuickMiner. OCTune on it's own will not work without Excavator running in the background.

**Comment by DarthOB1** [comment]
I have the same issue, NH QM is ON.  In fact, I can't even stop it.  If I install any earlier version I have no issues.  This is a bug with the latest RC.

**Comment by nicehashdev** [comment]
Can you enable logging and supply me logs?

**Comment by DarthOB1** [comment]
Hey DJ, appreciate the follow up. Looks like u guys pushed a new rc, this
one is working!

Regards

**Comment by nicehashdev** [comment]
Okay good, thanks :)
