### ISSUE TITLE
Nicehash Quickminer stoped mining

### ISSUE THREAD

**Issue by bmwf30** [nicehash/NiceHashQuickMiner#182]
nicehash quick miner stopped by itself 3 times today
![C1A6AB2F-BDC7-4E1E-9046-E46A9ED94583](https://user-images.githubusercontent.com/79402883/110602108-eeaed200-8185-11eb-8a45-93a6aae21f8d.png)

**Comment by nicehashdev** [comment]
Are you using /quick-miner page with it? If yes, stop using this page - whenever you close browser being on that page, it would stop Excavator at the same time.

**Comment by bmwf30** [comment]
What is the quick-miner page?
