### ISSUE TITLE
bug, disabled GPU

### ISSUE THREAD

**Issue by keden-greg** [nicehash/NiceHashQuickMiner#183]
I have 2 GPU's, I use the first one for daily usage and the second one for mining.

Issue: Everytime I stop & start the miner, program uses my 1st GPU, even tho gaming mode is enabled. I have to turn it off and on again so the GPU doesn't mine.

I don't see any place inside the program to disable the GPU, and in the Rig Manager over the webpage the GPU appears as not mining ( while it is ), the user should be allowed to choose which GPU's will mine.

PD: I have configured the config file `"disabledDevices":["1"],` and doesn't work.

**Comment by nicehashdev** [comment]
Game Mode would disable only GPU which has display attached. You do need to manually turn on/off any GPU. Just leave all GPUs enabled constantly. Before you go into the game, enable Game Mode and it will auto disable mining on GPU that is connected to your display while leaving the other one still mining.

**Comment by keden-greg** [comment]
Just to clarify, I don't want to mine with main GPU, it's the only one with a display attached.

I don't see an option to disable main GPU for mining, everytime I start & stop the miner, main GPU will start to mine along with the 2nd GPU.

I wanted to avoid this, by turning game mode on all the time ( which didn't work, game mode was enabled, and after pressing start it started to mine again ).

**Comment by nicehashdev** [comment]
Try following: enable all GPUs, so both of them work.

Then activate Game Mode. Do you see only 1 GPU mining now?

**Comment by keden-greg** [comment]
Yes, I have that working, issue is when I press button | stop | and then | start |, main GPU shouldn't start mining, and it does.

Now isn't happening, main GPU got "disabled", but earlier I was doing the same, and the main GPU ( even in game mode active after pressing start ) if I stopped and started again, the main GPU mined with game mode active.

**Comment by nicehashdev** [comment]
Is there any special reason why would you stop/start during gameplay?

But you gave good idea: we should disable start/stop functionality during gameplay to solve these unhandled scenarios.

**Comment by keden-greg** [comment]
No, but I think that's not the main point, I just want to disable GPU 1 from mine, only way I can do that is to enable game mode. As user, we should be able to choose which GPU mine and which doesn't, for example, what if I had 3 GPU's and I only want to mine with one?

Also, for some reason, I left the computer for 1 hour, it was minning, the excavator stopped and started again for some reason, and GPU 1 ( even tho Game Mode is enabled ) started to mine, while I was away from computer, getting 90 C° ( because this PC doesn't support if main GPU mine )

**Comment by nicehashdev** [comment]
You can enable/disable GPUs from Rig Manager.

**Comment by keden-greg** [comment]
In the Rig Manager GPU 1660 ( which is GPU 1 ) shows as not minning, that's the bug, so in the Rig Manager my GPU isn't minning, while in reality it is.
