### ISSUE TITLE
Laptop 3070 error Could Not Obtain Power Consumption

### ISSUE THREAD

**Issue by GraysonSlade** [nicehash/NiceHashQuickMiner#184]
Just got a new laptop and keep getting this error is there a fix i am not seeing?

**Comment by nicehashdev** [comment]
Please, try this version: https://github.com/nicehash/NiceHashQuickMiner/releases/tag/v0.4.1.2_RC

Then replace excavator.exe with this one: https://github.com/nicehash/NiceHashQuickMiner/releases/download/v0.4.1.2_RC/excavator_b723.zip

Should fix the issue for you.

**Comment by nicehashdev** [comment]
This is fixed with latest RC version now.
