### ISSUE TITLE
Add option to reset commands.json to defaults

### ISSUE THREAD

**Issue by yanickgirouard** [nicehash/NiceHashQuickMiner#185]
I have enabled the auto-tuning from the web control panel, and it inserted a whole lot of commands in the commands.json file. However, I found the tuning too aggressive and had worse performance than my manual tuning using MSI Afterburner (which was properly closed at the time). I disabled the auto-tuning but it left a command in the "on_quit" event to reset the fan control, which means it stopped my fan when I quit NHQM even though I was using MSI Afterburner. I wanted to reset the file to its bare minimum, and couldn't find a reference or an option to regenerate it.

An option to reset the commands file to its minimum default would be nice.

**Comment by nicehashdev** [comment]
First, in OCTune, click red button to reset all overclocks. Then click green button to save current configuration. Your commands.json file will be reset to default then.

You can also copy default commands.json file from a .ZIP installation package and replace yours.
