### ISSUE TITLE
Start mining when idle function 

### ISSUE THREAD

**Issue by sepivip** [nicehash/NiceHashQuickMiner#186]
It was in Planned... but now its gone... cant find in app as well... What I'm missing?

**Comment by nicehashdev** [comment]
This is already implemented and is default behavior of NiceHash QuickMiner. You can use apps, watch movies and even do light gaming while mining.

**Comment by zabytu** [comment]
Untrue. It bogs down gaming, locks up LHR cards, and makes the system unstable.
