### ISSUE TITLE
running too hot! Performance is degraded!

### ISSUE THREAD

**Issue by Walter66888** [nicehash/NiceHashQuickMiner#187]
Hi :
I'm using laptop 3070 with NiceHashQuickMiner
After I update to 4.1.2RC recently ,
It will shown
"
[21:23:57][0x00002004][warning] core | Device #0 is running too hot! Performance is degraded!
[21:23:57][0x00002004][warning] core | Device #0 GPU temp: 54 C
[21:23:57][0x00002004][warning] core | Device #0 HotSpot temp: 60 C
"
But my environment still and have no change ,
before I update to 4.1.1RC or 4.1.2
it's very stable to mining.

So,
1.Could you please let me know how to change temp warning value ? like over 80C

because It's not a very high temp, but will degrade my performance.

PS, I did change the OCtune fan , it's not helpful , Thank you

**Comment by nicehashdev** [comment]
Please check if you have lowered your max temperature limit in MSI Afterburner. It looks like this causes reporting of throttle reason: overheating which then prints this warning message.
