### ISSUE TITLE
failed download  minerprogram

### ISSUE THREAD

**Issue by joe11111-sudo** [nicehash/NiceHashQuickMiner#189]
![1](https://user-images.githubusercontent.com/74581472/110903758-e2bc3f00-8342-11eb-875f-1e82bbfa7ce4.PNG)

**Comment by nicehashdev** [comment]
Do you have any protection in place that blocks access to GitHub?

**Comment by joe11111-sudo** [comment]
no , i already threat this program from my nortan(security program)

**Comment by nicehashdev** [comment]
You can always manually download ZIP file: https://github.com/nicehash/NiceHashQuickMiner/releases/download/v0.4.1.3_RC/NiceHash_QuickMiner_v0.4.1.3_RC.zip

**Comment by joe11111-sudo** [comment]
![111](https://user-images.githubusercontent.com/74581472/110948574-7b22e580-837c-11eb-97aa-ba7983274fe7.PNG)
ermm wht problem now

**Comment by nicehashdev** [comment]
Like the error suggested, install latest NVIDIA drivers to solve this issue.
