### ISSUE TITLE
Question: How can i disable the overclocking functionality?

### ISSUE THREAD

**Issue by RoBiK75** [nicehash/NiceHashQuickMiner#19]
I want to use Afterburner to set my overclock (because it offers more control which enables me to achieve much better efficiency) but QuickMiner overrides my clock set in Afterburner.
How can i prevent QuickMiner from overriding my OC settings?
Thanks.

**Comment by nicehashdev** [comment]
QuickMiner does not apply any OC by default. If you do not use OCTune or do not set any OC profiles in commands.json, then no OC will be done.

**Comment by RoBiK75** [comment]
That is not what i am experiencing.
A fresh install of NiceHash_QuickMiner_v0.3.0.6_RC on a first start already applies it's own GPU clocks to my 1080Ti without me ever opening OCTune or making any adjustments to configuration at all.
It also re-applies the clocks each time it re-generates the DAG cache.

**Comment by nicehashdev** [comment]
Do you experience same behaviour with latest stable version 0.3.0.2 ?

**Comment by nicehashdev** [comment]
I just double checked 0.3.0.6 RC and I do not see any OC being set. Make sure you do not copy commands.json file if you are copying config files. OC profiles are saved in commands.json file.

**Comment by giroberto** [comment]
I am having the same behavior,
When I start, my hashrates are correct, but after some time(maybe an hour) my hashrates drop to stock values, I have to go to afterburner and reapply my settings

GeForce GTX 1060 6GB DaggerHashimoto: 16.63 MH/s Status Mining Temp 57ºC Load 100% RPM 1479
GeForce RTX 3080 DaggerHashimoto: 86.6 MH/s Status Mining Temp 64ºC Load 100% RPM 41%
GeForce RTX 3060 Ti DaggerHashimoto: 51.67 MH/s Status Mining Temp 63ºC Load 100% RPM 39%
GeForce GTX 1070 DaggerHashimoto: 24.16 MH/s Status Mining Temp 64ºC Load 100% RPM 2020
GeForce RTX 3060 Ti DaggerHashimoto: 51.65 MH/s Status Mining Temp 62ºC Load 100% RPM 38%

After reapplying
GeForce GTX 1060 6GB DaggerHashimoto: 20.53 MH/s Status Mining Temp 61ºC Load 100% RPM 1537
GeForce RTX 3080 DaggerHashimoto: 99.22 MH/s Status Mining Temp 60ºC Load 100% RPM 53%
GeForce RTX 3060 Ti DaggerHashimoto: 59.96 MH/s Status Mining Temp 63ºC Load 100% RPM 39%
GeForce GTX 1070 DaggerHashimoto: 24.2 MH/s Status Mining Temp 64ºC Load 100% RPM 2050
GeForce RTX 3060 Ti DaggerHashimoto: 60.08 MH/s Status Mining Temp 62ºC Load 100% RPM 38%

**Comment by Disparatado** [comment]
same here on 0.3.0.7, and also if i use another OC like MSI or Aorus, it goes wonky and does not show correct clocks and Power Draw

**Comment by rokubo** [comment]
Same here on 0.3.0.6 or 0.3.0.7 or 0.3.1.0 after 1 hour or so.  Rather than applying OC, to me it looks like it's resetting OC back to stock memory clock.  Here is my commands.json, which is pretty vanilla.

`[{
		"time": 0,
		"commands": []
	},{
		"time": 10,
		"commands": [{
				"id": 1,
				"method": "workers.reset.all",
				"params": []
			}]
	}, {
		"time": 15,
		"loop": 15,
		"commands": [{
				"id": 1,
				"method": "worker.print.efficiencies",
				"params": []
			}, {
				"id": 1,
				"method": "workers.reset.all",
				"params": []
			}]
	}, {
		"event": "on_quit",
		"commands": []
	}, {
		"event": "on_quickminer.start",
		"commands": []
	}, {
		"event": "on_quickminer.stop",
		"commands": []
	}
]`

**Comment by RoBiK75** [comment]
I concur with the above observation: the GPU OC settings get reset after the DAG-case is generated. This happens in versions 0.3.0.6 or 0.3.0.7 and 0.3.1.0.

> Do you experience same behaviour with latest stable version 0.3.0.2 ?

this does not happen in 0.3.0.2

> I just double checked 0.3.0.6 RC and I do not see any OC being set. Make sure you do not copy commands.json file if you are copying config files. OC profiles are saved in commands.json file.

I can only assume that you did not observe any change because your GPU clocks were already set to default.
I never copied anything, i always started with the software freshly extracted from the zip into a new directory.

**Comment by Disparatado** [comment]
I agree with above, and also starting from a new zip file without older files. Or does it generate in some specific location? I saw one user had the OCtune folder in System32 in Windows, so there may be some garbage lingering?

**Comment by nicehashdev** [comment]
Will go through this issue again with higher precision.

**Comment by nicehashdev** [comment]
Please, let me know if the issue still persist in latest 0.3.1.1.

**Comment by giroberto** [comment]
> Please, let me know if the issue still persist in latest 0.3.1.1.

Still having stock clocks performance when I start the to mine with 0.3.1.1, I applied my settings with afterburner now and later I will update if my clocks will change again.
I used a brand new folder.

**Comment by nicehashdev** [comment]
Okay, fixed in latest RC: https://github.com/nicehash/NiceHashQuickMiner/releases/tag/v0.3.1.2_RC

**Comment by RoBiK75** [comment]
> Okay, fixed in latest RC: https://github.com/nicehash/NiceHashQuickMiner/releases/tag/v0.3.1.2_RC

thanks, the problem seems to be resolved, this version is working properly on my rig
