### ISSUE TITLE
Quick Miner Terminal Errors

### ISSUE THREAD

**Issue by potasium56** [nicehash/NiceHashQuickMiner#190]
I been getting this terminal error constantly, it constantly aborts the mining process and re-mines...

![Image of Error](https://i.gyazo.com/3833909625c4ff5efb18b3ec93066b70.png)

**Comment by nicehashdev** [comment]
This happens when connection is terminated from the remove host - can be due to some firewall/security solution. Please check what kind of firewalls, routers you use.
