### ISSUE TITLE
erreur du terminal, deconnection constante

### ISSUE THREAD

**Issue by jeroskull** [nicehash/NiceHashQuickMiner#191]
![Capture](https://user-images.githubusercontent.com/80517429/110925178-28690f80-8323-11eb-8d72-443500756114.JPG)
bonjour, le terminal se deconecte et reconnecte constantamment avec un message d'erreur
Que dois-je faire svp

**Comment by nicehashdev** [comment]
Do you still have this issue? There was some maintenance that is gone by now.
