### ISSUE TITLE
disable update

### ISSUE THREAD

**Issue by daimonkori** [nicehash/NiceHashQuickMiner#194]
Good day. After the NHQM update is released, the old version cannot start in stealth mode because the active prompt dialog box will be updated. Do I understand correctly that checking for updates is carried out to the github resource?

**Comment by nicehashdev** [comment]
It is possible to disable autoupdater. In config nhqm.conf you need to set `bNoAutoUpdate` to `true`.

**Comment by daimonkori** [comment]
Thanks, I already did it. another question: from what ip address does the command for switching profiles come from? (light, medium, manual) the fact is that when using a DNS other than 8.8.8.8 this parameter cannot be changed

**Comment by nicehashdev** [comment]
This comes from file located here on GitHub: https://github.com/nicehash/NiceHashQuickMiner/blob/main/optimize/data_003.json
