### ISSUE TITLE
Install Reminder Window won't allow for close

### ISSUE THREAD

**Issue by EagleDragoonBear** [nicehash/NiceHashQuickMiner#195]
The button labeled "Okay, I have tested it and I understand it! Close this Dialog now" won't ungrey thereby allowing a click action. If I try to close by clicking the x in the top right, it closes the QuickMiner too. Thanks.
![Install error Screenshot 2021-03-12 145657](https://user-images.githubusercontent.com/61329033/110992286-b6ed8900-8343-11eb-9bb3-5462e03ef996.png)
hx

**Comment by nicehashdev** [comment]
Do what the button says: go to tray and right click NiceHash icon. When you do that and you see menu, then you will be able to close this dialog. This is here to teach you how to use NiceHash QuickMiner because there were so many people who didn't know how to close it.

**Comment by EagleDragoonBear** [comment]
Silly me. Thx!
