### ISSUE TITLE
v0.4.1.3 excavator returns "access denied" in the log and won't run

### ISSUE THREAD

**Issue by GabeBars** [nicehash/NiceHashQuickMiner#196]
The miner doesn't start. Tried reinstalling from the start, same problem.
The issue arose after I let it update to version 0.4.1.3.

[logs_nhqm.txt](https://github.com/nicehash/NiceHashQuickMiner/files/6132855/logs_nhqm.txt)

I dunno why but now the access to excavator is denied, as several lines point to that.

**Comment by nicehashdev** [comment]
Please, make sure that excavator.exe is not blocked by any antivirus program, including Windows Defender!

**Comment by GabeBars** [comment]
> Please, make sure that excavator.exe is not blocked by any antivirus program, including Windows Defender!

Bingo! Sorry about that... As it was running fine before, I didn't even think about the possibility of Windows Defender was messing with it. All running fine now. Thanks!
