### ISSUE TITLE
Disable Octune overclock when mining is stopped

### ISSUE THREAD

**Issue by jcodejedi** [nicehash/NiceHashQuickMiner#198]
Allow game mode to be activated from rig manager and/or from another windows user account.

or

When mining is stopped either locally or from the rig manager, give option to place primary graphics card overclock settings either to game mode settings, default, or keep mining overclocks.

When mining is started, mining overclock settings are reapplied.

——————-
The goal of this is to make quickminer more gaming rig friendly for pc user accounts other than the account that is running quickminer.

**Comment by nicehashdev** [comment]
Game Mode will be improved over time, but no timeline promised. For now, you can help yourself making manual adjustments to the commands.json file. You can practically make anything you want happen (using events start/stop mining). Incomplete documentation is available here: https://github.com/nicehash/excavator/tree/master/api

**Comment by jcodejedi** [comment]
Works like a charm! Thank you!
