### ISSUE TITLE
QuickMiner keeps stopping 

### ISSUE THREAD

**Issue by Rukkit** [nicehash/NiceHashQuickMiner#199]
QuickMiner keeps stopping after mining for a little. Ever since the new update got installed, seemed to have this issue. Says my memory clock could be too high, but I went and reset all OC settings. Uninstalled and reinstalled QuickMiner, restarted PC, and still no
![miner](https://user-images.githubusercontent.com/16450397/111012833-a8f73280-835a-11eb-92b8-c6616769aeb9.PNG)
 luck.

**Comment by nicehashdev** [comment]
Try to delete folder dagcache. Does that solve your issue?

**Comment by Rukkit** [comment]
> Try to delete folder dagcache. Does that solve your issue?

Tried that right now. Still does the same issue. I even uninstalled and reinstalled Nvidia drivers. Not sure what to do.

**Comment by dcup17** [comment]
I had same issue, are you using afterburner? I had to drop my memory then bring it back up once nicehash was running again, other wise i had the exact same issue and im also using a 2060 super

**Comment by nicehashdev** [comment]
Please, activate full logging, then make this bug happen and attach exported logs here. I will check if there is something wrong with memory OC reset during DAG generation.

**Comment by nicehashdev** [comment]
Also, what I have noticed is that once you have a driver crash, or too wild OC, even reducing that down to safe values, does not help. Driver needs to be restarted - reboot of PC is needed. If you didn't do it, try that first and then go straight to NiceHash QuickMiner without any OC. Does it work?

**Comment by Matts-Hub** [comment]
Same issue with my 2060. rebooting pc didn't help, nor did deleting the dagcache folder. I had to uninstall and reinstall NHQM, start mining with no OC set and then set it after a few minutes

**Comment by nicehashdev** [comment]
Please, enable logging and attach exported logs zip file here so I can inspect what happened.

**Comment by Rukkit** [comment]
> I had same issue, are you using afterburner? I had to drop my memory then bring it back up once nicehash was running again, other wise i had the exact same issue and im also using a 2060 super

I wasn't using afterburner at all. But I guess I'll try doing what you did.

**Comment by Rukkit** [comment]
> Same issue with my 2060. rebooting pc didn't help, nor did deleting the dagcache folder. I had to uninstall and reinstall NHQM, start mining with no OC set and then set it after a few minutes. I have only been using OCTune, not afterburner.

Same with me, I did all that you did as well. I didn't have any OC software. I used OCTune to force factory defaults. And still didn't have any luck.

**Comment by Rukkit** [comment]
> Please, enable logging and attach exported logs zip file here so I can inspect what happened.

Just to be clear I tried:
1. Uninstalling and reinstalling NHQM
2. Using OCTune to force a reset on all settings.
3. Reinstalled Nvidia drivers, selecting "clean install" to delete old stuff
4. Of course restarted, turned on/off, PC

So I downloaded Afterburner to make sure there is no OC on my graphics card. There was none. Reinstalled NHQM again and left the optimization of "manual" and it started to still do the same thing. Would stop and restart the miner about every minute. So I selected "medium" optimization, and now the miner has been working fine for about 13 minutes. So looks good for now, not sure what caused it to fail with no optimization? 

I enabled logging and it should be attached. Wonder if you can see what the issue might have been. Seeing as I'm not the only one that experienced the same issue with my 2060 Super.
[exported_logs.zip](https://github.com/nicehash/NiceHashQuickMiner/files/6138058/exported_logs.zip)

**Comment by Rukkit** [comment]
Ok, after a couple of hours of being fine. It's now doing the same thing again..... I attached the log 
[exported_logs.zip](https://github.com/nicehash/NiceHashQuickMiner/files/6138697/exported_logs.zip)

**Comment by PedroC1999** [comment]
I am also getting this issue, 3080 FE, Curve Undervolted/Overclocked by AfterBurner.

Works fine for a little while, then hash drops to 0 H/s, then the console comes up with Shutting Down followed by http | closing.
In OCTune events section, there is a logspam of "Cannot connect: /cuda_devices". Killing the process in task manager forces excavator to restart, and it goes back to working again for a little while.

[logs_nhqm.txt](https://github.com/nicehash/NiceHashQuickMiner/files/6144961/logs_nhqm.txt)
[excavator_log_2021-03-15_22-44-50.002.txt](https://github.com/nicehash/NiceHashQuickMiner/files/6144962/excavator_log_2021-03-15_22-44-50.002.txt)

**Comment by nicehashdev** [comment]
I see that you have used OPTIMIZE. OPTIMIZE is not compatible with manual OC. You need to set manual OC. I see that your device speed has dropped to 0 thus QuickMiner has performed your chosen recovery action.

Out of the log, it is is hard to see what exactly happened - because speed simply dropped to 0, GPU load as well. As if something started blocking excavator from executing further tasks. First, make absolute 100% sure, that no AV is blocking excavator. There are huge issues recently regarding that and the symptoms are very similar to your description - it works for few minutes then it stops.

**Comment by PedroC1999** [comment]
@nicehashdev I appreciate the response, but my "solution" does somewhat disprove that.

I was having many issues as described, but the "App" version was fine, I noticed the "App" used a different version of Escavator. I went on Github and downloaded the latest, copied it into the QuickMiner directory, replacing the old version, and its been fine since.

This is indicative that the issue was not Optimising or AfterBurner, but something you may want to look into.

**Comment by nicehashdev** [comment]
You mean the old Excavator works fine, but new one has issues? Which one works fine? Give me build number of version number.

**Comment by PedroC1999** [comment]
The Excavator included with Quick Miner (1.6.7) did not work, the Excavator from NHM (1.6.2 I believe?) worked, however https://github.com/nicehash/excavator/releases/tag/v1.6.7c this version here worked. Unsure why, but these are my findings

**Comment by nicehashdev** [comment]
This all points to the issue of some AV blocking certain functionalities of Excavator. Also, try latest 0.4.1.4 RC. Does it work?

**Comment by PedroC1999** [comment]
Everything is working for me right now, I already had the Quick Miner
directory whitelisted and ignored within Windows Defender, changing the
Excavator.exe from one to another was all I did.

**Comment by nicehashdev** [comment]
Does the 0.4.1.4 RC has this issue or not? This is what I would like to know now.

**Comment by PedroC1999** [comment]
> Does the 0.4.1.4 RC has this issue or not? This is what I would like to know now. And we had less issues with the old version (build 550) - it was never flagged as PUA by Defender. That could explain issues.
> 
> Making exclusion is not enough. You need to trigger Defender by running the executable and then manually select to "Allow on device". This is the only way to solve this issue unfortunately. And if you do not get trigger or no UI to select, then we recommend to perform scan of directory which may find it as PUA and then consequently display dialog where you can select to "Allow on device". More about it here: #204

I updated to the latest today, and it is fine as before

**Comment by nicehashdev** [comment]
Looks like solved. Closing.

**Comment by Rukkit** [comment]
I've tried the RC version, also didn't work for me. Issue isn't solved for me.

**Comment by ZenicaPA** [comment]
I have this issue on a new rig. Windows 10 20H2. Latest Nicehash version. .4.5.5. with Excavator 1.6.11f
Randomly happens. Usually I'll see the "could not obtain power consumption" in the Excavator log a few lines up from the "shutting down" "http closing".

I have the latest NVIDIA drivers as of today. I completely disabled Windows defender and Firewall as there is nothing else on this rig, software wise and I figure if my router didn't keep anyone out, Windows wouldn't be my savior.

**Comment by brainbug69** [comment]
> I have this issue on a new rig. Windows 10 20H2. Latest Nicehash version. .4.5.5. with Excavator 1.6.11f
> Randomly happens. Usually I'll see the "could not obtain power consumption" in the Excavator log a few lines up from the "shutting down" "http closing".
> 
> I have the latest NVIDIA drivers as of today. I completely disabled Windows defender and Firewall as there is nothing else on this rig, software wise and I figure if my router didn't keep anyone out, Windows wouldn't be my savior.

mate, any solution you got for this issue?
