### ISSUE TITLE
NVML

### ISSUE THREAD

**Issue by Senor2** [nicehash/NiceHashQuickMiner#2]
Whenever I try to open the miner it gives an error saying "unable to initialize NVML"

**Comment by Stardock2018** [comment]
same
![image](https://user-images.githubusercontent.com/37783446/107796474-20638300-6d17-11eb-87f2-4be8f821e11a.png)

**Comment by nicehashdev** [comment]
Please, tell me following:
- Your Windows version? x32 perhaps?
- Version of your NVIDIA drivers?

Are you aware that this is NVIDIA miner only?

**Comment by wwilsonn91** [comment]
I am having the same issue. 
Platform: Microsoft Windows [Version 10.0.18363.1316]
Arch: x64
(I don't know if this is relevant): I also don't have an NVidia device - I'm running an AMD Radeon RX580 Series 8GB device.

**Comment by cakonopka** [comment]
Same issue here too. Windows 10.19042 Build 19042
Using AMD Cards, 2X 5700's

**Comment by PurpleRose81** [comment]
Using AMD GPU on a Nvidia only miner? Of course it doesn't work you sillies. It even said so in the documentation that is was for Nvidia only.

**Comment by wwilsonn91** [comment]
> Using AMD GPU on a Nvidia only miner?

@PurpleRose81, do me a favor and read this:
> Supported hardware:
> 
> NVIDIA GeForce GTX 1000 series with min. 6 GB of GDDRAM,
> NVIDIA GeForce RTX 2000 series with min. 6 GB of GDDRAM,
> NVIDIA GeForce RTX 3000 series with min. 6 GB of GDDRAM,
> Intel CPUs with AVX2,
> **AMD CPUs with AVX2.**

Note: I bolded the portion of it that's relevant to your statement.

**Comment by PurpleRose81** [comment]
@wwilsonn91 You stated that you are using an AMD GPU. That is not supported by this experimental program. I am using it with my Ryzen 5 2600 and Nvidia RTX2060 with no issues. That is with mining on both CPU and GPU. Your issue is you trying to use an AMD GPU on a Nvidia GPU only miner. No where in the supported hardware did it list AMD GPUs.

**Comment by Senor2** [comment]
> Please, tell me following:
> 
> * Your Windows version? x32 perhaps?
> * Version of your NVIDIA drivers?
> 
> Are you aware that this is NVIDIA miner only?

Windows is x64 and im running a 1070
Nvidia driver version is: 384.76

**Comment by nicehashdev** [comment]
You need to have drivers version of min. 458+. Yours is 384 which is obviously not enough. Please, install latests drivers.

Also, this is NVIDIA driver - if you do not have NVIDIA device [specified here](https://github.com/nicehash/NiceHashQuickMiner/wiki/Supported-hardware), it will not work for you.

Only having capable CPU is not enough, this is primary a GPU miner but has a possibility for CPU mining so GPU miners do not have to install extra CPU miner when doing GPU mining!
