### ISSUE TITLE
DLL error while installing

### ISSUE THREAD

**Issue by rfunk2** [nicehash/NiceHashQuickMiner#20]
When I run NiceHashQuickMiner.exe I get an error message: Unable to load DLL 'nvml': The Specified module could not be found. (exception from HRESULT: 0x8007007E)

![Capture](https://user-images.githubusercontent.com/79022268/107859531-271df300-6e08-11eb-972e-a655ba6d459d.JPG)

**Comment by rfunk2** [comment]
So after reading further, This might not work with AMD Graphics cards (:

**Comment by nicehashdev** [comment]
No, it does not work if you do not have NVIDIA card. Closing.
