### ISSUE TITLE
Unable to load DDL nvml: the specifed module could not nobe found.

### ISSUE THREAD

**Issue by dinocollufio** [nicehash/NiceHashQuickMiner#202]
this is the error just executing for the first time the STABLE version.

I have not any NVIDIA card...so... what the file is looking for that?

NiceHash_QuickMiner_v0.4.1.3.zip
 100% useless for me... I have only one RX 580 4G card...

**Comment by nicehashdev** [comment]
NiceHash QuickMiner does not work on PCs without NVIDIA video card. List of supported hardware is here: https://github.com/nicehash/NiceHashQuickMiner/wiki/Supported-hardware
