### ISSUE TITLE
Hide Excavator window while mining.

### ISSUE THREAD

**Issue by Crimsom13** [nicehash/NiceHashQuickMiner#203]
I can't get to seem this function to work, so I can't fully transfer all my computers over yet, I like to play older games while mining and if the excevator window does not hide, it's kind of a deal breaker, Tried manually 

"bHideMiningConsole" : True,

Doing hide mining window in the ini file but it still pops up, please fix Asap!

Thanks.

**Comment by Crimsom13** [comment]
Also if we have multiple video cards, make sure we can toggle just the one we are using off like the old version.

**Comment by nicehashdev** [comment]
Not sure which version you use, but latest version works completely fine with this flag. Perhaps the issue is `True` must be `true`. Try it out.

**Comment by Crimsom13** [comment]
Ok, sorry I'm use to old video game inis that have capital letters, still hesitant to move my main rig over because I don't see individual gpu on off controlls yet.

Thanks!

**Comment by nicehashdev** [comment]
You can turn on/off certain GPU via Rig Manager (click stop/play button).

**Comment by Crimsom13** [comment]
Ok, I'll try that do you think you could add an option to do it in the actual right click context menu? going to rig manager might get tiring especially if I want to turn off on my my gpus to play a quick game with friends?

I'll switch over my main computer now, keep up the good work.

Thanks again!

**Comment by nicehashdev** [comment]
Regarding fan: https://github.com/nicehash/NiceHashQuickMiner/wiki/Troubleshooting#i-am-using-another-tool-for-managing-my-video-cards-fans-such-as-msi-afterburner-and-fan-speed-is-occasionally-reset-to-automatic-how-can-i-fix-this

You can customize all actions by making your own commands.json file.
