### ISSUE TITLE
OCtune not work newest RC version

### ISSUE THREAD

**Issue by jonneb** [nicehash/NiceHashQuickMiner#205]
Newest RCversion OCTune say Failed if click "selected" (and one card gtx1080 is selected), if click all, not say failed, but core clock / mem clock not changing... Older RC version works fine...

**Comment by nicehashdev** [comment]
Can you be more specific please? Give more details what exactly you did to trigger the bug.

**Comment by nicehashdev** [comment]
No reply. Closing.
