### ISSUE TITLE
I cant get ride of that notification after after latest update and right clicking on taskbar doesnt bring up any of those options,...

### ISSUE THREAD

**Issue by dcup17** [nicehash/NiceHashQuickMiner#207]

**Comment by dcup17** [comment]
Cant click on the banner that says ok i understand, only min or close that banner, and closing it closes miner

**Comment by OutrunSZN** [comment]
I have the same issue I can't access Quickminner through the context menu.

**Comment by dcup17** [comment]
Ive reinstalled so much that last day not very profitable, does your nicehash auto start? or do you have it turned on? Mine opens the program than just does nothing until i manual start

**Comment by OutrunSZN** [comment]
When I open Nicehash nothing happens until I start it on the website so no it doesn't autostart

**Comment by dcup17** [comment]
Right, kinda garbage if you ask me, defeats the purpose of an auto start, At least im not the only one, i figured i screwed something up during install so re did it like 5 times yesterday

**Comment by nicehashdev** [comment]
First, make sure that Defender is not blocking it by reading this: https://github.com/nicehash/NiceHashQuickMiner/issues/204

When you are sure that nothing is blocking it, then NiceHash QuickMiner is started automatically if you turned it off WITHOUT stopping it first. But if you stop it before turning it off, then it will start in stopped state and waiting for be started. So, if you want it to start mining when it starts, do not stop mining before you turn it off (or before you shut down or restart PC) - just keep it mining.

**Comment by nicehashdev** [comment]
Oh and regarding that dialog showing how to handle NiceHash QuickMiner - you can close it when you perform any action with context menu of the app - make sure you right click NiceHash icon on the RIGHT side of your screen and not left.

**Comment by dcup17** [comment]
Great, thanks team, just gonna power down here soon and see what that does, thanks for the help
