### ISSUE TITLE
Windows Defender block :- Win32/Wacatac.B!ml and Win32/Wacapew.C!ml as Trojan

### ISSUE THREAD

**Issue by Ar-Myn** [nicehash/NiceHashQuickMiner#208]
Hi Team,

I have major 2 question as below,

1)  I enable the auto update and once it updated windows defender blocked those two files show in below.

I already checked and confirmed the checksum before install in the beginning. So my **first question** is, is this 2 files allow in PC is **risk free or not**? 

![image](https://user-images.githubusercontent.com/80310887/111056434-64ca7600-84b1-11eb-8724-d9202f31540b.png)

![image](https://user-images.githubusercontent.com/80310887/111056478-a6f3b780-84b1-11eb-88bc-d12d312bf881.png)

2) However windows defender block this file since I update the the QuikMinner and  So I thought it is safe to allow them and I followed below steps,

1. Go to windows defender and unfortunately I select the "Start Action" in Defender. So defender is automatically removed those file. 
2. After I allowed those 2 files in  "Protection History" in Windows Defender.
3. So I tried to open the QuickMinner, its show error massage and ask me to Download and Overwrite. So there is no other option, I tried it(I choose RC version for download and overwrite). After few seconds its show again error massage to can't install.
4. So I closed that error massage and try to re-open the QuickMinner. Then again pop up the error massage.
5. 3rd time also i tried to closed that error massage and re-open the QuickMinner. At that time quick miner started normally.
6. its running without any errors and  I check the version and it's latest version(V 0.1.4.3) 

So my **2nd question** is,  I would like to know that above I **mentioned process is okay or not**? Or else I have to **uninstall the QuickMinner and reinstall it** ?

**Comment by nicehashdev** [comment]
These files were submitted to Microsoft on Friday already and we still got no response back. You can check whether file is authentic by right clicking the file, then going to Digital Signatures and there should be two signatures from company H-BIT, d.o.o. Serial number of the certificate is **0632554c6eec69c3efa44f842175e710**. If this matches with your files, then you can authentic files and you do not have to worry about it.

If everything is working normally, then you do not have to reinstall anything. If you have some issues, then it is better to reinstall.

Also check out this issue as it is related to your question: https://github.com/nicehash/NiceHashQuickMiner/issues/204
