### ISSUE TITLE
i already download but the file didnt appear it on my local pc 

### ISSUE THREAD

**Issue by asbilhasif** [nicehash/NiceHashQuickMiner#209]
![Screenshot 2021-03-14 180942](https://user-images.githubusercontent.com/80506120/111064734-aaf2fa00-84f0-11eb-927c-0b47c5a45fe1.jpg)

**Comment by nicehashdev** [comment]
If you have already installed NiceHash QucikMiner and you used default installation path, then NiceHash QuickMiner is located under _C:\Program Files_.

If you have problems downloading, please check out this issue: https://github.com/nicehash/NiceHashQuickMiner/issues/204
