### ISSUE TITLE
[Feature Request] Add Global Hotkeys

### ISSUE THREAD

**Issue by Nayrboh** [nicehash/NiceHashQuickMiner#210]
It would be great if we could have global hotkeys so I could control the quick miner with my stream deck. For things like Start, Stop, Gamemode, etc.

**Comment by nicehashdev** [comment]
There is a plan to introduce all the important features to be available through Rig Manager which means eventually through mobile apps and remotely from any place as long as you have access to your account. Some functionality is already available such as starting/stopping and disabling/enabling certain devices plus of course, OPTIMIZE feature. Then there is also remote rig reboot and name change possible.
