### ISSUE TITLE
NVIDIA Driver Update Error

### ISSUE THREAD

**Issue by smithpet001** [nicehash/NiceHashQuickMiner#211]
Hello,

When attempting to install the current-version quickminer that is available here, an error appears that says "Invalid NVIDIA driver version. Minimum is 458.00 / Please, install latest NVIDIA drivers!"

The problem is that, according to Windows Device Manager, I already have the latest driver.

Is this a bug? Or am I unaware of a problem with Windows drivers?

Thanks!!

**Comment by Warp15** [comment]
go to nvidia.com

**Comment by nicehashdev** [comment]
You can check driver version with tool such as GPU-Z, which will tell you that you have outdated version.

**Comment by smithpet001** [comment]
Ahhhh I’m so dumb. I trusted Windows. What a mistake!! Haha. Thanks!
