### ISSUE TITLE
add to FAQ

### ISSUE THREAD

**Issue by daimonkori** [nicehash/NiceHashQuickMiner#212]
Dear nicehashdev
In my question "disable update # 194" I asked a question related to the removal of profiles, where you provided a link to the configuration file: https://github.com/nicehash/NiceHashQuickMiner/blob/main/optimize/data_003.json but this is not the case.
The appeal goes to the address https://raw.githubusercontent.com/nicehash/NiceHashQuickMiner/main/optimize/data_003.json and if the resource https://raw.githubusercontent.com is blocked, we get the error "Not initialized yet". Please add to the FAQ. Thank

**Comment by nicehashdev** [comment]
Will think about some solution and text...

**Comment by nicehashdev** [comment]
Added: https://github.com/nicehash/NiceHashQuickMiner/wiki/Troubleshooting#when-trying-to-apply-optimize-i-get-error-not-initialized-yet
