### ISSUE TITLE
RTX 2060 Super :-  Possible best hashrate  and Possible best Efficiency

### ISSUE THREAD

**Issue by Ar-Myn** [nicehash/NiceHashQuickMiner#217]
Hi Team,

As I see in the README.md it says the RTX 2060 super excepted hashrate is 44 MH/s and in supported hardware under Wiki didn't mention.

I using  3 different geforce high end cards and it gets the fixed **41.55 MH/s** hashrate and  average efficiency around **380 kH/J** 

So its better be update. Just my suggestion due to new user compare the hash rate of   RTX 2060 super, RTX 2070 super  and RTX 2080 super on the README.md, he will probably go RTX 2060 super(less price compare to other 2)

**Comment by nicehashdev** [comment]
It all depends on chip quality. Some RTX 2060 SUPER can reach 44, some can reach only 41. Same goes for efficiency. Some chips use less voltage at given frequency, some use more. There can be huge differences in efficiencies even among same models of the same vendor.
