### ISSUE TITLE
DLL nvml missing

### ISSUE THREAD

**Issue by Total2021Novice** [nicehash/NiceHashQuickMiner#220]
After a fresh installation NiceHashQuickMiner starts, but crasshes with message "DLL nvml missing".
Switching-off the Firewall didnt help.
There is no such dll in Program Files/NiceHash
![image](https://user-images.githubusercontent.com/80676504/111128425-2a2a1180-8575-11eb-894c-3ec1bb959f25.png)

Win 10, absolute novice.
Thanks!

**Comment by slickhick** [comment]
having the same problem

**Comment by nicehashdev** [comment]
You need to have NVIDIA video card. If you do not have NVIDIA video card, then this would be the error you get.

**Comment by kikaider69** [comment]
> After a fresh installation NiceHashQuickMiner starts, but crasshes with message "DLL nvml missing".
> Switching-off the Firewall didnt help.
> There is no such dll in Program Files/NiceHash
> ![image](https://user-images.githubusercontent.com/80676504/111128425-2a2a1180-8575-11eb-894c-3ec1bb959f25.png)
> 
> Win 10, absolute novice.
> Thanks!

I just tried loading it up both 441 and 431 as well and get the same error
