### ISSUE TITLE
Support for 10 series nvidia cards

### ISSUE THREAD

**Issue by MarcoLeder** [nicehash/NiceHashQuickMiner#221]
Dear Nicehash

Feature request: 
Please add support for Nvidia 10 series cards so I can use my 1060 for mining with quick miner :)

Many thanks
Marco Leder

**Comment by nicehashdev** [comment]
NVIDIA 1000 series cards are already supported, but you need to have 6GB of VRAM. Detailed list is here: https://github.com/nicehash/NiceHashQuickMiner/wiki/Supported-hardware

**Comment by MarcoLeder** [comment]
Is there a way to get rid of the 6gb limit? (altering some lines of code mybe?) I have a 1060 with 3gb ^^ 
Best, Marco

**Comment by nicehashdev** [comment]
Unfortunately not. It could be possible to solve the issue by offloading some needed data to the host memory, but then the problem is low bandwidth of PCIe so the end speed would be very low (perhaps several MH/s) thus income generated not worth the trouble.
