### ISSUE TITLE
OC tune - multiple failures

### ISSUE THREAD

**Issue by beelzebubbles** [nicehash/NiceHashQuickMiner#222]
NiceHash v.0.4.1.3 Stable
Excavator is working fine, but when I go to OC tune I get multiple problems:
1. Log keeps saying: Failed to get cuda devices (although NiceHash Dashboard seems to recognize my GPU)
2. When I try to change any settings I get: Failed to save current command (e.g. TARGET GPU TEMP, 68C)

Setup:
ryzen 3950
ASUS TUF 3080

**Comment by nicehashdev** [comment]
This looks like Defender blocking excavator.exe. Please read this: https://github.com/nicehash/NiceHashQuickMiner/issues/204

Make sure that no files from NiceHash QuickMiner are being blocked.

**Comment by beelzebubbles** [comment]
thanks for the help, for some reason defender was not showing that it was blocking excavator
