### ISSUE TITLE
RTX 3080 Hashrate between 20-60 MH

### ISSUE THREAD

**Issue by CptCrunchy24** [nicehash/NiceHashQuickMiner#223]
I've been running NiceHash QuickMiner for two weeks now and I can barely get 80MH from my 3080 for more than a few hours when I'm supposed to get up to 100MH.
I've tried manually over/underclocking and using the Lite/Medium settings to auto-optimise but I'm still getting an average of 40MH and as low as 20MH.
I'll occasionally get short bursts of speed up to 80MH but it doesn't last long and the memory temperature is at 110 degrees the whole time.
The airflow in my case should be pretty decent. Core temps never exceed 60 degrees and I've heard others getting much more performance before their card starts thermal throttling. When I set power limit to about 60% it won't thermal throttle but I won't get anything above 40MH either.

![image](https://user-images.githubusercontent.com/76537316/111202096-67b18d80-85bb-11eb-888e-6563dfd21df8.png)

Did I lose hard on the silicon lottery or is it normal for hashrates to vary this wildly?

**Comment by helinus** [comment]
You need to check your Memory Junction/VRAM temperature, It's probably throttling because that temperature got too high.

**Comment by CptCrunchy24** [comment]
Yeah the VRAM gets to 95 degrees when I've got power limited to 170W. It doesn't thermal throttle until 110 degrees. Thermal throttling doesn't explain why I'm sitting at less than 20MH for hours though. Here's what I have on OCTune right now:

![image](https://user-images.githubusercontent.com/76537316/111236325-74010f00-85ea-11eb-8ea2-085b588bec0f.png)

**Comment by helinus** [comment]
Try the One click optimize: https://github.com/nicehash/NiceHashQuickMiner/wiki/One-click-Optimizations

**Comment by CptCrunchy24** [comment]
Yeah I have already tried the auto-optimisation modes and I get the same results as manual overclocking. I tried closing everything else down on my PC and it turns out Wallpaper Engine was reducing hashrate to 20MH/s but I still can't get above 60MH/s consistently even after shutting down every other process.

**Comment by helinus** [comment]
Post a screenshot of octune after you've set Optimize in rig manager to Lite

**Comment by CptCrunchy24** [comment]
I'm currently getting 67 MH/s but it's thermal throttling if I set to Lite.

![image](https://user-images.githubusercontent.com/76537316/111300232-c07b3780-8648-11eb-88a7-1285ce6205b7.png)


Medium is higher but also thermal throttling.

![image](https://user-images.githubusercontent.com/76537316/111300298-d7218e80-8648-11eb-8a48-16fbb7394bea.png)


My manual settings are getting me 55 MH/s without thermal throttling.

![image](https://user-images.githubusercontent.com/76537316/111300451-00421f00-8649-11eb-834a-a2ee691482ad.png)

**Comment by helinus** [comment]
You need to fix the cooling, either the card isn't getting enough cold air from the case fans or the cooler design of that GPU is really bad.

**Comment by CptCrunchy24** [comment]
That's strange because it's really cold in my house and I was hoping mining would help heat it up! I have two fans on the bottom of the case blowing straight into it. It's the founders edition so I would have thought with it's passthrough fan this should work really well.

**Comment by helinus** [comment]
> Have I just got really unlucky with the thermal pads on my VRAM?

Looks like it. And the Founders Edition doesn't have the same cooling performance as some of the other variants.

**Comment by CptCrunchy24** [comment]
I didn't think the difference would be this vast though. You've got other people easily getting 80-100 MH/s out of the box and I can only get 50-60 MH/s while keeping the temps at a safe level. It seems to be staying pretty consistent now that I've turned Wallpaper Engine and Steam off at least. But it'd be nice if I could get some more performance out of it.

**Comment by nicehashdev** [comment]
You obviously have issues with cooling your VRAM. Whenever VRAM is above 105 C, the speed may be reduced due to the temperature throttling. If you do not want to make physical adjustments to the card to fix overheating, then I suggest to set memory OC to minimal possible clock (-1000). According to this setting, set max core clock limit (alternative OC) and also adjust SmartFan (target VRAM) and keep your VRAM below 100 C. In Rig Manager, you should choose Manual optimization.
