### ISSUE TITLE
Additional User/Game Mode

### ISSUE THREAD

**Issue by JoergHbk** [nicehash/NiceHashQuickMiner#225]
Any chance to add a second/alternate Game/User Mode.

I just would like to have a mode which I can quickly activate for less power usage and NOISE.

It's just annoying when you are on an internet conference call and the system speeds up the fans. I happy to take a hit in the hashrate for having a quite mining mode.

Thanks

**Comment by nicehashdev** [comment]
There are plans for more OPTIMIZATION profiles which are coming in following weeks.

**Comment by Hukuma1** [comment]
Could I also suggest an implementation of ability to schedule specific profiles please? Ability to schedule this automatically/autoMAGICALLY would be most appreciated. Just using system time would suffice probably. (fans at 8am to 11pm at 100%, 11:01pm to 7:59am fans at 60%)

**Comment by nicehashdev** [comment]
Please, open another ticket for another enhancement. This issue is closed.
