### ISSUE TITLE
RTX 3060 optimization not working

### ISSUE THREAD

**Issue by wujin941005** [nicehash/NiceHashQuickMiner#226]
Lite and medium optimization setting is not working on my RTX 3060, no overclocking or underclocking has been done on the card. 

NHQM version is v0.4.1.3 stable, Nvidia driver is on Developer Game Ready 470.05.

**Comment by Goran456** [comment]
I have RTX 3060 and I have used the OCTune for overclocking. I got 43Mh/s at 100W with temperatures around 45 Celsius.

I have seen on [Reddit](https://www.reddit.com/r/NiceHash/comments/m6b38z/3060_4950_mh_17_hours_strong/?%24deep_link=true&correlation_id=40d32bfc-6456-4ce0-9633-ec7b58e47e41&post_fullname=t3_m6b38z&post_index=1&ref=email_digest&ref_campaign=email_digest&ref_source=email&utm_content=post_title&%243p=e_as&_branch_match_id=894872598246431778) even better results, with 50Mh/s but with manual overclocking. I tried multiple time using OCTune to get those results, but no luck. Any idea if in the future we are gonna get better optimization with OCTune?

**Comment by nicehashdev** [comment]
The optimization profiles were not tuned for recent RTX 3060 unlock. This needs to be done yet.

**Comment by nicehashdev** [comment]
Restart NiceHash QuickMiner and the problem should be fixed. You should get over 45 MH/s with around 100 W now.

**Comment by nicehashdev** [comment]
I have just noticed that 470.05 drivers use altered naming for CUDA devices which makes OPTIMIZE not work. Making new version to fix this issue. Should be shortly available.

**Comment by nicehashdev** [comment]
This problem is fixed in latest version 0.4.1.4 RC.
