### ISSUE TITLE
keep getting error "failed to get power limits" on quickminer 0.4.1.3

### ISSUE THREAD

**Issue by 0196071** [nicehash/NiceHashQuickMiner#227]
![Screenshot 2021-03-16 113338](https://user-images.githubusercontent.com/3613658/111336284-7ba4d000-864b-11eb-949f-6714c8e3f0b2.png)

keep getting this error when trying to mine on laptop

**Comment by 0196071** [comment]
i was able to make it work with the error still there by activating debug and developer mode on nvidia control pannel
![image](https://user-images.githubusercontent.com/3613658/111355890-2faf5680-865e-11eb-90bf-a4358ff2bf16.png)
![image](https://user-images.githubusercontent.com/3613658/111355924-38a02800-865e-11eb-87ed-4c737a5f186e.png)

and going to the new option "manage gpu counters" and selecting this option
![image](https://user-images.githubusercontent.com/3613658/111356068-5d949b00-865e-11eb-8fa6-df1d41a9774c.png)

**Comment by nicehashdev** [comment]
Laptops are officially not supported. Supported list is here: https://github.com/nicehash/NiceHashQuickMiner/wiki/Supported-hardware
That being said, regardless of this warning, mining may still work, you just may be unable to configure certain features.

**Comment by joezimjs** [comment]
@nicehashdev Is there a plan to support laptop GPUs at some point?
