### ISSUE TITLE
unable to deactivate game mode

### ISSUE THREAD

**Issue by knockreff** [nicehash/NiceHashQuickMiner#228]
unable to deactivate game mode -

When trying to deactivate game mode it give a error message "could not detect video card with connected display or you may be using an older video card for display"
When trying to close quickminer it gives an error because game mode is still active.  
When trying to pull the logs it actually started mining but still claimed to be in game mode.

running 1080 and AMD2290
v0.4.1.3 RC

**Comment by nicehashdev** [comment]
Please, enable full detailed logging, make the bug happen, then export logs and submit .zip file here. Thanks!

**Comment by slovenec88** [comment]
@knockreff, did you by any chance update nvidia drivers? Same happened to me, but reboot solves it.

**Comment by knockreff** [comment]
The error did occur after updating the drivers and hasn't happened again
yet.

**Comment by nicehashdev** [comment]
Looks like updating drivers during Game Mode is not a good idea. Will add this into troubleshooting and consider this issue as solved.
