### ISSUE TITLE
CLR error: 80004005 The program will now terminate

### ISSUE THREAD

**Issue by zombiemaker** [nicehash/NiceHashQuickMiner#229]
When starting the NiceHashQuickMiner.exe program, I get the error message "CLR error: 80004005 The program will now terminate".

**Comment by nicehashdev** [comment]
Let me know your operating system? NiceHash QuickMiner is fully supported only on Windows 10 x64.

**Comment by zombiemaker** [comment]
Windows 10 PRO 
Version 20H2
OS Build 19042.867

**Comment by nicehashdev** [comment]
Are you sure not antivirus is blocking any part of NHQM?

**Comment by nicehashdev** [comment]
No response, consider solved.
