### ISSUE TITLE
2 of the 3 fans of my gpu stopped working after using autotune

### ISSUE THREAD

**Issue by MM789123** [nicehash/NiceHashQuickMiner#230]
I'm having an issue with the fans on my gpu, i used the autotune first set to efficiency and then to speed to see what hashrates I could get and then i realized for the noise my gpu was making that 2 fans stopped working and 1 was set to 100% wihile it was tunning, then it was set to normal but just one fan kept going i dont know if i've broke the gpu or is a problem i can easily solve.

My gpu is an Nvidia gtx 1660 super aorus (gigabyte) and my OS is windows 10, let me know if u need more information to solve it.

Thank you for your attention

**Comment by nicehashdev** [comment]
You can always perform PC reboot to return everything into previous state. Let me know if that solves your issue.

**Comment by MM789123** [comment]
> You can always perform PC reboot to return everything into previous state. Let me know if that solves your issue.

Thank you for your answer, yes I' ve done that but haven't resolved the problem, just one fan is spinning @nicehashdev 
![IMG_20210317_125059](https://user-images.githubusercontent.com/80791610/111463307-b9732880-871f-11eb-98ee-ea2cc347de88.jpg)

**Comment by nicehashdev** [comment]
Reinstall drivers with clean reinstall. If that does not solve your issue then I am afraid that one of your fans has simply died.
