### ISSUE TITLE
Feature Request: Reboot if no compatible device found

### ISSUE THREAD

**Issue by Crusoe86** [nicehash/NiceHashQuickMiner#231]
I get this error, from time to time. But the PC will not restart like it does when I lost the Internet, the VGA driver crashes or the mining speed is to low / high.
Maybe the VGA driver is sometimes not fully loaded, when NiceHash starts.
Could you please implement a feature, that reboots the PC (after for e.g. 5min, to have enough time to look via TeamViewer etc.) when no GPU is recognized?

At the moment I increase the delay before starting NiceHash in the Task Scheduler. That helps the most times :)

Many regards
Chris :)

**Comment by nicehashdev** [comment]
This is already implemented, please check this: https://github.com/nicehash/NiceHashQuickMiner/wiki/Tips-&-tricks#3-define-what-happens-when-something-goes-wrong

**Comment by Crusoe86** [comment]
Please don’t mark unsolved issues as solved :D 
I use this options. Both at „3“.
But that seems not to work after the start when no GPU ist detected :/

**Comment by nicehashdev** [comment]
I have added this as an extra feature that will be implemented one day but no ETA.

**Comment by nicehashdev** [comment]
This feature has been added in 0.4.2.0 RC. Please, check here: https://github.com/nicehash/NiceHashQuickMiner/wiki/Tips-&-tricks#3-define-what-happens-when-something-goes-wrong
