### ISSUE TITLE
NH QuickMiner crashing 

### ISSUE THREAD

**Issue by LightChimera** [nicehash/NiceHashQuickMiner#234]
I've experienced constant crashing when attempting to start the quickminer in the last two days. It'll run for a couple of seconds, report an efficiency of 0.0 kH/J, then crash. I'm running a Ryzen 5 2600X on stock clocks, 16GBs of DDR4 at 3000MHz, and a GTX 1660 Super also at stock clocks (as in, they haven't been edited in the BIOS. I was running the medium optimization and it worked fine). The attached files are the complete reports from an instance where it had crashed. It mentions "resetting absolute core clock" and "postpone mem OC due to DAG gen" about half a second before it crashes. Help is appreciated. 

[excavator_log_2021-03-17_22-32-39.001.txt](https://github.com/nicehash/NiceHashQuickMiner/files/6160923/excavator_log_2021-03-17_22-32-39.001.txt)
[logs_nhqm.txt](https://github.com/nicehash/NiceHashQuickMiner/files/6160924/logs_nhqm.txt)
[excavator_log_2021-03-17_22-31-50.000.txt](https://github.com/nicehash/NiceHashQuickMiner/files/6160925/excavator_log_2021-03-17_22-31-50.000.txt)

**Comment by LightChimera** [comment]
The issue seems to be similar to one posted by PixelParallax two days ago.

**Comment by nicehashdev** [comment]
No, you have different issue. Your DAG simply does not get generated in whole 45 seconds. Something is consuming your GPU power, all of it. Another program, or even miner in the background.

You can try setting `"whenDeviceSpeedZero" : 1` in _nhqm.conf_ to disable Excavator being killed, but even if your DAG gets generated eventually, speed will be very very low. I suggest you analyze and figure out what is using your GPU so wildly first and then problem will be fixed.

**Comment by nicehashdev** [comment]
This problem has been fixed.
