### ISSUE TITLE
[Suggestion] - Add a temperature for GPU and Hotspot control by user in optimize settings

### ISSUE THREAD

**Issue by alanceloth** [nicehash/NiceHashQuickMiner#236]
Hi!
I was wondering, can we have a temperature control, like a type field to setup the temps for an optimized setting.
For example, I choose the medium preset and the temps  for my profiles are "ftg" : 58, "ftr": 74 :
![image](https://user-images.githubusercontent.com/11635850/111631047-b9336580-87d1-11eb-8c23-944a7b80475a.png)

But, what if I want to change this value to 47? The only impact will be in the fan speed, and not in the clock and mem config. So, I think that this will be helpful to some users (like me and my friends).

**Comment by gigaplex** [comment]
That's what the OCTune functionality is for. There's a section in there to change only the fan speed settings.

**Comment by alanceloth** [comment]
But, if you choose a profile in the OCTune, the Optmize function will overwrite this preset. I've tested early.

**Comment by nicehashdev** [comment]
You will have an ability to create own profiles in the near future, which should make things much easier. This feature is already on todo list.
