### ISSUE TITLE
Excavator - Failed Init Cuda

### ISSUE THREAD

**Issue by Vitor1939R4** [nicehash/NiceHashQuickMiner#237]
How i fix this error?

![Captura de ecrã total 18032021 211729 bmp](https://user-images.githubusercontent.com/80922836/111692193-7607df80-882f-11eb-9a45-7093de891ebb.jpg)

**Comment by alanceloth** [comment]
I've got a similar error when I try the Optimize Medium feature.. They said that is related to the TDP, some kind of error that my card can't handle the profile

**Comment by nicehashdev** [comment]
Could you please enable full logging and submit logs? Is there 3rd party OC tool that is messing with the clocks? Excavator on it's own reduces mem OC to 0 so that DAG generation cannot fail. This looks like something bypassed this protection by setting higher mem clocks.

**Comment by nicehashdev** [comment]
I am still waiting for logs to see whether memory OC was reset before DAG generation or not.

**Comment by nicehashdev** [comment]
No logs provided. Closing.
