### ISSUE TITLE
Excavator crashes every few minutes

### ISSUE THREAD

**Issue by Antoine-BL** [nicehash/NiceHashQuickMiner#240]
I've been having an issue where Excavator crashes and restarts every few minutes. I had been using the quickminer for the past three days without any issues. Today it suddenly started crashing like this every 5 minutes or so like clockwork. It does manage to mine properly between these crashes.

When these crashes happen I'm not typically doing anything GPU intensive. Just browsing the web or doing Zoom calls.

I am mining on a 2060 SUPER with 8GB VRAM

Here are the exported logs.
[exported_logs.zip](https://github.com/nicehash/NiceHashQuickMiner/files/6168738/exported_logs.zip)

I saw these lines right before the restart in the logs:
```
[[2021-03-19 01:02:48.556223] [thread=0x00004d90] [trace]]

	Response: {"id":1,"error":null}

[[2021-03-19 01:02:48.768977] [thread=0x00002d58] [warning]]

	device #0 | Failed init cuda (0) ctx: CUDA error 'all CUDA-capable devices are busy or unavailable' in func 'cudahelp::device_thread_init' line 154

[[2021-03-19 01:02:48.768977] [thread=0x00002d58] [debug]]

	wrkr0-0 | Worker thread ended

[[2021-03-19 01:02:48.768977] [thread=0x00003734] [info]]

	Shutting down

[[2021-03-19 01:02:48.769978] [thread=0x00003734] [debug]]

	cpu-miner | Stopping

[[2021-03-19 01:02:48.769978] [thread=0x00003734] [trace]]

	Executing: {"id":1,"method":"devices.smartfan.reset","params":[]}

[[2021-03-19 01:02:48.769978] [thread=0x00003734] [trace]]

	core | Command method: devices.smartfan.reset

[[2021-03-19 01:02:48.770977] [thread=0x00003734] [trace]]

	Response: {"id":1,"error":null}

[[2021-03-19 01:02:48.777979] [thread=0x00003734] [info]]

	http | Closing
```

**Comment by nicehashdev** [comment]
I haven't seen exactly this issue, but considering recent issues with Windows Defender, I would say you need to make sure that Excavator is 100% allowed on Defender.

**Comment by nicehashdev** [comment]
If it is not defender, then it must be your overclock. Especially, if you are mining with a laptop - OPTIMIZE buttons are not made for laptops.

**Comment by Antoine-BL** [comment]
I am on a desktop so cooling/power are probably not issues. 

However, selecting the lite preset seems to have avoided crashes. 

I still get the crashes on the Medium preset however. My GPU doesn't seem to be pushed very hard however. The fans only ever ramp up to 50% and my temps hover around 60C. 

I also made exception in Windows Defender, that doesn't seem to have helped. 

I guess I'll just have to tinker with manual settings to get better stability and performance. Overall it looks like an issue on my end. Thanks for the help and quick response!
