### ISSUE TITLE
"This app can't run on your PC"

### ISSUE THREAD

**Issue by Northy170** [nicehash/NiceHashQuickMiner#241]
Why do I get this when trying to install the Quickminer?

**Comment by Filipovnica** [comment]
Same for me, 4.1.3 version.

**Comment by nicehashdev** [comment]
NiceHash QuickMiner only works on Windows 10 x64 with following supported hardware: https://github.com/nicehash/NiceHashQuickMiner/wiki/Supported-hardware

**Comment by Northy170** [comment]
I should meet the requirements I suppose as I have  Windows 10 x64, ryzen 7 3700x and a 3060? Also tried with a 2070 but it works the same of course. Any help would be appreciated.

**Comment by nicehashdev** [comment]
Are you sure no AV is blocking QuickMiner? You need to 100% sure.

**Comment by Northy170** [comment]
I have tried turning both Windows Defender and AV completely off. Still, the exact same thing happens.

**Comment by nicehashdev** [comment]
Turning Defender off is not so simple; check here: https://github.com/nicehash/NiceHashQuickMiner/issues/204

**Comment by Northy170** [comment]
Tried step number two, no difference.

**Comment by nicehashdev** [comment]
How about if you try latest RC version? Does that happen as well?

**Comment by nicehashdev** [comment]
No response. Closing.

**Comment by Northy170** [comment]
Can't even download the latest RC version for some reason, so no solution yet
