### ISSUE TITLE
[Feature Request] Regenerate DAG if hashrate dips below threshold

### ISSUE THREAD

**Issue by AskAlice** [nicehash/NiceHashQuickMiner#242]
i do this manually a lot if i ever see my hashrate dip, i stop and start NHQM and it brings my hashrate back up.

If i could set a variable as to where it should never really be below, that would be great.

![image](https://user-images.githubusercontent.com/1855905/111809681-db44ea80-889a-11eb-996a-54a963c7201d.png)

**Comment by leovarmak** [comment]
+1

**Comment by nicehashdev** [comment]
This will not help you. I suggest you fix your original issue - too high temperature. This is going to fix your issue then.

**Comment by AskAlice** [comment]
@nicehashdev the too high temperature was on device 1. The speed dip was on device zero.

**Comment by nicehashdev** [comment]
If you are using Pascal based GPU, then there might be slight speed difference depending on DAG size. Pascals have issues with addressability of its TLB - when data of size more than 4 GB is being randomly accessed (in case of Eth DAG being over 4 GB). Thus TLB trashing is happening which reduces the speed. Maxwell 5.0 for example, has this limit at 1 GB, so some powerful Tesla Maxwell based cards are completely useless when it comes to mining Eth.

What you may be experiencing is luck - you get assigned to an order that is mining DAG 0000000... which is of size 1 GB and has much better performance on Pascal.

**Comment by AskAlice** [comment]
@nicehashdev i've had this happen before where it remains around 10 until i restart nicehash. i had just caught it early. The issue was mainly with an rtx 3070. there's a gtx 1070 at device 1-1 but I was not really experiencing issues with that hashrate.

**Comment by nicehashdev** [comment]
There is a well known memory leak in nvapi64.dll - connected to obtaining power usage. Perhaps, if as you said, happens after long uptime, the physical memory was exhausted and Windows started putting pages on HD thus slowing everything down? Check RAM usage next time.

And like I said, having logs of this event would help greatly.

**Comment by nicehashdev** [comment]
There was a fix that may solve your problem. Please check out latest RC version.
