### ISSUE TITLE
Rigs mining 0/1 not Working ??!

### ISSUE THREAD

**Issue by newbie2221** [nicehash/NiceHashQuickMiner#243]
Hello

i just installed the app and nothing is working...
drivers have been updated also, i dont know how to fix it...
![Captur3e](https://user-images.githubusercontent.com/80982254/111830362-1c1a1f00-88ee-11eb-99cf-da12c56768a2.PNG)
![Capture](https://user-images.githubusercontent.com/80982254/111830363-1cb2b580-88ee-11eb-9963-aebac2d78dbb.PNG)
![Capture1](https://user-images.githubusercontent.com/80982254/111830365-1cb2b580-88ee-11eb-963a-cd6668525990.PNG)
![Capture2](https://user-images.githubusercontent.com/80982254/111830367-1d4b4c00-88ee-11eb-9121-7d29411269f6.PNG)

**Comment by daimonkori** [comment]
you must use an adapter with 6GB of memory

**Comment by newbie2221** [comment]
Please can you paste link of an example , thank you from ebay or idk :)

daimonkori ***@***.***> (šajā datumā: Pk, 2021. g. 19. marts
20:31) rakstīja:

**Comment by nicehashdev** [comment]
This GPU is not supported. Check list of supported GPUs here: https://github.com/nicehash/NiceHashQuickMiner/wiki/Supported-hardware
