### ISSUE TITLE
Unable to find entry point named 'nvmlInitWithFlags' in DLL 'nvml'

### ISSUE THREAD

**Issue by HBenB** [nicehash/NiceHashQuickMiner#244]
I get this error right after installation.
I am using NVidia GeForce 310 with latest driver (342.01 Dec2016).
I added the "C:\Program Files\NVIDIA Corporation\NVSMI" to my environment path but still get the same error and cannot open the nicehash quickminer.
I also installed the RC release but same error pops-up.
![nvml dll Nicehash quickminer error](https://user-images.githubusercontent.com/80984932/111836865-617a2480-88cd-11eb-9a1b-4f3392724004.PNG).
Any help will be greatly appreciated.

**Comment by nicehashdev** [comment]
This card is not supported - too old.
