### ISSUE TITLE
Adjusting Memory timings to Reccomened for GTX 1080 causes BSOD on 4.2.0_RC

### ISSUE THREAD

**Issue by AlecWiese** [nicehash/NiceHashQuickMiner#246]
Running 0.4.2.0_RC and when adding the recommended memory timings for a GTX 1080 as outlined in the wiki page for [memory timings](https://github.com/nicehash/NiceHashQuickMiner/wiki/Memory-timings). 

i.e. the addition of the following lines to the commands.json file.
```
[{
		"time": 0,
		"commands": [{
				"id": 1,
				"method": "device.set.memory.timings",
				"params": ["0", "__MT0=16", "__MT1=4"]
			}]
```

My screens will switch to no signal for a few seconds, and then the BSOD appears. I'm hoping this isn't just an issue with my car, but I accept that this is a possibility.

the card is a Asus Strix GTX 1080, no OC enabled in nicehash OCtuner, or otherwise as I have no GPU tuning utilities installed. 

winDBG analysis snippt, can provide the whole file if needed, but it ends with "ANALYSIS_INCONCLUSIVE" so I'm not sure what help it may be. Let me know what other info I can provide.

```
VIDEO_SCHEDULER_INTERNAL_ERROR (119)
The video scheduler has detected that fatal violation has occurred. This resulted
in a condition that video scheduler can no longer progress. Any other values after
parameter 1 must be individually examined according to the subtype.
Arguments:
Arg1: 0000000000000002, The driver failed upon the submission of a command.
Arg2: ffffffffc000000d
Arg3: ffff98042db1b960
Arg4: ffff80059ff8edb0
```

**Comment by Donkeykong307** [comment]
Do you have Force Cuda P2 state set to off? I have an Asus Strix GTX 1080 and if i set it to off, i must overclock, even just +50 on memory to not BSOD. If you set it to on, then you can't overclock, but get a stable 30 MH/s.

**Comment by AlecWiese** [comment]
Running Nvidia profile inspector, do I have CUDA - Force P2 state set to on, and you're getting 30? I get 23-21 MH/s most of the time

**Comment by Donkeykong307** [comment]
Is that the GPU you are using for Windows as well? I'm using a iGPU (7700K), if i use my GTX 1080 then it will crash if changing the memory timings.

**Comment by AlecWiese** [comment]
Yeah it is, I'm only using it to mine in the off hours, and since I have a R7 1700x, I don't have an iGPU. Might see if I can pick up a GT 710 or the like to use drive my display and get the extra 7-10 MH/s over what I'm seeing now.

**Comment by nicehashdev** [comment]
No all cards can take these settings, try with 20 - 5.
