### ISSUE TITLE
Feature Request - Toggle to enable/disable mining on selected device

### ISSUE THREAD

**Issue by damngod** [nicehash/NiceHashQuickMiner#247]
Hi,

I'm using some RTX 3060 in combination with other RTX cards and I would like to disable mining on RTX 3060 with QuickMiner in order to use Octopus mining at full speed in parallel. Currently I use the Game Mode option to disable mining in QuickMiner however you can only disable one device, it needs to be connected to a display/HDMI dongle and Game Mode frequently gets reset. Beta driver is an option with RTX 3060 but it is too limited/cumbersome.

Thanks.

**Comment by helinus** [comment]
You can stop individual devices in Rig Manager https://www.nicehash.com/my/mining/rigs

**Comment by nicehashdev** [comment]
This is already possible when using Rig Manager. Just click on play/pause/stop button.
