### ISSUE TITLE
how to access  mining program to usb

### ISSUE THREAD

**Issue by joe11111-sudo** [nicehash/NiceHashQuickMiner#248]
hi any method to install nicehash mining program to a usb , so that  i don need to install window and device to output ,i just need to plug in the usb so that the nicehash program can run immediately.

**Comment by joe11111-sudo** [comment]
![1](https://user-images.githubusercontent.com/74581472/111870879-1b52bd00-89c2-11eb-9be8-daf2f0b88b55hi wht is this actual problem , i alrealdy install 2 4 ram but still got this problem

**Comment by joe11111-sudo** [comment]
![Uploading 2.PNG…]()

**Comment by helinus** [comment]
Quickminer is a Windows 10 program, so you need a booting version of Windows 10 to use this.
I think NiceHash OS matches what you are looking for: https://www.nicehash.com/nhos-mining

**Comment by nicehashdev** [comment]
We will not support this as the intention of NiceHash QuickMiner is to get fully installed on PC and approved by the owner of the PC. Any fast/quick/stealth/unknown methods are **NOT** supported and will not be endorsed or developed towards.

**Comment by joe11111-sudo** [comment]
thks ，are there have  maximun accomodate of graphic card or not?

**Comment by N0rdmann** [comment]
Aside from the already given assumption to abuse this as a stealth mining method... 
 _not sure how anyone should ever mine unnoticeable on anyone's PC with every FAN in the PC screaming at high load_  🙈 
... I clearly see a **valid use case** in an  (portable) mining OS installation completely **seperated** from your daily/production Environment!
Having to whitelist all mining software in virus scanner alone is already a big security risk for any sensitive data **IMHO**

Back2Topic there are several nice tools out there with which you can easily create a bootable windows env. on your usb stick (in which you then can **safely** run NHQuickminer) eg. [WinToUSB](https://www.easyuefi.com/wintousb/)

Hope this helps 👌
