### ISSUE TITLE
 Black Screen Stops Mining

### ISSUE THREAD

**Issue by GraysonSlade** [nicehash/NiceHashQuickMiner#250]
When i put my 3090 on Medium optimize and this was fine for 5 days this issue just started last night.  It now freezes my pc, black screen nd stop mining, I have to hard shut off and turn back on.  This happens after an hour or so.  Going to try using new RC and putting it on lite instead.  Anyone know of any solution?

**Comment by nicehashdev** [comment]
Something must have changed... Is it hotter? Did you update drivers. Your card is not stable with Medium optimization anymore. Check for factors what changed and you will solve the problem.

**Comment by GraysonSlade** [comment]
yeah the only thing i have changed was to download the latest nvidia
drivers a few days ago, and this happens only after a few hrs of running on
medium.

**Comment by nicehashdev** [comment]
Then it must be related to drivers. Check if going back to previous version resolves your issue?

**Comment by nicehashdev** [comment]
No response, consider solved.
