### ISSUE TITLE
Why is this on github?

### ISSUE THREAD

**Issue by pvinis** [nicehash/NiceHashQuickMiner#251]
It's a zip in this repo.. Where is the source?

**Comment by nicehashdev** [comment]
Source is available for parties that have some reason to inspect it **after NDA is signed**.

**Comment by pvinis** [comment]
Cool. I would like to have a list of those that have already asked and got the source for analysis etc, in the `README.md`. How does that sound?

**Comment by AskAlice** [comment]
I would like to improve this software, happy to sign an NDA.

**Comment by nicehashdev** [comment]
Currently, there are two ways to get access:
- As a developer; apply for a job - https://www.nicehash.com/jobs - we have a dire need for good, skilled developers.
- As an internationally confirmed security analyst who can, at the end, put a 100% safe stamp on this piece of software and help us fight war against AV companies that are unjustly marking it as malware or PUA. We are paying for this service of course.

**Comment by pvinis** [comment]
are there "stamps" so far?

**Comment by nicehashdev** [comment]
I don't know... but there should be. I have no time to check it out yet, but surely there must be a company that can make "security audit" of the software and confirm its nature.
