### ISSUE TITLE
NHQM Installer seems to be doing wrong thing when install path is "."

### ISSUE THREAD

**Issue by pasisavolainen** [nicehash/NiceHashQuickMiner#253]
Hi,
I have both NHQM itself and the installer in `Desktop\nhqm` and start it from there. It has asked and shows install path as `.`.
When I ran the update (0.4.2.1_RC?) this installation didn't update. I know it did update when I last did this update to `0.4.1.3 RC`.

I keep it in that path so I can make exclusion to windows defender on that path only (Virus & Threat Protection settings -> manage settings -> Exclusions) , otherwise Excavator keeps failing and there seems to be no way to allow it to run.

**Comment by nicehashdev** [comment]
Can you be more specific what the issue was exactly and how to reproduce the bug? Also please turn on full logging and submit logs here.

**Comment by pasisavolainen** [comment]
Now when I start Installer it asks: 
![image](https://user-images.githubusercontent.com/6162135/112161321-b4b4e580-8bf3-11eb-9ad2-6ac40b743ac0.png)
When the UI opens it has this:
![image](https://user-images.githubusercontent.com/6162135/112161390-c6968880-8bf3-11eb-9759-80c95b688859.png)

(notice there is different asked path vs. "installation folder"). I guess I didn't notice this change and thought that Installer would update what it asked instead of Program Files.

I can enter `.` into the `Installation folder` and this works. When Installer is next run it will ask 
![image](https://user-images.githubusercontent.com/6162135/112161845-2bea7980-8bf4-11eb-8795-092a3d4dcf54.png)
but still put the "program files" into installation folder textbox.

**Comment by nicehashdev** [comment]
The installation folder text input takes in absolute path, not relative. In next version will be fixed to allow only absolute paths.

**Comment by pasisavolainen** [comment]
IMO real issue is that it recognizes previous (customized) install path but still overrides it with the default (program files) one.
