### ISSUE TITLE
Optimize data explanation

### ISSUE THREAD

**Issue by darylounet** [nicehash/NiceHashQuickMiner#257]
Hi !
I have a GeForce RTX 2060 and have a very nice efficiency (thanks for this !) with QuickMiner. I'm moving to Ubuntu (directly with Excavator as QM doesn't exist for Linux) but I can't get the efficiency I had using Windows and QM.
On the [Optimize data file](https://github.com/nicehash/NiceHashQuickMiner/blob/main/optimize/data_003.json), can you explain these terms : "pt", "dmc", "mcc", "fm", "ftg" and "ftr"
`{ "name": "GeForce RTX 2060", "op": [
      { "id": 2, "pt": 0, "dmc": 900, "mcc": 1050, "fm": 3, "ftg" : 58, "ftr": 74 },
      { "id": 1, "pt": 0, "dmc": 600, "mcc": 990, "fm": 3, "ftg" : 62, "ftr": 78 }
    ]}`
This way I may manually set these parameters to have the same efficiency as Windows. Thanks !

**Comment by Donkeykong307** [comment]
pt = Power Target
dmc = Delta Memory Clock
mcc = Max Core Clock (Absolute)
fm = Fan Mode
ftg = Fan Target GPU Temp
ftr = Fan Target (V)Ram Temp

If you checked the data_002.json it has these in there.

**Comment by nicehashdev** [comment]
pt is actually "profile type", but the rest are correct yes.
