### ISSUE TITLE
Rig information not displaying on rig manager

### ISSUE THREAD

**Issue by RDTHRCKT** [nicehash/NiceHashQuickMiner#258]
![issue 1](https://user-images.githubusercontent.com/81193512/112060219-47418000-8b33-11eb-9e4e-025d79fa15a6.jpg)
![issue 2](https://user-images.githubusercontent.com/81193512/112060240-4f99bb00-8b33-11eb-80ab-642c90e36bde.jpg)

It seems to be mining alright, but for some reason it isn't displaying properly. Very occassionally it will momentarily display, but then it disappears again.

![hashrate](https://user-images.githubusercontent.com/81193512/112060635-d0f14d80-8b33-11eb-9f3e-95408f59b434.jpg)

**Comment by nicehashdev** [comment]
Please, enable full logging and submit logs here. Also try latest RC 0.4.2.1, some bugs regarding this have been fixed lately.

**Comment by RDTHRCKT** [comment]
[exported_logs.zip](https://github.com/nicehash/NiceHashQuickMiner/files/6200627/exported_logs.zip)

I can't figure out what's wrong. Initially it does display properly, but everytime it drops and tells me the rig is either "unknown" or offline. Though it is still mining the entire time, from what I can tell.

**Comment by nicehashdev** [comment]
Considering how communication between NHQM and Excavator is suddenly cut off, I would say that something (like an AV - Windows Defender) starts blocking Excavator from working properly. Make sure this is not the case.
