### ISSUE TITLE
Frequently Restart and Reboot

### ISSUE THREAD

**Issue by Captamtama** [nicehash/NiceHashQuickMiner#259]
Getting Frequently Restart and Reboot more than 3 times a day
Tried Reinstalled driver used DDU but the problem still persists
I have the log but I don't know what to look

[exported_logs.zip](https://github.com/nicehash/NiceHashQuickMiner/files/6194911/exported_logs.zip)

**Comment by nicehashdev** [comment]
I see you have cards overclocked. What happens if you don't overclock them?

**Comment by Captamtama** [comment]
Tried used stock clock got warning then next 1 hr rig reboot and cant run quickminer 

![stockclock semaphore and io warning](https://user-images.githubusercontent.com/81284556/112411908-36218a80-8d50-11eb-97d3-4e2d893e389e.png)
![After reboot no detect](https://user-images.githubusercontent.com/81284556/112412045-708b2780-8d50-11eb-9412-25b4d90ef5b4.png)
[exported_logs.zip](https://github.com/nicehash/NiceHashQuickMiner/files/6201741/exported_logs.zip)

**Comment by nicehashdev** [comment]
I see you have unstable connection; it gets terminated often. Check your wifi/router and make it better.

You can also try latest 0.4.3.1 RC version and see if anything improves.

Besides that, I don't see anything problematic.
