### ISSUE TITLE
status of mining rig is ''unknown''

### ISSUE THREAD

**Issue by Teriaky** [nicehash/NiceHashQuickMiner#26]
I switched to QuickMiner v0.3.0.6 with 2 3070 and everithing is working ok but I cannot see my rig status from the website or from my android app . It shows me the H\S rate but says Rig Status Unknown . From the log files I found this error 

[DEBUG] [watchdog] HTTP API GET failed: The server committed a protocol violation. Section=ResponseHeader Detail=CR must be followed by LF

How can I fix it ? Thanks in advance

**Comment by nicehashdev** [comment]
Did you update whole package or just some parts of the application? I would suggest you to redownload 0.3.0.6 RC plus latest OCTune fix (2) and then try again.

**Comment by Teriaky** [comment]
It worked thank you !

**Comment by nicehashdev** [comment]
Fixed. Closing.
