### ISSUE TITLE
Feature Request: 2 Thoughts about Memory OC on OCTune

### ISSUE THREAD

**Issue by mikeroygray** [nicehash/NiceHashQuickMiner#260]
You guys are smart folks, so I'm positive there's a good reason why you don't already have these features - nonetheless, TWO ideas:

1) Best of all: One-click memory clock Autotune. It seems counterintuitive that the single most important OC setting for mining is the one where we take the trial-and-error route.

2) A SEPARATE field JUST for making changes to memory clocks, no chance of accidentally changing core clocks and power limits. At the moment, after running autotune, it's easy to accidentally mess up the autotuned core clock and power settings if you try adjusting memory clocks.

**Comment by nicehashdev** [comment]
Unfortunately, there is no reliable way to determine stable memory OC. It really depends on each chip. Some cards can take more, some can take less. When appropriate stable memory OC is found, from there on, it is possible to quite reliably determine max core clock which makes stable OC profile.

We will think about further enhancements of OCTune.

**Comment by mikeroygray** [comment]
Wouldn't it be possible to run a stress test loop, increasing the memory
clock by x each loop until the app detects stability issues, then reducing
clocks towards last stable x? (The stress test would be excavator ... Or,
depending on use case, running excavator while doing other stuff in the
foreground.)

I mean, that's how I establish the oc-ability of my silicon, and it seems
like a process that could be automated.

**Comment by nicehashdev** [comment]
The feature is on TODO list and it does not have high priority yet - there are other things more important at the moment.
