### ISSUE TITLE
NHMP-SSL Forcibly Closed By Remote Host (10054)

### ISSUE THREAD

**Issue by LanceMcCarthy** [nicehash/NiceHashQuickMiner#261]
A few times a day, I will hear the GPU fans stop. When I check the logs, the problem was a  forcible disconnected:
the following errors:

```
[warning] nhmp-ssl | read: An existing connection was forcibly closed by the remote host (10054)
[info] nhmp | Disconnected
[warning] nhmp-ssl | ws handshake: The I/O operation has been aborted because of either a thread exit or an application request (995)
```

![image](https://user-images.githubusercontent.com/3520532/112355124-bd64f480-8ca3-11eb-9819-429c4319a02a.png)

Let me know if there's anything else I can add that will help.

**Comment by nicehashdev** [comment]
This happens when you lose connection with remote host. It is nothing wrong with the application itself. To avoid getting this problem, use more reliable connection. If you use wifi, use cable.

**Comment by LanceMcCarthy** [comment]
This machine has a 10Gbs LAN fiber to UDM pro, then a 1Gbs WAN.

It is not a poor connection issue (I have 9 other VMs on the same machine and none of them lost host connection.

Ill start collecting logs for the nhqm network adapter. Thanks
