### ISSUE TITLE
1660 Super bad clocks

### ISSUE THREAD

**Issue by TeleNach0s** [nicehash/NiceHashQuickMiner#262]
Used RIG manager on MEDIUM, core clock goes down to 960Mhz which is okay but why does the memory get downclocked too? Guess its just a typing mistake in data_004.json. Please FIX it. Im getting low Hashrates with your settings right now. Much appreciated

**Comment by nicehashdev** [comment]
There are several types of VRAM on 1660 Super. We haven't been able to identify all possible combinations. Looks like you have the one which has VRAM that likes positive OC. You can modify profile for your own needs following steps here: https://github.com/nicehash/NiceHashQuickMiner/wiki/One-click-Optimizations#is-it-possible-to-slightly-modify-optimization-profiles

Or wait till we identify all possible VRAMs and make rules for all of them.

**Comment by TeleNach0s** [comment]
I tried to change it manually but i dont see any "optimizeProfilesCustomDataURL" line in the config file to set my custom path

**Comment by TeleNach0s** [comment]
Ok so adding the command renders the config file corrupted and gets me a new one instead.. So thats clearly not working. Any chance u could provide me with a config file that sets my core clock to 900Mhz and my memory clock to 7500Mhz, I would really love the miner to start with these values at startup.

**Comment by nicehashdev** [comment]
You need to use latest RC version. It is not going to work with stable version 0.4.1.3.
