### ISSUE TITLE
NVIDIA Drivers version, Not Compatible

### ISSUE THREAD

**Issue by Reallyhhh** [nicehash/NiceHashQuickMiner#266]
![Prob1](https://user-images.githubusercontent.com/81325088/112409367-be237800-8cef-11eb-9da4-75ae13eb2390.PNG)
 
After downloading the Installer and installing one of the programs, the beta or not. I get the error message (provided above) Not sure why as my drivers are updated to the most recent versions NVIDIA offers. Not sure what the deal is. I'm using a basic RTX 2060 for reference. 

What is odd is that I am able to use the original miner just fine with no problems, but I would like to use the quick miner so I have easy access to keeping my card cool as a cucumber. If there's any solution let me know.

**Comment by nicehashdev** [comment]
Download NVIDIA drivers from here: https://www.nvidia.com/Download/index.aspx
