### ISSUE TITLE
could not obtain power consumption!

### ISSUE THREAD

**Issue by Alamer1** [nicehash/NiceHashQuickMiner#267]
Hello,

I was on 4.3.0 RC version and my miner that has 4 3060tis connected via 1x raisers and 2x 3060s connected direct to the motherboard on x16 slots with HDMI dummies, it was stable and worked well for a whole day after the build with no issues.

Today i get a notification for nicehash quick miner 4.3.1 update, right after updating it gave me "could not obtain power consumption!" message for 2 cards, then the miner stopped, I rebooted and after a little bit it crashed into a black screen, I switched back to 4.3.0 which was stable for me for a whole day without issues.

I am using the Nvidia driver 470.05

Thanks 
Amer

**Comment by Alamer1** [comment]
Adding, downgrading to 0.4.3.0 RC and now my rig is stable with no issues for over 5hrs, will continue to update if something new happens.

**Comment by nicehashdev** [comment]
Do you have issues with any other cards besides 3060 with latest ver? Also log files would be very helpful.

**Comment by Alamer1** [comment]
Hello, log files attached, please note that i am currently on the previous (0.4.3.0) version since it is working well with my miner on driver version 470.05
[exported_logs.zip](https://github.com/nicehash/NiceHashQuickMiner/files/6207916/exported_logs.zip)

**Comment by nicehashdev** [comment]
As discussed in discord, if you have issues after VRAM clock reduction, let me know.
