### ISSUE TITLE
Invalid DAG generation

### ISSUE THREAD

**Issue by daimonkori** [nicehash/NiceHashQuickMiner#269]
Good day. Today, after updating to version 0.4.3.1 RC, two of my 1060 cards refused to work with the Invalid DAG generated error. I tried downgrading, updating the NVidia driver, changing the swap size, but nothing worked ..

[excavator_log_2021-03-25_21-41-08.000.txt](https://github.com/nicehash/NiceHashQuickMiner/files/6206487/excavator_log_2021-03-25_21-41-08.000.txt)

**Comment by nicehashdev** [comment]
So, you are saying that now even older NHQM versions are not working? What about NHQM stable 0.4.1.3? It looks like you did not apply any overclock. Do you have Force P2 for CUDA enabled or disabled?

**Comment by daimonkori** [comment]
The stable version doesn't work either. How can I test the CUDA function?

**Comment by nicehashdev** [comment]
So in general NHQM never worked for you? Perhaps try older stable version 0.3.2.6?

**Comment by daimonkori** [comment]
YES, thanks, this version is working. After that I disabled two NVIDIA services and the RC version started working. I will test

**Comment by nicehashdev** [comment]
Okay. What kind of NVIDIA services did you disable?

**Comment by daimonkori** [comment]
Nvidia Display container
