### ISSUE TITLE
invalid dag generated. is your memory oc too hign

### ISSUE THREAD

**Issue by roleq1** [nicehash/NiceHashQuickMiner#27]
invalid dag generated is your memory oc too hign

**Comment by nicehashdev** [comment]
You will need to tell more. This happens when invalid DAG is generated, most likely due to too intensive memory overclock which corrupts DAG. If you use built-in Excavator profiles (OCTune), then this would not happen, as during DAG generation, memory clock is reduced to standard one (delta 0).

**Comment by nicehashdev** [comment]
No response, closing.

**Comment by roleq1** [comment]
Спасибо. Я попробую без разгона

чт, 18 февр. 2021 г. в 07:06, djeZo <notifications@github.com>:
