### ISSUE TITLE
Cant find "optimizeProfilesCustomDataURL" in config file

### ISSUE THREAD

**Issue by choobs96** [nicehash/NiceHashQuickMiner#271]
Hi NH team,
I've read through https://github.com/nicehash/NiceHashQuickMiner/wiki/One-click-Optimizations. However, I couldn't find the "optimizeProfilesCustomDataURL" that I could use to add the latest data004 JSON file.

I'm currently on RTX 2060 and I would like to enhance my mining performance.

**Comment by nicehashdev** [comment]
Are you using latest RC version? You need to use latest ver (not stable).
