### ISSUE TITLE
Excavator OCTune - artifacting after overtune

### ISSUE THREAD

**Issue by TheCashewKid** [nicehash/NiceHashQuickMiner#272]
I have been mining with nicehash medium optimization (around 39mH/s) for around 2 weeks with my 2070 Super graphics card nearly nonstop and it has been stable for that time. I decided to test the Nicehash OCTune Autotune to get the most out of my card and my computer started artifacting nearly when the autotune was done. I adjusted the Autotune parameters (totally wrong I think retrospectively) to:
8800 mem clock
210 starting core clock
2100 core clock max

I have restarted the computer several times, turned off mining and reloaded the BIOS that I have been using for the last 6 months but I can't get the artifacting / temporary black screen flash to go away. I think I must have killed the card. The temps were still below 60C the whole time it was autotuning. Is there any reset that I can do to try to fix this? I assume there isn't anything I can do and I pushed the card too hard and now I have to pay the price but I'm hoping there is something I can do.

My advice to beginners is to not fiddle with the settings too much. Any help would be greatly appreciated.

Specs:
![image](https://user-images.githubusercontent.com/81402006/112575892-31e08600-8dbf-11eb-8e67-1aaa1d5d7150.png)

i7-6700k - undervolted slightly
EVGA GeForce RTX 2070 Super XC Gaming, 8GB GDDR6 - undervolted and slightly OC when not mining
MSI Z170A Gaming M5 motherboard
650W Gold PSU

The computer is approximately 6 years old, new additions being a new NVMe ssd and the 2070 added New Years Day 2020.

**Comment by nicehashdev** [comment]
Try with reinstallation of drivers. Try the card in another PC. If it is the problem there too, then unfortunately it is really the card. But it would have died anyway if it was destined to die. Tuning did not cause this; perhaps it only pushed the "death button" which would be otherwise pushed by some game.
