### ISSUE TITLE
Bugs ; Can't run Nice Hash Miner and  NH QuickMiner under Windows 10 32 bit 

### ISSUE THREAD

**Issue by Paulabtc2021** [nicehash/NiceHashQuickMiner#275]
URGENT Help need and fix and solve issue below details :
i  have issues with  nicehash/NiceHashMiner (Any released Ver NiceHash QuickMiner or  NH OS or NHM 3.0.X.X )  not working (Can't run),   the problem is when i run UI i get Message bug  " our current release does not support 32 bits CPU  Hardware Windows 10 OS profile under  Windows  10 32 bits .and does not work Windows 10 or newer operating system 32 -bit  And more time shipping new features. Can you generating  from your source code and publish and ship new  custom inheritance release Win32 UI + Source Code (C#,Html)  (And more time shipping new features for Windows 10 32 bits and More  Release  NH UI Win32 bits   are  needed ) NiceHash QuickMiner OR  NH OS for Windows 10 or newer operating system 32 -bit For/Support  intel Pentium (old devices pc) CPU mining   with AES support and all our new  Algorithms tips and tricks and stuff  
best Regards

**Comment by nicehashdev** [comment]
Yes, 32 bit OS is **not** supported. If you wish to run NiceHash QuickMiner, you need to have decent modern hardware and this works with 64 bit OS - Windows 10 x64.

**Comment by Paulabtc2021** [comment]
Can us publish and ship to me Custom mini  release GUI (like miniZ miner Win32 bin app + Source Code  to  i will run NiceHash QuickMiner,   on old Device Hardware 32 bit OS  supported  and   works with  ANY CPU 32 bit  OS - Windows 10 x32 .  because  i don't  have decent modern hardware and i can't  and don't interested to buy  AND SPEND for current bad performance Hardware x64

**Comment by nicehashdev** [comment]
If you have 32bit OS, you probably do not use [supported hardware](https://github.com/nicehash/NiceHashQuickMiner/wiki/Supported-hardware). 32bit version of NHQM would be useless in this case.
