### ISSUE TITLE
.ddl error when trying to run QuickMinner

### ISSUE THREAD

**Issue by Stalkerous** [nicehash/NiceHashQuickMiner#276]
![This is the error on Windows 10 64bit](https://user-images.githubusercontent.com/9377015/112685266-b0ced080-8e4a-11eb-8390-6240dcbeb644.jpg)
I do not even have an Nvidia GPU mine is AMD RX480 XFX so, why would it ask for an Nvidia .ddl file... Please let me know what could be done to fix it, thank you.

**Comment by nicehashdev** [comment]
QuickMiner does not work for AMD. It is NVIDIA only miner.
