### ISSUE TITLE
CUDA error 'an illegal instruction was encountered' in func 'cuda_daggerhashimoto::run' line 935

### ISSUE THREAD

**Issue by R77S77** [nicehash/NiceHashQuickMiner#277]
Hello!

I always get this error "CUDA error 'an illegal instruction was encountered' in func 'cuda_daggerhashimoto::run' line 935" when i try mining with an RTX 2070 Super, on the same hardware a RTX 3060 Ti works fine. If i try to use both cards at the same time, i get the error for both cards.

I tried quickminer v0.4.1.3 STABLE and the higher RC versions.

What can cause this error?

I would be very thankful for help!

**Comment by nicehashdev** [comment]
This happens when overclock is unstable. You have to dial your clocks back down. If you already did, then you also need to reboot PC so drivers gets fully restored.

**Comment by R77S77** [comment]
Thank you!

I don‘t use any extra overclocking on this card, i forgot to wrote it is an 2070 Super **OC**.

Could this factory overclocking cause the problem? But it is only for GPU, not for RAM.

**Comment by R77S77** [comment]
I checked again the clocking of the card, everything is lower than default until i start the quickminer.

Quickminer/excavator boosts it up to 16702 which is 2702 over the default clocking of 14000, i think this is the problem.

Is it possible to give quickminer/excavator a lower clocking on start?

**Comment by nicehashdev** [comment]
If you did not set any OC, then this is indeed a strange behavior. Clocks should not get higher than default. Make sure that there isn't some strange Afterburner profile being activated. I would suggest clean reinstall of all video drivers and if that doesn't help even clean reinstall of Windows. If you have a chance, try to test the card using another PC and see if the VRAM clock shoots up there too.

**Comment by R77S77** [comment]
I already tried a clean reinstall of different drivers many times und also a clean reinstall of Windows. The problem persists...
There are no other tools installed, just Windows and Nvidia drivers.

The same behavior is on two different mainboards.

Is there any logging where i could see what causes this problem?

And is there a possibility to underclock the RAM on startup of excavator?
