### ISSUE TITLE
20% lower performance with Optimize, and OCtune doesn't help much

### ISSUE THREAD

**Issue by fudun** [nicehash/NiceHashQuickMiner#278]
I have a MSI RTX 3080 Gaming X Trio with Suprim X BIOS running Nicehash Quickminer in my main work station. With Afterburner I have tweaked this to a nightly setting reaching 103 MH/s, and a low noise setting at about 95 MH/s used at daytime while using the computer. Power usage is not a factor at this time of year, as my Norwegian basement man cave/home office is freezing most of the year.

If I run Optimize with the new "High" setting, I am stuck at 81 MH/s.

My main issue is that Optimize and most settings in OCtune cut the power limit down to 100%, while I need at least 113% not to be limited. This is because even with the Suprim BIOS I have a power limit of 200 Watt for Cuda core work. This is why I had to change BIOS in the first place - to be able to increase the power limit.

So while you have some great features that beat Afterburner for mining, I still have to use Afterburner for optimum performance.

Also, absolute memory clocks have a strange offset of about 750 MHz. Haven't retested in the latest RC.

The features I think are great are 
1) The Fan control for setting a VRAM temp target, because I had to do this manually through HWINFO and Afterburner
2) Autotune - even though I already know my optimum core clock, this would be great for tuning a new card.
3) Undervolt - makes it possible to go lower than 725 mV which is minimum through Afterburner.
4) It seems that some of the settings allowed me to set an absolute Memory clock above the +1500 Afterburner allows (which I run for the noisy setting). And while that didn't help me as OCtune set powerlimit down to 100%, I think this would be really interesting to try if I wasn't at power limited

So one suggestion I think would work great in my case would be:

Setting either an absolute or max core clock with an absolute (or offset) core voltage (underclock and undervolt), while also being able to set a power limit above 100%. The max power limit should be limited by the BIOS anyway, so it shouldn't impose that much of a risk of user failure and burnt cards.

So to give an example of how that would work with actual numbers, I could set:

Absolute Core Clock: 1100 MHz
Absolute Core Voltage: 675 mV (could be done with a -50 mV offset too, probably)
Power Limit: 116%
Fan Control: Fan speed 100% Vram: 105 Hotspot: 70
Absolute Memory Clock: 12 500 MHz

**Comment by fudun** [comment]
Another great feature could be memory clock tuned to a target VRAM temp. So if 100% fan speed still doesn't stop VRAM temp from rising above the target, you could throttle the memory clock.

**Comment by nicehashdev** [comment]
Unfortunately, we were not aware of this card and it's unusual TDP config for CUDA mode.

We will take a deeper look into it once we get a sample of this card.

**Comment by nicehashdev** [comment]
Try latest version now and let me know if it is any better. TDP is relaxed to max possible when setting max core clock.

**Comment by nicehashdev** [comment]
Considered solved. Closing.
