### ISSUE TITLE
GTX 1070 Optimization

### ISSUE THREAD

**Issue by Captamtama** [nicehash/NiceHashQuickMiner#280]
So Happy when the new release finally support GTX 1000 series, Hoping to get 27-29 hash on my GTX 1070
But when trying Optimization setup with my GTX 1070, none of the setups bring to higher Hash and Efficiency than my Manual tune.
Give you the comparison so you can have more data and cook a better setup in the next release.

Manual Tune
![1 Manuall Tune](https://user-images.githubusercontent.com/81284556/112709661-f7c1d200-8eed-11eb-9837-fe0f389059ab.png)

Lite Tune
![2 Lite Tune](https://user-images.githubusercontent.com/81284556/112709688-1c1dae80-8eee-11eb-90de-f27b54749ac5.png)

Medium Tune
![3 Medium Tune](https://user-images.githubusercontent.com/81284556/112709697-293a9d80-8eee-11eb-83b7-7cd93f6fe7b9.png)

Efficient Tune
![4 Efficient Tune](https://user-images.githubusercontent.com/81284556/112709707-38215000-8eee-11eb-80cc-c18c37d0ee9e.png)

Efficient Low Tune
![5 Efficient Low Tune](https://user-images.githubusercontent.com/81284556/112709713-44a5a880-8eee-11eb-94ff-0b053f212a58.png)

**Comment by nicehashdev** [comment]
Optimization profiles are intended for users that don't know enough about OC to do it on their own. These profiles need to be conservative to give support to wide range of cards out there. If all cards were capable of higher speed, then these would be already set by manufacturer. But not all cards can do it - silicon lottery.

You probably have a very good chip thus can reach higher speeds. But that does not mean everyone else can do it. If we higher clocks for profiles to fit your card, then there will be many users with stability issues - the ones that were not so lucky with silicon lottery.
