### ISSUE TITLE
Feature request: Automatic optimization.

### ISSUE THREAD

**Issue by Alamer1** [nicehash/NiceHashQuickMiner#282]
Hello,

I have a suggestion:

What if there was an optimization level called "Auto"? what it does is actually benchmarks all cards individually and sets the overclocks for each card differently as per how good the cards are, and during mining it would monitor for any above target rejections and reconfigures the OC for that particular card and keep doing it till everything is as best as possible!

hope this is a good idea!
Amer Alnomany

**Comment by nicehashdev** [comment]
This has already been requested and is on TODO list.
