### ISSUE TITLE
Chrome Blocking Download

### ISSUE THREAD

**Issue by rrichards440** [nicehash/NiceHashQuickMiner#284]
I've tried to download both the installer and the zip file, and both of them were blocked from download by chrome due to detecting viruses. What is the way around this?

**Comment by Xalaxis** [comment]
Open your downloads using Ctrl+J, from there you will have the option to "download dangerous file" if it is blocked.

**Comment by nicehashdev** [comment]
> Open your downloads using Ctrl+J, from there you will have the option to "download dangerous file" if it is blocked.

I believe you got the answer here. Thank you.

We are fighting all the major companies to get this false positive issues resolved. But it is a slow process. Eventually if this is not resolved by them, lawsuits will be filled for all the caused damages.

**Comment by rrichards440** [comment]
Ultimately what I had to do was go into Chrome's settings and disable safe browsing. When I tried to just continue with the "dangerous download" it would immediately change over to "Failed-Virus detected".
