### ISSUE TITLE
Feature Request: Momentarily force fan to 75% when deactivating Game Mode

### ISSUE THREAD

**Issue by helinus** [nicehash/NiceHashQuickMiner#285]
The same that happens when activating an optimization mode to prevent vram getting too hot before fans catch up.

**Comment by nicehashdev** [comment]
If you use latest prerelease RC 0.4.4.0, then this is already fixed.

**Comment by helinus** [comment]
I have version 0.4.4.0 RC and with the Lite-optimization applied in Rig manager results in the following vram temperature/fan-speed graph with Game mode active for about one minute the first time and two minutes the second time, the fans begin to ramp up when vram reaches 96/98 degrees which is about 30 seconds after game mode deactivation allowing vram to reach 102/104 degrees.
![Screenshot 2021-03-29 083245](https://user-images.githubusercontent.com/2891812/112795933-89a21a00-9069-11eb-861c-aa12ae9d3464.jpg)

**Comment by nicehashdev** [comment]
You can adjust fan algorithm in more detail using this: https://github.com/nicehash/excavator/tree/master/api#device-smartfan-set-advanced

**Comment by helinus** [comment]
"Starting fan level when mode 2 or 3 is used." doesn't seem to be used when disabling Game Mode with SmartFan still in mode 3.

**Comment by nicehashdev** [comment]
How do you mean? I just tested, works fine. You need to be more specific.

**Comment by helinus** [comment]
When Game Mode is configured as follows the fan does not catch up fast enough when i deactivate Game mode.
![image](https://user-images.githubusercontent.com/2891812/113032529-3b3b6b00-9190-11eb-9953-4a39a6f25c7c.png)

The solution would probably be to reapply the current Smartfan mode when deactivating Game Mode.

**Comment by nicehashdev** [comment]
Are you using latest RC 0.4.5.0?

**Comment by nicehashdev** [comment]
Latest version 0.4.5.3 RC reapplies fan profile when you exit game mode. Please try it and report if this solves your problem.

**Comment by helinus** [comment]
Version 0.4.5.3 RC solved this.
