### ISSUE TITLE
Option to trigger manual update check

### ISSUE THREAD

**Issue by Xalaxis** [nicehash/NiceHashQuickMiner#287]
My client has not yet picked up the new RC build. Is there a way, or can it be added if not, to manually check for updates and take advantage of the built-in updater?

**Comment by nicehashdev** [comment]
The latest STABLE version is still 0.4.1.3. If you would like to receive RC versions, then you need to enable this feature in your config. Read more here: https://github.com/nicehash/NiceHashQuickMiner/wiki/Tips-&-tricks#8-enable-automatic-updates-of-rc-versions

**Comment by Xalaxis** [comment]
Strangely this setting was false, despite running an RC build.
