### ISSUE TITLE
serviceLocation

### ISSUE THREAD

**Issue by ben1628** [nicehash/NiceHashQuickMiner#288]
The default setup is serviceLocation = -1.

I'm located in Toronto and expect it to choose USA-EAST, instead, it always go to USA-WEST.  Is there a reason for the software to do that, is it because it is more **profitable** to connect to WEST? or it doesn't know where I am?

the difference is 64 ms vs 33 ms (EAST)

Thanks.

**Comment by nicehashdev** [comment]
Please, open your `nhmq.conf` file and copy paste content of property `serviceLatencies`.

Example:
```
"serviceLatencies" : [
		{
			"bIgnore" : false,
			"minLatency" : 18,
			"serviceLocation" : 0,
			"testTime" : 132612141332634692
		},
		{
			"bIgnore" : false,
			"minLatency" : 148,
			"serviceLocation" : 1,
			"testTime" : 132612142012683740
		},
		{
			"bIgnore" : false,
			"minLatency" : 37,
			"serviceLocation" : 2,
			"testTime" : 132612142372740521
		},
		{
			"bIgnore" : false,
			"minLatency" : 155,
			"serviceLocation" : 3,
			"testTime" : 132612142692820288
		}
	],
```
