### ISSUE TITLE
On the new RC, the "Optimize" buttons in rig manager are broken

### ISSUE THREAD

**Issue by Xalaxis** [nicehash/NiceHashQuickMiner#289]
![image](https://user-images.githubusercontent.com/12937964/112770356-57b79600-901e-11eb-9ebc-dd14c7aa7b11.png)

I'm using a custom optimize JSON which has not changed between revisions, but no changes had been made to the profile I modified.

**Comment by nicehashdev** [comment]
This is known and will be fixed soon.

**Comment by Xalaxis** [comment]
@nicehashdev Now there is no optimize button at all for me?

**Comment by Xalaxis** [comment]
Updating to the latest optimize configuration fixed this.
