### ISSUE TITLE
Feature request: Ability to pause mining

### ISSUE THREAD

**Issue by musahi0128** [nicehash/NiceHashQuickMiner#290]
Hi,

I am using this for about one month now and love some extra cash it generate. Great!

Now, I am mining on laptop, so it's really not ideal and not very good for long term. So far I run the miner from 8pm thru 7am then 8am thru 5pm. Within that period of time the fan is working nonstop which make me a little bit worried.

It will be great if there is feature to pause mining after numbers of accepted shares for period of time that user can set. Like, pause mining for 3 minutes after 100 accepted shares. This will definitely better than running non-stop because there is time for my laptop to cool down and rest a little bit.

Hope you can implement something like this.

Thank you!

**Comment by nicehashdev** [comment]
This will not be implemented. You may use [Excavator's API](https://github.com/nicehash/excavator/tree/master/api) and customize commands.json file to fit your needs.
