### ISSUE TITLE
NVIDIA NVML lib memory leak

### ISSUE THREAD

**Issue by nicehashdev** [nicehash/NiceHashQuickMiner#292]
EDIT, from last post:
**Latest non-DCH drivers (465.89) work fine for all generations (Pascal, Volta, Turing and Ampere):** https://www.nvidia.com/download/driverResults.aspx/172060/en-us

**No memory leak, decent speeds, complete compatibility.**

**DCH ONLY!**
It looks like latest NVIDIA drivers (461.92 and 491.75, perhaps others) have massive memory leak bugs in NVML library. This memory leak affects all applications using NVML library including Excavator and NiceHash QuickMiner. We have determined that **version 460.89 NON-DCH is good and has no memory leak** that would affect Excavator or NiceHash QuickMiner hence it can be used for days/weeks without any restarts.

There is a simple test to verify whether you have memory leak version of drivers:
1. Open CMD.EXE as Administrator.
2. Run: `nvidia-smi.exe -l` and observe memory consumption of process _nvidia-smi.exe_ (for example with Task Manager).
3. If you see increase of several kB once per second, then there is leak of power consumption method - which we have bypassed with Excavator already thus Excavator is not affected.
4. If you see increase of several hundred kB once per second, then there is massive memory leak as explained. Excavator is also affected in this case.

I will post more information when more is known.

**Comment by nicehashdev** [comment]
Looks like NON-DCH 460.89 is fine, 460.89 DCH still has issue of huge memory leak.

**Comment by bmwf30** [comment]
What is dch?

**Comment by KGA00** [comment]
> What is dch?

Microsoft DCH (Declarative Componentized Hardware supported apps) driver and refers to a new Windows 10 driver package preinstalled by OEMS implementing the Microsoft Universal Driver paradigm. While the base core component files remain the same, the way DCH drivers are packaged differs from previous Legacy (Standard) drivers. 
Recommend the normal driver, WHQL, and not DCH.

**Comment by Alamer1** [comment]
is the beta driver 470.05 effected by this leak as well? thanks for the findings

**Comment by nicehashdev** [comment]
It looks like DCH drivers have this issue. Non-DCH are OK. Also 470.05 DCH is affected and is leaking mem badly.

**Comment by CocoCrisp** [comment]
I found a way to download the 461.92 standard type and it seems the leak I had is gone now.

**Comment by nicehashdev** [comment]
Yes, looks like only DCH versions are affected.

**Comment by Alamer1** [comment]
> is the beta driver 470.05 effected by this leak as well? thanks for the findings

is there anyway to go around this? im using this driver due to having 3060s mining eth on quick miner.

**Comment by nicehashdev** [comment]
Since we have a solution for this, it is no longer relevant.

**Comment by Jsaini23** [comment]
Hey guys i tried using the drivers mentioned...atill have mem leak
