### ISSUE TITLE
Unable to deactivate Game Mode when monitor is not connected

### ISSUE THREAD

**Issue by Robert-Saiter** [nicehash/NiceHashQuickMiner#293]
After entering game mode with a monitor connected then disconnecting the monitor I am unable to deactivate game mode.  

Error is 
**_Could not detect video card with connected display or you may be using older video card for display!_**

Version: **0.4.5.0 RC**

I can understand the message when attempting to activate game mode but when attempting to deactivate game mode I am not so sure.   

Connecting a display to the card allows me to deactivate game mode as expected.

**Comment by nicehashdev** [comment]
This will be fixed in next version that comes pretty soon. Now, the card is "remembered" and when you deactivate Game Mode, previous mining state is applied on it so the bug you had cannot happen anymore.

**Comment by Robert-Saiter** [comment]
Thank you!!
