### ISSUE TITLE
Cannot connect: /cuda_devices

### ISSUE THREAD

**Issue by ThatGuyJacobee** [nicehash/NiceHashQuickMiner#295]
Hi there,
So this is the second time this has happened, basically in the OCTune I see `Cannot connect: /cuda_devices` and I can't start mining at all. It registers my 3070 on the OCTune page and everything, but everytime I press start mining on the web interface it just says "Enabling device RTX 3070" within the quickminer cmd. Also the cpu miner also doesn't start at all. I've tried reinstalling the quickminer with no success. The first time this happened a reinstall fixed it but not this time. I also tried resetting everything in the OCTune.

Another side-note, my saved configuration within OCTune also didn't load when I started up quickminer, had to do it manually as everytime I launched, it first loaded my config but then back to default. I even checked the command file and it had the correct core limit and memory clock in there but still loaded the default. (I'll show screenshot below too)

I can see something is wrong in the logs apparently it can't find file specified. 
There are pretty much alot of errors within the log which I don't understand.
I've dropped the log below hopefully you can help me out with this :)

![image](https://user-images.githubusercontent.com/42719082/112907441-c7448880-90e5-11eb-9d63-ce6dceb52543.png)
![image](https://user-images.githubusercontent.com/42719082/112907521-e80cde00-90e5-11eb-9d99-6c16a0d0fcae.png)
[log.txt](https://github.com/nicehash/NiceHashQuickMiner/files/6224880/log.txt)

**Comment by ThatGuyJacobee** [comment]
I've updated to the latest v0.4.5.0 RC and it's fixed my miner, it working now.
The only bug now that's occurring now is the OCTune saved config not loading on startup as I've mentioned on the 2nd paragraph in the main issue. 😀

**Comment by nicehashdev** [comment]
The attached log is from NiceHash Miner, not NiceHash QuickMiner.

I suggest you to make a clean install with this version: https://github.com/nicehash/NiceHashQuickMiner/releases/tag/v0.4.5.0_RC

**Comment by nicehashdev** [comment]
Are you sure config is not saved? Open commands.json file and check if it was changed.

Also, you need to set Rig Manager OPTIMIZATION to Manual if you wish to use manual OCTune settings.

**Comment by ThatGuyJacobee** [comment]
Yeah that fixed it. Here's a log by the way for the OCTune saved configs not loading.
[exported_logs.zip](https://github.com/nicehash/NiceHashQuickMiner/files/6225017/exported_logs.zip)

**Comment by ThatGuyJacobee** [comment]
Awesome yeah I had it set to medium optimization and now it's working. Thank you for the fast support and have a good day/night😀
