### ISSUE TITLE
Add hour tracking

### ISSUE THREAD

**Issue by PedroC1999** [nicehash/NiceHashQuickMiner#296]
This is a suggestion, I am wondering if a feature can be added to track hours of mining.

This can be used alongside the current graphs, and as a more accurate/useful way of measuring daily costs and profits, as opposed to a 24h average that for many small scale miners is unrealistic, as we often can't keep track of runtimes and when we are running in the scale of days, and often only mine for shorter periods.

**Comment by nicehashdev** [comment]
We believe that charts available on Rig Manager are detailed enough to give you all the available information you need regarding mining. There are power related stuff still missing and this will be added once available by all mining clients. Additionally, you have ability to export data. You can use exported data in any kind of app to make charts as you please.

This feature will not be implemented.
