### ISSUE TITLE
Please add minimize mining windows to tray

### ISSUE THREAD

**Issue by francescocmazza1** [nicehash/NiceHashQuickMiner#297]
Could you please consider adding minimize mining windows to tray? I like to have the ability to check the mining windows every now and then, but without the nuisance of always having mining windows in windows central bar. I hope you understand what I mean. Thank you very very much!

**Comment by Xalaxis** [comment]
I'd like to support this feature too. The `"bHideMiningConsole"` option is great for just getting the console window out of the way, but if you want to inspect it for some reason a tray menu toggle would be nice.

**Comment by francescocmazza1** [comment]
Thank you very much friend!

Il mer 31 mar 2021, 17:28 djeZo ***@***.***> ha scritto:
