### ISSUE TITLE
core | No compatible devices found!

### ISSUE THREAD

**Issue by Slyke** [nicehash/NiceHashQuickMiner#30]
Getting this error when running NHQM:
```
=========================== www.nicehash.com =========================
           Excavator v1.6.2b GPU Miner for NiceHash.
           Copyright (C) 2021 NiceHash. All rights reserved.
=========================== www.nicehash.com =========================

Build time: 2021-02-01 22:57:38
Build number: 550
Provided startup commandline:

                        Version: NiceHash QuickMiner
                Automatic hardware detection and mining tryout.
                Please, do not close this window!
                To manage this miner, use your web browser,
                go to: https://www.nicehash.com/quick-miner

[02:45:25][0x00003e08][info] Log started, build v550
[02:45:25][0x00003e08][error] core | No compatible devices found!
[02:45:25][0x00003e08][info] http | Listening on ::1:18000
[02:45:25][0x00003e08][info] core | Initialized!
```

Using a `NVIDIA GeForce RTX 2080 Ti` as specified here: https://github.com/nicehash/NiceHashQuickMiner/wiki/Supported-hardware

`devices_cuda` response from networks tab:
```
{"devices":[],"id":1,"error":null}
```

I have disabled CPU mining, just mining with the GPU.

**Comment by nicehashdev** [comment]
What is your driver version?

**Comment by Slyke** [comment]
`DxDiag` Output:
![image](https://user-images.githubusercontent.com/6442613/107943816-183b5b80-6f42-11eb-92e7-427f7d763637.png)

**Comment by nicehashdev** [comment]
If you install this: https://github.com/nicehash/NiceHashQuickMiner/releases/tag/v0.3.0.2

then it will tell you if your driver is too old.

**Comment by Slyke** [comment]
Awesome, I'm updating to latest drivers now and will let you know if that fixes it!

**Comment by Slyke** [comment]
Yep, my bad. Outdated drivers!
