### ISSUE TITLE
Can't run nicehash quick miner

### ISSUE THREAD

**Issue by JoseJoaoMario** [nicehash/NiceHashQuickMiner#301]
![image](https://user-images.githubusercontent.com/81702031/113173121-76d14600-921f-11eb-858c-cd4d4082bb05.png)

when i try to runn it shows this message, what should i do?

**Comment by nicehashdev** [comment]
You need to have NVIDIA drivers installed. QuickMiner only works for NVIDIA cards.

**Comment by JoseJoaoMario** [comment]
i will install right now to see if it works, thank you !!

**Comment by JoseJoaoMario** [comment]
![image](https://user-images.githubusercontent.com/81702031/113196862-595da580-923a-11eb-9132-d3e97fc462b0.png)

can you guys help me on this ?
