### ISSUE TITLE
"High" Mode Performance Issue

### ISSUE THREAD

**Issue by PatrickRodriguz2** [nicehash/NiceHashQuickMiner#302]
I'm using 3x 3090's. Once I started using v0.4.5.3 the performance of "high" optimization has dropped dramatically. Efficiency and hash rate has dropped dramatically, including power draw. See the screenshot attached.
![sample](https://user-images.githubusercontent.com/81702422/113174511-71bcc880-9218-11eb-847f-6c040feda100.jpg)

**Comment by nicehashdev** [comment]
I have just tested that and it works fine. What you should do is:
1. Make sure you have non-DCH version of drivers. Get latest non-DCH from here: https://www.nvidia.com/download/driverResults.aspx/172060/en-us
2. After you install, reboot (sometimes it is not needed, but in fact it is needed and saves many problems).
3. If it still doesn't work, enable logging and attach logs so I can inspect them.
