### ISSUE TITLE
My NiceHash QuickMiner is BUGGIN'

### ISSUE THREAD

**Issue by Wittyzz** [nicehash/NiceHashQuickMiner#303]
Okay the issue started when it was saying I the GPU- didn't have enough to work on so it closed a few times so I stopped it because I was playing a game at that time so it made sense after I stopped playing the game I turned on nicehash again and it kept on just closing randomly every 50 seconds and I've tried reinstalling live 3 times it never says any kind of error before just disconnecting I have wired internet so that shouldn't be it either. And then it opens again instantly and starts. Also I cannot close it manually if I do it just opens again even if I stop mining it opens automatically again.

**Comment by nicehashdev** [comment]
You need to use taskbar - on the right side there are icons - right click on NiceHash icon then choose Exit.

There was picture shown the first time you started it. You must have learned this, no?

**Comment by Wittyzz** [comment]
Yeah i did learn that but even after i pressed exit it still wouldn't close down even if I did it manually it would just open up again

**Comment by Wittyzz** [comment]
Also that doesn't explain why my NiceHash QuickMiner kept on closing every 50 seconds

**Comment by nicehashdev** [comment]
If you did exit it using tray icon, then it must have closed down.

But now you are saying that it was closing on its own?

I cannot help you if you do not give me reasonable and logic explanation of the problem.

**Comment by Wittyzz** [comment]
Alright, listen here. I said it closes every 50 seconds after I closed it since it wasn't doing anything because a game was taking too much GPU power so it keeps on closing every 50 seconds and there is no reasoning behind it. And now for some reason, it does work when I press exit on the small icons it didn't before.

**Comment by nicehashdev** [comment]
So, there is no problem anymore now?

**Comment by Wittyzz** [comment]
Yes there is..... It keeps closing every 50 seconds. But the exit/closing nicehash is gone.

**Comment by nicehashdev** [comment]
If it is closing every 50 seconds it means that there is mining error and it doesn't have any speed, so it restarts Excavator.

What card do you have?

**Comment by Wittyzz** [comment]
I have a nvidia geforce 1060 6GB and it has worked in the past for like a month almost but then when i closed it today it randomly just started doing that. and when it is on for the 50 seconds it does produce etherium.

**Comment by nicehashdev** [comment]
You have some other program that is also using your GPU thus making Excavator very slow so it cannot generate DAG in 45 seconds time thus it gets restarted. Verify what kind of applications are running. First thing you should do is reboot PC.

**Comment by Wittyzz** [comment]
Spotify google chrome discord task manager. Nothing really

**Comment by nicehashdev** [comment]
Close them all and see what happens then.

**Comment by Wittyzz** [comment]
I've had way stronger apps open without this happening I know for a fact it isn't that. And it doesn't say that it has anything to do with my gpu power and it works perfectly fine the 50 seconds it is on doing just as much work as usual with more gpu power to go.

**Comment by nicehashdev** [comment]
There is no work being done - speed is 0, that's why it closes. You can increase this timer and wait longer. Open _nhqm.conf_ and change `"whenDeviceSpeedSeconds" : 45,`  to `"whenDeviceSpeedSeconds" : 60,` . This will let it wait longer before restarting. See if it helps.

**Comment by Wittyzz** [comment]
So how do you know there's no work being done i can see the the daggerhashimito new job (clean) multiple times a second so does that not mean there's a working going on?

**Comment by nicehashdev** [comment]
Because speed of your mining is 0 - miner did not complete a single hash = no work done.

**Comment by Wittyzz** [comment]
But how am i gaining bitcoin on the nicehash app then if it's not doing any work? because i am gaining from the 50 seconds it is on at a time.

**Comment by nicehashdev** [comment]
Please, install latest version: https://github.com/nicehash/NiceHashQuickMiner/releases

Then use following Excavator: https://github.com/nicehash/NiceHashQuickMiner/releases/download/v0.4.5.5/excavator_b821.zip (replace original excavator.exe in your install folder).

**Comment by Wittyzz** [comment]
I already have installed the latest version 5 times man.

**Comment by nicehashdev** [comment]
Also install latest excavator build 821: https://github.com/nicehash/NiceHashQuickMiner/releases/download/v0.4.5.5/excavator_b821.zip

**Comment by Wittyzz** [comment]
do you know what that does look a lot like the exact same link,

**Comment by nicehashdev** [comment]
Latest RC version has fix regarding invalid DAG generation.

**Comment by Wittyzz** [comment]
aight thanks for telling me i should do what i already had done and closing the room without the problem being fixed.
