### ISSUE TITLE
RTX 3060 TI Hashing rate 61 to 61.54

### ISSUE THREAD

**Issue by ben1628** [nicehash/NiceHashQuickMiner#304]
I'm still using V0.4.1.3 and Nvidia driver 461.09.  The hashing rate seems to be pretty good.  It has been running for weeks without problem and monitoring, which is just great.

The question is should I upgrade to the latest version?

Thanks.

**Comment by nicehashdev** [comment]
You can always revert back to the old one, but new SW always brings features that are always good, and improvements. If there is something wrong, then you should report it and it will get fixed.
