### ISSUE TITLE
OC not save 

### ISSUE THREAD

**Issue by Captamtama** [nicehash/NiceHashQuickMiner#305]
just upgrade to 0.4.5.4 RC 
previous OC not working,
always back reset to max TDP
try resetting, save, and restart, then apply new OC
start again with max TDP and OC not apply
All configuration file not working on event start or stop, cant delay OC

**Comment by nicehashdev** [comment]
Make sure you set OPTIMIZATION profile in Rig Manager to Manual. If you have some OPTIMIZATION set, then it will  override your OCTune settings.

**Comment by Captamtama** [comment]
Yes its in Manual mode in rig manager
OC set via octune save in command file but not apply in excavator
octune for 3070 failed to apply in single or selected
closing excavator window will reset all cards to 100% TDP, then restart mining with 100% TDP, save of not work

**Comment by DarkAssassin48** [comment]
I confirm. Saving TDP setting does not work

**Comment by nicehashdev** [comment]
How do you open OCTune? There needs to be auth token provided. Example:

![octuneurl](https://github.com/nicehash/NiceHashQuickMiner/blob/main/images/octuneurl1.png?raw=true)

Without auth token, you can only view GPU stats, but not modify anything (can't change clocks, can't save OC configuration).

You can open URL with auth token if you right click NiceHash icon and then click OCTune. Auth token is saved in _nhqm.conf_.

**Comment by DarkAssassin48** [comment]
[

https://user-images.githubusercontent.com/40138340/113303883-2edb1d80-930a-11eb-9906-831aed9ec9fb.mp4

](url)

**Comment by nicehashdev** [comment]
I did not see you pressing the green button that saves current configuration in that video. If you do not press Save button then the modifications you make aren't saved into the file.

**Comment by DarkAssassin48** [comment]
https://user-images.githubusercontent.com/40138340/113307428-c857fe80-930d-11eb-8f2e-4ac811baf1bb.mp4

**Comment by nicehashdev** [comment]
Is your issue related to TDP not being set like here: https://github.com/nicehash/NiceHashQuickMiner/issues/306 ?

**Comment by Captamtama** [comment]
yes, as my explanation in 1st post

**Comment by nicehashdev** [comment]
Okay, then this is duplicate. Go to https://github.com/nicehash/NiceHashQuickMiner/issues/306 A fixed excavator.exe was posted there.

**Comment by DarkAssassin48** [comment]
> Okay, then this is duplicate. Go to #306 A fixed excavator.exe was posted there.

Yes. Fix. Now everything is saved
