### ISSUE TITLE
TDP not set

### ISSUE THREAD

**Issue by lonelymyp** [nicehash/NiceHashQuickMiner#306]
0.4.5.4
![image](https://user-images.githubusercontent.com/2085051/113306645-fab52c00-930c-11eb-8c44-5759647f31f4.png)

In 0.4.5.3 - OK

**Comment by nicehashdev** [comment]
Confirming. Really a bug. Already working on it.

**Comment by nicehashdev** [comment]
Let me know if following excavator.exe fixes your issue (build 818):
[excavator_build818.zip](https://github.com/nicehash/NiceHashQuickMiner/files/6244385/excavator_build818.zip)

**Comment by nicehashdev** [comment]
Fixed in latest RC version. Closing.
