### ISSUE TITLE
1080ti hashing slower 32H/s down to 28MH/s with v0.4.5.5 update

### ISSUE THREAD

**Issue by panascope** [nicehash/NiceHashQuickMiner#308]
How do we bring this hashrate back you please
1 Have  1080ti and all have slowed down after update

Windows 10

Cheers

**Comment by nicehashdev** [comment]
You will have to completely revamp your OC settings and experiment with memory timings: https://github.com/nicehash/NiceHashQuickMiner/wiki/Memory-timings

If you are lazy, then just use OPTIMIZE. And do **NOT** use EthEnlargementPill - it may mess with memory timings set by Excavator which could lead into instability.

**Comment by panascope** [comment]
Certainly not lazy! Just not sure where to start:
Could you provide simple starter settings for 1080ti? It would be very helpful, as I am not an expert and I have been loyal to using nicehash for 2 years now.

Thank you in advance

**Comment by panascope** [comment]
"Medium" worked VERY well!! wow
