### ISSUE TITLE
big crashes with my rtx 3090

### ISSUE THREAD

**Issue by evrenbicer** [nicehash/NiceHashQuickMiner#309]
hello there, after the update, there are lots of problems after picking high and efficient modes. 
![20210401_234727](https://user-images.githubusercontent.com/81778504/113353569-8dbe8800-9346-11eb-810c-e4f05379c614.jpg)

pls help urgently

**Comment by evrenbicer** [comment]
sorry my device 5 is 3060ti

**Comment by nicehashdev** [comment]
First reboot your PC.
If it doesn't work, update your drivers to the latest non-DCH version: https://www.nvidia.com/download/driverResults.aspx/172060/en-us
Then if it doesn't work, do DDU first and then install drivers. If that doesn't work, reinstall Windows then install drivers and then NHQM and will work 100% all OK.

**Comment by evrenbicer** [comment]
![20210402_001513](https://user-images.githubusercontent.com/81778504/113355147-045c8500-9349-11eb-9688-4260987a64bd.jpg)
![20210402_001500](https://user-images.githubusercontent.com/81778504/113355153-06264880-9349-11eb-8ceb-a27adfc4ad58.jpg)

**Comment by evrenbicer** [comment]
this is also my second rig, how about this one?

**Comment by nicehashdev** [comment]
Same procedure. These errors should not happen at all - signalize some error in NVIDIA libraries/drivers.

**Comment by evrenbicer** [comment]
thanks I will try your recommendations

**Comment by evrenbicer** [comment]
it kept rebooting, so I am using older version of our miner, I think there are lots of people who have similar problems. Please could you help all of us for a new stable release

**Comment by nicehashdev** [comment]
If you have issues with crashes of Excavator (with Lite optimization or crashes that did not happen with previous version), or you are getting Invalid DAG message, you may try following test version of [Excavator Build 820](https://github.com/nicehash/NiceHashQuickMiner/releases/download/v0.4.5.5/excavator_b820.zip). Simply replace your original excavator.exe with the new one. SHA256 of the ZIP package is `7068D4BF28089C3B309B1051ED69C3F40DD7FB5837737EEF02191E84C6B5A651`. Please, report your results by submitting [an issue](https://github.com/nicehash/NiceHashQuickMiner/issues). If it doesn't work, [enable full detailed logging](https://github.com/nicehash/NiceHashQuickMiner/wiki/Tips-&-tricks#5-enable-logging-for-better-troubleshooting), export log files and attach exported .zip file to the issue.

**Comment by nicehashdev** [comment]
Do you still have issues with this?

**Comment by evrenbicer** [comment]
I have 7 rigs, 5 of them works well till the update with the new release. However, 2 of them couldnt and I tried all the ways that a computer scientist can do!! Even I changed the mainboard-cpu, I tried all your solutions, even I bought a new windows 10 pro!! They keep restarting after a period of time.  As a result I am using the older stable version of NQM, and these 2 rigs are working without any problems. So we can understand that new release has still some problems. By the way, I have 5-6 different GPU's and 4-5 different graphic card brands in these 2 rigs. So I hope you will fix these problems with the upcoming releases. The negative part is my old release NQM couldnt use full potential of my GPUs :(

**Comment by evrenbicer** [comment]
I have 7 rigs, 5 of them works well with new NQM.  However, 2 of them couldnt and I tried all the ways that a computer scientist can do!! Even I changed the mainboard-cpu, I tried all your solutions, even I bought a new windows 10 pro!! They keep restarting after a period of time. As a result I am using the older stable version of NQM, and these 2 rigs are working without any problems. So we can understand that new release has still some problems. By the way, I have 5-6 different GPU's and 4-5 different graphic card brands in these 2 rigs. So I hope you will fix these problems with the upcoming releases. The negative part is my old release NQM couldnt use full potential of my GPUs :(

**Comment by nicehashdev** [comment]
Do you still get this issue you posted in screenshot - failed to set power mode and failed to set core uvolt, or do you have another problem now?

Are you aware that not all cards are stable on all optimize profiles? We try to cover as much GPUs as possible, but it is impossible to make optimizations for all cards. What kind of optimizations are you trying to apply? What about Lite, does it work with Lite?

**Comment by evrenbicer** [comment]
I have 3 micron 1 samsung here. And as u can see the NQM older version  is working. Still sometimes it restarts but not often. The new NQM makes it restarts frequnetly

![14as](https://user-images.githubusercontent.com/81778504/113511360-19fbc580-9568-11eb-97b9-d7b3009eac12.jpg)

**Comment by nicehashdev** [comment]
Could you make a test and see how often it restarts if you take out Micron card?

**Comment by evrenbicer** [comment]
here is the details. 2 cards are identical, the others are different. check out the working conditions. Now they are mining with previous version NQM
![22](https://user-images.githubusercontent.com/81778504/113511562-00a74900-9569-11eb-8580-d9e790e4f8af.jpg)
![33](https://user-images.githubusercontent.com/81778504/113511568-06049380-9569-11eb-997c-131443a8573d.jpg)


![11](https://user-images.githubusercontent.com/81778504/113511557-fab16800-9568-11eb-9f2c-483eb0238f2a.jpg)

**Comment by evrenbicer** [comment]
> Could you make a test and see how often it restarts if you take out Micron card?

shall I check with new NQM?

**Comment by nicehashdev** [comment]
Yes, take out Micron card and just try with other 3 running latest version.

**Comment by evrenbicer** [comment]
I will, by the way I have been testing 2060s with micron on latest version for about 3380 minutes! Not stopped at all. 41.5 mh with high opti. What would you like to say about it :)

**Comment by evrenbicer** [comment]
also I have 1660s micron and 2060 micron in my another rig. working non stop for 3260min so far. here are the details
![145134](https://user-images.githubusercontent.com/81778504/113512408-2afb0580-956d-11eb-9bfa-991919d2d8e0.jpg)

**Comment by evrenbicer** [comment]
I think there is another problem, we should find out why?

**Comment by evrenbicer** [comment]
on second thought, can it be because of high temp of some chips regardless of the brand of the chip. The optim. settings can make some chips too hot and cause reset

**Comment by nicehashdev** [comment]
Yes, if chips are too hot, they consume more power and there s higher chance for data corruption which leads into instability = crashes.

Optimization profile for 1660 SUPER with Micron VRAM has been changed so it should be okay (at least Lite profile should work fine for you).

**Comment by nicehashdev** [comment]
If you still have issues with 1660 Micron memory, continue here: https://github.com/nicehash/NiceHashQuickMiner/issues/315
