### ISSUE TITLE
> And another question; perhaps you had an AMD GPU before and you did not reinstall Windows after upgrading to NVIDIA card?

### ISSUE THREAD

**Issue by dictatore** [nicehash/NiceHashQuickMiner#31]
> And another question; perhaps you had an AMD GPU before and you did not reinstall Windows after upgrading to NVIDIA card?

No.I assembled a PC from new components, initially this assembly was assembled from such components and nothing has changed. Perhaps reinstalling Windows will help, I hope. Since there are two more users on this PC, and perhaps they installed something that interferes with the work.
I recently became interested in mining, Windows was installed a long time ago and during this time a lot of things were installed or removed, experimented. After the first withdrawal of funds, I will try to reinstall Windows and then I will report the result.

_Originally posted by @dictatore in https://github.com/nicehash/NiceHashQuickMiner/issues/10#issuecomment-779144664_

**Comment by nicehashdev** [comment]
Okay. Please, report your findings here: https://github.com/nicehash/NiceHashQuickMiner/issues/10#issuecomment-779144664
