### ISSUE TITLE
Excavator Invalid Dag Generation Memory OC too high?  3060RTX

### ISSUE THREAD

**Issue by Cheeks87** [nicehash/NiceHashQuickMiner#310]
I was mining on this 3060 with the last quickminer with zero issues.  I saw you had an update and Installed it and started getting this error.  Ive tried to remove the OC but the OCtune isnt making changes.  I am currently running the 470.05 Driver for the RTX 3060 for the unlocked hashrate.  I was running the "medium tune" through the quickminer.  
What can I do on my end to attempt to remedy this?  
![dagger](https://user-images.githubusercontent.com/81778910/113355151-592eda00-930e-11eb-9394-c66e24d67b68.jpg)

**Comment by nicehashdev** [comment]
Try to reboot your PC first.

**Comment by Cheeks87** [comment]
I have done this, as well has reinstall quickminer, and rebooted the Nvidia drivers.

**Comment by nicehashdev** [comment]
Enable full logging and export logs after it happens then attach them here.

**Comment by Cheeks87** [comment]
[exported_logs.zip](https://github.com/nicehash/NiceHashQuickMiner/files/6246579/exported_logs.zip)

Here they are.

**Comment by nicehashdev** [comment]
If you use this excavator, does it work: https://github.com/nicehash/excavator/releases/download/v1.6.11d/excavator_v1.6.11d_b815_Win64_signed.zip

**Comment by Cheeks87** [comment]
I just want to add as well the benchmark also failed for excavator for daggerhashimoto, though with NBMiner I can still use Daggerhashimoto.  Not sure if that helps any at all or not.

This was when I was testing out the NiceHash Miner and not the quickminer.

**Comment by Cheeks87** [comment]
I replaced the excavator file in my quickminer installation path with the one you provided and Im still getting the same thing.

**Comment by Cheeks87** [comment]
Im not sure what happened, but its working exactly like it should with my "medium" settings turned on.

**Comment by nicehashdev** [comment]
If you have issues with crashes of Excavator (with Lite optimization or crashes that did not happen with previous version), or you are getting Invalid DAG message, you may try following test version of [Excavator Build 820](https://github.com/nicehash/NiceHashQuickMiner/releases/download/v0.4.5.5/excavator_b820.zip). Simply replace your original excavator.exe with the new one. SHA256 of the ZIP package is `7068D4BF28089C3B309B1051ED69C3F40DD7FB5837737EEF02191E84C6B5A651`. Please, report your results by submitting [an issue](https://github.com/nicehash/NiceHashQuickMiner/issues). If it doesn't work, [enable full detailed logging](https://github.com/nicehash/NiceHashQuickMiner/wiki/Tips-&-tricks#5-enable-logging-for-better-troubleshooting), export log files and attach exported .zip file to the issue.

**Comment by nicehashdev** [comment]
Continue here: https://github.com/nicehash/NiceHashQuickMiner/issues/315
