### ISSUE TITLE
Constant Rig Crashes Despite Following Directions

### ISSUE THREAD

**Issue by Hawaii1090** [nicehash/NiceHashQuickMiner#311]
Was running 4.5.4 stable fine for days, updated to 4.5.5  and the rig constantly blue screens and reboots. Updated NVIDIA drivers per the troubleshooting guidelines, rebooted the machine, same issue. Will show this error then about 30 seconds later the screen goes black and it reboots.

3x 1660 Super
1x RTX 3070
1x RTX 3080

I manually went back to v4.5.4 and it's running fine now. Cannot run 4.5.5. What else can i try to get it to work?

![Error](https://user-images.githubusercontent.com/81779239/113355626-11f51900-930f-11eb-8039-c8db30c02e79.png)
`

**Comment by nicehashdev** [comment]
Can you give me version of Excavator that works fine for you and which one doesn't work fine?

**Comment by nicehashdev** [comment]
Also tell me what kind of OCs are you running or you use OPTIMIZE and what happens if you go down 1 step with OPTIMIZE?

And is your driver DCH or non-DCH?

**Comment by Hawaii1090** [comment]
> 
> 
> Can you give me version of Excavator that works fine for you and which one doesn't work fine?

Thank you for the prompt reply. 
Working: 0.4.5.4
Not Working: 0.4.5.5

**Comment by nicehashdev** [comment]
Select LITE and report back what happens.

I need version of excavator (or build number), it is printed out at start or if you right click it and go into file properties.

**Comment by Hawaii1090** [comment]
ill get excavator in a few. the lastest version released causes the issue.

how can i select lite if it crashes when it starts?

**Comment by nicehashdev** [comment]
Delete nhqm.conf file to reset QuickMiner.

Before you boot into Windows, unplug PC from internet.

**Comment by nicehashdev** [comment]
Can you tell me model of your 3080?

**Comment by Hawaii1090** [comment]
> 
> 
> Delete nhqm.conf file to reset QuickMiner.
> 
> Before you boot into Windows, unplug PC from internet.

Working: excavator  V1.6.11d
Non Working : excavator   1.6.11f

The 3080 is ASUS 3080. 

Uninstalled, deleted the c:\program files\NiceHash directory, re-installed have it running now - will let it run for a hour and advise if any issue. Thank you for your great support!

**Comment by nicehashdev** [comment]
So, Lite is working now? You can do one more test; take excavator.exe from 0.4.5.4 and put it into 0.4.5.5. Does Medium work OK then without crashes?

**Comment by Hawaii1090** [comment]
not working. was running for a bit then errored and restarted on 'lite'. 
![erro2](https://user-images.githubusercontent.com/81779239/113363336-9ac78100-931e-11eb-810d-98dd8222fdf2.png)

**Comment by nicehashdev** [comment]
Okay, so we know now that the problem is not overclock, but something else. Please, try swapping files as I suggested.

**Comment by Hawaii1090** [comment]
Swapping what files?

**Comment by Hawaii1090** [comment]
> 
> 
> Okay, so we know now that the problem is not overclock, but something else. Please, try swapping files as I suggested.

Trying swapping the files now. It ran and then the same error. Can't use this version

**Comment by Hawaii1090** [comment]
It was up and running, on nicehash i had the "optimize" button. I went to a single card and tried to swap it to "Efficient". Immediatey crashed the rig.
![Erro3](https://user-images.githubusercontent.com/81779239/113365189-79b55f00-9323-11eb-88ae-8697723119b5.png)

**Comment by Hawaii1090** [comment]
The issue is definatley the 1660s. When i optimize the other cards, they seem to work fine.

**Comment by nicehashdev** [comment]
Can you try with older version? What if you run latest stable 0.4.1.3? Does it work all OK or problems?

**Comment by nicehashdev** [comment]
If you have issues with crashes of Excavator (with Lite optimization or crashes that did not happen with previous version), or you are getting Invalid DAG message, you may try following test version of [Excavator Build 820](https://github.com/nicehash/NiceHashQuickMiner/releases/download/v0.4.5.5/excavator_b820.zip). Simply replace your original excavator.exe with the new one. SHA256 of the ZIP package is `7068D4BF28089C3B309B1051ED69C3F40DD7FB5837737EEF02191E84C6B5A651`. Please, report your results by submitting [an issue](https://github.com/nicehash/NiceHashQuickMiner/issues). If it doesn't work, [enable full detailed logging](https://github.com/nicehash/NiceHashQuickMiner/wiki/Tips-&-tricks#5-enable-logging-for-better-troubleshooting), export log files and attach exported .zip file to the issue.

**Comment by Hawaii1090** [comment]
> 
> 
> Can you try with older version? What if you run latest stable 0.4.1.3? Does it work all OK or problems?

it was fine with the last version. I tried this version -> https://github.com/nicehash/NiceHashQuickMiner/releases/tag/v0.4.5.4_RC

. If install and leave alone it works. If i use optimize it crashes  Running now with no optimizations and its okay.

**Comment by Hawaii1090** [comment]
> 
> 
> If you have issues with crashes of Excavator (with Lite optimization or crashes that did not happen with previous version), or you are getting Invalid DAG message, you may try following test version of [Excavator Build 820](https://github.com/nicehash/NiceHashQuickMiner/releases/download/v0.4.5.5/excavator_b820.zip). Simply replace your original excavator.exe with the new one. SHA256 of the ZIP package is `7068D4BF28089C3B309B1051ED69C3F40DD7FB5837737EEF02191E84C6B5A651`. Please, report your results by submitting [an issue](https://github.com/nicehash/NiceHashQuickMiner/issues). If it doesn't work, [enable full detailed logging](https://github.com/nicehash/NiceHashQuickMiner/wiki/Tips-&-tricks#5-enable-logging-for-better-troubleshooting), export log files and attach exported .zip file to the issue.

Tried replacing excavator. As soon as i click optimize it crashes.

**Comment by nicehashdev** [comment]
Please, continue here: https://github.com/nicehash/NiceHashQuickMiner/issues/315
