### ISSUE TITLE
hashing not working since the last update

### ISSUE THREAD

**Issue by YeetMyCode** [nicehash/NiceHashQuickMiner#314]
![image](https://user-images.githubusercontent.com/81785429/113369648-cacb5000-932f-11eb-93c6-1c8fab2407f9.png)

my NiceHash miner stop working after the automatic update, 
i tried to update, roll back my gpu driver and windows driver, and still got that *error. the program said is initiated, but no hashing, nothing. maybe take a look

Thank in advance

**Comment by nicehashdev** [comment]
If you have issues with crashes of Excavator (with Lite optimization or crashes that did not happen with previous version), or you are getting Invalid DAG message, you may try following test version of [Excavator Build 820](https://github.com/nicehash/NiceHashQuickMiner/releases/download/v0.4.5.5/excavator_b820.zip). Simply replace your original excavator.exe with the new one. SHA256 of the ZIP package is `7068D4BF28089C3B309B1051ED69C3F40DD7FB5837737EEF02191E84C6B5A651`. Please, report your results by submitting [an issue](https://github.com/nicehash/NiceHashQuickMiner/issues). If it doesn't work, [enable full detailed logging](https://github.com/nicehash/NiceHashQuickMiner/wiki/Tips-&-tricks#5-enable-logging-for-better-troubleshooting), export log files and attach exported .zip file to the issue.

**Comment by CuttzCyrpto** [comment]
seems I am having same issues.
I was getting INV AUTH TOKEN for a little there in the browser when clicking start. So I reset my 2factor only to discover that gives my account a cool down.
Guess ill have to wait a day or 2 to see if it happens again. If I had have known there was this many errors I defiantly wouldn't have updated.

Is there a solution?

**Comment by YeetMyCode** [comment]
Everything is working now, thank you guys!

**Comment by CuttzCyrpto** [comment]
![image](https://user-images.githubusercontent.com/81786243/113370931-cd21be80-93b0-11eb-81e7-df2fb51d47b6.png)

**Comment by nicehashdev** [comment]
> Everything is working now, thank you guys!

What solved the problem?

**Comment by nicehashdev** [comment]
@CuttzCyrpto you are using some old version - build v742 is pretty old. We are using v819 and v820 now.

**Comment by CuttzCyrpto** [comment]
this is what it updated to. ill have a look for a newer version. now

**Comment by CuttzCyrpto** [comment]
so I have replaced the old excavator with the ne file posted in this thread. hit start and it kind of seems t be working but...its trying to pen another while its mining. also throwing heaps of messages now
![Uploading image.png…]()

**Comment by CuttzCyrpto** [comment]
![image](https://user-images.githubusercontent.com/81786243/113379384-0fed9180-93c5-11eb-9c7a-769f14b20911.png)
as you can see task bar showing 2 instances  do i need to do something else o get this version to work smoothly?

**Comment by CuttzCyrpto** [comment]
ok I may have found a fix. I had to allow my Malwarebytes full permission to the folder. as the new version wasn't supported. even though the old one was. 
I also performed a PC reset and it seems to be working solid now.
   
![image](https://user-images.githubusercontent.com/81786243/113379989-c140f700-93c6-11eb-90e5-98557c969157.png)

**Comment by MrEnergy64** [comment]
Update: I had to remove all Nicehash Tools from my Windows machine, reboot it, installed QuickMiner 0.4.5.5 and now everything is running again.

**Comment by ssmining** [comment]
Im having the same issue since the update, press start on the quickminer icon on the taskbar and nothing happens. Have restarted, re-installed and nothing. Am running build v819 since the 1 April update.

**Comment by CuttzCyrpto** [comment]
I fixed it via virus protection.
Had to add the new exc files but yeah it was my virus protection as the fault

**Comment by nicehashdev** [comment]
Looks like fixed.
