### ISSUE TITLE
Add option to suppress the alert when switching "Game Mode"

### ISSUE THREAD

**Issue by limacohen** [nicehash/NiceHashQuickMiner#316]
Just a simple checkbox to not show the alert anymore. Ideally, a way to switch modes just by double clicking the tray icon.

![Alert](https://i.imgur.com/i1VAsog.png)

**Comment by nicehashdev** [comment]
Check config; you can do that already.

**Comment by limacohen** [comment]
Thanks! I couldn't find any docs on the config file so for posterity, this would be:
`"gameStateOverclock" : {
		"bHideConfirmationDialogs" : true
}`
