### ISSUE TITLE
Хэшрейт на RTX 3090 и GTX 1080 Ti отличается от калькулятора примерно на 10 MH/s

### ISSUE THREAD

**Issue by Yuranka** [nicehash/NiceHashQuickMiner#318]
Всем здравствуйте! Как недавно стало известна прекрасная новость, что наконец-то добавили оптимизацию для 1xxx серий GTX видеокарт и я наконец-то смог оптимизировать вторую видеокарту, но вот проблема, вместо заявленных на RTX 3090 - 120 Mh/s и на GTX 1080 TI - 46 Mh/s я получаю на RTX 3090 - примерно 105-112 Mh/s, а на GTX 1080 Ti - 39-42 Mh/s, хоть и немного не дотягиваю до положенных, но всё равно обидно, ведь теряю почти целых 10 Mh/s! Какие-то сторонние программы для разгона типа MSI Afterburner не использую, воспользовался лишь Высокой оптимизацией от NiceHash на NiceHash Quick Miner, подскажите, как можно исправить данную проблему.
![bandicam 2021-04-02 18-49-43-702](https://user-images.githubusercontent.com/81821208/113431936-2e638500-93e5-11eb-96e8-6b033b6a8318.jpg)

**Comment by nicehashdev** [comment]
English please.
