### ISSUE TITLE
Not compatible with GeForce GTX 1050 Ti

### ISSUE THREAD

**Issue by ByLuisG27** [nicehash/NiceHashQuickMiner#321]
I have installed the program and it does not work properly with the Nvidia GeForce GTX 1050 Ti processor.

**Comment by idsbrj** [comment]
I have same problem but with Nvidia GeForce GTX 1050

**Comment by idsbrj** [comment]
![excavator](https://user-images.githubusercontent.com/14222008/113465671-e583ee80-942d-11eb-8a92-9e89c37ed16c.PNG)

**Comment by nicehashdev** [comment]
This GPU is not supported, check here: https://github.com/nicehash/NiceHashQuickMiner/wiki/Supported-hardware
