### ISSUE TITLE
After starting Quickminer 0.4.5.5 the screen is going black sometimes orange etc. and its stuck there.

### ISSUE THREAD

**Issue by MrAltik** [nicehash/NiceHashQuickMiner#322]
I installed the new version and this keeps happening... i dont know what to do... i think I will switch to previous versions...
I have GeForce GTX 1660 SUPER

**Comment by vanjo666** [comment]
yep, many people are having this problem too with 1660s, how to switch to previous versions anw?

**Comment by JaminSince83** [comment]
Same here I went back to 4.2.1 RC and it worked fine.

**Comment by vanjo666** [comment]
> Same here Im using the latest Nvidia Driver 465.89, clean instalkl didnt make any difference so I went back to 4.2.1 RC and it worked fine.

how to install previous version?

**Comment by MrAltik** [comment]
> > Same here Im using the latest Nvidia Driver 465.89, clean instalkl didnt make any difference so I went back to 4.2.1 RC and it worked fine.
> 
> how to install previous version?

Look here for releases... https://github.com/nicehash/NiceHashQuickMiner/releases

Interesting is that when I went back from 0.4.5.5 to 0.4.5.3 version this was not happening but it now does same on 0.4.5.3 version so thats weird. lmao 

I think I'll try 0.4.2.1 as he said.

**Comment by nicehashdev** [comment]
What kind of memory do you have on 1660 SUPER?

**Comment by JaminSince83** [comment]
It’s 6GB

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by MrAltik** [comment]
Yeah it's 6 GB

**Comment by nicehashdev** [comment]
Micron, Hynix, Samsung?

**Comment by evrenbicer** [comment]
Djezo, I have the same problem with 1660s. So do you think it might happen due to memory chips?? because in my some rigs 1660s works fine with new release, another rig with 1660supers doesnt work, so I am using older NQM
I am shocked if it is true

**Comment by MrAltik** [comment]
> Micron, Hynix, Samsung?

Oh like this? Then I have (G.Skill Aegis 16GB (2x8GB) DDR4 3200 CL16)

**Comment by nicehashdev** [comment]
No, VRAM on GPU. Is it Micron, Samsung or Hynix? You can check that with GPU-Z.

**Comment by nicehashdev** [comment]
> > Same here Im using the latest Nvidia Driver 465.89, clean instalkl didnt make any difference so I went back to 4.2.1 RC and it worked fine.
> 
> how to install previous version?

0.4.2.1 is still using old optimization data (003) which would explain many things - mainly, Micron cannot take memory clocks of 600 (for Lite) and 900 (for Medium). I have inserted new profiles for Micron into data 005 which is being used recently. All owners of 1660 SUPER with Micron memory should try it out and see what happens now (all you have to do is restart NiceHash QuickMiner) - try Lite and Medium. Does it crash or does it work and what kind of speeds do you get.

Previous profile was applying negative memory clock and as far as I know, this works good only for Hynix. Did you get good speeds with previous versions? You should be getting over 30, over 31 with Medium profile. Hynix memory gets almost 31.5 MH/s with Medium profile.

**Comment by MrAltik** [comment]
> GPU-Z

Sorry for that. There is screenshot with GPU-Z.
![sdad](https://user-images.githubusercontent.com/34842092/113513227-e4a3a780-9568-11eb-9d3e-e14e5c6deacc.gif)

**Comment by nicehashdev** [comment]
Okay, looks like the problem is in Micron memory. I have added an exception. Please, restart your NiceHash QuickMiner (latest version) and it should be good now. Note that Medium and Efficient may not work if your memory chips are really bad, but Lite should work for sure.

**Comment by nicehashdev** [comment]
If you still have issues, please continue here: https://github.com/nicehash/NiceHashQuickMiner/issues/315

**Comment by JaminSince83** [comment]
I can confirm this is now working on medium efficiency on v4.5.5.

My 1660 Super had Micron memory too.
