### ISSUE TITLE
Update to latest

### ISSUE THREAD

**Issue by ben1628** [nicehash/NiceHashQuickMiner#325]
There was a message asking me to update to latest...

I assume that's all I need to do to update to latest without reinstalling.

I then click Optimize and choose High on my mobile and everything seems to be working. efficiency is better.

It doesn't seem to update commands.json at all !

**Comment by nicehashdev** [comment]
Commands.json file is not being update when you are working with OPTIMIZE profiles. Commands.json is used for manual OC only.
