### ISSUE TITLE
Improved GTX 1080 Medium optimization profile

### ISSUE THREAD

**Issue by alexandrurobertlazar** [nicehash/NiceHashQuickMiner#328]
Hello,

I would like to suggest some very slight modifications to the Medium profile. Please note these clocks are stable for my GPU, and may not be stable for all GTX 1080s.

Core clock delta +165 MHz (I would suggest +125, to be on the safe side)
Memory clock delta: leave as it is
TDP: 110W

With this, I get very similar speeds to the Medium profile as it is right now (to get the same speeds - TDP 115W), except I have a much higher efficiency, and I am able to have my fan at 50%.

**Comment by nicehashdev** [comment]
+125 is quite high core overclock and I do not think that all cards can take this. I will run some tests and see what can be done, perhaps for a new High profile that hasn't been made for 1080 yet.

**Comment by alexandrurobertlazar** [comment]
I would rather suggest keeping my suggestion for a Medium profile, and setting a TDP of 130W for the High profile. With 130W, I can achieve 33+ MH/s with my settings (+165 core clock). I have done myself other tests with my card, and increasing even more the TDP does not make any effect to hashrate.

Normally, a GTX 1080 should be able to easily get +125 core clock, even for gaming.

**Comment by nicehashdev** [comment]
It really depends what kind of card you have. I have one sample that just wouldn't go above 30 and it works with only certain memory clocks, others crash out with cuda error. 1080 are really weird cards and hard to tune with some common settings. Far from what can be achieved with 3070 for example.

**Comment by nicehashdev** [comment]
Improved Efficient and High was added. This should be enough since High gets you 34 MH/s and Efficient gets you 33 MH/s at 110 W now.
