### ISSUE TITLE
3060ti less performance and more power consumption

### ISSUE THREAD

**Issue by ricardovsilva** [nicehash/NiceHashQuickMiner#33]
I'm using v0.3.0.2 of excavator. In comparison to Phoenix + MSI it is consuming more energy and processing less.
![image](https://user-images.githubusercontent.com/2130182/107959888-b7804300-6f82-11eb-88c2-0a6727ddd911.png)

![image](https://user-images.githubusercontent.com/2130182/107960357-4b520f00-6f83-11eb-9bf7-36d0b099df42.png)

![image](https://user-images.githubusercontent.com/2130182/107960270-2f4e6d80-6f83-11eb-8bf2-ce3e967d7959.png)

This is, of course, on windows. On Ubuntu I get at maximum 50MH/s, with Phoenix Miner, and cannot set memory overclock.

**Comment by nicehashdev** [comment]
Well, according to your performance, you are doing definitely something wrong with your settings/drivers/cooling.

Normally, Excavator gets 60 MH/s at around 120 W.

**Comment by nicehashdev** [comment]
No response, closing.

**Comment by ricardovsilva** [comment]
Sorry, I had no time in past to read that. 
What can I be doing wrong? Phoenix is working fine, not 60MH/s per 120W but 60MH/s per 130 ~ 160W. GPU temperature is never going up to 60 celsius degrees. I'm new in mining world but I believe that 60 is ok, right?

Is there some specific driver that I should use with excavator?

**Comment by ricardovsilva** [comment]
> you are doing definitely something wrong with your settings/drivers/cooling.  

This is kinda generic answer, obviously is there something wrong and this one can be settings/driver/cooling OR excavator. Since Phoenix achieve a good result and excavator not, I eliminated the the first three options. But I'm open to suggestions.
