### ISSUE TITLE
Quick Miner is running but showing "offline" in rig manager

### ISSUE THREAD

**Issue by nighttrain1979** [nicehash/NiceHashQuickMiner#330]
Rig is running but I can't manage it, I can see it's projected earnings, stats, etc. It shows as "offline" on rig manager and iphone app.  Excavator shows accepted shares, power, eff, etc.

**Comment by nicehashdev** [comment]
Make sure that no AV is interfering with any files of NiceHash QuickMiner. Even if you whitelisted, made exclusion or even turned AV off, it can still happen to be alive and make a mess. Check this conversation I had recently: ![img](https://user-images.githubusercontent.com/10868174/113488986-c040c000-94c1-11eb-9830-6646bd94c9af.jpeg)

**Comment by nighttrain1979** [comment]
I have no 3rd party AV. I am running win 10 pro so I have disabled defender in Group policy. When I first installed quick miner about a week ago it was working perfectly but something broke it. I have 2 other rigs on same network and they are running QM with zero issues. I have uploaded logs for further help, thank you.
[exported_logs.zip](https://github.com/nicehash/NiceHashQuickMiner/files/6254814/exported_logs.zip)


I am seeing errors like this:
[2021-04-03 22:25:15:296] [TRACE] [watchdog] HTTP API GET: /devices_cuda
[2021-04-03 22:25:16:152] [TRACE] [watchdog] No devices, cannot establish opt profiles
[2021-04-03 22:25:17:165] [TRACE] [watchdog] No devices, cannot establish opt profiles
[2021-04-03 22:25:17:308] [DEBUG] [watchdog] Getting devices parse err: The request was aborted: The operation has timed out.
[2021-04-03 22:25:17:308] [DEBUG] [nhmws] Sending status data
[2021-04-03 22:25:17:308] [TRACE] [nhmws] Sending: {"method":"miner.status","params":["UNKNOWN",[]]}
[2021-04-03 22:25:17:308] [TRACE] [nhmws] Sent result: True
[2021-04-03 22:25:18:182] [TRACE] [watchdog] No devices, cannot establish opt profiles

**Comment by nicehashdev** [comment]
What kind of video card(s) do you have?

**Comment by nighttrain1979** [comment]
Problem rig is running all 30 series, 14 cards, 1 x 3080, 2 x 3070, 11 x 3060ti

**Comment by nighttrain1979** [comment]
I did a restart, and reset network adapter in case there was dns issue or something of that nature, I just checked rig manager and it is now showing online, which is good. I will see if it holds and if it allows me to use one click optimization, which is what I would prefer. It's such a cool upgrade you guys have done. I will follow up if the problem persists. Please let me know if you see something obviously wrong in my logs.  Thank You.

**Comment by nighttrain1979** [comment]
Spoke too soon, it's back to "unknown" status already, ugh

**Comment by nicehashdev** [comment]
Sad truth is that API call `/devices_cuda` can be very "hungry", because NVIDIA API calls require a lot of CPU processing and take a lot of time to execute. This method also returns data for all devices so in your case, it takes around 3 seconds to be executed. This is  outside of expected response - 2 seconds. Try setting  `"watchDogAPITimeout" : 2000` to `"watchDogAPITimeout" : 5000,` in _nhqm.conf_ and then restart NiceHash QuickMiner.

Also, make sure you are using non-DCH drivers! It is very important in this case otherwise you are leaking memory like a ...

**Comment by nighttrain1979** [comment]
Thank you, do you have a link for the recommended non-dch driver?

**Comment by nighttrain1979** [comment]
Found it. Another question, is there any way to pre-load oc settings when running qm for the first time? I have an issue where my rig reaches too much power draw before I am able to configure the overclocks, thus tripping my 20 amp breaker. It won't come online fast enough for the optimizations to take hold before this happens.

**Comment by nicehashdev** [comment]
You can configure to use local optimization data file: https://github.com/nicehash/NiceHashQuickMiner/wiki/One-click-Optimizations#is-it-possible-to-slightly-modify-optimization-profiles

**Comment by nighttrain1979** [comment]
OK, installed latest non-dch driver, changed config file for watchdog timeout increase. Rig is now appearing in rig manager and one click optimization worked. Will see if it holds. Thank you for the help, you guys are rockstars. Cheers!

**Comment by nighttrain1979** [comment]
All is well except when I try the "high" one-click optimizations. My one 3080 will start reporting 1000w power draw and then the whole thing crashes and windows reboots. I am assuming that it's just too much for the card and should stick with "medium" on that one.
