### ISSUE TITLE
[QUESTION] 

### ISSUE THREAD

**Issue by rpomav** [nicehash/NiceHashQuickMiner#335]
**Has the question been answered in [Wiki](https://github.com/nicehash/NiceHashQuickMiner/wiki)? There is no such question in [FAQ](https://github.com/nicehash/NiceHashQuickMiner/wiki/FAQ) or [Troubleshooting collection](https://github.com/nicehash/NiceHashQuickMiner/wiki/Troubleshooting)?**
Yes/No.

**Your question is...**

=========================== www.nicehash.com =========================
           Excavator v1.6.11f GPU Miner for NiceHash.
           Copyright (C) 2021 NiceHash. All rights reserved.
=========================== www.nicehash.com =========================

Build time: 2021-04-01 17:10:09
Build number: 819
Provided startup commandline: -c commands.json -qx -qm -d 2 -f 0 -wi localhost -wp 18000 -wa bd6d04e7-2fec-4134-8e22-e6095d9aed28

[12:24:27][0x000002b0][info] Log started, build v819
[12:24:27][0x000002b0][error] core | No compatible devices found!
[12:24:27][0x000002b0][info] http | Listening on [::1]:18000
[12:24:27][0x000002b0][info] core | Initialized!

I have a Nvidia geforce gtx 1650

**Comment by nicehashdev** [comment]
GTX 1650 is not supported. Please check list of supported hardware: https://github.com/nicehash/NiceHashQuickMiner/wiki/Supported-hardware
