### ISSUE TITLE
New To Nice Hash

### ISSUE THREAD

**Issue by TankEngine1234** [nicehash/NiceHashQuickMiner#338]
Hi, I just started a day ago on nice hash and my profits have been extremely low considering how much I should be making which is around $4. I feel like my rig is not mining anything at all so I would like some help. 
![image](https://user-images.githubusercontent.com/81930928/113520837-ad260280-954a-11eb-813a-68644d68ee31.png)
![image](https://user-images.githubusercontent.com/81930928/113520875-ccbd2b00-954a-11eb-9750-345b21ddf6a5.png)
![image](https://user-images.githubusercontent.com/81930928/113520878-cdee5800-954a-11eb-9ab0-33c112ed9228.png)
![image](https://user-images.githubusercontent.com/81930928/113520909-ff672380-954a-11eb-9acd-dcfcbe40e427.png)

**Comment by nicehashdev** [comment]
Please, try to replace your excavator.exe with this one: https://github.com/nicehash/NiceHashQuickMiner/releases/download/v0.4.5.5/excavator_b821.zip

Then restart NiceHash QuickMiner.
