### ISSUE TITLE
[BUG] Task manager not showing the GPU being used?

### ISSUE THREAD

**Issue by carbon69420** [nicehash/NiceHashQuickMiner#339]
**Describe the bug**
Hello, I'm new to NiceHash and bitcoin mining in general.  When I start mining with my GPU (Nvidia RTX 2060 Super) And go to task manager it doesn't seem to be doing anything, usually when I'm just browsing, my GPU runs at around 20-40 percent. and when I turn on my miner, it stays at 20-40 Percent. I don't know if task manager is just bugged, or NiceHash is.

1. Turn on Excavator GPU
1. Go to 'Task manager'
2. Look at % of GPU usage

**Expected behavior**
I was expecting the gpu usage to shoot up to around 90-100%, as when i mine ether with a different miner, it does that.

Screenshot:
https://imgur.com/a/HfWV2KP

 - Version number: 0.4.5.5
 - RC or STABLE? Stable

**Additional context**
This does not happen for the CPU (Ryzen 5 1600 @ 3.2 GHz)

**Comment by nicehashdev** [comment]
You need to select `CUDA` workload to be displayed, then you will get % of load. By default, task manager shows 3D load.
