### ISSUE TITLE
3.0.7 RC won't start without a NVidia Card

### ISSUE THREAD

**Issue by schwaenchen** [nicehash/NiceHashQuickMiner#34]
![image](https://user-images.githubusercontent.com/79098898/107964145-4607bb00-6fa9-11eb-90fa-954ea292437f.png)

**Comment by Disparatado** [comment]
Can you translate in English? Heil mussolini!

**Comment by StoneyEagle** [comment]
The DLL "nvml": The specified module was not found. 
(Exception from HRESULT: 0x8007007E) can not be loaded.

**Comment by nicehashdev** [comment]
QuickMiner DOES NOT work without NVIDIA card. **This is NVIDIA miner.**
