### ISSUE TITLE
QuickMiner crashes whole system [BUG] 

### ISSUE THREAD

**Issue by GEHORC** [nicehash/NiceHashQuickMiner#340]
**Describe the bug**
This is less of a bug and more of a first impression of the new 1000-Series OC-Profiles in QuickMiner in this users setup.
In short:
QuickMiner, at least on my system, is way less stable then "traditional" NH Miner while delivering lower hashrates at the same time.
In long:
I am running a single GTX 1080 and no CPU mining.
I have been running the NiceHash Miner with ETHlargement enabled until yesterday. The hashrate with Excavator was ~26MH/s.
My overcklock in Afterburner was: Power Limit: 70%; Core clk offset: 0; Mem clk offset: +500
With this setum I never had crashes, screen artefacts etc.

After learning about the new additions to Quickminer I tried it out and at first was blown away by hashrates (as reported by excavator) of ~34MH/s. After few minutes the medium and efficient settings revealed themselves as very unstable even with added negative mem clk offsets. It seemed that my card doesn't like the "RRD=4" component of the memory timings (whatever that does).  Especially during DAG generation I was getting memory artefacts on screen and whole system freezes (shouldn't the OCTuner-profile be reset during DAG generation) (Afterburner was turned off the whole time!)

I settled on a custom OC profile of: "dmc": 200, "dcc": 0, "pl": 100, "fm": 2, "ftg" : 62, "mt": [["FAW","16"],["RRD","5"]]
With this the hashrate was ~23MH/s.
This worked the whole night but crashed the system half an hour ago while a YT-Video was running in the background.

All this hassle occurs while the hasrate and reward is ultimately lower then with NH-Miner.
I will go back to NH-Miner for now and hope for improvements of QuickMiner.
![2021-04-05_09h53_58](https://user-images.githubusercontent.com/81954637/113551847-9f798700-95f5-11eb-8d05-a5e16f1bced6.png)
![2021-04-05_10h15_43](https://user-images.githubusercontent.com/81954637/113553808-99d17080-95f8-11eb-97d2-75ab84c79636.png)

One more thing: I really prefer the look and feel of the NH-Miners software interface.
I understand that the upside of QuickMiner should be that it only runs code by you guys and not 3rd-party closed-source stuff.
However: All the advancements of QuickMiner (eg. OC-Tuner) could also be implemented in NH-Miner and the User can choose not to use the 3rd-party plugins. Out of the box my NH-Miner has several plugins not installed.
This could be the way forward: 3rd Party plugins not installed OOTB but user can choose.
Just my 2¢.

Thank you for the work you do and have a nice week.

**Version affected (please complete the following information):**
 - Quickminer Version: 0.4.5.5
 - Nvidia driver Version: 465.89 (non DCH)

**Comment by nicehashdev** [comment]
It is very hard to create unified OC profiles, especially when there are so many variables to be set - for Turing and Ampere this task is simple - there is only memory clock and max core clock. But Pascal and cards with GDDR5X which also need memory tweaks are completely different story.

First I would suggest to use memory tweaking rule of FAW being multiple of RRD, which means if you use RRD = 5 then set FAW to 20. There are other memory timings that can be tweaked - perhaps this is the path to better stability. Unfortunately, I do not have any card available here nor time to play with it. Keep in mind that NVIDIA never had memory timings stuff available publicly - this is the first time for NVIDIA, it was always just AMD. Besides, GDDR5X is used only by NVIDIA thus there is not much documentation regarding numbers for memory timings. What you need to do is experiment and try to find good numbers.

The available tools are very powerful - the only missing piece is ability to set memory voltages. Beside that, you can do:
* core clocks,
* memory clocks,
* core voltages and
* memory timings.

I am certain that with enough dedication you can find perfect numbers that would make your card go well beyond 32 MH/s, probably near 40 MH/s.
