### ISSUE TITLE
[BUG] Invalid DAG generated & 0MH/s since updating to 0.4.5.5 on GTX 1060 6gb

### ISSUE THREAD

**Issue by Minty1876** [nicehash/NiceHashQuickMiner#341]
I updated to 0.4.5.5 excavator this morning, since updating my GTX 1060 6gb has constant invalid DAG generated messages in the miner and 0 H/s reported speed.

Any ideas as to what has happened? It was running very nicely before the update.

[exported_logs.zip](https://github.com/nicehash/NiceHashQuickMiner/files/6257702/exported_logs.zip)

**Comment by nicehashdev** [comment]
Update to the latest RC version and your problem will be solved: https://github.com/nicehash/NiceHashQuickMiner/releases

**Comment by Minty1876** [comment]
Unfortunately this hasn't resolved the problem. Any other suggestions would be greatly appreciated.

**Comment by nicehashdev** [comment]
Update drivers to the latest non-DCH version.

**Comment by Minty1876** [comment]
Update to excavator v1.7.0b actually fixed the problem. Back working again, thank you devs great work.
