### ISSUE TITLE
[BUG] v0.4.6.0 RC report HotSpot Temp as VRAM Temp to Rig Manager on RTX3090

### ISSUE THREAD

**Issue by Arvenies** [nicehash/NiceHashQuickMiner#342]
After changing from v0.4.5.5 to v0.4.6.0 RC reported VRAM in Rig Manager on RTX3090 have value of Hot Spot, not actual VRAM temp:
![obraz](https://user-images.githubusercontent.com/80607526/113572178-0b6ce700-9618-11eb-9648-f0a5278936d9.png)
![obraz](https://user-images.githubusercontent.com/80607526/113572223-1b84c680-9618-11eb-86e3-0ac5eb6119b3.png)
![obraz](https://user-images.githubusercontent.com/80607526/113572265-2fc8c380-9618-11eb-8f5b-b0960e0f2d41.png)

**Comment by Arvenies** [comment]
Same issue with RTX3080:
![obraz](https://user-images.githubusercontent.com/80607526/113574260-00b45100-961c-11eb-88dc-be3c76d2fa95.png)
![obraz](https://user-images.githubusercontent.com/80607526/113574309-17f33e80-961c-11eb-8934-1ce71d2eb1b0.png)
![obraz](https://user-images.githubusercontent.com/80607526/113574278-090c8c00-961c-11eb-9d6a-2850a9c57f0d.png)

**Comment by nicehashdev** [comment]
Yes, this will be fixed in following days (it needs to be done on website/mobile apps). For the time being, use OCTune to get VRAM temps.

**Comment by TekGamer** [comment]
I have noticed the same behavior with v0.4.6.0 RC, Rig Manager on the website and the mobile iOS app is showing the GPU Hot Spot Temp value instead of the GPU Memory Junction Temperature.

**Comment by dmgm** [comment]
When you do fix this, would you also consider the colour coding of the heat result?
My understanding, from what I have read online, is that the vram is rated to 95c. If this is correct, I'd think the number should be green until 95c where perhaps it should be yellow. I don't know at what point it should turn red, perhaps about the same temperature as the card would trigger a thermal throttle down?

Given Nicehash would likely encourage users to make the most of their hardware when not gaming (that's the market for NHQM) I would like to feel confident that if the dashboard shows green, I am operating the card within spec and not causing damage.

Can you do this?

**Comment by nicehashdev** [comment]
This has been resolved. Regarding colors, please open new issue (feature) and suggest how do you think it should be.
