### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by jriggit** [nicehash/NiceHashQuickMiner#343]
**Describe the bug**
Latest beta displays hotspot gpu temp instead of VRAM temp on Android app.

**To Reproduce**
1. Download quickhashminer v 0.4.6.0 rc
2. Click on rigs > devices (mine is an rtx 3080)
3. Scroll down to VRAM temp.
4. See error. Vram temp is obviously lower that realistic. It matches my gpu hotspot temp on the pc. Actual quickhash miner temps and fan control still work, so this issue is only cosmetic (but I specifically prefer QHM for it's ability to easily monitor vram temp)

**Version affected (please complete the following information):**
 - Version number: 0.4.6.0 RC
 - RC or STABLE? RC 

**Additional context**

**Comment by nicehashdev** [comment]
Already known: https://github.com/nicehash/NiceHashQuickMiner/issues/342 Duplicate, closing.
