### ISSUE TITLE
[BUG] Prerelease v0.4.6.0 RC causes my screen to flicker and then a system reboot

### ISSUE THREAD

**Issue by zephry-dev** [nicehash/NiceHashQuickMiner#344]
I updated to the latest release candidate. As soon as when I start mining, the screen begins to flicker and eventually reboots. I went back to the stable release and it is no longer an issue. I am running 3090 with the latest non-DCH driver. I have been using both stable and RC releases on all my rigs with no issues so far except this release.

**Comment by nicehashdev** [comment]
Are you using OPTIMIZE and which profile?

**Comment by zephry-dev** [comment]
> Are you using OPTIMIZE and which profile?

Yes I am. I have been only using the Medium profile. Computer CPU/ RAM is also stable. My memory junction temperature and GPU temps are well controlled -- 50C GPU and 90C vram.

**Comment by nicehashdev** [comment]
Do you have issues with Lite as well?

**Comment by zephry-dev** [comment]
I will test different settings and report back later.

**Comment by zephry-dev** [comment]
Something changed since 4/4/21 (whether excavator or quickminer) and its causing my 3090 rig to be unstable even though I haven't changed anything.

**Comment by nicehashdev** [comment]
As you can see, only `Extreme` was added for 3090 in past few days: https://github.com/nicehash/NiceHashQuickMiner/commits/main/optimize/data_005.json
