### ISSUE TITLE
[BUG] "Failed to get power limits - issue with NVIDA drivers, err=4" (after update)

### ISSUE THREAD

**Issue by OLDxGOAT** [nicehash/NiceHashQuickMiner#346]
**Describe the bug**
"Failed to get power limits - issue with NVIDA drivers, err=4"

**To Reproduce**

**Expected behavior**
Excavator needs to run 

**Screenshots**

**Version affected (please complete the following information):**
 - Version number [e.g. 0.4.5.5]
 - RC or STABLE? Stable

**Additional context**

**Comment by nicehashdev** [comment]
This is a problem with drivers - your drivers are in some half-ready state. First, try reboot. If that doesn't help, reinstall drivers.

**Comment by OLDxGOAT** [comment]
I have reinstalled drivers.  I've also tried changing from studio to gaming drivers, with no luck.  Any suggestions.

**Comment by helllgast** [comment]
Hi,
I have same problem on notebook MSI with nvidia 3060 laptop gpu with latest nvidia notebook drivers, maybe this is by design in laptop gpus. This error was in previous version as well. But OC Tune work fine...

**Comment by OLDxGOAT** [comment]
Yesterday it all worked.  Now it will not.  Any suggestions?  Can I download a previous of the program or driver?
I should not have clicked on update :(

**Comment by ktaletsk** [comment]
Same issue here on gtx 1660ti maxq on a laptop. Driver reinstall didn't help

**Comment by nicehashdev** [comment]
Not all laptops support power (get/set) functions. Mining still works regardless of this issue. There is nothing that can be done if the laptop/GPU itself does not support power functions.
