### ISSUE TITLE
[BUG] TIME_WAIT

### ISSUE THREAD

**Issue by GeorgiiKoro** [nicehash/NiceHashQuickMiner#347]
**Describe the bug**
Hi!
i got a bug with excavator.exe, after some time (approx. 10-20 hours) this application used all of my free TCP ports range. 
I didn`t know exactly where was problem source, symptoms was very strange: opened sites in browser works correctly, miner successfully mined. But if i want to open a new site, or start anything requires internet - i getting an error. After PC restart - everything works correctly for 10-20 hours. 

**To Reproduce**
1. Start Quickminer on my Windows 10 :-)
2. Wait some time;
3. type in CMD "netstat -anob"
4. See error - a lot of open (not propertly closed) dynamic TCP ports with TIME_WAIT status. As i understood - in default windows settings TCP connection with TIME_WAIT status automatically closes after 4 minutes of wait, vacates the space in dynamic ports range for further use. But excavator.exe didn`t close the connections, and continue to open new. 

![Screenshot 2021-04-06 020111](https://user-images.githubusercontent.com/47216794/113637070-6506fd00-967c-11eb-8552-a263e3870a04.png)
...
![Screenshot 2021-04-06 020129](https://user-images.githubusercontent.com/47216794/113637086-76e8a000-967c-11eb-8fce-3bbd582f7d53.png)

**Version affected (please complete the following information):**
 - Version number 0.4.5.5
 - STABLE

**Hardware**
GPU 3070+3080, connected directly to motherboard
CPU 5960x

**Comment by nicehashdev** [comment]
This may be related to the low timeout period set by default in QuickMiner. Check if setting higher timeout helps by adjusting `"watchDogAPITimeout"` in _nhqm.conf_ from 2000 to some higher value? For example, 5000.

I see that an average PC running QuickMiner has about 50 of such TIME_WAIT connection states accumulated after days of running, but not more. So it should not cause any issues.

**Comment by nicehashdev** [comment]
Also read this: https://stackoverflow.com/questions/35006324/time-wait-with-boost-asio

> TIME_WAIT comes after a clean disconnect by both parties, and it only lasts a few minutes. The way to avoid it is to be the end that receives the first close. Typically you want to avoid it at the server, so you have the client close first.
