### ISSUE TITLE
Feature Request - Overclock Memory with Autotune

### ISSUE THREAD

**Issue by Swiftnc** [nicehash/NiceHashQuickMiner#35]
Can you attempt to overclock the memory automatically via Autotune?  I would think you could look at the mining speed over 1 minute and then up the speed until such time as it starts giving errors or speed decreases.  Start at minimum safe memory overclock and the step up by 50 every minute.  While not perfect, it would help many users get better speed with no technical knowledge.

**Comment by nicehashdev** [comment]
It is not so easy; too high memory clock can simply crash whole machine. It is very unpredictable behaviour thus very hard to make reliable code for it.

**Comment by Swiftnc** [comment]
Agree that this would be hard, however perhaps logic similar to Ryzen Clock Tuner 2.0, where it logs settings to files before applying and sets autostart to continue testing once restoring from a crash, thus if it crashes, it is restarted, then it knows what it did and the results of a unexpected termination.  I would think the approach of log, and low overclock, wait 1 minute to get average hash, then log, up clock by 25, and get average hash rate, and continuing up every minute until average hash rate is lower.  And by starting slow, the hash rate should lower before you start hitting crashing as memory correction starts kicking in.... Perhaps up memory at 50 instead so less testing hops, less accurate, but still way better than no memory overclock for most.

**Comment by nicehashdev** [comment]
Added to TODO list: https://github.com/nicehash/NiceHashQuickMiner/wiki/Planned-features
