### ISSUE TITLE
[BUG] RC QM Crashing PC

### ISSUE THREAD

**Issue by NickoliVolkolf** [nicehash/NiceHashQuickMiner#357]
**Describe the bug**
Black screen freezing PC entirely within 5 minutes of starting quickminer.

**To Reproduce**
Turn on mining using 0.4.6.x

**Expected behavior**
For QM to not crash my PC. It just started with the RC from yesterday .6.0. Also tested using .6.5, same issue.

**Version affected (please complete the following information):**
 - RC .0.4.6.0
 - RC .0.4.6.5

**Hardware**
EVGA 3080 FTW3 Ultra, direct to PCI 3.0

**Logs**
Attached, I don't see anything really.
[log.txt](https://github.com/nicehash/NiceHashQuickMiner/files/6273346/log.txt)

**Additional context**
I downgraded to the latest Stable and it is running fine. You'll see that in the logs as well.

**Comment by nicehashdev** [comment]
According to provided log, I would say you had issues with Excavator getting blocked by AV.

Also, can you provide all logs (including excavator logs).

**Comment by NickoliVolkolf** [comment]
Attached are the logs. I haven't changed anything AV wise, the whole folder is excluded as it has been from day 1 using QM. I've been mining on the latest stable since I opened this without any changes to the AV.
[excavator_log_2021-04-07_12-41-55.001.txt](https://github.com/nicehash/NiceHashQuickMiner/files/6273562/excavator_log_2021-04-07_12-41-55.001.txt)
[excavator_log_2021-04-07_12-39-25.000.txt](https://github.com/nicehash/NiceHashQuickMiner/files/6273563/excavator_log_2021-04-07_12-39-25.000.txt)

**Comment by nicehashdev** [comment]
That is the problem; making exclusion is not enough, you need to "allow on device". Then it stops getting targeted by Defender.

**Comment by nicehashdev** [comment]
What is common for both logs you submitted is that speed goes to 0 before whatever happens. I am 99% sure it is Defender blocking Excavator. Make sure you allow it. Here is procedure how to do it: https://github.com/nicehash/NiceHashQuickMiner/issues/204

**Comment by NickoliVolkolf** [comment]
I have defender off, including the firewall. Was something changed in the latest RC that would be causing it. I haven't touched anything since I started using QM in v0.3.0.6_RC (besides updating when prompted)

**Comment by nicehashdev** [comment]
I will repeat again; it does not help to have defender off or to have exclusion list. It would still block it unless you make "allow on device" exception for exactly that excavator.exe. It is a (intentional) bug by Microsoft to make mining very hard on PC.

**Comment by NickoliVolkolf** [comment]
You're missing the point of the bug ticket. It was fine for 2 months, now in the RC it isn't working. A generic defender causing it doesn't explain it. Unless there is a new excavator.exe packaged with the latest RC. If you want to close it with that, its up to you. I'll just stick to the stable version as I have no issues with it. And If you have defender off, there isn't a way to make an exception to a software that isn't running in the first place.

**Comment by nicehashdev** [comment]
Yes, there is new excavator.exe packed with it. In every new version, there is most likely new excavator.exe packed in because changes and updates are needed there too.

**Comment by NickoliVolkolf** [comment]
I'll upgrade to the latest RC again tonight and post the logs (with reputation based turned off). There isn't a way to exclude in defender as it isn't on. I don't see how excavator crashing/being blocked causes a PC to hard lock and need rebooted. But either way Thank you for your time. I'll post logs later.

**Comment by nicehashdev** [comment]
There is new RC version which is built using latest CUDA version (11.2 update2) which shall hopefully resolve all the unexplained errors. Try it please and report back.

**Comment by NickoliVolkolf** [comment]
So far so good. Been mining for about 20 minutes with no issues. I'll close this in an hour or so if everything continues to be fine. Thanks!

**Comment by nicehashdev** [comment]
Okay good. Glad your problem is fixed.

**Comment by NickoliVolkolf** [comment]
Yep still good. Thanks again!
