### ISSUE TITLE
[FEATURE] Allow Hibernate the PC, when Quickminer is Stopped manually 

### ISSUE THREAD

**Issue by moops44** [nicehash/NiceHashQuickMiner#358]
Could you please consider allow Hibernate when i stop Quickminer manually .
I need to Quit Quickminer complete that the PC go in to the Hibernate Mode, specially at night times the Fan Noise disturbs 
I hope you understand what I mean. Thank you very very much!

**Comment by nicehashdev** [comment]
When you turn off QuickMiner, you can go into sleep mode. Until QuickMiner is turned on, sleep mode is not available.

**Comment by moops44** [comment]
I know this allready, thats why i asked if there is any option to force hibernate after a time, but yeah i found a freeware program thats force hibernate with a timer even when quickminer is running and starts mining again when i wake up the pc
I thought maybe you can implent such feature
