### ISSUE TITLE
0.3.0.7 breaking AutoTune clock Min/Max number

### ISSUE THREAD

**Issue by Disparatado** [nicehash/NiceHashQuickMiner#36]
Hi, as the picture below, after some OC tuning, the Auto-Tune goes dumb and cannot set clock speeds to do its search

![Untitled](https://user-images.githubusercontent.com/78882077/107976210-7d7e6380-6fb9-11eb-91c0-52fb580f94aa.jpg)

**Comment by nicehashdev** [comment]
I would suggest just reloading the page; I am making updates to this code daily so a lot is changed and can be fixed by the way.

**Comment by Disparatado** [comment]
i know, just wanted to share with you :)
