### ISSUE TITLE
Reported Profitability

### ISSUE THREAD

**Issue by Vinasis01** [nicehash/NiceHashQuickMiner#360]
**Has the question been answered in [Wiki](https://github.com/nicehash/NiceHashQuickMiner/wiki)? There is no such question in [FAQ](https://github.com/nicehash/NiceHashQuickMiner/wiki/FAQ) or [Troubleshooting collection](https://github.com/nicehash/NiceHashQuickMiner/wiki/Troubleshooting)?**
Yes/No.

**Your question is...**
I have 2 rigs, first rig has an rtx 3080 and an rtx 3070 and in the picture picture it shows that it's getting 15.31$/day, second rig has 3x rtx 3080 + 2x rtx 3070 and 2x rtx 3060 TI and it shows that it's getting 38.53$/day.
The numbers don't seem to reflect correctly and many times it's like this, second rig should display a lot more, what might be the issue? 
![chrome_orsIPdM9DM](https://user-images.githubusercontent.com/49044292/113984344-aa315780-9853-11eb-86c1-e6093f0e2d01.png)

**Comment by nicehashdev** [comment]
These numbers are current and not average which you should be looking at. Please read here for more information about this topic: https://github.com/nicehash/NiceHashQuickMiner/wiki/Hashing-speed,-accepted-rejected-speed-and-shares
