### ISSUE TITLE
My OCTune does not identify my RTX 3090 card, so I am unable to set limits or temp controls

### ISSUE THREAD

**Issue by apok67** [nicehash/NiceHashQuickMiner#361]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version affected (please complete the following information):**
 - Version number [e.g. 0.4.5.5]
 - RC or STABLE?

**Hardware**
Describe GPUs used and how are GPUs connected to the motherboard.
CPU?

**Logs**
Activate logging first, then record event - bug - then export logs into a .zip file and attach it when submitting this issue.

**Additional context**

**Comment by apok67** [comment]
OCTune isnt working with this on my RTX3090.  It does not populate with any data and so I cant tune anything.  Please help

**Comment by nicehashdev** [comment]
You need to make sure that Excavator.exe is running. If it is not, probably AV has deleted it.

**Comment by apok67** [comment]
It is running, and mining now, but no OCTune info or controls are working

**Comment by nicehashdev** [comment]
Open NiceHash QuickMiner context menu from taskbar tray and select OCTune from it. It will open you browser with appropriate address to OCTune.
