### ISSUE TITLE
[FEATURE] Specify Graphics Card and CPU to apply Game Mode to and option to disable/exclude mining on it

### ISSUE THREAD

**Issue by dethknite** [nicehash/NiceHashQuickMiner#362]
When configuring/applying game mode, it would be nice to only apply the settings to a specific card (and/or CPU). Example. I have 3 graphics cards in a PC, and am mining with all 3 and the CPU. When I want to enter game mode, I only need/desire the primary graphics GPU in windows to stop mining/revert, and the CPU to stop mining.

Currently this it is my understanding this requires the stopping of all mining.

**Comment by dethknite** [comment]
Nevermind. I was misunderstanding it as it already disables mining on it.

**Comment by N0rdmann** [comment]
So its automatically only disabling the Card with a detected connectd display?
So far i've always manually stopped mining on the gaming card via the RigManager Website -_-

**Comment by dethknite** [comment]
Yeap. I thought the same but realized it is resetting the clocks/power and disabling mining on the primary which covers what I would want/expect. The only desired additions would be including CPU mining or tying it to that at least.. but eh--might be confusing to some if it stored the previous value and then reverted it.
