### ISSUE TITLE
[FEATURE] Min/Max Limits On Auto Fan Speed

### ISSUE THREAD

**Issue by racineda** [nicehash/NiceHashQuickMiner#363]
**Is your feature request related to a problem? Please describe.**
I run using the target VRAM/CORE temp for the fan speed and it works great. This is perfect for when ambient is rising and becomes really warm. When ambient drops fan speed drops as well (expected) leaving fans running slow and keeping temps at target. This means the VRAM on 3080/3090 run hotter than they have to if fans were running at a higher fan speed. Example ambient drops and fans slow to 50% keeping VRAM at 90C. If the fans were to only drop to some min fan speed VRAM could be running cooler as in something lower than target which would is better for long term reliability.

**Describe the solution you'd like**
Id like to set a minimum/maximum fan speed when in the target GPU/VRAM/Hotspot temp mode. This would allow temps to be potentially better than the set target (when ambient allows) which is desirable for reliability. Another use case could be a user does not want to use a 100% as their max fan speed but still wants to use the auto fan controller feature.

**Describe alternatives you've considered**
Open to suggestions.

**Additional context**
Some simple test boxes for setting limits (min/max) on fan speed when using the auto fan speed identical to the boxes that are there now would be wonderful.

**Comment by nicehashdev** [comment]
This is already done: https://github.com/nicehash/excavator/tree/master/api#device-smartfan-set-advanced

You will have to modify commands.json to make it work.

**Comment by isral** [comment]
@nicehashdev 
Please provide sample to set minimum fan speed.
