### ISSUE TITLE
[QUESTION] Copy Rig ID

### ISSUE THREAD

**Issue by TimSirmovics** [nicehash/NiceHashQuickMiner#364]
**Has the question been answered in [Wiki](https://github.com/nicehash/NiceHashQuickMiner/wiki)? There is no such question in [FAQ](https://github.com/nicehash/NiceHashQuickMiner/wiki/FAQ) or [Troubleshooting collection](https://github.com/nicehash/NiceHashQuickMiner/wiki/Troubleshooting)?**
No.

**Your question is...**
While aplying optimisation profiles my PC crashed a few times and NH lost it's config.
It generated a new one which created a new Rig in Rig Manager.
I wanted to continue with the history of my old rig, so I copied the old Rig ID out of the URL in Rig Manager into authorization\uniqueID in nhqm.conf, and restarted.
This did seem to work in that Rig Manager showed the old rig as mining, but NH now only shows a speed of 0 MH/s.

Is what I want to do possible, or have I missed something?

**Comment by nicehashdev** [comment]
Where do you see speed 0 MH/s ?

Perhaps you need to click on start mining somewhere?

**Comment by TimSirmovics** [comment]
Yes this is after I have started mining, it shows in the system tray menu.
I can see jobs coming in to excavator but none complete.

**Comment by nicehashdev** [comment]
Check in Rig Manager - you probably have device disabled. Click on "Play" button to enable it.

**Comment by TimSirmovics** [comment]
You were right - thank you.
