### ISSUE TITLE
NiceHash QuickMiner OCTune mix with OPTIMIZATION

### ISSUE THREAD

**Issue by cesarlopes** [nicehash/NiceHashQuickMiner#368]
After last update of NiceHash QuickMiner to version v0.4.7.1 RC I can't change any configuration of OCTune.

For example, I really like the automatic medium optimization, but I like to change only the target temperature from 58 to 56, since my card has 3 fans and so it is around 55% of the fan usage and a lower temperature.

But unfortunately after the last update I am unable to make this adjustment, the following message appears:
"Cannot modify value for device #0 Please, set OPTIMIZATION profile in Rig Manager to Manual first before editing OC values."

However, if I change on the site to Manual then I lose all the settings for the Medium option that I like.

What is the suggestion for me to use the parameters of the Medium Optimization but with a lower target temperature?

**Comment by Xalaxis** [comment]
You'll want to use the instructions listed at https://github.com/nicehash/NiceHashQuickMiner/wiki/One-click-Optimizations#is-it-possible-to-slightly-modify-optimization-profiles to modify the custom optimization profiles applied.

**Comment by N0rdmann** [comment]
Rather than modifying the optimization profiles, I've just noted down the settings, switched to manual via rig manager, manually set the optimized settings + some own adjustments and used "save current configuration" on OCTune... **works fine for me**

Took me a while to figure out that you have to set it to **Manual** in RigManager that it actually loads the settings you saved via "save current configuration" button 🙈😉

**Comment by profedsoncruz** [comment]
Hi, I used to set medium / high profiles and then set fan to fixed speed of 60% using OC Tune. Now with this change in the last RC version (0.4.7.1) I can't use OCTune to apply fixed speed for the fans anymore. I would like to ask if it is possible to set a fixed fan speed using the data_005.json and what are the parameters to add there. Thanks!

**Comment by Xalaxis** [comment]
@profedsoncruz I think fixed fan mode is `"fm": 1`, but I'm not sure what the paramater for fan duty is because it's never been used in a NiceHash profile. Incidentally, if you just want to just automatic fan speed, that's `"fm": 0`. That's what I use.

**Comment by cesarlopes** [comment]
> @profedsoncruz I think fixed fan mode is `"fm": 1`, but I'm not sure what the paramater for fan duty is because it's never been used in a NiceHash profile. Incidentally, if you just want to use automatic fan speed (OEM), that's `"fm": 0`. That's what I use.

Were you able to set a value for the fan in fixed mode?

**Comment by Xalaxis** [comment]
> Were you able to set a value for the fan in fixed mode?

I'm afraid I still don't know what the parameter is. I'll mention the dev.

Hi @nicehashdev. What's the optimization profile keyword for fan fixed percentage mode? I know it'll be `"fm": 1` followed by something like `"fan_percent": "30"`, but I don't know what fan_percent should be in the file and can't find anything like that in the older optimization profiles. Thanks for all your work!

**Comment by nicehashdev** [comment]
Unfortunately, fixed fan mode was never full implemented, because it was never used in part of optimizations.

Your best solution for now is to simply use custom OC in OCTune and save it with the green button.

**Comment by nicehashdev** [comment]
Solution is here: https://github.com/nicehash/NiceHashQuickMiner/issues/420
