### ISSUE TITLE
JQuery not saved in the system folder.

### ISSUE THREAD

**Issue by StoneyEagle** [nicehash/NiceHashQuickMiner#37]
After auto update to 0.3.0.7 the OCTune files are available from the "C:\Windows\System32\octune" folder but jquery.min.js is not copied to there, breaking the functionality of the page.
Loading the HTML file from the original unzipped folder still works fine, i've copied the JQuery for now.

**Comment by nicehashdev** [comment]
Why would you like to run OCTune in Windows\System32 folder?

**Comment by StoneyEagle** [comment]
I don't 😂 I did not move the files in there, I noticed them being there by clicking the octune button in the system tray.

**Comment by nicehashdev** [comment]
Hmm must have something to do with running as admin. Did you explicitly run as Admin? Which version of Windows are you using?

**Comment by StoneyEagle** [comment]
I've clicked on the update button a few times and restarted a few times before the update would actually update, not sure if that has something to do with it.
The original startup and autostart was from the extracted zip folder inside my user download directory. 

I don't have UAC turned on, that's why i jumped to the in-house miner the moment i saw there is someone to be held accountable for bad code.

OS Name:    Microsoft Windows 10 Pro Insider Preview
OS Version: 10.0.21301 N/A Build 21301

**Comment by nicehashdev** [comment]
One more thing: What kind of auto startup method did you use? Were you using service method?

**Comment by nicehashdev** [comment]
Please, completely reinstall with the latest 3.1.2 RC version and let me know if this issue of files being in Windows/System32 still occurs.

https://github.com/nicehash/NiceHashQuickMiner/releases/tag/v0.3.1.2_RC

**Comment by StoneyEagle** [comment]
I'm using the task scheduler and for now the files are loaded from the download folder so I'm closing the issue.
I'll reopen it if it occurs again.
