### ISSUE TITLE
Device could not obtain power consumption

### ISSUE THREAD

**Issue by wingedworrier** [nicehash/NiceHashQuickMiner#370]
NH Quick Miner displays the above and periodically shuts down.
The problem seems to be getting more frequent.
Have checked risers and connections and don't think they are the problem.(fans run and MSI AB detects all three cards). Also don't think its the cards.
When one 1660S is remove the setup runs stable.

Set up
EVGA: 1* RTX3090 + hybrid (on motherboard) - 117MH/s; 285w; 0.41 MH/j
EVGA: 2* GTX1660S (on risers) - 31.3 MH/s; 78w; 0.41 MH/j
PSU: EVGA1000w

**_Two hours later rig fails due same issue above with only one 1660. Therefore, must be a software/setting issue._**

Appreciate any and all constructive comments.
Thanks,
Wingedworrier

**Comment by wingedworrier** [comment]
![Capture PNG1660 PNG1660](https://user-images.githubusercontent.com/29429280/114256047-0332f400-99ea-11eb-88b5-13f0c86c22d2.PNG)
![Capture PNG3090 PNG3090](https://user-images.githubusercontent.com/29429280/114256051-05954e00-99ea-11eb-9195-8aa45e610689.PNG)
[Certificate of Title 2097-11 Unit 2, 56 Sulman Road, WEMBLEY DOWNS 6019.pdf](https://github.com/nicehash/NiceHashQuickMiner/files/6289133/Certificate.of.Title.2097-11.Unit.2.56.Sulman.Road.WEMBLEY.DOWNS.6019.pdf)
**### This is with one 1660 removed**

**Comment by Marcus1630** [comment]
Hello, I have the same problem that happens constantly

**Comment by nicehashdev** [comment]
Please, use established issue forms; I need extra info - version used, log files etc.

**Comment by nicehashdev** [comment]
Also, if everything is fine at start, but it gets messed after a while, then the reason is in driver crash which is caused by unstable OC values. I would suggest dialing down your OC values a bit and see if that helps.

If you use risers, then this is another factor that may be contributing instability to your configuration. Make sure you have set gen2 version for your PCIe lanes in BIOS and try to use best shielded usb cables; also try to replace them. Sometimes that makes a huge stability difference.

**Comment by wingedworrier** [comment]
Thanks for your response.
Pcie Gen 2. I have tried to find that on the motherboard but no success.
I have a Gigabyte Z490 UD AC mono. Can you give me a few ideas on where to look in the bios.
Tks
Richard

**Comment by nicehashdev** [comment]
If you paste BIOS pictures then I may help you point you in the right direction.

**Comment by wingedworrier** [comment]
Thanks for your help. Reading the manual always help
