### ISSUE TITLE
Display Vendor in Excavator/OCTune/Rigmanager

### ISSUE THREAD

**Issue by N0rdmann** [nicehash/NiceHashQuickMiner#372]
As the shortage on cards goes on I (and probably many others) have a wild mix of card from different vendors in my rig...
So since they all need slightly different settings to run optimal it would be nice to see the vendors of the cards, at least in OCTune (or rigmanager for applying optimization profiles)

Currently i have to play arround with stopping fans to find the correct card which is a litle hassle 😜

**Comment by nicehashdev** [comment]
This is already done, but not exposed. Excavator's API already returns subvendor ID (example: `"subvendor":"10de"`). Unfortunately, I do not have a codetable to transform codes to Vendor names. If you can get me this table, I will make it.

**Comment by nicehashdev** [comment]
This will be added in next version.
