### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Atmos99** [nicehash/NiceHashQuickMiner#373]
Hello ,
I have two rigs.
One of them is with 5x nvidia 1060 6GB. After update with 04.5.5 i can manage it.
But on the other rig i`m with 9x P106 (miners edition 1060 6gb) , after updating the quick miner i still don`t have the manage option.

Regards
Dimitar

**Comment by nicehashdev** [comment]
P106 is not officially supported by NHQM. Please, use NiceHash Miner.
