### ISSUE TITLE
Can I limit GPU Usage[QUESTION] 

### ISSUE THREAD

**Issue by crabmeat11** [nicehash/NiceHashQuickMiner#375]
**Has the question been answered in [Wiki](https://github.com/nicehash/NiceHashQuickMiner/wiki)? There is no such question in [FAQ](https://github.com/nicehash/NiceHashQuickMiner/wiki/FAQ) or [Troubleshooting collection](https://github.com/nicehash/NiceHashQuickMiner/wiki/Troubleshooting)?**
No.

**Your question is...**
Is there a way to limit the GPU usage instead of stopping it completely when using game mode or wanting to use the computer for other things? I saw there was a limit to CPU usage but could not find anything on GPU.

**Comment by nicehashdev** [comment]
Unfortunately, NVIDIA does not provide such feature. It is always all on or all off. Perhaps in the future this will be possible, but currently it is not.
