### ISSUE TITLE
[FEATURE] Selecting graphics card to use on GameMode

### ISSUE THREAD

**Issue by lukaszcholewka** [nicehash/NiceHashQuickMiner#376]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I want to play game on other graphics card than primary. I need to set other overclock values and manually disable mining on other card which I want to use for games.

**Describe the solution you'd like**
Add selecting card for games in GameMode configuration.

**Describe alternatives you've considered**
Example in red box
![image](https://user-images.githubusercontent.com/9151465/114286232-32cf1400-9a5d-11eb-8e3b-490b0c305829.png)

**Additional context**
Game Mode feature is very good and usefull. With selecting card for GameMode it will be awesome.

**Comment by nicehashdev** [comment]
Do you use more monitors and have them plugged in different video cards? What would be the reason for doing that?

**Comment by lukaszcholewka** [comment]
I have got two graphic cards. I want to play games on card which is connected to secondary PCI port on motherboard. I cannot swap cards on motherboards because heat generating will be worse. And when i want to activate GameMode always is selecting card which is connected to primary port.

**Comment by nicehashdev** [comment]
By default, Game Mode works always by disabling mining on GPU connected to display. I can imagine, that this may not work for you if you use more GPUs, each one being connected to some display. Is that the case or not?

**Comment by lukaszcholewka** [comment]
Yes, it is that case. And all users of RTX 3060 may got that problem, because RTX 3060 for full hashrate must be connected to monitor :(

**Comment by nicehashdev** [comment]
I see. There will be extra config in next version which'd allow you to set device UUID of wanted display.

**Comment by innatum** [comment]
@nicehashdev Fantastic! Thank you. I've wanted this feature since getting my 3060 two months ago. It will be a major help and time saver.

Like the OP, I have multiple GPU's and monitors. My 3060 occupies the first PCI-E slot and my 3080 the second slot. They cannot be physically swapped due to case constraints. When I activate Game Mode, I want the 3080 disabled for mining and overclocked for gaming, NOT the 3060 which is auto-detected as Primary. This feature will save a LOT of headache.

Thank you!

**Comment by nicehashdev** [comment]
New version with this feature supported is out already (for internal testing for now and you may download it on your own if you wish).

**Comment by innatum** [comment]
@nicehashdev I installed the new RC version and don't see an option to change the primary GPU anywhere...

**Comment by innatum** [comment]
@nicehashdev I updated to RC version 0.5.1.3 today. No option to set the primary GPU. Which version are you referring to that has this feature? Thanks.

**Comment by nicehashdev** [comment]
Here are instructions: https://github.com/nicehash/NiceHashQuickMiner/wiki/Game-Mode#5-misc

**Comment by innatum** [comment]
@nicehashdev Unfortunately that doesn't work. I followed the instructions and tried everything. Adding the UUID to "overrideDisplayDeviceUUID" in the config file causes the file to reset to default settings. When I edit the config file and save, Nicehash QuickMiner immediately reverts to default settings and prompts me to add my Mining Address again.

Any way around this?  In the official release, will changing the Primary GPU be easier?

**Comment by nicehashdev** [comment]
If NHQM asks you for mining address, it means that your config file is corrupted, invalid JSON file. You can verify whether your config is valid json by submitting it here: https://jsonformatter.curiousconcept.com/

Make sure to use `"` to encapsulate your GPU UUID and `,` at the end of the line.
