### ISSUE TITLE
[OPTIMIZATION] 

### ISSUE THREAD

**Issue by Vinasis01** [nicehash/NiceHashQuickMiner#377]
**Are you aware of the latest [Optimization data](https://github.com/nicehash/NiceHashQuickMiner/tree/main/optimize) being used?**
Yes/

**I am suggesting new optimization or modification of existing optimization?**
Modification: Before when you set a certain optimization for example "Medium" or "Lite" it was possible to just change a specific parameter like the fan by setting it to a fixed speed, currently that is not possible unless you switch to manual > put the values again for OC, this is similar to going back to normal Nice Hash Miner + Afterburner.

I would suggest setting the same previous method, a user can set "Medium" or "Lite" or "High" and can change a specific parameter without having to adjust all the settings.

**For GPU:** NVIDIA GeForce ...
**Optimization name:** Lite/Medium/High/Efficient
**Special VRAM & Manufacturer:** Yes/No

**My suggested optimization data is following:**
I suggest core clock...

**Comment by nicehashdev** [comment]
Duplicate: https://github.com/nicehash/NiceHashQuickMiner/issues/378
