### ISSUE TITLE
[QUESTION] How to set fixed fan speed using data_005.json for 0.4.7.1 RC

### ISSUE THREAD

**Issue by profedsoncruz** [nicehash/NiceHashQuickMiner#378]
Hello there! since the last update, I can not use OCTune anymore to set the fixed fan speed that I was using before.
OCTune changes does not get applied unless I change the optimization to manual, and I don't want to.

So my question is: Is it possible to set a fixed fan speed using the data_005.json ? If so, what are the parameters to add there. Thanks!

**Comment by nicehashdev** [comment]
Yes, there are several options. One of them is creating your own optimization profiles: https://github.com/nicehash/NiceHashQuickMiner/wiki/One-click-Optimizations#is-it-possible-to-slightly-modify-optimization-profiles

**Comment by nicehashdev** [comment]
Also duplicate with this: https://github.com/nicehash/NiceHashQuickMiner/issues/368
