### ISSUE TITLE
[FEATURE] Power/Memclock target VRAM/Hotspot temp

### ISSUE THREAD

**Issue by alasdair-grant-jdcp** [nicehash/NiceHashQuickMiner#379]
**Is your feature request related to a problem? Please describe.**

There is an 'autotune' feature already that maximizes efficiency for setting card clocks; same with fan speeds.  The issue I run into however is the fans aren't aggressive enough so I just have to crank them at 100% all the time anyways.  I live in a temperate area and am discovering that I have to REALLY dial back card power and even memory clock to keep my GDDR6X temps 90-92C (Winter v Summer = -30C - +30C).  As the seasons change I'm willing to drop hashrate to preserve the card - nobody yet knows what is the true 24/7 safe temp for card longevity.  I have mined enough to pay for 2 more cards if availability wasn't an issue but we all understand what the pain would be to be left high and dry with bags of BTC but only scalpers to get a replacement...

**Describe the solution you'd like**

I'd like to see the ability to have the Excavator OCTune client dynamically shift card power and clocks to a target max VRAM temp (I.E. 92C) then as ambient temperatures rise and fall, hashrate may go up and down but the card temp would be relatively stable.  For those with fan speed/noise constraints, this could also be a part of the target (say 92C with MAX fan speed of 70%, have it seek optimal power limit and core/mem clockspeeds based on that.  

**Describe alternatives you've considered**

As it stands now, I monitor the VRAM temps and manually adjust

**Additional context**

N/A

**Comment by nicehashdev** [comment]
That is interesting idea, but I need to think about implementation approach. I think reducing core clock approach would be the best  way.

**Comment by nicehashdev** [comment]
[excavator_v1.7.1a_build873_Win64.zip](https://github.com/nicehash/NiceHashQuickMiner/files/6330598/excavator_v1.7.1a_build873_Win64.zip)
Use with latest QuickMiner. There is 5th Fan mode; you can set max fan speed. When max fan speed is reached, max core clock is being reduced. When temp drops, first max core clock goes up to previous set one.

Only works with alternative OC.

Let me know what you think about it.

**Comment by alasdair-grant-jdcp** [comment]
Thank you for this. Trying now.  I think this might be an improvement.  took a bit of tweaking - I set fan max-speed to be 100%, and selected the option to VRAM/Hotspot; but now setting the core-max and memory clock as static and the power consumption is fluctuating, resulting in less steady (but acceptable) temps, fans ramp down/up accordingly.  It appears to be working.

Hashrate & efficiency I'm not sure yet, too soon to tell how we are doing there.

I'd say this is a great start to my desired endpoint - but would like this kind of limiting control option applied to the Rig Manager Optimize setting.  This would set the fan max speed (if applicable) and max VRAM temp (let's face it on Ampere cards the GPU temp isn't the concern its VRAM) then the software can ensure optimal mining within these constraints.  I'm still in the position where I have to choose a memory clock for the power limit, core clock & fans to scale which means 3 of 4 are dynamic.

Question - would it be easier or more effective to give the memory clock a more dynamic treatment and manually tune card core clock?  Or is this way better?

**Comment by nicehashdev** [comment]
Changing memory clock draws a lot more code related possible issues compared to limiting max core clock. Besides, changing memory clock does not guarantee you that you will reach wanted result (you can do max minus delta -1000 and temperature may still stay too high in certain scenarios). At the end, the only drastic enough measurement is changing core clock.

The end goal is to offer "Quiet" optimization profiles in rig manager.
