### ISSUE TITLE
No compatible hardware [BUG] 

### ISSUE THREAD

**Issue by Becker180** [nicehash/NiceHashQuickMiner#381]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version affected (please complete the following information):**
 - Version number [e.g. 0.4.5.5]
 - RC or STABLE?

**Hardware**
Describe GPUs used and how are GPUs connected to the motherboard.
CPU?

**Logs**
Activate logging first, then record event - bug - then export logs into a .zip file and attach it when submitting this issue.

**Additional context**

**Comment by nicehashdev** [comment]
This is not a bug. If you do not have supported hardware, then NHQM cannot run. Check list of supported hardware here: https://github.com/nicehash/NiceHashQuickMiner/wiki/Supported-hardware

**Comment by dsf500** [comment]
I am having this issue with 1070's which is on the list. and the drivers are properly installed.
