### ISSUE TITLE
GTX 1080ti won't boost when mining any more.

### ISSUE THREAD

**Issue by macangel** [nicehash/NiceHashQuickMiner#382]
I have a pair of GTX 1080tis, normally running in SLI. I have them for gaming, but whenever I'm not gaming, I've been turning on mining. A few weeks ago I noticed that one of the cards would no longer boost during mining. It was hard to figure out which one because Windows counts them backwards, but I found out that it was the card in PCIe slot 1 (the first card). It would have no problems during gaming. It boosts and games no problem, reaching just under 2000MHz. But when mining is turned on, it hovers around 300MHz. The second card would boost and run no problem.
SLI is turned OFF. And currently it has only that card installed. I took the other one out for troubleshooting. The current game I'm playing, Nioh, does not support SLI.
I've tried 3 different sets of drivers, using DDU each time.
Windows 10 64 bit is fully updated.
Tried Nice Hash Miner, and Quick Miner. Uninstalled and reinstalled, clean each time.

**Comment by nicehashdev** [comment]
After PC reboot, if the cards do not boost without you turning on NHQM, then the issue must be in drivers or hardware. Any change that NHQM may do is only for the period of current active session (reboot wipes off any settings).

**Comment by macangel** [comment]
> 
> 
> After PC reboot, if the cards do not boost without you turning on NHQM, then the issue must be in drivers or hardware. Any change that NHQM may do is only for the period of current active session (reboot wipes off any settings).

This has been going on for a number of weeks. I've obviously restarted many times if I changed the drivers, cleaned with DDU, and took the second card out. It boosts during gaming, but NOT for Nice Hash, either quick miner or regular.

**Comment by nicehashdev** [comment]
Are you using OPTIMIZATION profiles? Then your core clock will go up to certain clock and no more. This is OK and nothing wrong with that. It is intended to be like that.

**Comment by macangel** [comment]
> 
> 
> Are you using OPTIMIZATION profiles? Then your core clock will go up to certain clock and no more. This is OK and nothing wrong with that. It is intended to be like that.

I have profiles created in MSI Afterburner. Been using them for years. They work on the one card, but not this other one, the one that's in the first slot. No matter what profile you are going to refer to, it should be boosting more than 300MHz. That's what it is at rest and simple web browsing. As I mentioned in the original post. One card mines fine, the other doesn't. Both cards can game fine, either in SLI or on their own. Right now I only have in the one card. The other has been taken out of the case completely. I am still gaming with it, using a resolution of 7680x1440 with no issues. But when I restart Nice Hash, it boosts to full speed for a couple of seconds, then drops down to about 300MHz. I've tried different drivers, all Windows updates, restarting, uninstalling and reinstalling Nice Hash, both version. One card will mine, the other won't. Both cards can play games. It is just the one card with mining, either by itself, or with both cards installed.

**Comment by nicehashdev** [comment]
Reinstall NHQM to make sure you don't have any OC commands saved in commands.json file.

If it still doesn't work, then reinstall NVIDIA drivers using DDU. Make sure to install latest non-DCH drivers when you are installing drivers.

**Comment by nicehashdev** [comment]
I consider this issue resolved.
