### ISSUE TITLE
[BUG] CUDA error 'unknown error' in func 'cuda_daggerhashimoto::run' line 1220

### ISSUE THREAD

**Issue by Poss77** [nicehash/NiceHashQuickMiner#383]
I have a rig with four 3060 ti. It works fine for a month, but since a few days, one of the GPU is crashing excavator (I tried 0.4.5.5 and v0.4.7.1 RC) after 2-3 minutes. All my cards use the Lite optimization, but I tried a lot of different OC parameters for that card and it always crash. When I remove that specific GPU, it works fine with the 3 others (If I try with 3 GPU including the problematic one, it crash again after a few minutes). I have the latest NVIDIA driver without DHC and no antivirus.

Is it the GPU that is broken? What else can I tried?

Here is a screenshot of the excavator when the bug happen:
![error](https://user-images.githubusercontent.com/82526500/114892135-7ec1e600-9dda-11eb-9e6d-66f71dfd8aed.PNG)

**Comment by nicehashdev** [comment]
Make sure there is no AV blocking any files of NHQM. Since nobody else has this issue, it must be your configuration.

Also, which version of NVIDIA drivers do you use? Try to run without any optimizations. Does it crash then too? Make sure your cards are not in P0 state when mining.

**Comment by Poss77** [comment]
The only AV that I have is the one with windows (and it's deactivated).  I use NVIDIA driver 465.81 and the cards are not in P) state.

I tried with no optimization, and it still crash after a few minutes.  I think that card is defective...

**Comment by nicehashdev** [comment]
If the AV is deactivated it does not mean it is not blocking it. We have figured it out multiple times (it is a bug with AVs or conspiracy to try to get as many people off earning easy money).

**Comment by pav12345** [comment]
Hi, i have same problem. How you fix that?
I was trying disable one gpu, but no different. All my rigs do at same time. My network works fine. Must be from outside. It send quick swap for 00000000 then do same screen like this one. Any solution?

**Comment by nicehashdev** [comment]
Which version of QuickMiner are you using @pav12345  ?

**Comment by pav12345** [comment]
Last one stable one, is on auto update. It updated few times and no different . I trying find out what can be wrong, low RAM, small virtual RAM, small hardrive? Not sure. I have 32G RAM, 250G hardrive intel 7 10 gen, It was game PC rebuild to rig, but doing same think like other one with lover spec. So must be in system, or some hacks. It run fine till it send cuda-daggerhasimoto Device .. quick swap DAG to 000000000. Then that GPU get speeds up MH/s little bit then drop in half and later crash. Then RIG restart him self and all back to normal. No more quick swap to 00000000.  My GPU normal speed is 45-46. When that happen it jump to over 48, then drop 30 and crash.

**Comment by nicehashdev** [comment]
I assume you have 1080 Ti? How about you try with stock overclock? That sounds just your OC being too aggressive.

**Comment by randommemer** [comment]
I'm actually getting the same error too. I used to be able to run my 2060 mobile with alternative OC core to 750(which sets the gpu to around 60W) and memory +1000 but since yesterday, anything higher than +650 mem(power does not seem to be a factor of stability) will crash the driver and excavator will show the same "line 1220" error as well as "Failed init cuda (0) ctx: CUDA error 'all CUDA-capable devices are busy or unavailable' in func 'cudahelp::device_thread_init' line 160

**Comment by nicehashdev** [comment]
> I'm actually getting the same error too. I used to be able to run my 2060 mobile with alternative OC core to 750(which sets the gpu to around 60W) and memory +1000 but since yesterday, anything higher than +650 mem(power does not seem to be a factor of stability) will crash the driver and excavator will show the same "line 1220" error as well as "Failed init cuda (0) ctx: CUDA error 'all CUDA-capable devices are busy or unavailable' in func 'cudahelp::device_thread_init' line 160
> 
> EDIT1: I just noticed the 2060 runs in a P0 state without me changing anything. Not sure how it was before.

If it runs in P0 state, then all overclocks are higher than expected. You should reduce memory OC in this case. That may be the reason for your issues.

**Comment by pav12345** [comment]
is only 2060 or any others do to? How to turn it off? Thx

**Comment by nicehashdev** [comment]
You can turn it off the same way it was turned on. Perhaps you installed some app that did it.

**Comment by pav12345** [comment]
I do not turn it on, so how?

**Comment by randommemer** [comment]
I also haven't done anything to mess with the P states. Even after a fresh windows install, whenever I run the miner, P0 is the state it always goes to.

**Comment by nicehashdev** [comment]
I have noticed that some cards don't have P2 state at all, notably low end cards such as GTX 1660. But even though this was the case, using optimization such as Lite or even Medium was working just fine.

**Comment by pav12345** [comment]
I try all lite and fail, i try all medium and fail and i try all manual and fail. It some strange go from network as i am close to 2 rigs and i can recognize crash before that happen by sound as fans start getting quicker as speeds go faster. I mean speed mh/s for few sec before crash. Like something make overclock all GPU at same time.I got fresh win 10 and still doing that. Must be something inside quickminer software. Not sure how to find out

**Comment by pav12345** [comment]
I try reduce power for one card what was crash all times when quick swap to 000000000. This time it say DAG cache (00000000) generation complete 251ms and drop all cards 20% speed then in few sec still crash. So no clue what to do with it.

**Comment by nicehashdev** [comment]
Are you using latest NVIDIA drivers? 466.11 ?

**Comment by pav12345** [comment]
yes

**Comment by nicehashdev** [comment]
Please, enable file logging and submit logs - complete, with startup of NHQM up to the point of the crash.

**Comment by evrenbicer** [comment]
Same things happened to my some rigs as well, However, I used lite or mid opts and they are working well now. The point is, I cannot get full potential out of my cards such as gtx 1080 or gtx 1660, at least 2-3mh more :(

**Comment by pav12345** [comment]
Did you fix that problem with drop speed? I tried but it dont make differents :(

**Comment by pav12345** [comment]
Sending my crash file since start till crash and restart. If that helps. Just where to send it? Is safe send here?

**Comment by pav12345** [comment]
I reinstal win 10 on one rig and it stop crashing. I have to try on my big rig if that help to

**Comment by pav12345** [comment]
Well I did reinstalled big rig to, add extra space for virtual memory but not sure why keep doing that crash. Is better th before, but still keep crash. I have mobo MPG Z390 edge AC, any idea how to set bios to make it stop crashing on 11 GPU?
Easy just set mining on 4G on bios, but i have to using 1 x 4  (PCI-E adapter) splitters for risers. any help please? thx

**Comment by nicehashdev** [comment]
I would pin that to having stability issues if you are using 11 GPUs with risers. It is hard to get such configurations being fully stable. You can help yourself with following guide: https://github.com/nicehash/NiceHashQuickMiner/wiki/Mining-Rig-with-QuickMiner-in-one-hour

Also, do not forget to apply MSI as it can greatly improve stability of your Rig (make sure to use PCIe gen 2 for that!).

**Comment by pav12345** [comment]
I have driver 466.11 not that old ones

**Comment by Sission** [comment]
Hi! i have the same issue. I have 2 3090 and one 3080. The 3090s work fine. However, I changed the 'optimzation' to 'medium' of 3080 in NiceHash manager then it raises the same error.

**Comment by lshaf** [comment]
> Hi! i have the same issue. I have 2 3090 and one 3080. The 3090s work fine. However, I changed the 'optimzation' to 'medium' of 3080 in NiceHash manager then it raises the same error.

How about 'efficient'?
I've been struggle with the same error so I manage to get better performance by manually overclock it.

**Comment by mondo139** [comment]
Nice and does the manually OC you go with the nicehash recommendation?
