### ISSUE TITLE
[BUG] NHQM keeps trying to re-install after every reboot in Windows 10

### ISSUE THREAD

**Issue by mikeroygray** [nicehash/NiceHashQuickMiner#384]
**Describe the bug**
Every time I reboot to Windows 10, I get a message that Nicehash is, apparently, trying to re-install itself. This has been happening for over a week now, I can't pinpoint when it started.

First message: NH is already installed, would you like to overwrite.
Second message (if I click "no"): Error installing!

**To Reproduce**
Reboot Windows.

**Expected behavior**
Not try to reinstall

**Screenshots**
see ...

**Version affected (please complete the following information):**
makes no difference. I've try uninstalling, reinstalling, rebooting ad nauseam. So far, nothing I can do can remove this weird loop. I don't see anything in "Task Manager /Startup", nor do I see anything in Scheduler.

**Hardware**
Probably not relevant, but I have single 3090 in the first PCIE 4.0 slot. I even tried moving it to slot 2, no change. My MB is an asus rog strix x570-e 

**Logs**
comes before
![1](https://user-images.githubusercontent.com/37187713/114906203-17c42180-9e1a-11eb-948d-621beffc5ae2.jpg)
![2](https://user-images.githubusercontent.com/37187713/114906204-185cb800-9e1a-11eb-88a6-8d24b62df6c4.jpg)

**Additional context**

**Comment by mikeroygray** [comment]
P.S. NHQM work fine otherwise. I currently have it installed through Windows, I was using the ZIP file version before. Either one starts properly and runs perfectly. This re-install loop is not connected to the actual installation.

**Comment by nicehashdev** [comment]
Please, try latest version 0.4.7.1. Make sure that no AV is interfering with any files of NHQM. If some files get deleted, NHQM may ask you to reinstall.

**Comment by mikeroygray** [comment]
I've already got RC 0.4.7.1. installed - I've let the process install it a couple times, hoping it would be happy. No dice. Also, Windows security isn't throwing any messages at all.

Would it help to turn of "Real-time Protection" and reboot??

**Comment by nicehashdev** [comment]
The problem is that most of AVs make "silent" deletes of files. This is well known with Windows Defender. It may just delete or block your file without notifying you.

**Comment by mikeroygray** [comment]
OK, what can I do to make it stop? Having this happen every single time I reboot is getting extremely annoying.

**Comment by nicehashdev** [comment]
Try to install it in a very simple path, such as: C:\nhqm

Let me know if that works?

**Comment by mikeroygray** [comment]
OK, daytime again in Switzerland.

I can put the WORKING installation anywhere I like - but the installation PROCESS that ALWAYS autostarts with Windows is not able to choose any place BESIDES the protected path. (c:\program files\etc.) 

Basically: there is something something, somewhere in windows telling windows to start this installation process every single time I log into my account. It seems like this should be a task scheduler issue, but I can't seem to find anything.

**Comment by nicehashdev** [comment]
Yes. You can also try to remove windows autostart and readd it back.

Also, it needs to be started as Administrator with full permissions. Is it?

**Comment by nicehashdev** [comment]
I consider this issue solved.

**Comment by mikeroygray** [comment]
Umm. Just for the record, this isn't resolves in the least. 

As far as I can tell, the only way to fix is to reinstall Windows, which is just too much of a pain.

**Comment by mikeroygray** [comment]
P.S. Put otherwise: The thing has screwed up my current installation and there is absolutely nothing I can do to get rid of the process.
