### ISSUE TITLE
No Hardware detected

### ISSUE THREAD

**Issue by liocha12063** [nicehash/NiceHashQuickMiner#385]
It work fine for a while then stop and it couldn't restart  and now it doesn't see the GPUs 
![Error](https://user-images.githubusercontent.com/25189101/114976000-11de3880-9e3a-11eb-91a3-cbdd60f18ada.PNG)

**Comment by nicehashdev** [comment]
You have problems with drivers. Make sure your drivers are correctly installed and that all GPUs are stable. Check here for more info: https://github.com/nicehash/NiceHashQuickMiner/wiki/Mining-Rig-with-QuickMiner-in-one-hour#2-install-nvidia-drivers

**Comment by alexcomo95** [comment]
Same issue even after installing the latest non-DCH driver's version.
