### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by StepGitHub** [nicehash/NiceHashQuickMiner#387]
Hi! The new version 0.5.0.1 RC (Excavator 1.7.0 c) does not work correctly on my Palit 3060 and Palit 1660 ti. At the start, some kind of warning about MSI was issued. After 30 seconds of operation, Excavator gives errors and reboots. Version 0.4.7.1 RC (Excavator 1.7.0 b) works without problems. And all previous versions worked without problems.Windows 10 64, Nvidia drivers 470.05. Thank's.

**Comment by nicehashdev** [comment]
Yes, it gives warning about MSI interrupts not being used which reduces your stability. You can activate MSI going NHQM Task Tray Icon -> Settings -> Extra -> Apply MSI interrupts

**Comment by nicehashdev** [comment]
You can read more about it here: https://github.com/nicehash/NiceHashQuickMiner/wiki/MSI---Improve-stability-of-your-PC-Rig
