### ISSUE TITLE
Startup when windows start

### ISSUE THREAD

**Issue by Riones** [nicehash/NiceHashQuickMiner#39]
Hello everyone!
If I Install Nice Hash "normal", they startup automaticly.
But If I put This QuickMiner, They Don't.
I Put This on Execut - Shell:Startup

Can you fix this please?
I like more this QuickMiner, but I need, that start automaticly On startup Windows.

Thank you.
best regards

**Comment by nicehashdev** [comment]
You can activate autostartup with Windows by right clicking NiceHash QuickMiner icon in notification area. It is explained here: https://github.com/nicehash/NiceHashQuickMiner/wiki/Starting-for-the-first-time#5-startup-with-windows
