### ISSUE TITLE
Not detecting my GPU

### ISSUE THREAD

**Issue by shashank725** [nicehash/NiceHashQuickMiner#391]
**Describe the bug**
My GPU GTX 1650Ti is getting detected.

**Expected behavior**

**Screenshots**
![GTX](https://user-images.githubusercontent.com/77995024/115073168-9487f600-9f15-11eb-88ab-9f03199184aa.JPG)

**Version affected (please complete the following information):**
 - Version number:  Stable release: 0.4.5.5
 - RC or STABLE? : Stable

**Hardware**
Describe GPUs used and how are GPUs connected to the motherboard.
CPU?

**Logs**
Activate logging first, then reco
[exported_logs.zip](https://github.com/nicehash/NiceHashQuickMiner/files/6327432/exported_logs.zip)
rd event - bug - then export logs into a .zip file and attach it when submitting this issue.

**Comment by nicehashdev** [comment]
This GPU is not supported.
