### ISSUE TITLE
Optimize options are missing (Only Manual and Lite)

### ISSUE THREAD

**Issue by RigRTX3090** [nicehash/NiceHashQuickMiner#392]
**Describe the bug**
Optimize options in Rig manger are gone just manual and lite are visible but using android mobile app all options are available (manual, lite, medium, high, extreme ...
**To Reproduce**
1. Dashboard
2. Rig Manager
3. Rigs
4. optimize options

**Expected behavior**
To see optimize options (manual, lite, medium, high, extreme ...

**Screenshots**
If applicable, add screenshots to help explain 
![Screenshot 2021-04-17 085809](https://user-images.githubusercontent.com/82683718/115091518-12babb80-9f5b-11eb-87c6-fe2f78b3e45a.png)
your problem.

**Version affected (please complete the following information):**
Prerelease v0.5.0.1 RC

**Hardware**
6x RTX3090
connected via riser

**Logs**
Activate logging first, then record event - bug - then export logs into a .zip file and attach it when submitting this issue.

**Additional context**

**Comment by knowledgeispower101** [comment]
I noticed this as well for v0.5.0.1 RC. If click on that arrow on the left next to the rig name, you actually will see all the optimize options show up for that particular GPU in the rig; it's just the parent directory optimize options that are affected

**Comment by takeruadelbert** [comment]
same here, there's no medium and high option.

**Comment by nicehashdev** [comment]
This is not a bug but something that was added to reduce possibility of crashes when people were activating higher tier optimize for all devices of a rig. You can still get all options if you do it per device and not per rig/group.

**Comment by Yildiz81** [comment]
#723
