### ISSUE TITLE
[QUESTION] 0.5.0.1_RC game mode problem

### ISSUE THREAD

**Issue by hexterm** [nicehash/NiceHashQuickMiner#393]
I am testing the 0.5.0.1_RC version and everything seems ok except "game mode".
I can configure and activate game mode, play something and when I want to deactivate GM I always get:

"Could not detect video card with connected displays or you may be using older video card for display."

I am using the latest non-DCH driver and my card is an RTX 3080.

Is this a known issue or I am doing something wrong?

**Comment by AussieWarren** [comment]
This happens a good bit for me too. I think it's after my display driver has crashed previously.

**Comment by AussieWarren** [comment]
This happens to me a good bit too. I think it's after my display driver has crashed. Just now I restarted my Nvidia driver from the OCTune page (didn't resolve issue), restarted excavator from the OCTune page (didn't resolve), then restarted NiceHash QuickMiner as a whole which let me use Game Mode again.

**Comment by nicehashdev** [comment]
If your drivers get updated or some other weird scenario happens that affects UUID of your GPU, then Game Mode gets broken aswell. I suggest rebooting PC after each driver update as this operation is known to change GPU UUID in some cases.

**Comment by nicehashdev** [comment]
Upcoming version will not be so strict when quitting - you can quit even if Game Mode is still on, but it is suggested o perform reboot then, because not everything may be OK (some unexpected OC values may be still applied).

**Comment by nieXas** [comment]
this happens for me after monitor is turned off for a while and turned back on. but it may be because driver crash during it?
