### ISSUE TITLE
[QUESTION] GPU Utillization Drop

### ISSUE THREAD

**Issue by comset** [nicehash/NiceHashQuickMiner#394]
v0.5.0.1 RC or 0.4.5.5
NVIDIA driver 461.72 or 165.89
RTX3070 and 3080

I am monitoring with OCtune. The medium setting value is set manually and used.
A few hours after starting mining, the GPU usage rate drops from 100% to the 70% level for a moment and returns to the original 100%. (1-2 seconds)
I don't think there is any problem with some fluctuations, but there are times when they fluctuate significantly.
I repeat this many times, is it normal? Of course, MEM remains 100%.
What is worrisome is that the power consumption will drop considerably from 115W to 75W due to the decrease in GPU utilization.
So far, REJECTED and HW Err have not occurred.
Does it affect mining?

Restarting Excavater will fix this, but it will happen again after a few hours.

Improvement measures I have taken
Windows 10 clean install
Driver reinstallation
BIOS reset
PSU changes

**Comment by nicehashdev** [comment]
What kind of CPU do you use? Is there some app that uses a lot of your CPU?

**Comment by comset** [comment]
I am using celeron G5920 and Asrock H470.
The only installed apps are the NVIDIA driver and NHQM.
The UHD Graphics 610 is connected to the display via HDMI.

**Comment by nicehashdev** [comment]
What kind of speeds do you get? What is your average accepted speed (over days or more) when you check the chart on NiceHash Rig Manager? Is it equal to what your cards are reporting? If yes, then I see no problem. That is probably related to DAG being generated.

**Comment by comset** [comment]
The speed was 280 MH / s and the average permissible speed was about the same.
When GPU usage and power consumption drop
If the Excavater doesn't show the DAG generation log, is it still affected by the DAG?
I was relieved to know that it was related to DAG.
Thank you.

**Comment by nicehashdev** [comment]
Yes, if it happens here and there only, then it must be DAG being generated. You can see this in Excavator console - it will says something about it.

If your average accepted speed is expected, then there is nothing to worry about.

**Comment by comset** [comment]
Thank you!
