### ISSUE TITLE
[QUESTION] Can I enable / disable mining based on a webpage?

### ISSUE THREAD

**Issue by Catchears** [nicehash/NiceHashQuickMiner#395]
**Has the question been answered in [Wiki](https://github.com/nicehash/NiceHashQuickMiner/wiki)? There is no such question in [FAQ](https://github.com/nicehash/NiceHashQuickMiner/wiki/FAQ) or [Troubleshooting collection](https://github.com/nicehash/NiceHashQuickMiner/wiki/Troubleshooting)?**
No.

**Your question is...**
I have solar panels and would only like to mine when solar power is available. I can set a webpage up which does something depending on whether power is available or not, but is it possible to control the miner with that?

**Comment by nicehashdev** [comment]
You can script many things using Excavator API: https://github.com/nicehash/excavator/tree/master/api
