### ISSUE TITLE
[QUESTION] NiceHash QuickMiner warning #104

### ISSUE THREAD

**Issue by amore514** [nicehash/NiceHashQuickMiner#396]
When I start NHQM I get a warning "NiceHash QuickMiner warning #104" MSI disabled! Please enable MSA for better stability

This might be a noob question but what is this? how / where do I enable it?

**Comment by nicehashdev** [comment]
NiceHash QuickMiner taskbar icon -> Settings -> Extra -> Apply MSI Interrupts

**Comment by nicehashdev** [comment]
https://github.com/nicehash/NiceHashQuickMiner/wiki/MSI---Improve-stability-of-your-PC-Rig
