### ISSUE TITLE
[QUESTION] High and Medium Optimization options disappeared?

### ISSUE THREAD

**Issue by mobilemid** [nicehash/NiceHashQuickMiner#397]
I just notice this today, but the high and medium optimization setting on Quick Miner are no longer present. I am running a NVIDA 2080 Super.

I really liked the Medium optimization setting. How come it was removed?

**Comment by nicehashdev** [comment]
No, just do it per device not per rig or group: https://github.com/nicehash/NiceHashQuickMiner/issues/392
