### ISSUE TITLE
[QUESTION] Linux availability

### ISSUE THREAD

**Issue by davebulaval** [nicehash/NiceHashQuickMiner#403]
When do you expect to finish the instruction for Linux users?

https://github.com/nicehash/NiceHashQuickMiner/wiki/Virtual-Mining#virtual-mining

**Comment by nicehashdev** [comment]
Linux instructions are already there: https://github.com/nicehash/NiceHashQuickMiner/wiki/Virtual-Mining#linux--quickminer

If you have some additional questions, just ask.

**Comment by davebulaval** [comment]
> Linux instructions are already there: https://github.com/nicehash/NiceHashQuickMiner/wiki/Virtual-Mining#linux--quickminer
> 
> If you have some additional questions, just ask.

The doc stated not in the final stage and contains TODO.

> WARNING: Incomplete instructions! Work in progress...

> BIOS preparation - TODO

**Comment by nicehashdev** [comment]
Yes, BIOS is very system specific and we are still collecting data what is available and what should be set in BIOS. If it doesn't work for you, try to experiment and see what works. Also, when you find solution, please, report it, so we can share with others.
