### ISSUE TITLE
[BUG] OCTune showing wrong VRAM temp when using laptop with multiple GPUs.

### ISSUE THREAD

**Issue by l3thalsab3r** [nicehash/NiceHashQuickMiner#404]
Currently, when using QuickMiner on my Asus Zephyrus G15 (2021) with a 3070 it is showing the correct GPU temperature, but for the VRAM temperature, it is incorrectly displaying the temperature of the integrated GPU instead which is the AMD Vega chip. 

I'm not sure if it's supposed to be reporting the VRAM temperature or the Hotspot temperature since I believe that the 3070 does not have any VRAM sensors but none the less it is the incorrect temperatures which is the bug. I've attached a screenshot to hopefully further explain the issue.

It's happening on version RC 0.5.1.0 and I just updated to 0.5.1.3 and the issue persists.
![Wrong temps](https://user-images.githubusercontent.com/82844880/115304761-2fe9b880-a11a-11eb-966f-a8e0120fe780.png)

**Comment by nicehashdev** [comment]
Please, open your browser and get me content of the following website: `http://localhost:18000/devices_cuda`

**Comment by l3thalsab3r** [comment]
Here's what showed up:

{"devices":[{"device_id":0,"name":"GeForce RTX 3070 Laptop GPU","gpgpu_type":1,"subvendor":"1043","details":{"cuda_id":0,"sm_major":8,"sm_minor":6,"bus_id":1,"sli":false,"bus_slot_id":1,"ram_maker":"Samsung","pci_ident":"VEN_10DE&DEV_249D&SUBSYS_118C1043&REV_A1"},"uuid":"GPU-46a89716-c385-50d6-ec9b-a092c16c73be","gpu_temp":62,"gpu_load":100,"gpu_load_memctrl":100,"gpu_power_mode":-1,"gpu_power_usage":72.05,"gpu_power_limit_current":-3.0,"gpu_power_limit_min":0.0,"gpu_power_limit_max":0.0,"gpu_power_limit_default":0.0,"gpu_tdp_current":-5.0,"gpu_clock_core_max":2100,"gpu_clock_core":600,"gpu_clock_memory":6250,"gpu_clock_memory_default":6001,"gpu_fan_speed":-3,"gpu_fan_speed_rpm":-2,"gpu_memory_free":2632241152,"gpu_memory_used":5957693440,"intensity":1,"hw_errors":0,"hw_errors_success":293,"kernel_times":{"avg":62354,"min":62261,"max":62435,"umed":62368},"oc_data":{"core_clock_delta":0,"memory_clock_delta":249,"power_limit_watts":-3,"power_limit_tdp":-5,"core_clock_limit":600,"core_uvolt":[],"vfc":[],"mt":{}},"fans":[],"too_hot":false,"__vram_temp":59,"__hotspot_temp":68,"smartfan":{"mode":0,"fixed_speed":100,"target_gpu":60,"target_vram":90,"start_level":75,"override_level_min":-1,"override_level_max":-1,"decrease_k":200,"increase_k":2000,"increase_n_gpu":-3,"increase_n_vram":0},"oc_limits":{"core_delta_min":-1000,"core_delta_max":1000,"vram_delta_min":-1000,"vram_delta_max":3000,"tdp_min":0,"tdp_max":0},"gpu_mvolt_core":618,"gpu_memory_timings":{"bEditable":false,"timings":{"RC":77,"RFC":180,"RAS":51,"RP":26,"CFG0_R0":0,"CL":24,"WL":5,"RD_RCD":26,"WR_RCD":17,"CFG1_R0":25,"RPRE":0,"WPRE":1,"CDLR":8,"WR":26,"W2R_BUS":7,"R2W_BUS":7,"PDEX":12,"PDEN2PDEX":15,"FAW":16,"AOND":0,"CCDL":2,"CCDS":2,"REFRESH_LO":5,"REFRESH":4,"RRD":4,"DELAY0":20,"CFG4_R0":28,"ADR_MIN":5,"CFG5_R0":0,"WRCRC":16,"CFG5_R1":0,"OFFSET0":39,"DELAY0_MSB":0,"OFFSET1":13,"OFFSET2":7,"DELAY01":10}},"optimize_locked":false}],"id":1,"error":null}

**Comment by nicehashdev** [comment]
So, it is `"__vram_temp":59` and that is what OCTune displays. Your Hotspot is 68, but that isn't displayed in OCTune.

**Comment by l3thalsab3r** [comment]
Got it. I wonder why it's reporting that VRAM temp then when in GPUz it's showing a Hotspot temp and no VRAM temp for this specific chip. None the less I assume it's not really an issue for you to figure out at this point so I'll leave it for you to decide how to continue at this point. Unless if it would be possible to include the Hotspot temp in OCTune in a future update . Thanks for clarifying and the tip on seeing the full data!

**Comment by nicehashdev** [comment]
NVIDIA in recent drivers exposed one more sensor that isn't GPU and isn't hotspot. I assume it could be VRAM (or VRM). The behavior and place is identical to the one on GDDR6X displaying mem tjunction.

**Comment by l3thalsab3r** [comment]
Interesting and that would explain it then. Thanks for the note!
