### ISSUE TITLE
[BUG] 0.5.1.3 borks the high tuning on 1080ti

### ISSUE THREAD

**Issue by objecttothis** [nicehash/NiceHashQuickMiner#405]
**Describe the bug**
Not sure what changed between 0.5.1.0 and 0.5.1.3 but I went from 44-46MH/s and 210kH/J on my 1080ti with High optimization to 40-42 MH/s and 190kH/J.  I had to downgrade back to 0.5.1.0 and now I'm back to 44-46.

**To Reproduce**
upgrade to 0.5.1.3 from 0.5.1.0 when it prompts you. 
**Expected behavior**

**Screenshots**

**Version affected (please complete the following information):**
 - Version number [e.g. 0.4.5.5] 0.5.1.3
 - RC or STABLE? RC

**Hardware**
Describe GPUs used and how are GPUs connected to the motherboard. Zotac ArcticStorm 1080ti (not the mini)
CPU?

**Logs**
Activate logging first, then record event - bug - then export logs into a .zip file and attach it when submitting this issue.

**Additional context**

**Comment by nicehashdev** [comment]
Were you using 0.5.0.1 or 0.5.1.0?

**Comment by objecttothis** [comment]
0.5.1.0

**Comment by objecttothis** [comment]
After returning back to 0.5.1.0 I'm back to getting 44-46 MH/s
![Screenshot_20210420-015009](https://user-images.githubusercontent.com/17935339/115307869-e54c5880-a17a-11eb-84a5-9e66b98b9ce2.jpg)

**Comment by nicehashdev** [comment]
Please, try to take excavator.exe from 0.5.1.3 and use it in 0.5.1.0. What happens in this case?

**Comment by objecttothis** [comment]
Just backed up the excavator.exe from 0.5.1.0 and swapped in the excavator from 0.5.1.3.  I am getting the same 44-46MH/s.  It haas the same version number 1.7.1d as the one from 0..5.1.0 but a different date stamp and different file size.

**Comment by lukaszcholewka** [comment]
I've got the same problem after upgrade from 0.5.1.0 to 0.5.1.3. It's not a problem with excavator. It's a problem with optimisation profile. After upgrade optimisation profile doesn't work and rig is on default settings (no OC). In 0.5.1.3 version I can't change optimisation profile on web, no buttons to check profile :)

**Comment by nicehashdev** [comment]
Are you perhaps using your own optimization data? Because in 0.5.1.3, it has been upgraded to use version 6.

**Comment by objecttothis** [comment]
> 
> 
> Are you perhaps using your own optimization data? Because in 0.5.1.3, it has been upgraded to use version 6. If that is the case, you need to upgrade version in your file to 6 otherwise optimizations won't work.

I can't speak for @lukaszcholewka but I was just using the High profile, installed 0.5.1.3 and it restarted on the high profile, but with lower hash rates, so none of my own optimization data.

**Comment by nicehashdev** [comment]
@objecttothis enable logging and submit logs. We will see if any optimizations do get applied at all.

**Comment by objecttothis** [comment]
I uninstalled Quickminer completely and then downloaded and installed 0.5.1.3 and took logs of that.
[exported_logs 0.5.1.0.zip](https://github.com/nicehash/NiceHashQuickMiner/files/6345409/exported_logs.0.5.1.0.zip)

Then I ran the installer and installed 0.5.1.3.  Unlike other upgrades, this one causes problems with my rig manager.  I have to add a new rig and delete the old one.  In the past it just remembered my rig and I didn't lose my stats, but this one thinks it's a new rig.

I started the logger and was pissed because it was actually showing similar hash rates as 0.5.1.3.  Then I exported the log and stopped logging.
[exported_logs 0.5.1.3.zip](https://github.com/nicehash/NiceHashQuickMiner/files/6345410/exported_logs.0.5.1.3.zip)

When it stopped logging it restarted quickminer and excavator and I kid you not, it was back down to 40-42MH/s!  I kid you not.  It's like this little bastard knew I was watching.  However I started up the logging again and it kept the same lower hash rate while I was logging this time.  The 0.5.1.3 log with a timestamp of 21:04 is the one that shows the lower hash rate. I know we are only talking about a 4-6MH/s difference, but it's a noticeable difference.

You can see from my stat graph below that I'm getting gradually increasing overall hash rate and then right at the end it drops off.  That was the point where I stopped the logging and it restarted and let 0.5.1.3 go on it's own.  I don't think I'm imagining this.

![image](https://user-images.githubusercontent.com/17935339/115437117-d7e7aa80-a21c-11eb-9a21-e708f16cad9d.png)

**Comment by nicehashdev** [comment]
This sounds like just other apps using your GPU. Read this: https://github.com/nicehash/NiceHashQuickMiner/wiki/FAQ#faq08

**Comment by objecttothis** [comment]
Maybe, but I don't buy that suddenly other apps start using the gpu when I have nothing open and it's at the EXACT moment that excavator restarted when I turned off logging when the exact same processes running and the hashrate drops. Seems pretty sus to me.

**Comment by nicehashdev** [comment]
I checked your logs and there is nothing else but fault of some 3rd app consuming some of your GPU power which causes your lower speeds in certain occasions.

**Comment by Intoxicus** [comment]
You're telling me 5.1.3 isn't a problem with optimizations....

**Comment by objecttothis** [comment]
I think that's what @nicehashdev is saying.  I've had several times where my hash rate will tank down to below 30MH/s and If I put it back at manual then high it will jump back up to 43-45ish.  It seems like more than just "other apps using the GPU".  It'd be nice if there was a log of apps that were using the GPU like that.  I'm using task manager and it shows GPU usage at 1-2%

**Comment by Intoxicus** [comment]
There's a bug with the optimizations I tried to report and @nicehashdev denied was anything.

Then I see reports reporting the same bug...
