### ISSUE TITLE
[BUG] Extreme optimization on water cooled 1080 ti crashes the GPU driver

### ISSUE THREAD

**Issue by objecttothis** [nicehash/NiceHashQuickMiner#406]
**Describe the bug**
If I change the optimization from high to extreme it crashes the video card driver and I have to bump it back down.

**To Reproduce**
change the optimization to extreme on the rig manager

**Expected behavior**
perhaps there are 1080ti's out there that can handle the extreme optimization, but in case there aren't I thought I'd post this.  perhaps the 1080ti optimizations should be toned down just a tad on extreme and that might be enough to not crash the GPU driver.

**Screenshots**

**Version affected (please complete the following information):**
 - Version number [e.g. 0.4.5.5] 0.5.1.0-0.5.1.3
 - RC or STABLE? RC

**Hardware**
Describe GPUs used and how are GPUs connected to the motherboard. Zotac ArcticStorm 1080 ti (not mini) on a custom water loop.
CPU?

**Logs**
Activate logging first, then record event - bug - then export logs into a .zip file and attach it when submitting this issue.

**Additional context**

**Comment by nicehashdev** [comment]
Each chip is different, we cannot guarantee any optimization to work for you, even if you have water cooled system. Unfortunately, you will have to set manual OC for your card.
