### ISSUE TITLE
[FEATURE] Add "TITAN Xp COLLECTORS EDITION" to json config file

### ISSUE THREAD

**Issue by reginhild** [nicehash/NiceHashQuickMiner#408]
**Is your feature request related to a problem? Please describe.**
Latest release of QuickMiner added optimization for Titan Xp cards. Unfortunately, the Collector's Edition goes by a different name and is not picked up by the code due to the json config file only having "TITAN Xp" naming convention.

**Describe the solution you'd like**
Add a section in the json file with naming convention "TITAN Xp COLLECTORS EDITION" that duplicates the data from the "TITAN Xp" section.

**Describe alternatives you've considered**
None

**Additional context**
![titanxp_opt](https://user-images.githubusercontent.com/82412257/115315979-a942d480-a135-11eb-87e7-f293082a4d8d.jpg)

**Comment by nicehashdev** [comment]
Added. Install latest 0.5.1.3 RC and let me know if it works.

**Comment by reginhild** [comment]
Testing out now with the new options!
