### ISSUE TITLE
INFO: OCtune can try to start tuning when the user stopped mining, so no meaningful results are available

### ISSUE THREAD

**Issue by TerryFrench** [nicehash/NiceHashQuickMiner#41]
This is FYI only. 
yesterday, I somehow stopped mining and started OCTune after that. 
OCTune did not crash (great), but it had infinite efficiency for all settings, and would not have found any meaningful setting to use. 

So I recommend forcing mining to start when you start tuning. Or fail tuning and ask the user to start mining. 
Maybe disable the "stop" or have "Stop" also stop tuning if the user clicks on stop mining while tuning is happening.

**Comment by nicehashdev** [comment]
This whole project is Experimental so far, so of course, unexpected/stupid actions are not fully covered yet. For now, it is something you need to take care of - do not stop mining when you perform OCTune Autotune.

Eventually, OCTune and Autotune will be done over Rig Manager and start/stop control will be integrated and part of the functionality.
