### ISSUE TITLE
[BUG] Installer STABLE version points to v0.4.5.5 instead of v0.5.1.3

### ISSUE THREAD

**Issue by TimSirmovics** [nicehash/NiceHashQuickMiner#410]
![image](https://user-images.githubusercontent.com/10243286/115388555-5ba29680-a21f-11eb-822b-68bd4c7846ec.png)

**Comment by nicehashdev** [comment]
This is not a bug but a delay caused by github and CF infrastructure - not all servers are updated at the same time, so it may take some time, several minutes.
