### ISSUE TITLE
Can't override fan settings when optimisation used on latest version 5.1.3 [BUG] 

### ISSUE THREAD

**Issue by insom1337** [nicehash/NiceHashQuickMiner#411]
When I try to override the default fan settings in 'OCTune' it says I must first set the the optimisation profile in rig manager to manual.

In the past I have always used the medium / high profile and then also edited to a fixed percentage the fan speed within OCTune - is this intended?

Thanks

**Comment by nicehashdev** [comment]
https://www.nicehash.com/blog/post/modify-existing-optimization-profiles

**Comment by insom1337** [comment]
But this could be done with every single previous version of quick miner including the pre release builds?

**Comment by nicehashdev** [comment]
Mixing both - optimizations and custom OC settings were causing upredictable results. It is not possible to know which one will be executed at any time. If you want custom settings, you should use OCTune and set them as you wish, apply and have full custom automatization without any upredictable behavior.

**Comment by treppey** [comment]
I also want to change my fixed fan speed. I followed the guide @nicehashdev provided, but when I choose manual and play around with the settings in OCTune my GPU severely underperforms. I screenshotted my OCTune on efficient settings and made them the same on Manual but altered the fan speed. How can my gpu underperform if the settings are the same? Do I need to use some other software to change my fan speed?

**Comment by nicehashdev** [comment]
Provide information:
- your card
- optimization you were using
- settings you applied

And I will tell you what you are missing.

**Comment by treppey** [comment]
GTX 1080
https://imgur.com/a/GUUSJah
I think this will explain everything.

**Comment by nicehashdev** [comment]
I see that:
- You did not apply undervolt
- I don't see it (scroll down, there you have memory timings), but I would guess that you did not apply memory timings

When you do that, power consumption will go down and speed will go up. Your problem will be solved.

**Comment by treppey** [comment]
Thank you very much, will do that :)

**Comment by treppey** [comment]
When I try to apply undervolt it says:
Device #0: Cannot perform for GPU arch: Pascal

**Comment by nicehashdev** [comment]
Where are you doing undervolt? You need to do it under classical OC (left side, not right side).

Set it to 850 mV and core clock should be 1800 - that is stable for most of the cards. Then you can go up from that, bump voltage to 1000 mV and set core clock to 2010. Then try to decrease voltage from 1000 until GPU becomes unstable.

**Comment by treppey** [comment]
Ah, I finally did it. Ty, am at a stable 32 h/s

**Comment by UnsignedRealityCheck** [comment]
@nicehashdev I think you're missing the point. What used to work earlier is that you could set Optimization to any level and THEN adjust your fan speed curve to fit your rig to set the fan level and noise to something tolerable. If you overheat, that's your problem. Many of us have custom setups and want to set the fan level to where we are comfortable.

With 0.4.x I had a whisper quiet system with 69C and fans running where I wanted them. Now I can't change it unless I meddle with the optimization settings which I don't want to (and don't have the knowledge).

Just let us change the fan settings or at least make it an option behind a "I know what I'm doing" button.

**Comment by Belbol** [comment]
This is annoting...
I want to keep the optimization, just change the fan speed but i can't change it with the latest version.

I understand that they want us either to use their own preset optimization or our own, but i don't consider fan speed as part of the optimization, and it should be fixable.

Any one can give me a like for the previews version? i can't mine when the fan is on 100%

**Comment by UnsignedRealityCheck** [comment]
> This is annoting...
> I want to keep the optimization, just change the fan speed but i can't change it with the latest version.
> 
> I understand that they want us either to use their own preset optimization or our own, but i don't consider fan speed as part of the optimization, and it should be fixable.
> 
> Any one can give me a like for the previews version? i can't mine when the fan is on 100%

100% agree. My rig can handle temps up to 69-70C easily stable but the new version simply won't accept this and forces the temps to be lower. This is just stupid.

**Comment by MajorMaccas** [comment]
I'm in the exact same boat with the OP - multiple 3070 FE's and a 3090 FE, I had them all set on High optimization, and then just set a fan profile of fixed at 40% (65% for the 3090 beast!), leaving them all under 70C and near silent at full hashrate!

Can you please separate fan curve from OC settings, as they were before?  Luckily I did this on my main gaming rig first, with just a single 3070, so my main mining rig will not update until this is sorted.

**Comment by MajorMaccas** [comment]
Guys! I the fix!  Open octune.js - in the octune folder of nicehashquickminer program folder.  Default location:
C:\Program Files\NiceHash\NiceHashQuickMiner\octune\octune.js

Open it in notepad, Ctrl+F to find, search for "apply_fan" then see a couple of lines down the line that reads:
`if (is_optimize_locked(dev_id)) return;`

Just comment out this line with // at the beginning of the line.  This then won't check if an optimisation is selected when setting a fan profile, and works just like the pre 0.5 builds!
![image](https://user-images.githubusercontent.com/55187116/115466157-95779b00-a227-11eb-89c8-54dea6bd6339.png)

**Comment by nicehashdev** [comment]
> @nicehashdev I think you're missing the point. What used to work earlier is that you could set Optimization to any level and THEN adjust your fan speed curve to fit your rig to set the fan level and noise to something tolerable. If you overheat, that's your problem. Many of us have custom setups and want to set the fan level to where we are comfortable.
> 
> With 0.4.x I had a whisper quiet system with 69C and fans running where I wanted them. Now I can't change it unless I meddle with the optimization settings which I don't want to (and don't have the knowledge).
> 
> Just let us change the fan settings or at least make it an option behind a "I know what I'm doing" button.

That only worked until first excavator crash/close. It wasn't not a reliable solution. Not even saving commands is not reliable. Simply mixing OCTune with OPTIMIZE is bad idea because end results are not predictable (in most cases, OPTIMIZE is last to apply). The real solution will be available in the future when Rig Manager is merged with OCTune, but for that to happen, some protocol changes are needed first in the backend.

**Comment by MajorMaccas** [comment]
I mean I can't speak for anyone else, but across all my 30 series cards, hitting High optimisation, and then manually fixing fan speed has been rock solid for over a month now, hitting efficiencies as high as 570KH/J!

**Comment by nicehashdev** [comment]
Here, with this version, if you use local optimize database (version 6!), you can define "fs" which is integer fan speed in % (from 0 to 100).
[NHQM_v0.5.1.4_added_fs.zip](https://github.com/nicehash/NiceHashQuickMiner/files/6346905/NHQM_v0.5.1.4_added_fs.zip)

Example (set fan speed to fixed 95% for Extreme profile):
```
...
"devices": [
    { "name": "GeForce RTX 3090", "op": [
      { "id": 4, "pt": 0, "dmc": 1500, "mcc": 1200, "fm": 1, "fs" : 95 },
      { "id": 3, "pt": 0, "dmc": 1200, "mcc": 1140, "fm": 3, "ftg" : 56, "ftr": 90 },
...
```

**Comment by nicehashdev** [comment]
You might wanna check this out also: https://github.com/nicehash/NiceHashQuickMiner/issues/420

**Comment by MildodaDildo** [comment]
> @nicehashdev I think you're missing the point. What used to work earlier is that you could set Optimization to any level and THEN adjust your fan speed curve to fit your rig to set the fan level and noise to something tolerable. If you overheat, that's your problem. Many of us have custom setups and want to set the fan level to where we are comfortable.
> 
> With 0.4.x I had a whisper quiet system with 69C and fans running where I wanted them. Now I can't change it unless I meddle with the optimization settings which I don't want to (and don't have the knowledge).
> 
> Just let us change the fan settings or at least make it an option behind a "I know what I'm doing" button.

The reference fan on my 1080ti is just screaming now at 100% and temps are no better than when it was super quiet...how do we go back to the old version?

**Comment by UnsignedRealityCheck** [comment]
> > @nicehashdev I think you're missing the point. What used to work earlier is that you could set Optimization to any level and THEN adjust your fan speed curve to fit your rig to set the fan level and noise to something tolerable. If you overheat, that's your problem. Many of us have custom setups and want to set the fan level to where we are comfortable.
> > With 0.4.x I had a whisper quiet system with 69C and fans running where I wanted them. Now I can't change it unless I meddle with the optimization settings which I don't want to (and don't have the knowledge).
> > Just let us change the fan settings or at least make it an option behind a "I know what I'm doing" button.
> 
> The reference fan on my hybrid 1080ti is just screaming now at 100% and temps are no better than when it was super quiet...how do we go back to the old version?

Probably by just uninstalling the current and reinstalling the old from scratch, but you need to probably reconnect your rig to nicehash web page and lose all statistics.

I'm having the same issue, my fans we screaming at 100% and the temps were only few degrees lower than with fans at 50% and they were completely quiet.

The devs are saying that you can achieve the same result (optimizations + quiet fans) by poking around the json files and applying the settings manually.

**Comment by Yuranka** [comment]
I have a problem with the GTX 1080 Ti, I select "High optimization", then copy all the parameters from the OC Tune and enable "Manual optimization" and enter exactly the same data including the Voltage, but even if you increase or decrease the fan speed, the hashrate will still be less by 10 or 15.

**Comment by nicehashdev** [comment]
> I have a problem with the GTX 1080 Ti, I select "High optimization", then copy all the parameters from the OC Tune and enable "Manual optimization" and enter exactly the same data including the Voltage, but even if you increase or decrease the fan speed, the hashrate will still be less by 10 or 15.

Are you sure you set memory timings too?

**Comment by Yuranka** [comment]
> > I have a problem with the GTX 1080 Ti, I select "High optimization", then copy all the parameters from the OC Tune and enable "Manual optimization" and enter exactly the same data including the Voltage, but even if you increase or decrease the fan speed, the hashrate will still be less by 10 or 15.
> 
> Are you sure you set memory timings too?

Yes, of course, I can show you.

**Comment by Yuranka** [comment]
![bandicam 2021-04-21 16-04-41-430](https://user-images.githubusercontent.com/81821208/115558898-dc16d500-a2bb-11eb-8ec8-eb8e5a445ed2.jpg)
![bandicam 2021-04-21 16-06-24-230](https://user-images.githubusercontent.com/81821208/115558914-df11c580-a2bb-11eb-94ad-e7fa68826967.jpg)
Where the hashrate is higher, there is High optimization, where the hashrate is lower, there is Manual optimization.

**Comment by Yuranka** [comment]
> > I have a problem with the GTX 1080 Ti, I select "High optimization", then copy all the parameters from the OC Tune and enable "Manual optimization" and enter exactly the same data including the Voltage, but even if you increase or decrease the fan speed, the hashrate will still be less by 10 or 15.
> 
> Are you sure you set memory timings too?

I'm afraid you made some mistake during the update, please check.

**Comment by UnsignedRealityCheck** [comment]
> > > I have a problem with the GTX 1080 Ti, I select "High optimization", then copy all the parameters from the OC Tune and enable "Manual optimization" and enter exactly the same data including the Voltage, but even if you increase or decrease the fan speed, the hashrate will still be less by 10 or 15.
> > 
> > 
> > Are you sure you set memory timings too?
> 
> I'm afraid you made some mistake during the update, please check.

This whole thing needs to be a lot less convoluted for common use cases.

**Comment by Yuranka** [comment]
> > > > I have a problem with the GTX 1080 Ti, I select "High optimization", then copy all the parameters from the OC Tune and enable "Manual optimization" and enter exactly the same data including the Voltage, but even if you increase or decrease the fan speed, the hashrate will still be less by 10 or 15.
> > > 
> > > 
> > > Are you sure you set memory timings too?
> > 
> > 
> > I'm afraid you made some mistake during the update, please check.
> 
> This whole thing needs to be a lot less convoluted for common use cases.

I completely agree with you, before that everything was much easier.

**Comment by renedx** [comment]
This should totally be a UI option. I’m so done with fixing fan speed on each release/update/reboot. They would totally perform better with a minimum fan speed set to e.g. 75. But I’m fine with the optimize being managed by NiceHash, it should just include a way to set minimum fan speed per device (some ASUS req. 85 to be perfect VRAM).

They now running with that going on-off-on-off using the latest NiceHash and I cannot imagine this being a good thing.

**Comment by Yuranka** [comment]
> This should totally be a UI option. I’m so done with fixing fan speed on each release/update/reboot. They would totally perform better with a minimum fan speed set to e.g. 75. But I’m fine with the optimize being managed by NiceHash, it should just include a way to set minimum fan speed per device (some ASUS req. 85 to be perfect VRAM).
> 
> They now running with that two back fans going on-off-on-off using the latest NiceHash and I cannot imagine this being a good thing.

I think we'll just have to wait and the NiceHash guys will fix it.

**Comment by renedx** [comment]
> I think we'll just have to wait and the NiceHash guys will fix it.

Went with your manual approach now (had some stability issues with some 4x3080s rigs). They're working as expected now (just 1M/hs less, couldn't find out why). Thanks for the tip :)

**Comment by Yuranka** [comment]
> > I think we'll just have to wait and the NiceHash guys will fix it.
> 
> Went with your manual approach now (had some stability issues with some 4x3080s rigs too). They're working as expected now (just 1M/hs less, couldn't find out why). Thanks for the tip :)

You're welcome. ;)

**Comment by neo-jubil** [comment]
> Нельзя смешивать ОПТИМИЗАЦИЮ и ручную настройку. Вам нужно выбрать, какой из них использовать. Это поможет вам на вашем пути, если вы хотите настроить:
> https://www.nicehash.com/blog/post/modify-existing-optimization-profiles

You can't mix OPTIMIZATION and manual configuration. if I put any optimization... then I have a creeping temperature, the fans then spin then stand how do I fix the rotation of the fans for myself.version 0.5.1.3

**Comment by Xalaxis** [comment]
Hey @insom1337 and everyone else here, Nicehash has added feature #420 that should cover your needs (customizing an optimization profile). Have you given it a go?

**Comment by nicehashdev** [comment]
This issue is resolved. OCTune with this modification will be available with next version.
