### ISSUE TITLE
[BUG] pc wouldn’t detect monitor

### ISSUE THREAD

**Issue by saxobroko** [nicehash/NiceHashQuickMiner#414]
After enabling MSI off the latest build my computer wouldn’t show display and would beep 5 times indicating no display. I could tell the pc was working fine as all the parts were spinning normally. After Maybe 6 reboots it started working again. This is just an FYI if this happens to anyone else.

**Comment by nicehashdev** [comment]
Can you provide more information:
- version of your Windows 10
- your motherboard, does it have latest BIOS installed?
- your GPU
- how is your GPU connected to your motherboard?
- what is your pcie GEN setting in BIOS? according to specs, MSI is supported on PCIe gen2+

**Comment by saxobroko** [comment]
Version	10.0.19042 Build 19042
asrock b460m pro4
MSI 1660S
through the top pcie 16 slot
pcie version 3

**Comment by nicehashdev** [comment]
All of this hardware should support MSI. Can you please update your BIOS or make sure it is latest version?

**Comment by saxobroko** [comment]
Running version P1.50 which is the latest version

**Comment by nicehashdev** [comment]
And your NVIDIA driver version is?

**Comment by saxobroko** [comment]
The latest, 466.11 Game Ready

**Comment by nicehashdev** [comment]
Can you open GPU-Z and make a screenshot of your GPU? And, is your MSI currently enabled?

**Comment by saxobroko** [comment]
![image](https://user-images.githubusercontent.com/18757374/115401239-88f64100-a22d-11eb-8fd5-c8bd217a33b4.png)
and no the msi box is not checked

**Comment by nicehashdev** [comment]
One more thing; check in your BIOS whether above 4G decoding is enabled. If it is not, please enable it and then try MSI. Thanks!

**Comment by saxobroko** [comment]
4G decoding was enabled, then i booted and tried to enable msi once more and it said it was already optimised.

**Comment by nicehashdev** [comment]
Okay, so MSI is enabled and all works for you now. Must have been driver update then. Case closed.

**Comment by saxobroko** [comment]
This is still happening for me

**Comment by saxobroko** [comment]
Albeit unlikely with no other house to test, I am assuming that I have a bad pcie slot as it’s now working correctly in my 2nd slot

**Comment by saxobroko** [comment]
To be honest if your rig is already stable the small extra hash rate isn’t worth it.
