### ISSUE TITLE
cannot open the installer after the new update

### ISSUE THREAD

**Issue by elijah525** [nicehash/NiceHashQuickMiner#416]
after i updated the new installer i cannot open the installer whit the new version even after restarting the pc or delete the full nicehas software still doesnt wanne open help me asap

**Comment by nicehashdev** [comment]
You need to check your AV (Defender) - it is most likely blocking it.

**Comment by elijah525** [comment]
ooh the old installer still works and opens but not the new i checked defender and everything is off

**Comment by baiwan-chenhao** [comment]
the same as me.

**Comment by Xalaxis** [comment]
Are you getting any errors? Access denied? Have you tried temporarily disabling Real-time protection to see if that makes any difference?

**Comment by baiwan-chenhao** [comment]
there are no reactions when I click on it. but I change to 4.1.1.6,it work!

**Comment by nicehashdev** [comment]
Besides disabling real time protection, also disable "reputation-based protection". This one is blocking NHQM silently.

Check here: https://github.com/nicehash/NiceHashQuickMiner/wiki/Troubleshooting#windows-defender-is-blocking-nicehash-quickminer--i-get-notification-that-excavatorexe-was-blocked-from-running
