### ISSUE TITLE
GTX 1660 - OCTune can't control the fan

### ISSUE THREAD

**Issue by cesarlopes** [nicehash/NiceHashQuickMiner#418]
I have 3 video cards on my computer: 1660, 1660ti and 3070.

Only the 1660 has a strange fan behavior, any way I put an example "Target GPU & VRAM / HotSpot T." or "Fixed speed" in any of them the fan is oscillating between 33% as a minimum and any value above as 44% even in 70% sometimes when the temperature rises a little more.

I tried to change the drivers of my computer from 461.40 to 470.05 in all behavior seems to be the same.

I would prefer the fan to stay fixed for example at 50% but I am not getting it, does anyone have any idea how to do this?

**Comment by nicehashdev** [comment]
I would suggest you to update drivers to 466.11. That is the latest official version.

**Comment by cesarlopes** [comment]
I am currently using this driver 466.11, I tested it with the other drivers to see if I could change the behavior but apparently it didn't help.

My card model is ph-gtx1660-o6g firmware 90.16.34.00.37, could it be a problem with it?

**Comment by nicehashdev** [comment]
Just to make sure; your cards are desktop and not laptop cards, right?

**Comment by nicehashdev** [comment]
Did you perhaps modify max fan speed (level)? Please, paste your commands.json file here.

**Comment by cesarlopes** [comment]
I don't think I even touched this file, but I'll paste it here to see if it helps:

[{
		"time": 0,
		"commands": []
	}, {
		"time": 20,
		"commands": [{
				"id": 1,
				"method": "workers.reset.all",
				"params": []
			}]
	}, {
		"time": 30,
		"loop": 30,
		"commands": [{
				"id": 1,
				"method": "worker.print.efficiencies",
				"params": []
			}]
	}, {
		"time": 1,
		"loop": 4,
		"commands": [{
				"id": 1,
				"method": "devices.smartfan.exec",
				"params": []
			}]
	}, {
		"event": "on_quit",
		"commands": []
	}, {
		"event": "on_quickminer.start",
		"commands": []
	}, {
		"event": "on_quickminer.stop",
		"commands": []
	}, {
		"time": 10,
		"commands": []
	}]

**Comment by nicehashdev** [comment]
Reboot your PC.

Is your problem solved?

**Comment by cesarlopes** [comment]
I've restarted the computer a few times, done it again now and the symptom remains the same.

It looks like it improved a bit when I leave it set to just Target GPU Temp.

But if I try "Fixed Speed" mode or "Target GPU & VRAM / HotSpot T." the fan cooler looks like it has a hiccup :-)

I would love to leave a fixed amount, it would bother me much less.

I didn't activate the extra option "Apply MSI interrupts" should I use it? I don't think it would change anything in relation to the fan mode, correct?

**Comment by nicehashdev** [comment]
No, MSI has nothing to do with fans.

Well, it is best that you enable logging and let's take a look inside what is happening.

**Comment by cesarlopes** [comment]
[exported_logs.zip](https://github.com/nicehash/NiceHashQuickMiner/files/6347262/exported_logs.zip)

**Comment by nicehashdev** [comment]
I don't understand what the problem is. I see that fans are being adjusted towards your target. Yes, that may take some time, it is not instant, because it is using one class function (it doesn't try to predict future) - algorithm is very simple, so it may take a while, but once it reaches the sweetspot, it stays there.

**Comment by cesarlopes** [comment]
I think I solved it, every time I reinstalled the driver I used the clean install of nvidia itself, but today I decided to use the DDU to remove the drivers and then the installation the driver of nvidia again and it seems that it solved it.

**Comment by neo-jubil** [comment]
> поведение вентилятора

I have the same problem with the fans with the 1660 card how did you solve the problem?

**Comment by cesarlopes** [comment]
What solved for me was to remove all old video drivers with the DDU program (Display Driver Uninstaller Download version 18.0.3.9) and then I installed the latest version of the NVIDIA driver (466.11-desktop-win10-64bit- international-dch-whql)

**Comment by neo-jubil** [comment]
> Что решило для меня, так это удалить все старые видеодрайверы с помощью программы DDU (Display Driver Uninstaller Download version 18.0.3.9), а затем я установил последнюю версию драйвера NVIDIA (466.11-desktop-win10-64bit - international-dch-whql)

when I have manual overclocking,everything is OK, and when I put a light one, or another one, I can't adjust the fans,you also have cards that start to warm up

**Comment by cesarlopes** [comment]
Unfortunately this limitation of the fan setting is from the NiceHash Quick Miner program itself, isn't it? When you select a preset like that Light one, the program no longer lets you adjust the fans in the newer versions.

I also don't like this lock, I liked the old version where I could touch the fans.

**Comment by neo-jubil** [comment]
> К сожалению, это ограничение настройки вентилятора связано с самой программой NiceHash Quick Miner, не так ли? Когда вы выбираете предустановку, подобную этой Легкой, программа больше не позволяет вам регулировать вентиляторы в более новых версиях.
> 
> Мне тоже не нравится этот замок, мне нравилась старая версия, где я мог дотрагиваться до вентиляторов.

maybe in the new version I will make it so that you can adjust the fans yourself
