### ISSUE TITLE
[FEATURE] Ability to toggle CPU mining with game mode

### ISSUE THREAD

**Issue by ironpossum** [nicehash/NiceHashQuickMiner#419]
**Is your feature request related to a problem? Please describe.**
When I enable game mode, it does not stop CPU mining, so I need to do it manually, which seems to defeat the intent of game mode.

**Describe the solution you'd like**
I would like the choice to include CPU mining to be disabled when game mode is activated, and re-enabled when game mode is deactivated.

**Describe alternatives you've considered**
The only other alternative is the way I'm currently doing it, which is to disable it manually after I activate game mode.

**Additional context**
Nothing that I can think of.

**Comment by Xalaxis** [comment]
CPU mining disables for me when game mode is enabled on v0.5.1.3. Can you double check if this is still the case?

**Comment by nicehashdev** [comment]
Did you try to game with CPU mining enabled? Because CPU mining is set to lowest possible priority and it should not affect your gaming performance at all.

**Comment by ironpossum** [comment]
I was using 4.5.5_stable before, but I just now upgraded to 5.1.3_stable and confirmed that this is still the case.

Whereas it's set to the lowest cpu priority, it will still affect games negatively simply because all cores are in use and will have rested the clocks based on a thermal limit, whereas while gaming it would likely be able to boost higher on individual cores as needed. Additionally, games such as Valheim will see SIGNIFICANT performance reduction, despite the low CPU priority. For reference, I'm using a Ryzen 3900x.

**Comment by Xalaxis** [comment]
Strange, I'm on a 3900x as well and enabling game mode is definitely disabling CPU mining for me (which is what I want, for the same reasons as you). Maybe there's a config I've changed somewhere I've missed?

**Comment by nicehashdev** [comment]
So, the thing is following; if you have only one GPU and CPU, then yes, your CPU stops mining aswell. But if you have more GPUs, then CPU doesn't stop mining. I will fix this in next release.

**Comment by ironpossum** [comment]
Ah, that would explain it! I do have a 2nd GPU in the same rig. Thanks!

**Comment by nicehashdev** [comment]
Next ver disables CPU mining during Game Mode.
