### ISSUE TITLE
Fails to start mining

### ISSUE THREAD

**Issue by o94kiwi** [nicehash/NiceHashQuickMiner#42]
Using quick miner for the first time, I just get the error message for NVAPI error, and nothing happens. I don't have any antivirus running and am using rtx 3060 ti with latest drivers. As a side note I switched to the normal NiceHash miner and Excavator fails during the benchmark. Windows 10 is on the 20H2 update if that's an issue.

**Comment by Disparatado** [comment]
did you DDU the drivers first and disconnected internet when booting to windows after DDU, to install new?

**Comment by o94kiwi** [comment]
Thank you very much that solved the issue.

**Comment by Disparatado** [comment]
happy to help a fellow miner 👯‍♂️
