### ISSUE TITLE
[FEATURE] Option to pre-populate OCTune with an optimization profile

### ISSUE THREAD

**Issue by Xalaxis** [nicehash/NiceHashQuickMiner#420]
**Is your feature request related to a problem? Please describe.**

Sometimes users want to be able to tweak an optimization profile without customizing the underlying JSON. They are currently unable to do that using OCTune without manually hand-copying the values from the profile in, which can be especially hard for newer users.

For instance, recently I wanted to test what effect different fan profiles had on my Optimize "High" preset. I decided not to bother because I didn't want to manually figure out which optimization profile settings went in which box in OCTune.

Issue #368 would also be helped if this was implemented.

**Describe the solution you'd like**

OCTune should have an "Import from Optimization Profile" button that pre-fills the paramaters based on the published optimization profiles. This would allow users to rapidly customize their own manual profile and be useful for both newbies and pros alike.

**Describe alternatives you've considered**

- Users manually entering the information from the optimization profile to OCTune - Can be cryptic and hard for new users due to the JSON layout lacking human-readable names.

**Comment by nicehashdev** [comment]
Eventually, Rig Manager and OCTune will be merged and you will be able to add, delete, modify, export, import various profiles. All platforms (NHQM, NHM and NHOS).

**Comment by nicehashdev** [comment]
Actually, after giving it a second thought, it is not so hard to do it, just need to write some JS code. Will do it and let's see.

**Comment by nicehashdev** [comment]
Here it is, enjoy: https://github.com/nicehash/NiceHashQuickMiner/releases/download/v0.5.1.3/octune_optimize_profiles.zip

Just replace all files in octune folder. I think usage is pretty straightforward. Buttons that you need to press are going to be marked with yellow border.

**Comment by dek211** [comment]
I just want to lower the target temperature on the Vram temp to ramp up my fans sooner. I can no longer do this

**Comment by nicehashdev** [comment]
You can. Load this new OCTune I uploaded, then:
1. Select Manual profile in Rig Manager.
2. Open OCTune.
3. Select your card (single selected card).
4. From OPTIMIZATION's dropdown box choose optimization profile you were using.
5. Some buttons will be highlighted with yellow color. Click them all.
6. Finally, click green button to save your configuration.

In between you can of course modify anything you wish.

**Comment by Xalaxis** [comment]
@nicehashdev Loving this! The only thing it seems to be missing is that it doesn't prefill "Adjust memory timings" at the moment, for example the Efficiency profiles on the 1060.

**Comment by nicehashdev** [comment]
I will check for possible bugs, was in a hurry and didn't do it.

**Comment by dek211** [comment]
> You can. Load this new OCTune I uploaded, then:
> 
> 1. Select Manual profile in Rig Manager.
> 2. Open OCTune.
> 3. Select your card (single selected card).
> 4. From OPTIMIZATION's dropdown box choose optimization profile you were using.
> 5. Some buttons will be highlighted with yellow color. Click them all.
> 6. Finally, click green button to save your configuration.
> 
> In between you can of course modify anything you wish.

I had to uninstall and re install to make this work. 
It is super simple once you get it going.

Thanks!!

**Comment by Xalaxis** [comment]
Hi @nicehashdev, did you figure out why it wasn't working for memory timings?

**Comment by nicehashdev** [comment]
It was fixed with new OCTune files; redownload them.

**Comment by Xalaxis** [comment]
Brilliant! Thanks for this great new feature. I'm closing the issue now.
