### ISSUE TITLE
The AVG doesnt permit to install the excavator  [QUESTION] 

### ISSUE THREAD

**Issue by gaberman** [nicehash/NiceHashQuickMiner#421]
The AVG Doesnt permit to install the excavator, I say to allow theb download but when I try to open the installer opens a windows that saids that the archive have a virus and doesnt opens when I sad that Im Admin. What can I do to install now ?

**Comment by nicehashdev** [comment]
I suggest you to contact support of your AV provider and ask them how to proceed in this case.
