### ISSUE TITLE
Hotspot temperature gone from the NiceHash dashboard when using quickminer? (3060 Ti) [QUESTION] 

### ISSUE THREAD

**Issue by zakeryooo** [nicehash/NiceHashQuickMiner#425]
Since the latest stable update (0.5.1.3) when using Nicehash QuickMiner my NiceHash dashboard has gone from showing my GPUs 3060 Ti Hotspot temp, to showing the VRAM temp (which is a pretty useless measurement on a 3060 Ti because it doesn't have an internal VRAM temp sensor).

Is there a way to get the Hotspot temp reading back? Thanks

**Comment by knowledgeispower101** [comment]
It's the same one. They just renamed it. My 2080 also doesn't have a VRAM sensor, and they call what was the hotspot sensor the VRAM sensor...the temps are 100% identical. On the app it still even lists it as Hotspot temp...

**Comment by zakeryooo** [comment]
> It's the same one. They just renamed it. My 2080 also doesn't have a VRAM sensor, and they call what was the hotspot sensor the VRAM sensor...the temps are 100% identical. On the app it still even lists it as Hotspot temp...

It's not the same one. Not for the 3060 Ti at least, my hotspot temperature right now is 65c, the NiceHash dashboard is reporting 43c for "VRAM Temp".

**Comment by nicehashdev** [comment]
Latest NVIDIA driver introduced one more temperature sensor which has same location as GDDR6X. We cannot fully know whether this is VRAM sensor, because NVAPI documentation is private, but it would be strange to locate sensor at same location as GDDR6X and not being VRAM then.
