### ISSUE TITLE
[BUG] Cant lauch NHQM because of deleted files by the AV

### ISSUE THREAD

**Issue by matx33** [nicehash/NiceHashQuickMiner#426]
I already put NHQM in the exlcusion for the AV but it still deletes the files any ideas? 
![image](https://user-images.githubusercontent.com/77109454/115538298-52243780-a2ce-11eb-85b0-ea5a21077410.png)
![image](https://user-images.githubusercontent.com/77109454/115538353-5d776300-a2ce-11eb-8f1d-830e36e1f98b.png)
And there are no logs in NHQM folder

**Comment by matx33** [comment]
I was working fine before

**Comment by matx33** [comment]
Now i cant even install it 
![image](https://user-images.githubusercontent.com/77109454/115560051-cf5ba680-a2e6-11eb-8a70-f290dadc8985.png)

**Comment by nicehashdev** [comment]
Try this: https://github.com/nicehash/NiceHashQuickMiner/issues/204

More I have no idea what to do.

**Comment by matx33** [comment]
i already did those steps before.

**Comment by nicehashdev** [comment]
Unfortunately, we cannot do anything to prevent NHQM being false flagged by AVs due to their political decisions. This is not about technical stuff anymore but politics and will need to be solved using law and lawsuits.
