### ISSUE TITLE
[BUG] After installing 0.4.5.5 and now on the new release

### ISSUE THREAD

**Issue by Eternally-Dragz** [nicehash/NiceHashQuickMiner#427]
**Describe the bug**
After initially installing the miner the miner works. However when I shut down my pc and open the miner again it will black screen and crash my entire system causing it to reboot.

**To Reproduce**
1. Shut down system
2. Start miner
3. Artifacts for couples second
4. Black screen then reboot

**Expected behavior**
I expected the miner to be working before the update to 0.4.5.5

**Screenshots**

**Version affected (please complete the following information):**
 - Version number started with 0.4.5.5 and now on 0.5.1.3
 - Stable

**Hardware**
GTX 1660 super
GTX 1080 
Ryzen 7 2700X

**Logs**
Can't acquire logs after shutdown.

**Additional context**
The miner seems fine when installing it again however after I shut down my system the problem will occur.

**Comment by nicehashdev** [comment]
Update your drivers to 466.11.

**Comment by Eternally-Dragz** [comment]
I had updated the drivers and even uninstalled and reinstalled the drivers but the problem still occurs.

**Comment by nicehashdev** [comment]
Do you still have issue with this?

**Comment by nicehashdev** [comment]
No response, closing.
