### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by haughtyprince** [nicehash/NiceHashQuickMiner#429]
On v0.5.1.3 the manual oc is getting overrided everytime resulting high temps and higher voltage than what is set in the manual OC. Software used is MSI afterburner. Optimize was set to manual. I have a MSI GTX 1070

**To Reproduce**
Download v0.5.1.3 and just run it.

**Expected behavior**
Voltage settins get overrided resulting in high temps.

**Screenshots**

**Version affected (please complete the following information):**
 - v0.5.1.3
 - STABLE

**Hardware**
MSI GTX 1070  connected directly to the pcie port
CPU? No

**Logs**
Activate logging first, then record event - bug - then export logs into a .zip file and attach it when submitting this issue.

**Additional context**

**Comment by nicehashdev** [comment]
This is not a bug. Use OCTune to set voltages you would like. Periodic overriding is needed, because on some cards, manual voltage adjustment gets lost.
