### ISSUE TITLE
"Apps & Functions" still shows version RC on stable release.

### ISSUE THREAD

**Issue by kaio** [nicehash/NiceHashQuickMiner#431]
Description of problem:
- The "applications & functions" list still shows NiceHash QuickMiner as RC rather than stable.

Version-Release number of selected component (if applicable):
v0.5.1.3_stable

How reproducible:
- Always.

Steps to Reproduce:
1. Download QuickMiner v0.5.1.3_stable from https://github.com/nicehash/NiceHashQuickMiner/releases, https://github.com/nicehash/NiceHashQuickMiner/releases/download/v0.5.1.3/NiceHashQuickMinerInstaller.exe
2. Install that.
3. Run Windows built-in "Apps & Functions" program.
4. Search "nicehash" for the installed Quickminer.
5. Check results.

Actual results:
- The version shows "v0.5.1.3_RC".

Expected results:
- The version shows "v0.5.1.3_stable".

Additional info:
- Confirmed the installed version is "v0.5.1.3 Stable" by right-click tray icon -> About.

![Screenshot 2021-04-22 082737](https://user-images.githubusercontent.com/31382/115628841-9c480000-a344-11eb-8a01-a693cd6a2a7c.png)

**Comment by nicehashdev** [comment]
This is a low priority bug (only visual) and has low priority to be fixed.

**Comment by nicehashdev** [comment]
Will be fixed in new ver.
