### ISSUE TITLE
[BUG] Internet Speed reduced?

### ISSUE THREAD

**Issue by amore514** [nicehash/NiceHashQuickMiner#432]
Has anyone else reported their internet speed dropping while NHQM is running? Even if mining is stopped, but NHQM is still running, my internet speed drops from 900 Mbps to under 15 Mbps? As soon as I exit NHQM a speed test will go back to 900?

**Comment by nicehashdev** [comment]
I would guess this being an issue with your security software, hardware or even ISP.

NHQM does not use a lot of bandwidth, so it cannot be the source of issue.

**Comment by amore514** [comment]
With all of my testing, this is 100% the NHQM causing the problem. As soon as I stop and exit NHQM my speeds are back to normal. this has been happening for a while now. It could be my hardware but it 100% NHQM causing this problem.
