### ISSUE TITLE
My rigs keep restarting and not working - URGENT PLZ

### ISSUE THREAD

**Issue by evrenbicer** [nicehash/NiceHashQuickMiner#433]
pls can you help me, they have been working perfectly for the last 2-3 days. Suddenly 8 of my rigs start to restart and give this error...
![dasdas](https://user-images.githubusercontent.com/81778504/115649999-19697a00-a331-11eb-9ac6-124e084d4dc8.jpg)

now they are not working.

**Comment by evrenbicer** [comment]
Whats happening guys????

![Uploading vasd.jpg…]()

**Comment by evrenbicer** [comment]
![Uploading vasd.jpg…]()

**Comment by ZORO735** [comment]
I got the same problem bro this error showed up after I updated the quickminer 
![2B1684F3-EC66-42B0-AB75-2E273D0336FA](https://user-images.githubusercontent.com/83000561/115674090-fac9aa00-a355-11eb-9d26-ce5cbb0dc7ad.png)

**Comment by evrenbicer** [comment]
whats happening all of my rigs are not working, why isnt someone explaining why?

**Comment by evrenbicer** [comment]
I think it is releated with europa pool, pls nicehash staff confirm or change our pools to USA

**Comment by Sentrozom** [comment]
Yeah, same error here (1080ti and 2070 Super)... I am rolling back to previous version.

**Comment by ZORO735** [comment]
> whats happening all of my rigs are not working, why isnt someone explaining why?

yo try to change ur server location https://github.com/nicehash/NiceHashQuickMiner/wiki/Tips-&-tricks  and after that change ur optimizer to Lite and try mine is working fine now after i did that

**Comment by HighHopess** [comment]
Can u guys try to change your server locations manually for now?

**Comment by ZORO735** [comment]
> Can u guys try to change your server locations manually for now?

yes from QM setting and to edit config file and look for server location https://github.com/nicehash/NiceHashQuickMiner/wiki/Tips-&-tricks 
this link show u how to do it pick the location more close to u and get u low MS

**Comment by evrenbicer** [comment]
Thanks zoro ;) I have tried changing the server to "2" which has been working not bad for 10 hours. I hope it will keep up. However "ms" has dropped. So I am accepting mining jobs slower :( I hope someone from NICEHASH will fix this server issue.

**Comment by nicehashdev** [comment]
Please, enable logging and submit logs when this error happens.

**Comment by nicehashdev** [comment]
Are you still experiencing this problem?

**Comment by nicehashdev** [comment]
No response, closing.
