### ISSUE TITLE
[BUG] Illegal memory access was encountered

### ISSUE THREAD

**Issue by TrickyT1964** [nicehash/NiceHashQuickMiner#434]
Fairly consistent crashing, will crash persistently for hours before being perfectly fine again

Temps stable @ 64C
running 1080ti rig settings are on efficient was getting 41MH/s each before crashing constantly for hours with message

 [[2021-04-22 17:59:25.096961] [thread=0x00002908] [warning]]

	wrkr1-1 | CUDA error 'an illegal memory access was encountered' in func 'cuda_daggerhashimoto::run' line 1281

[[2021-04-22 17:59:25.099981] [thread=0x00002c08] [warning]]

	wrkr0-0 | CUDA error 'an illegal memory access was encountered' in func 'cuda_daggerhashimoto::run' line 1281

Version: STABLE v0.5.1.3
NVIDIA Drivers: 466.11

**Comment by 4runnerwanted** [comment]
I'm having this exact issue. Code is identical for my two 1070ti's. The second card is still crushing it at 31.5 MH/s and now the first card can barely hold 27 MH/s.

**Comment by nicehashdev** [comment]
These errors signalize too high OC. Note that every card cannot be fully compatible with every optimization profile. You need to be lucky to have a good chip. To maximize potential of your device, you have to use manual OC using OCTune. Check Wiki, there are plenty information and instructions on how to use OCTune.

**Comment by 4runnerwanted** [comment]
This error was not a problem until 5.1.3 came out. I have not changed my custom OC settings since February.
