### ISSUE TITLE
[QUESTION] I am keep getting this error!

### ISSUE THREAD

**Issue by Belbol** [nicehash/NiceHashQuickMiner#437]
![1](https://user-images.githubusercontent.com/82907070/115759505-fe3a5100-a3a8-11eb-89e4-f9e3c88b6d5b.PNG)
my QuickMiner is starting without problem, and after mining for several minutes, i am getting this error.
I tried to reinstall, and to clear OC settings but i am still getting the same error, and i started to get it only recently after the last update.

**Comment by Sentrozom** [comment]
Yeah, same error here...

**Comment by ZORO735** [comment]
i have this error too try to change ur server location and change ur optimizer to lite and try again my cmd now working fine but lets see if will stay working fine im testing it

**Comment by ZORO735** [comment]
> ![1](https://user-images.githubusercontent.com/82907070/115759505-fe3a5100-a3a8-11eb-89e4-f9e3c88b6d5b.PNG)
> my QuickMiner is starting without problem, and after mining for several minutes, i am getting this error.
> I tried to reinstall, and to clear OC settings but i am still getting the same error, and i started to get it only recently after the last update.

well the problem solved for me just change ur server location from QM to setting and edit config and set the closest location for u , you can check it from here how to change it https://github.com/nicehash/NiceHashQuickMiner/wiki/Tips-&-tricks

**Comment by nicehashdev** [comment]
Duplicate: https://github.com/nicehash/NiceHashQuickMiner/issues/433

**Comment by Belbol** [comment]
Thanks ZORO735 and nicehashdev for the solution.

**Comment by ZORO735** [comment]
> Thanks ZORO735 and nicehashdev for the solution.

you welcome dude ^_^
