### ISSUE TITLE
OCtune loses some of its settings after some time - RC 0.3.0.7

### ISSUE THREAD

**Issue by GabeBars** [nicehash/NiceHashQuickMiner#44]
I'm using auto OCtune to let my 3090 run 120MH/s without reaching 100C in tjunction and at 290W of power. Went to sleep. When I came back in the morning it was back at 380W of power and tjunction hitting 100C. Sometimes it loses the fan settings too and sets back to auto.
Just my 2 cents. Loving QuickMiner so far! Good work, guys!

edit: spelling

**Comment by Disparatado** [comment]
I confirm just now, my memory clock reset to 6800, it was about 8h of all together runtime of excavator, and about 10 minutes after last tweak of core clock (apply alt oc)

**Comment by nicehashdev** [comment]
Can you check if there was a crash of Excavator in the meantime?
Enable [logging](https://github.com/nicehash/NiceHashQuickMiner/wiki/Tips-&-tricks#4-enable-logging-for-better-troubleshooting) to determine that.

**Comment by nicehashdev** [comment]
Consider not relevant anymore. Closing.

**Comment by isral** [comment]
I encounter similar problem.
I set core clock to 1230, but randomly become 1245.
Despite the difference is only 15, but the temperature raise and fan become noisy.

v0.5.1.3
GTX 1660
Windows 10 64 bit.
