### ISSUE TITLE
[BUG] Speed degrades to 0 h/s on new QuickMiner (0.5.1.3)

### ISSUE THREAD

**Issue by MrBarley** [nicehash/NiceHashQuickMiner#440]
**Describe the bug**
I'll run QM (0.5.1.3) on any optimized tune (Lite or Medium - I use Medium mainly), and after 1-60 minutes it just floats down to 0 h/s then the program itself hangs on http | Closing. I have to request it to close it in app to get it to close/restart. I have added a whitelist to the programs themselves and the folders in my AV program (Windows Defender) but this hasn't fixed the problem. I also tried installing to a new folder, and whitelisting that folder/exe's, but no change.

I've also tried random fixes like adding the programs as exceptions to the Windows Firewall, checking my connectors on the GPU, changing the location in conf, trying out diff OC profiles, comparing checksums on the installer, trying standalone w/o the installer, etc. I've noticed a few others reporting this issue with no fix in sight on the NiceHash Discord as well.

When looking at GPU-Z, the moment everything starts to slow down to 0 h/s, all the power related sensors show power getting halved. Limited to 100W, Memory Controller load goes to 0, etc. Weird part is it is still drawing 100W at 0 h/s. Once the program hits http | Closing, GPU-Z reports PerfCap reason being VRel and something VOp as well.

**To Reproduce**
Run the program, after 1-60 mins, it'll suddenly limit power to the card and h/s drops to 0. These issues don't occur on 0.4.5.5.

**Screenshots**
[Excavator + GPU-Z](https://i.imgur.com/hqYpVl8.png)
[Whitelisted Files + Folders](https://i.imgur.com/opU4sK7.png)
[nVidia Drivers](https://i.imgur.com/bdu9tLO.png)

**Version affected (please complete the following information):**
 - 0.5.1.3
 - RC

**NVIDIA driver version**
466.11 - Standard (verified working in GPU-Z)

**Hardware**
3080 TUF OC, in PCI-E port.
2700X Ryzen.

**Logs**
[exported_logs.zip](https://github.com/nicehash/NiceHashQuickMiner/files/6361446/exported_logs.zip)

**Additional context**
I do have Afterburner on the PC, but I've always had it running stock tune before closing it. No difference here, I've even gone as far as to completely disable it, but no change in behaviour. This is my personal PC, so I game/work on it during the day, and mine over night.

**Comment by nicehashdev** [comment]
According to your provided screenshot of GPUZ, it is clearly visible that your GPU utilization is at 100% when excavator is being closed (hence, doesnt perform any load). Looks like some software takes priority over Excavator, which causes it to drop hashrate to 0. Default error handling mechanism kicks in then which restarts Excavator.

You will have to analyze your system and figure out which 3rd app is consuming all of your GPU processing power. Once you figure that out and remove/disable it, your problem will be fixed.
