### ISSUE TITLE
temperature 

### ISSUE THREAD

**Issue by neo-jubil** [nicehash/NiceHashQuickMiner#441]
Hello, I make optimization easy or effective immediately the temperature creeps and the fans are standing or spinning very slowly what can I do so that I can install the vrescheniye of the fans myself?

**Comment by nicehashdev** [comment]
OPTIMIZE profiles have predefined fan behavior. You can modify them using one of the following methods: https://www.nicehash.com/blog/post/modify-existing-optimization-profiles

**Comment by neo-jubil** [comment]
> Профили ОПТИМИЗАЦИИ имеют предопределенное поведение вентилятора. Вы можете изменить их одним из следующих способов: https://www.nicehash.com/blog/post/modify-existing-optimization-profiles

I need to be able to adjust the fans when I put a light, efficient fan speed drops and the temperature rises

**Comment by nicehashdev** [comment]
Yes, you can always modify settings in OCTune manually and set it to your preferences.
