### ISSUE TITLE
[FEATURE] Disable OC optimizations completely as in app setting

### ISSUE THREAD

**Issue by Intoxicus** [nicehash/NiceHashQuickMiner#445]
**Is your feature request related to a problem? Please describe.**
NHQM keeps resetting it being set to manual. I don't want or need OC optimizations in the first place.

**Describe the solution you'd like**
A setting to completely disable OC optimizations that is more effective than setting it to manual

**Describe alternatives you've considered**
Setting it to manual is not always effective. 

**Additional context**
Not everyone wants or needs the OC optimizations. Some people like me have hybrid kits and other cooling arrangements that are not accounted for in these optimizations. Some people like to DIY regardless.
To a non power user it is an appealing feature. 
As a power user I would prefer to be able to completely disable it so it can't automatically change my settings and cause crashes.

**Comment by nicehashdev** [comment]
Manual setting will not interfere with any OC setting with the exception of changing memory OC to 0 during DAG generation. If you wish to disable this feature as well, then pass the -g parameter to the excavator launch command line. If using higher memory OC, this is not recommended to do as will surely generate invalid DAG. Miner then tries to generate it again and keep trying until successful.
