### ISSUE TITLE
Device #0-0 coul not obtain power consumption!

### ISSUE THREAD

**Issue by PEDemers** [nicehash/NiceHashQuickMiner#45]
[log_E.txt](https://github.com/nicehash/NiceHashQuickMiner/files/5992110/log_E.txt)
![Nice_Err3_E](https://user-images.githubusercontent.com/49821959/108132816-80dd2200-7081-11eb-894f-c420a22ee022.jpg)
I redid the installation of the DRIVER Nvidia 461.51 and downloaded the NiceQuickMiner 0.3.7_RC and Octune_v0.3.0.7_RC_fix1
I still see Device # 0-0 Could not Obtain power consumption!
Device # 1-1 Could not Obtain power consumption!
Device # 2-2 Could not Obtain power consumption!
Device # 3-3 Could not Obtain power consumption!

**Comment by nicehashdev** [comment]
1. Download new NVIDIA drivers but do not install them yet.
2. Disconnect your internet.
3. Uninstall your NVIDIA drivers (clean) using a tool such as [DDU](https://www.guru3d.com/files-details/display-driver-uninstaller-download.html)
4. Install NVIDIA drivers from point 1.
5. Now everything should work fine.

**Comment by chrisngrod** [comment]
@nicehashdev 

Uninstalled without reboot and uninstalled with reboot.  Still coming up with the same notice.

Tried running 3.0.7 and 3.1.0 (Excavator 1.6.2e).  3080 mobile GPU.

**Comment by PEDemers** [comment]
I deleted NiceHash_3.0.5.6 and NiceHash_QuicMiner 0.3.1.0RC
I redid the installation of NiceHash_3.0.5.6 and NiceHash_QuicMiner 0.3.1.0RC
Do not forget I deactivate the security of windows and exclude the folders where each program is installed
![Nice_Err3_E](https://user-images.githubusercontent.com/49821959/108236312-c26add00-7114-11eb-9445-cf9a8aaa4da6.jpg)

**Comment by PEDemers** [comment]
I deleted NiceHash_3.0.5.6 and NiceHash_QuicMiner 0.3.1.0RC
I redid the installation of NiceHash_3.0.5.6 and NiceHash_QuicMiner 0.3.1.0RC
Do not forget I deactivate the security of windows and exclude the folders where each program is installed
![Err_Bon_E](https://user-images.githubusercontent.com/49821959/108239648-1cb96d00-7118-11eb-91c2-020281ea980d.jpg)
