### ISSUE TITLE
[FEATURE] Auto Update

### ISSUE THREAD

**Issue by amore514** [nicehash/NiceHashQuickMiner#450]
Can you add an auto-update option? maybe options to turn this on/off and if on pick stable or RC? maybe some kind of notification when an auto-update was applied? (Email, SMS, in-app)

**Comment by nicehashdev** [comment]
Auto update is available since version 0.3.0.0. You can also choose between STABLE and RC. Check wiki for more info.

**Comment by amore514** [comment]
I guess it does push an auto-update but it's not "Auto-Updating" I have to click a button to run the update. Is there a way to have to update without having to click a button?
