### ISSUE TITLE
[QUESTION] Service Locations don’t change 

### ISSUE THREAD

**Issue by superman1203** [nicehash/NiceHashQuickMiner#453]
**Has the question been answered in [Wiki](https://github.com/nicehash/NiceHashQuickMiner/wiki)? There is no such question in [FAQ](https://github.com/nicehash/NiceHashQuickMiner/wiki/FAQ) or [Troubleshooting collection](https://github.com/nicehash/NiceHashQuickMiner/wiki/Troubleshooting)?**
N

**Your question is...**
What is...
When I edit my nhqm file to change to USA west server, the changes do not save.  Even though I have the service location set to -1 for USA-west it just connect to USA-east. Am I doing something wrong?

**Comment by Donkeykong307** [comment]
"-1" isn't USA-west, it's automatic selection. I think you want "1" as your service location.

If you check out the  [Tips and Tricks](https://github.com/nicehash/NiceHashQuickMiner/wiki/Tips-&-tricks#2-choose-your-service-location-to-improve-your-latency-and-reduce-number-of-stale-shares) you can see the service locations.

**Comment by superman1203** [comment]
Yes your right. I misunderstood. Thank you for your help.
