### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by ckng2000** [nicehash/NiceHashQuickMiner#454]
I have three 3060/3070 laptop running Quick miner and all three doesn’t have to optimization button to press. The button part is completely blank. Please advice 
![68184A4D-D407-4C21-9692-45F292DC8E47](https://user-images.githubusercontent.com/19760140/115987048-029f7d80-a5e6-11eb-9992-0ead7503ed27.jpeg)
![8BAE7050-79E2-4103-B01C-F3AE9044CCB1](https://user-images.githubusercontent.com/19760140/115987063-14812080-a5e6-11eb-88c8-dddcf3fd778d.jpeg)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version affected (please complete the following information):**
 - Version number [e.g. 0.4.5.5]
 - RC or STABLE?

**NVIDIA driver version**
Which one do you use?

**Hardware**
Describe GPUs used and how are GPUs connected to the motherboard.
CPU?

**Logs**
Activate logging first, then record event - bug - then export logs into a .zip file and attach it when submitting this issue.

**Additional context**

**Comment by nicehashdev** [comment]
Laptop devices are officially not supported. You will have to manually tune them using OCTune.
