### ISSUE TITLE
NHQM Crashing on 5.1.3 due to optimizations being applied when set to manual[BUG] 

### ISSUE THREAD

**Issue by Intoxicus** [nicehash/NiceHashQuickMiner#455]
**Describe the bug**
It seems to want to apply optimizations even though I want it set to manual.

**To Reproduce**
Unsure

**Expected behavior**
It will apply an optimization silently and cause crashes

**Screenshots**

**Version affected (please complete the following information):**
5.1.3 srable

**NVIDIA driver version**
Which one do you use?

**Hardware**
Describe GPUs used and how are GPUs connected to the motherboard.
CPU?

**Logs**
Activate logging first, then record event - bug - then export logs into a .zip file and attach it when submitting this issue.

**Additional context**
I can see when it happens because suddenly my hashrate gets a lot lower.
From 95-100+ to 85ish means it applied an optimization I don't want
Allow an option to completely disable optimizations please.

**Comment by Intoxicus** [comment]
I downgraded to 4.5.5 with excavator 1.6.11g because it's constantly crashing because of what appears to be an issue with the optimizations being forced or something.

All I can say for sure is I can tell it's sometime trying to apply an optimization and ignoring the manual setting.

If we could completely disable OC Optimizations(not everyone wants or needs them and for some they're a problem) then this would not be an issue at all.

**Comment by nicehashdev** [comment]
You will have to provide much more information for me to consider this relevant bug (hardware, software, driver version etc). These questions are there in the form for a reason. Without them, I consider this bug report invalid. Once you have all relevant information available, open a new bug report.
