### ISSUE TITLE
[OPTIMIZATION] 1080 GTX Optimization Profiles

### ISSUE THREAD

**Issue by Cloudguy29** [nicehash/NiceHashQuickMiner#456]
**Are you aware of the latest [Optimization data](https://github.com/nicehash/NiceHashQuickMiner/tree/main/optimize) being used?**
Yes

**I am suggesting new optimization or modification of existing optimization?**
Modification

**For GPU:** NVIDIA GeForce 1080 GTX
**Optimization name:** Lite/Medium/High/Efficient
**Special VRAM & Manufacturer:** No

**My suggested optimization data is following:**
I'm using a 1080 GTX and for the past several months, I've been able to achieve 37+ hash rates with Trex miner using Nicehash Miner, EthLargementPill and MSI Afterburner with:

+165 Core
+850 Memory
79% Power Limit (about 155 watts)

A big reason I avoided using QM for the 1080 was due to the lower hash rate than NH Miner and manual overclock.

I have since moved my graphics card from out of case to inside of case and am trying to find an optimization profile that won't cause temps to go too high but still manage higher hash rates (Inside case temps are 67+ degrees vs. outside of case was 59).  With NH Miner, I've been able to manage 34-35 hash rates at 140 watts inside the case but the temps are still a little higher than I'd like.

I downloaded QM and reviewed the Efficient Settings and am getting about 32.2 hash rate with 120 watts (I tried "High" and this also resulted in 32.x hash rate). I was curious if there's anyway to tweak the settings a bit more since I'd love to see "Efficient" get closer to 34 hash rate and "High" profile perhaps to 35+?

**Comment by nicehashdev** [comment]
Every chip is different. What may work good for you, will not work for someone else. With optimization profiles, we tried to support wide array of devices. This means that gaining maximum out of your device, you **have** to perform manual tuning.

**Comment by TimSirmovics** [comment]
I also have the same outcome. Efficient is 32.x., and High is the same but uses more power.
Is the High profile supposed to achieve a higher hash rate than Efficient?
