### ISSUE TITLE
Dockerizing QuickMiner

### ISSUE THREAD

**Issue by RascoApps** [nicehash/NiceHashQuickMiner#458]
**Has the question been answered in [Wiki](https://github.com/nicehash/NiceHashQuickMiner/wiki)? There is no such question in [FAQ](https://github.com/nicehash/NiceHashQuickMiner/wiki/FAQ) or [Troubleshooting collection](https://github.com/nicehash/NiceHashQuickMiner/wiki/Troubleshooting)?**
[similar question](https://github.com/nicehash/NiceHashQuickMiner/wiki/Virtual-Mining#linux--quickminer)
**Your question is...**
Have you considered Dockerizing QuickMiner onto a windows image? it might help with the AV scans.

**Comment by nicehashdev** [comment]
Yes, but the problem is we cannot distribute this - Windows license issue.

We will however provide instructions - some we already had here: https://github.com/nicehash/NiceHashQuickMiner/wiki/Virtual-Mining#linux--quickminer
