### ISSUE TITLE
120GB ssd gets filled up when running quickminer

### ISSUE THREAD

**Issue by denvelt** [nicehash/NiceHashQuickMiner#460]
**Has the question been answered in [Wiki](https://github.com/nicehash/NiceHashQuickMiner/wiki)? There is no such question in [FAQ](https://github.com/nicehash/NiceHashQuickMiner/wiki/FAQ) or [Troubleshooting collection](https://github.com/nicehash/NiceHashQuickMiner/wiki/Troubleshooting)?**
Yes/No.

**Your question is...**
What is...

When running nicehash quickminer my 120gb ssd runs our of space and and the rig does not show up on rig manager.

Is there a fix for this?

**Comment by nicehashdev** [comment]
Which version are you running? Make sure to install latest version which limits log file size so logs cannot fill harddrive space.

Other than that, disk space filling up sounds like unrelated issue to NHQM.

Regarding Rig Manager; make sure there is no AV interfering, blocking, deleting any NHQM files.
