### ISSUE TITLE
[QUESTION] Max Core Voltage on 1660 Super in OCTune

### ISSUE THREAD

**Issue by Cloudguy29** [nicehash/NiceHashQuickMiner#461]
**Has the question been answered in [Wiki](https://github.com/nicehash/NiceHashQuickMiner/wiki)? There is no such question in [FAQ](https://github.com/nicehash/NiceHashQuickMiner/wiki/FAQ) or [Troubleshooting collection](https://github.com/nicehash/NiceHashQuickMiner/wiki/Troubleshooting)?** No

**Your question is...**
Looking at OCTune, I see that the GeForce GTX 1660 Super has an MCV of 625 mV but the "Core Volt" that is showing is 643.
This is using the Optimize Profile of "Efficient."

Is this supposed to be the case? Wouldn't having a higher Core Volt showing than MCV be bad or am I misunderstanding? Could you explain how this works? Also, I noticed that if you increase the Core Voltage that the hash rate DECREASES? How does that work?

![mcv1660](https://user-images.githubusercontent.com/83173599/116110703-8bb4c400-a67b-11eb-87c8-84577d3691de.PNG)

**Comment by nicehashdev** [comment]
0.643 V is max Voltage of your GPU. It cannot go lower than that.

**Comment by Cloudguy29** [comment]
Then why is the profile mcv than the output???
