### ISSUE TITLE
NHQM crashes on Optimization "HIGH" for GeForce GTX 1660 Ti Gallardo from MANLI [BUG] 

### ISSUE THREAD

**Issue by NormanZ3** [nicehash/NiceHashQuickMiner#462]
**Describe the bug**

NHQM crashes ( screen freezes, W10 Blue Screen appears, reboot takes place )
**To Reproduce**

Just switch on Optimzation "HIGH" for MANLI GeForce GTX 1660 Ti.

**Expected behavior**

**Screenshots**

The only screenshot i can add is this one from the "Excavator OC Tune". For all my 1660 Ti's the "HIGH" Optimization works and also the manufacturers are properly identified. As you can see i have MSI, ASUS and Gigabyte. The one from MANLI is recognized as "NVIDIA".

![image](https://user-images.githubusercontent.com/83120339/116162615-73ce5600-a6f6-11eb-8903-93b6fad70c0b.png)

**Version affected (please complete the following information):**
 - Version number 0.5.1.3
 - STABLE

**NVIDIA driver version**

Version: | 466.11  WHQL
-- | --
Release Date: | 2021.4.14
Operating System: | Windows 10 64-bit
Language: | English (US)

**Hardware**
Connected via Riser to ASROCK H110 PRO BTC
GPU: MANLI Geforce GTX 1660 Ti

**Logs**
I might need so instructions on how to provide these logs, my logs are empty and i am not sure if i want to enable logging again and crash my RIG on purpose.

I got 2 of these MANLI GPU´s 8 days ago, one already died ( nolonger visible in the mainboard - slot empty it says) However i can not prove it is related to NHQM, but i have not activated the "MSI Interrupts" function again - i had serious issues with that, i couldn´t get my rig to work.

Regarding the potentially broken Manli GPU, it was brand new and i still hope to get it replaced.

I wanted to mention that as others may have similar experience.

BTW: Lite and Medium will not make the RIG/WIN10 crash.

**Comment by nicehashdev** [comment]
Not ever card is guaranteed to be able to run perfectly stable on any profile. This is mentioned in several places. If this was possible then producer would make GPUs with higher speed already.

**Comment by NormanZ3** [comment]
Thanks for your feedback, i asume i will not be able to reach 30+ MH/s with
that manufacturer then. Will this be also the reason why MSI Interrupts
lead to problems ?

BR

Norman


Am Di., 27. Apr. 2021 um 10:43 Uhr schrieb djeZo ***@***.***>:
