### ISSUE TITLE
nhmp-ssl | connect:  10060

### ISSUE THREAD

**Issue by hdchieh** [nicehash/NiceHashQuickMiner#463]
nhmp-ssl | connect:  10060

10060 - no response

sometimes connected, but it frequently occurs.
I tried to change dns, modify hosts... didn't work.

**Comment by hdchieh** [comment]
Although the NiceHash Miner can immediately connect to the pool.

**Comment by nicehashdev** [comment]
Check your security software, hardware, routers, firewalls, modems etc.. something is blocking your connection.
