### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by dj-fiorex** [nicehash/NiceHashQuickMiner#466]
**Describe the bug**
When i select "Efficient" or "High" profile with NiceHash QuickMiner and a Gainward GTX1080 Phoenix 8Gb,  Excavator crashes with illegal instruction error

**To Reproduce**
1. Select Efficient or High in NiceHash Web Interface
2. Excavator set new profile
3. See error
4. Crash and restart

**Expected behavior**
I can select "Efficient" or "High" on my Gainward GTX1080 Phoenix like i do in another computer with same spec but a GTX1080 made by Gigabyte (GTX1080 Mini)

**Version affected (please complete the following information):**
 - 0.5.1.3 STABLE

**NVIDIA driver version**
466.11

**Hardware**
Gainward GTX1080 Phoenix 8GB and i5-6700K

**Logs**
[logs.zip](https://github.com/nicehash/NiceHashQuickMiner/files/6387370/logs.zip)

**Comment by nicehashdev** [comment]
Not every optimization profile is guaranteed to work for every GPU. You need to have a good chip to be able to run High optimization. Same goes for Efficient thus Efficient Low was created for cards that cannot handle Efficient.
