### ISSUE TITLE
Temperature reading wrong

### ISSUE THREAD

**Issue by grazianognoll** [nicehash/NiceHashQuickMiner#47]
Hardware:
- 750W PSU
- Asus H470-Pro motherboard
- Intel pentium gold G6400
- 8GB ram
- KFA2 Geforce RTX 3090

Issue:
By using NiceHashQuickMiner, the temperature reading is wrong.

![image](https://user-images.githubusercontent.com/13349492/108268188-1650e280-7164-11eb-831c-d26c323b1dfa.png)

**Comment by grazianognoll** [comment]
I think it's some kind of scaling issue:
![image](https://user-images.githubusercontent.com/13349492/108268312-3a142880-7164-11eb-9d70-46b90add2de3.png)

I'm using the pre-release version v0.3.1.0

**Comment by grazianognoll** [comment]
On the OCTune interface the temperature reading is correct:
![image](https://user-images.githubusercontent.com/13349492/108269606-22d63a80-7166-11eb-9d3e-0133542764ff.png)

**Comment by nicehashdev** [comment]
It will be fixed soon on frontend - both GPU and VRAM temps will be displayed.

**Comment by nicehashdev** [comment]
Fixed.
