### ISSUE TITLE
[BUG] RTX 3060Ti getting 55mh/s rather than 60 mh/s

### ISSUE THREAD

**Issue by Harizia** [nicehash/NiceHashQuickMiner#470]
**Describe the bug**
Im having a difficult on having average 60mh/s for my RTX 3060Ti. 
The new v0.5.1.3 im having now making 55mh/s on average and 45mh/s when i only open discord.

![image](https://user-images.githubusercontent.com/83355959/116421372-5a054e00-a871-11eb-8e83-0b5a8b10ac66.png)

![Screenshot_22](https://user-images.githubusercontent.com/83355959/116421500-799c7680-a871-11eb-84a2-9720aeaac0b3.png)
![Screenshot_21](https://user-images.githubusercontent.com/83355959/116421508-7acda380-a871-11eb-93bf-a36ea0c8373c.png)

**Comment by nicehashdev** [comment]
Please, read here: https://github.com/nicehash/NiceHashQuickMiner/wiki/FAQ#faq07
