### ISSUE TITLE
OCTune restarts to default values

### ISSUE THREAD

**Issue by KAOS191** [nicehash/NiceHashQuickMiner#472]
I have three PCs doing the same thing (MSI SUPRIM 3080). After I set everything and click "save..." in OCTune, let it run for few hours and then when I connect with remote desktop tool to check if everything is smooth and open OCTune again it changes Memory Overclock to factory default (9251MHz) and fans goes to 30% (rise automatically back to 70-tish again in steps during 40 seconds due to instant accumulating heat). Other values like core clock and custom fan settings stays the way I set them. The issue happens in the moment when I log on to machine. Commans.json stays the way I saved it before.
Also it would be nice if OCTune gave us more settings in commands file. Like - with the new feature reducing core clock (which is not helpful - I need to reduce memory clock too), to change it back to original state when the temp gets better (day and night differences).
Or at least possibility to turn off OCTune completely...
I am adding full log file of described event.
[exported_logs.zip](https://github.com/nicehash/NiceHashQuickMiner/files/6394585/exported_logs.zip)

**Comment by nicehashdev** [comment]
Can you check if the problem is there if you use another remote managing tool such as TeamViewer?

**Comment by KAOS191** [comment]
> 
> 
> Can you check if the problem is there if you use another remote managing tool such as TeamViewer?

I am using Remote Desktop from Windows store, others like TeamViewer demands to have display connected which I do have not. I should add that other machines which have EVGA cards do not have the same issue, otherwise they are the same configuration (HW and SW like).

**Comment by KAOS191** [comment]
I have connected monitor to test it with TeamViewer and results are the same. I thought Dragon Center from MSI could cause this, but it does not apply the settings for GPU which is set there and behaves the same when Dragon Center is disabled. The value for memory clock is 9251Mhz which is suspicious for me too, but I guess that is factory settings OCed to 9501 by MSI.

**Comment by ilc72** [comment]
I also have the same problem with my 3090 FE card, each reboot requires me to go into OCtune and reset the values. Each time I save the values but it just keeps happening.

**Comment by nicehashdev** [comment]
> I also have the same problem with my 3090 FE card, each reboot requires me to go into OCtune and reset the values. Each time I save the values but it just keeps happening.

This is not the same problem; your problem happens after reboot. Please, open your own issue instead of hijacking other issues.

**Comment by nicehashdev** [comment]
3080 is normal to have memory at 9251 when doing CUDA (mining) work by default. Please, try everything with Dragon Center disabled. It is clearly possible that this peace of SW resets your OC when remote connection is established.

**Comment by KAOS191** [comment]
You are most likely right with Dragon Center to blame, but it is some process which happens during windows loading - or in my case loging into the account. I will search for it, just to turn it off is not enough. Probably some service which controls other stuff like LEDs or CPU OC. I hoped that OCTune would be able to take over right after and put in the values which it has set in json.

**Comment by nicehashdev** [comment]
Okay, I will mark this as resolved then. You should contact maker of Dragon Center - they should not reset OC just because someone remotely logs in.
