### ISSUE TITLE
[FEATURE] Add a configuration or command line argument to bypass crash reset screen

### ISSUE THREAD

**Issue by RobLaw0304** [nicehash/NiceHashQuickMiner#473]
**Is your feature request related to a problem? Please describe.**
I wrote a script to kill my mining processes when certain users log in since they game and are not capable of shutting off and starting mining on their own.  When the script kills the process, nicehash quickminer sees this as a crash and refuses to start in the background upon their logout via the other script i wrote.  The start mining script works perfectly if i gracefully quit quickminer.

**Describe the solution you'd like**
There should be a command line argument or configuration item for "scripted mode" to allow for bypass of UI elements prior to start of mining.  It should also force mining to begin rather than relying on last state.  This allows normal users the flexibility to reset their optimizations when things go wrong but presents power users with options for keeping their rigs running for dual purposes.

**Describe alternatives you've considered**
Nicehash Miner contains code that allows mining to halt immediately when activity is detected. Ultimately this is what i'm trying to mimic, just by using login/logout events.

**Comment by nicehashdev** [comment]
Try to run it with `—count` command line param. You can also adjust seconds to 0 instead of 10 in config file.
