### ISSUE TITLE
[BUG] Invalid DAG generated

### ISSUE THREAD

**Issue by Rukkit** [nicehash/NiceHashQuickMiner#474]
**Describe the bug**
Invalid DAG generated show's up after starting to mine NiceHashQuickMiner

**To Reproduce**
Just happens in 20 seconds after starting to mine.

**Version affected (please complete the following information):**
 - Version number v0.5.1.3
 - RC or STABLE? Both

**NVIDIA driver version**
466.11

**Hardware**
Just one 2060 Super, and not using any overclocking software.

I've tried uninstalling driver with DDU and installing driver without DCH. Rebooting my PC. Uninstalling and reinstalling NHQM. Using OCTune to force defaults. Nothing has worked. Have waited for new NHQM versions to come out for about a month, and each one has not fixed the issue for me.  

[exported_logs.zip](https://github.com/nicehash/NiceHashQuickMiner/files/6396513/exported_logs.zip)

**Comment by nicehashdev** [comment]
So, it does not work for you, even if you use old versions like 0.4.5.5 or 0.4.1.3?

**Comment by Rukkit** [comment]
> So, it does not work for you, even if you use old versions like 0.4.5.5 or 0.4.1.3?
> 
> Also, try to add `-g` extra command line launch parameter to Excavator (which disables DAG verification mechanism), but my guess would be you getting all share above target rejects.
> 
> Can you test inserting this GPU into another PC and see if it works there?

I don't have another PC unfortunately. But will try the old versions you recommended and will report back shortly.

**Comment by Rukkit** [comment]
So I tried the older versions and had no luck. Both didn't work and would get the same error.

So I tried using the newest version and putting -g in command line launch parameter, would seem like it works for like 30 seconds and then just gives and error about "illegal access memory" something like that, hard to read it as it goes away quick and restarts miner.

**Comment by nicehashdev** [comment]
Unfortunately, you have that one-in-a-million issue with drivers that is hard to fix as it seems to be persistent even through DDU. When we get such case in a lab, we just reformat whole windows and solve the issue.

**Comment by nicehashdev** [comment]
Also, when you reinstalled NHQM - it must have been clean reinstall which also deleted dagcache folder. This folder keeps already generated dag cache files so CPU does not have to regenerate them again. If for some reason, a mistake is there, you will have issues until you delete dagcache and force miner to generated new dagcache.

**Comment by Rukkit** [comment]
Yeah I’ve deleted that folder multiple times before and no luck. I’ll do full windows 10 reset and see if that helps. Will report back to you to let you know if it works or not.

**Comment by Rukkit** [comment]
Ok so I reset my whole PC. And installed the standard drivers like recommended in nicehash article. And NHQM still is spitting out the same error. 

"vmem too high" and sometimes will say something like "illegal access to memory"

Not sure what else I can do. Do you think I should try a certain driver version? I've been using latest driver version. And this all started happening around the time that Phoenix miner was recommended to stop using.

**Comment by nicehashdev** [comment]
Did you configure enough virtual memory?

**Comment by nicehashdev** [comment]
invalid access to memory, virtual memory and invalid DAG are 3 different things.

**Comment by Rukkit** [comment]
I set virtual memory to 8000 MB since I only have one 2060 Super that I'm using to mine with. 

Most of the time I get the "invalid dag is vmem OC too high" and then sometimes (but not as common) I get "illegal access to memory" (something like that, like I said, it flashes very fast that I can't read it all).

So basically miner would restart like every 15-20 seconds and then when I do -g command, it actually started to mine for a couple mins finally, but then it failed. 

I attached the logs. I really hope this can get figured out. It's been about a month since I've been able to get this to work.

[exported_logs.zip](https://github.com/nicehash/NiceHashQuickMiner/files/6424606/exported_logs.zip)

**Comment by nicehashdev** [comment]
This all sounds like a broken memory then. If reinstall of drivers did not help and reinstallation of Windows… don’t know what else can you do. Do other mining sw work and games etc? Without any issue?

Matjaz Skorjanc

Founder
***@***.***

**Comment by nicehashdev** [comment]
This sounds like a broken memory issue then. Do you have issues with other miners or when you game? Any artifacts? You may also try to reduce memory clock to -500 or -1000 and use `-g` switch when launching excavator.

**Comment by nicehashdev** [comment]
Okay, I see what the problem may be. You are simply running our of video memory. Do you have integrated GPU or another GPU that you may use for rendering display? Alternatively, shut down as many unneeded apps as you can. I believe your GPU simply consumes all available memory and then this issue starts appearing.

**Comment by Rukkit** [comment]
> Okay, I see what the problem may be. You are simply running our of video memory. Do you have integrated GPU or another GPU that you may use for rendering display? Alternatively, shut down as many unneeded apps as you can. I believe your GPU simply consumes all available memory and then this issue starts appearing.

Looks like this may have solved it. I have an 10600K intel with onboard graphics, so I have my monitor on the onboard graphics now. It's been running for 8 mins, and no problems so far. I will report back with you after a day or so to let you know if this indeed has fix the issue.

**Comment by nicehashdev** [comment]
Great. Closing as fixed.

**Comment by Rukkit** [comment]
> Great. Closing as fixed.

Sad thing is, it worked for a whole day and a half, and then it went back to giving "is vmem OC too high"
