### ISSUE TITLE
[BUG] OCTune not working (v0.5.1.3 Stable)

### ISSUE THREAD

**Issue by remiteeple** [nicehash/NiceHashQuickMiner#478]
**Describe the bug**
Upon starting the QuickMiner and opening the OCTune panel, any modification to the GPU settings will fail, including a reset of said settings.  In short, there is currently no 1st-party (NiceHash) method for me to tune my GPU.  I have reinstalled my graphics drivers twice and completely reinstalled QuickMiner approximately 10 times with different configurations each time.  Additionally any NiceHash software is completely whitelisted by my AV.

**To Reproduce**
1. Start QuickMiner
2. Open OCTune
3. Attempt to change any GPU setting

**Expected behavior**
The expected behavior is for the settings of my GPU to be changed upon their change in the OCTune UI.

**Screenshots**
![image](https://user-images.githubusercontent.com/20644236/116616706-ffb8cb80-a90a-11eb-837d-b2aa4f09bb24.png)
(The image depicts me starting the OCTune UI and attempting to set my fans to their default/auto profile, then attempting to run the Autotune feature.)

**Version affected (please complete the following information):**
 - v0.5.1.3
 - STABLE

**NVIDIA driver version**
Game Ready Driver Version 466.11

**Hardware**
2080ti XC Ultra installed directly into PCI-E slot on Motherboard.

**Logs**
[exported_logs.zip](https://github.com/nicehash/NiceHashQuickMiner/files/6401608/exported_logs.zip)

**Additional context**
There was no distinct event that would have caused this.  OCTune was working fine for two weeks before this happened.

**Comment by nicehashdev** [comment]
How do you open OCTune? Make sure to open it through QuickMiner taskbar tray menu first time, so the authentication key is provided.

**Comment by remiteeple** [comment]
> How do you open OCTune? Make sure to open it through QuickMiner taskbar tray menu first time, so the authentication key is provided.

That is exactly what I do.

**Comment by nicehashdev** [comment]
The invalid auth token means that Excavator was started with different token that you are providing when executing commands. You need to be sure that you are always launching OCTune through taskbar and that when updating, you replaced all files in folder _octune_ with new ones. The problem must be on your side somewhere, because this works for everyone else, so really check out how Excavator is started (with which auth token) and which auth token your browser is provided when starting up OCTune (which is basically just opening website). It is also possible that you are using special web browser that doesnt handle written JS code the same way as Chrome and IE/Edge. In that case, try with different browser.

**Comment by remiteeple** [comment]
> The invalid auth token means that Excavator was started with different token that you are providing when executing commands. You need to be sure that you are always launching OCTune through taskbar and that when updating, you replaced all files in folder _octune_ with new ones. The problem must be on your side somewhere, because this works for everyone else, so really check out how Excavator is started (with which auth token) and which auth token your browser is provided when starting up OCTune (which is basically just opening website). It is also possible that you are using special web browser that doesnt handle written JS code the same way as Chrome and IE/Edge. In that case, try with different browser.

I start QuickMiner by default using the executable file.  I then right-click the icon in the task tray and open OCTune.  There is no special action I am taking to break the system.  I will install another brower and test with it but I have been using the latest version of Edge and it was working fine until a week ago.

**Comment by nicehashdev** [comment]
You can also set auth token to `""` in _nhqm.conf_ thus eliminating need for it which reduces your mining security a bit.
