### ISSUE TITLE
1080ti sets clock back to base after a while. HWInfo tells me Performance Limit - Utilization

### ISSUE THREAD

**Issue by lfsando** [nicehash/NiceHashQuickMiner#481]
I have a ROG Strix 1080ti OC.
After 30 minutes or so the GPU ignores the OC set by OCTune and drops back to 1569MHz which is the base clock for this card.

[HWInfo tells me that I'm having Performacing limitation due to Utilization. Which as far as I understand is that the GPU is not recognizing the miner as a heavy GPU user. And clocks it back down.

The only fix I know is to restart the computer or play a video in the background.

I have the latest RC version.

**Comment by nicehashdev** [comment]
Duplicate: https://github.com/nicehash/NiceHashQuickMiner/issues/477
