### ISSUE TITLE
[QUESTION] Min memory issue

### ISSUE THREAD

**Issue by Shadowsfury** [nicehash/NiceHashQuickMiner#483]
**Has the question been answered in [Wiki](https://github.com/nicehash/NiceHashQuickMiner/wiki)? There is no such question in [FAQ](https://github.com/nicehash/NiceHashQuickMiner/wiki/FAQ) or [Troubleshooting collection](https://github.com/nicehash/NiceHashQuickMiner/wiki/Troubleshooting)?**
No

**Your question is...**
In early versions of QM the OCTune could be used on lower memory settings - I forget how low though.

Since a few weeks ago the minimum memory clock is 8250.

That works for my 3080 (10400 speed) and my best silicon lottery 3070 (8300 speed). 

But 2 of my 3070s can't overclock very well and need something more like 8100 memory clock. Thus I now can no longer use OCTune to set these settings.

Why was the minimum memory speed brought up to 8250? Can it go back to something lower?

**Comment by nicehashdev** [comment]
Min memory value is defined according to memory type; for GDDR6X it is 8250. For GDDR6 it is 5800. Try to select your card in dropdownbox - this will also use new limits which should fix your issue.

Min limits are defined in _octune.js_ file.

**Comment by Shadowsfury** [comment]
Ohhh I see - thank you.

My 3080 is the first device and I only ever used the check boxes up the top.

I see now that if I change the dropdown boxes, the minimum speeds update.
