### ISSUE TITLE
[BUG] quickminer crashes repeatly every 10-20 min 

### ISSUE THREAD

**Issue by cmar433** [nicehash/NiceHashQuickMiner#485]
**Describe the bug**
i have setup "restart Nvidia driver" then Quickminer start again but after few minutes crashing again and again.

[excavator_log_2021-05-01_14-13-12.002.txt](https://github.com/nicehash/NiceHashQuickMiner/files/6409536/excavator_log_2021-05-01_14-13-12.002.txt)
[logs_nhqm.txt](https://github.com/nicehash/NiceHashQuickMiner/files/6409537/logs_nhqm.txt)
[_export_events.txt](https://github.com/nicehash/NiceHashQuickMiner/files/6409538/_export_events.txt)
[excavator_log_2021-05-01_14-11-53.001.txt](https://github.com/nicehash/NiceHashQuickMiner/files/6409539/excavator_log_2021-05-01_14-11-53.001.txt)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version affected (please complete the following information):**
 - Version number [e.g. 0.4.5.5]
 - RC or STABLE?

**NVIDIA driver version**
Which one do you use?

**Hardware**
Describe GPUs used and how are GPUs connected to the motherboard.
CPU?

**Logs**
Activate logging first, then record event - bug - then export logs into a .zip file and attach it when submitting this issue.

**Additional context**

**Comment by nicehashdev** [comment]
Change it to reboot PC. NVIDIA is not capable of restoring its drivers without full reboot unfortunately.
