### ISSUE TITLE
[BUG] Config is lost when updating with the prompt

### ISSUE THREAD

**Issue by Moustachauve** [nicehash/NiceHashQuickMiner#486]
When starting NH Quickminer and seeing the prompt asking if we want to update to the newest version, saying yes will reset the current config and will not make a backup of it, so all configs and overclocks are lost

**Comment by nicehashdev** [comment]
Please, check your AV. This must be issue with your AV deleting some NHQM files.

**Comment by Moustachauve** [comment]
@nicehashdev My antivirus (windows defender, default on windows 10) has the NHQM folder whitelisted. This was my first time updating using the prompt as I usually update manually by overwriting my files from the zip (and being careful not to override the command.json file)

**Comment by nicehashdev** [comment]
Unfortunately, due to bugs in Defender, this is not enough. You have to explicitly allow in Defender to let all NHQM files through.

**Comment by Moustachauve** [comment]
@nicehashdev like so?
![image](https://user-images.githubusercontent.com/2206577/117076723-dfbb4a80-ad04-11eb-8281-1f864e04da07.png)

If yes, then it was already done

**Comment by nicehashdev** [comment]
This is exclusion list which is usually not enough. You need to explicitly allow it when defender asks you for it. Read more here: https://github.com/nicehash/NiceHashQuickMiner/issues/204
