### ISSUE TITLE
[FR] More info on tray icon right click

### ISSUE THREAD

**Issue by berkctezc** [nicehash/NiceHashQuickMiner#487]
Addition to mining speed more detailed statics like power usage, temperatures would be useful for ones who prefer to set mining console disabled. It also decreases need to use third party tools like gpu-z. I am aware that you can access that kind of info in octune and nicehash rig manager but just for checking these statics it would be easier to just right click in tray icon. Also this feature could be customizable in options gui. Thanks for reading.

**Comment by nicehashdev** [comment]
There is some more info added in latest version. This is it for now. More data would just make everything too bulky, especially for people with more video cards.

Perhaps we will make OSD overlays in the future, will add that on TODO list.
