### ISSUE TITLE
[FEATURE] Change priority of excavator.exe

### ISSUE THREAD

**Issue by Nawor3565** [nicehash/NiceHashQuickMiner#488]
I run QuickMiner and a home media server on the same rig. I would like to be able to manually set the priority of excavator.exe, so that mining doesn't cause video streaming to stutter. However, it seems like excavator is always run with the "high" priority, and if I change it manually in Task Manager, it just reverts back to high whenever excavator is re-launched. Could you add, say, a line in the config file to modify excavator's default priority?
![Nicehash bad](https://user-images.githubusercontent.com/19783632/116819771-80600d80-ab3f-11eb-9db1-17b2356b4b7e.png)

**Comment by nicehashdev** [comment]
This is only CPU priority which does not affect GPU priority. Changing CPU priority to lower value will not improve performance of any GPU task but only increase chance for stale shares thus reduce your mining performance. I am not sure anything can be gained doing this. You need to convince me there is an actual result possible to expect doing this.

**Comment by Nawor3565** [comment]
Ah, I understand. I didn't realize that the priority only applied to the CPU and not GPU. In that case, since the xmrig process is already low priority by default, I guess nothing really needs to change.
