### ISSUE TITLE
Only 2 of 3 fans are being controlled by QuickMiner

### ISSUE THREAD

**Issue by blacklabel8829** [nicehash/NiceHashQuickMiner#489]
I have an EVGA RTX 3080 XC3 and QuickMiner, when using an optimized setting, is only changing the speed of fans 1 and 2. Fan 3 is not changing speeds alongside the other two fans.

![image](https://user-images.githubusercontent.com/30968995/116901896-7bb35c00-ac08-11eb-91d2-ebfc25f4d617.png)

OCTune only shows 2 fans as well:
![image](https://user-images.githubusercontent.com/30968995/116902055-b0bfae80-ac08-11eb-85ef-7bd3be2e6497.png)

**Comment by nicehashdev** [comment]
This has been reported already. Unfortunately, there is nothing I can do yet - we do not have this specific card to test the bug and Excavator is using NVAPI according to specs, adjusting speed on all fans being reported. Until we get our hands on one of these models, the situation unfortunately will not be improved.
