### ISSUE TITLE
Uninstalling NiceHash QuickMiner

### ISSUE THREAD

**Issue by ThunderBos** [nicehash/NiceHashQuickMiner#49]
I've installed this program... but wish to uninstall it. Please explain how do we do this ?

**Comment by nicehashdev** [comment]
Read here: https://github.com/nicehash/NiceHashQuickMiner/wiki/Installation#4-optional-remove-previous-version

**Comment by ThunderBos** [comment]
According to #4.... i'm to use "NiceHashQuickMiner.exe --uninstall --keepconfig"
In the zip file i downloaded "NiceHash_QuickMiner_v0.3.0.2.zip" does have an uninstall function ?

**Comment by nicehashdev** [comment]
No, it does not have install function either - it is just a zip package that you unzip to any location you want. Then everything is contained inside the folder where you unzipped + if you did autostart methods, these need to be removed as well. This is something automatically taken care of when you launch it with `--uninstall`.

**Comment by ThunderBos** [comment]
Sorry but how do i launch --uninstall
![Capture](https://user-images.githubusercontent.com/79244668/108318294-74dd9580-7224-11eb-9c94-f54a9fc93231.JPG)

**Comment by nicehashdev** [comment]
[uninstall.zip](https://github.com/nicehash/NiceHashQuickMiner/files/6001194/uninstall.zip)

Put this file into your NiceHash QuickMiner folder and launch it (double click).

**Comment by nicehashdev** [comment]
I assume this problem is solved. Closing.
