### ISSUE TITLE
[BUG] HW err only during dag-generator

### ISSUE THREAD

**Issue by Arvenies** [nicehash/NiceHashQuickMiner#490]
During cyclical dag-generator operations sometimes there are produces HW errors, and only during this phase. DAG generation during startup of excavator, quick-swap DAG and normal jobs don't generate HW errors. Because cyclical dag-generator doesn't happen that often and not every card on every dag-generator operation generate this error, it's not so easy to reproduce and observe. On average there is one HW err for about 1000-2000 HW ok.

**To Reproduce**
Just wait for cyclical dag-generator and hope it will occur.

**Expected behavior**
Just no error during this phase.

**Screenshots**
![obraz](https://user-images.githubusercontent.com/80607526/117063545-47818d80-ad25-11eb-8a85-e138a2b2b2b8.png)

**Version affected:**
Observed at current RC v0.5.1.4 RC with Excavator v1.7.1d, but probably the same was on v0.5.1.3. No such problem with older versions v0.4.x.x, but since v0.5.0.0 new RC versions were so often and I updated to every new RC version, it's hard to tell when exactly it was introduced.

**NVIDIA driver version**
466.11 standard

**Hardware**
Observed on my and my friend's 4 different rigs, 3 of them are just PC with one GPU (2x 3080, 1x 3090), the one from which the screenshot is rIg with 6 GPUs, running manual tuned MHz speed configuration for more than 2 months without earlier HW errors. Almost every GPU with this problem observed is different model and vendor, and waiting enough (2-3 days) HW errors are observed on every GPU this way.

**Logs**
Because of rare occurrence didn't started logging during this problem.

**Additional context**
Introduced in one of the last version, rigs where tuned this way that there were no HW errors at all even after 24h operation for weeks.

**Comment by nicehashdev** [comment]
Will take a look into this...

**Comment by Nunsferatus** [comment]
Having the same problem...

![image](https://user-images.githubusercontent.com/83787364/117359607-4b95e280-aec0-11eb-9352-b88e1987c9e2.png)

**Comment by Arvenies** [comment]
This is not the same problem. You have HW errors during normal jobs, not only during dag-generation, so most likely it is GPU stability or oc problem. In my case there are no HW errors during normal jobs, only few during or just after dag-generation.

**Comment by Nunsferatus** [comment]
Thanks

Nunsferatus

**Comment by Arvenies** [comment]
After updating QM to v0.5.1.6 and Excavator to v1.7.1h b890 I don't observe this problem any more.

**Comment by nicehashdev** [comment]
Okay good, problem fixed then.

**Comment by Br3ach** [comment]
Glad I found this. I have the same problem:

![image](https://user-images.githubusercontent.com/14320127/124384621-7b9c0f00-dcd2-11eb-98cb-e45a88475ff0.png)

3080 + 3090 HW error only when DAG regenerating, 477.11 (+MSI enabled), 0.5.2.0, Excavator 1.7.3b.
