### ISSUE TITLE
Every time I download it and open it after it is done, it says "No compatible hardware detected" and says restart computer. It still does not work when I restart it. What do I do? 

### ISSUE THREAD

**Issue by elijay847** [nicehash/NiceHashQuickMiner#491]
**Has the question been answered in [Wiki](https://github.com/nicehash/NiceHashQuickMiner/wiki)? There is no such question in [FAQ](https://github.com/nicehash/NiceHashQuickMiner/wiki/FAQ) or [Troubleshooting collection](https://github.com/nicehash/NiceHashQuickMiner/wiki/Troubleshooting)?**
Yes/No.

**Your question is...**
What is...

**Comment by nicehashdev** [comment]
What kind of hardware do you have? Please, check this list: https://github.com/nicehash/NiceHashQuickMiner/wiki/Supported-hardware
