### ISSUE TITLE
[QUESTION] How to change mining address?

### ISSUE THREAD

**Issue by ReecezZ** [nicehash/NiceHashQuickMiner#493]
**Has the question been answered in [Wiki](https://github.com/nicehash/NiceHashQuickMiner/wiki)? There is no such question in [FAQ](https://github.com/nicehash/NiceHashQuickMiner/wiki/FAQ) or [Troubleshooting collection](https://github.com/nicehash/NiceHashQuickMiner/wiki/Troubleshooting)?**
No.

**Your question is...**
So I entered my coinbase BTC address instead of my NiceHash address, so in the log it quits the program (it won't mine) because it says
[Info] nhmp | Failed to subscribe 
[Info] nhmp | Reason: Invalid BTC address. (26) 
[Info] nhmp | Disconnected

So how do I change my BTC address to the wallet in Nice Hash?

**Comment by nicehashdev** [comment]
The simplest way is to reinstall QuickMiner. You can also delete nhqm.conf file and then start QuickMiner - it will ask you for Mining address again.
