### ISSUE TITLE
[BUG] Nicehash v.0.5.1.6 RC's menu is kind of flickery

### ISSUE THREAD

**Issue by Xalaxis** [nicehash/NiceHashQuickMiner#495]
**Describe the bug**

The right click menu has started flickering recently. If I had to guess, it's trying to update it really fast and temporarily moving content around.

**To Reproduce**
Steps to reproduce the behaviour:

Open the right click menu. For extra flicker/jump hover over the Game Mode menu.

**Comment by Xalaxis** [comment]
https://user-images.githubusercontent.com/12937964/117304311-832b6d00-ae75-11eb-89f5-fd6fed08a7a4.mp4

**Comment by nicehashdev** [comment]
Will be fixed in next version.

**Comment by nicehashdev** [comment]
This is fixed in new upcoming version.
