### ISSUE TITLE
OCtune memory settings on RTX 2070 sometimes add 50mhz causing errors in the excavator

### ISSUE THREAD

**Issue by mrcrisp** [nicehash/NiceHashQuickMiner#498]
I'm running an RTX 2070 with core set at 1020mhz and memory 7600mhz which should total 1900mhz and sometimes it does overclock the memory to 1900mhz but the issue I am experiencing is sometimes when the excavator restarts the memory speed jumps 50mhz to 1950mhz and that produces errors. If I lower the memory overclock in OCtune to 7400mhz then the clocks return to 1900mhz but then sometimes it drops 50mhz and I end up at 1850mhz, losing performance.

I do not have any other overclocking software running at the time although I have MSI Afterburner installed. The memory speed can stay at the set speed for hours but then when the excavator restarts, sometimes it will drop 50mhz and sometimes it will add 50mhz.

I am also running a RTX 2060 alongside and that seems to be fine at the high optmised settings and will stay at 1950mhz no issues, its just the RTX 2070 that is either adding or removing 50mhz.

Any solution? Thanks.

**Comment by nicehashdev** [comment]
Please, try to see if this happens when you don't have MSI Afterburner running in parallel as it may interfere with clocks set by QuickMiner.

**Comment by nicehashdev** [comment]
Do you have `Force P2 state for CUDA` disabled by any chance? Then this would explain what you are observing. In that case you either have to enable it back or customize your own OC settings in OCTune.
