### ISSUE TITLE
nhmp Disconnected

### ISSUE THREAD

**Issue by nicezrz** [nicehash/NiceHashQuickMiner#5]
Hi Guys,

I have set up the software, but it always appears nhmp Disconnected.

![Capturex](https://user-images.githubusercontent.com/78979662/107809928-de980400-6d39-11eb-9874-124aa078f916.PNG)

**Comment by nicehashdev** [comment]
Please, describe what kind of software do you run on your PC? Is there some firewall/proxy you use? Some special antivirus protection? What happens when you switch that off?

**Comment by nicezrz** [comment]
The new mining software: NiceHash_QuickMiner_v0.3.0.2
I uninstall the antivirus protection software and turn off off the firewall and real-time virus & threat protection.
I think the problem is my ISP.
My server is the end of ".edu". 
Do you know how to solve this problem? Does VPN solve this problem? Or I should buy ATT or other network plans. 
Thank you very much!

**Comment by Lyes-SS** [comment]
this morning while checking the window of "Excavator" I found this error "nhmp | disconnected"
0 H/s
By checking on "https://www.nicehash.com/my/mining/stats"
I realized it was like that for over 9 hours, from 3:45 am until 12:59 pm.
I had to restart "NiceHash QuickMiner" to resume mining.

9 hours of electricity use and about  4$ in income were lost 😞 

Windows 10
Firewall & proxy disabled

**Comment by nicehashdev** [comment]
Disconnected means that someone has ordered miner to stop mining. Make sure nobody else has access to your miner.

Regarding your ISP issues, if NiceHash host is blocked, we cannot do anything about that. You can use VPN to solve the problem.

**Comment by nicezrz** [comment]
I use my personal PC for mining and nobody can access it. If someone accesses it, I can find it because I use it every day.

I tried to use VPN this afternoon but when I check 
nslookup nhmp-ssl.eu.nicehash.com
nslookup nhmp-ssl.usa.nicehash.com
in the command line. It still appears my school Server: ns.XXXXXX.edu

and time-out to connect to the server.

![Capture22](https://user-images.githubusercontent.com/78979662/107891281-856fd200-6eeb-11eb-909d-ca79e658b928.PNG)

**Comment by nicehashdev** [comment]
Yes, this means that your network blocks access to NiceHash domains. You need to use VPN.

**Comment by Lyes-SS** [comment]
This is what I thought to myself, "this is because of my ISP" but by checking my brother's miner who is next door and uses the traditional "Nicehash miner 3.0.5.6" he didn't get any problem.
look
![Capture](https://user-images.githubusercontent.com/43107219/107891481-32b00d80-6f1f-11eb-80e2-7366e43427e8.PNG)

We use the same ISP.

being a little programmer myself, I suggest you add a function that restarts the miner when it detects 0 h/s for more than 20 seconds or so,
because I just quit and relaunched the app to get everything back to normal. but unfortunately i can't do that when i'm sleeping lol.
it would be nice to automate all this :)

Thank you for having answered me and good luck to the whole team.

**Comment by nicezrz** [comment]
Thank you very much! 

I tried the second VPN and it works.

Thank you again!

![Capture111](https://user-images.githubusercontent.com/78979662/107893222-edc4b080-6ef7-11eb-80ef-ad6cab996a91.PNG)

**Comment by nicehashdev** [comment]
> This is what I thought to myself, "this is because of my ISP" but by checking my brother's miner who is next door and uses the traditional "Nicehash miner 3.0.5.6" he didn't get any problem.
> look
> ![Capture](https://user-images.githubusercontent.com/43107219/107891481-32b00d80-6f1f-11eb-80e2-7366e43427e8.PNG)
> 
> We use the same ISP.
> 
> being a little programmer myself, I suggest you add a function that restarts the miner when it detects 0 h/s for more than 20 seconds or so,
> because I just quit and relaunched the app to get everything back to normal. but unfortunately i can't do that when i'm sleeping lol.
> it would be nice to automate all this :)
> 
> Thank you for having answered me and good luck to the whole team.

This is already done, read here: https://github.com/nicehash/NiceHashQuickMiner/wiki/Tips-&-tricks#3-define-what-happens-when-something-goes-wrong

Also, suggest to open new ticket for problems that are not related to this one specifically. Closing this one soon.

**Comment by Lyes-SS** [comment]
Great, thank you very much :)

**Comment by AlejandroAbolafio14** [comment]
need help with this problem  
![image](https://github.com/nicehash/NiceHashQuickMiner/assets/127498914/3e89aa95-3ba7-4490-92e5-e98f29ab7ad3)

**Comment by GhostHermes** [comment]
> need help with this problem ![image](https://private-user-images.githubusercontent.com/127498914/292586220-3e89aa95-3ba7-4490-92e5-e98f29ab7ad3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzOTQ3NTksIm5iZiI6MTcwNDM5NDQ1OSwicGF0aCI6Ii8xMjc0OTg5MTQvMjkyNTg2MjIwLTNlODlhYTk1LTNiYTctNDQ5MC05MmU1LWU5OGYyOWFiN2FkMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNFQxODU0MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZmFkZTk5NmM1ODU5ZTMyODAzMmFmNmIyNTQ4MmYxODFiYmNjZmFhMDk4YTAxZjNlOTg2MTUzZDQ4MWZkZjE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GvTI7OkRLQr-gonWYIRUDrlvjboxsI4IQaA7f4i6acQ)

I am having basically the same issue on a fresh install on my gaming desktop. Gonna try the VPN workaround, as opening a firewall exception changed nothing.
