### ISSUE TITLE
Question regarding OC tuner

### ISSUE THREAD

**Issue by Disparatado** [nicehash/NiceHashQuickMiner#50]
Could you implement a function, to manually set time spent (or a slider with options, 1minute, 5 minute, etc.) on testing each core clock step? I think it skips to the next to fast, as I get better results with manually searching?
Or where to change the code so it would spend more time?
Keep up the good work man! Ask for a raise! ;)

**Comment by nicehashdev** [comment]
[octune_0.3.1.2_RC_impr_1.zip](https://github.com/nicehash/NiceHashQuickMiner/files/6000760/octune_0.3.1.2_RC_impr_1.zip)

Use this one (for 0.3.1.2 RC) and then you can change
```
const KT_WAIT_TIME = 2500;
const KT_ITERATIONS = 3;
```

Increasing these values will make it wait longer. I suggest you keep KT_WAIT_TIME in between 2000 and 5000 and increase iterations to whatever number you like.

**Comment by Disparatado** [comment]
Again, THANK YOU for the great work! you are a One Man Army :), damn how I hate coding :) never had the right teacher and patience in c++ during school

**Comment by nicehashdev** [comment]
Speed has no correlation with luck. If your OC is unstable, then you will get rejected shares with reason: share above target.

**Comment by Disparatado** [comment]
Thanks man! Just went trough, great read and answered most questions, there is one more I was wondering, as there was no mention in the readme, "maxDeviceSpeed" 300
what is it for?
I only get JOB NOT FOUND rejects, (from the read, i understand its due to being late and the share being clean, generating new ones) so it is safe to increase the clocks until share above target starts to appear?

I also wonder at night, which network adapter settings to tweak for better latency, this has boggling me for some time. 
It's ok not to answer, you already did more than you had to (and read all the bull dong we leave for you). If only I could help somehow with my free time...
