### ISSUE TITLE
[BUG]  Prerelease v0.5.1.6 RC crashing window

### ISSUE THREAD

**Issue by amore514** [nicehash/NiceHashQuickMiner#504]
Not sure this is going to go anywhere but I figured I would report it. Ever since upgrading to Prerelease v0.5.1.6 RC windows has been unstable. Windows keeps crashing. Maybe I could run for a few hours before crashing. 

I thought it was something else but I downloaded the last version of NHQM and now things are stable.. I am now sure the crashing was caused by this version.

**Comment by nicehashdev** [comment]
I will need some more info; what exactly is crashing? Excavator? NHQM? Log files?

**Comment by amore514** [comment]
> Same here, Windows crashes since v0.5.1.6 RC - before this version it was stable.

Glad I am not the only one. For sure moving back a version resolves the problem.

**Comment by nicehashdev** [comment]
Does 0.5.1.3 work fine?

Which version of NVIDIA drivers are you using? Is it DCH or non DCH?
Which GPUs do you use?

**Comment by amore514** [comment]
Yes, 0.5.1.3 is what I moved back to, and it's stable. 

**9 GPU total.** 
- GeForce RTX 3070
- GeForce RTX 2080 SUPER
- GeForce RTX 2070 SUPER (3)
- GeForce RTX 2070
- GeForce RTX 2060
- GeForce GTX 1080 Ti
- GeForce GTX 1080

I'll post the driver info when I get home.

**Comment by amore514** [comment]
I am using the Nvidia 27.21.14.6192 drivers.

**Comment by amore514** [comment]
I'm not sure if I am using DCH or non-DCH drivers? I'm not sure how to tell. Which one is preferred? should I upgrade the version also?

**Comment by nicehashdev** [comment]
Check your driver version with GPU-Z. It will be somewhere between 460 and 470. It will also tell you if it is DCH or not there.

**Comment by nicehashdev** [comment]
No response. Considering this issue as resolved.
