### ISSUE TITLE
QuickMiner fill all the space on C: when running.

### ISSUE THREAD

**Issue by cbugeja** [nicehash/NiceHashQuickMiner#505]
**Has the question been answered in [Wiki](https://github.com/nicehash/NiceHashQuickMiner/wiki)? There is no such question in [FAQ](https://github.com/nicehash/NiceHashQuickMiner/wiki/FAQ) or [Troubleshooting collection](https://github.com/nicehash/NiceHashQuickMiner/wiki/Troubleshooting)?**
No.

**Your question is...**
I have noticed that as soon as I launch NiceHash QuickMiner on to Windows 10, all of my C: drive gets filled up with only a handfull of MB left. As soon as I quit QuickMiner, C: breathes a sigh of relief and shows that there are quite a few GB free on it.

Has this behaviour been seen before? What's the way forward?

**Comment by nicehashdev** [comment]
Please, provide more information. What kind of hardware do you have. How much free space do you have? Which version do you see having this issue?

**Comment by cbugeja** [comment]
Windows 10 Pro v1909 running on an Intel i7 6700K CPU @ 4 GHz with 16 GB RAM and an NVIDIA GeForce 1060 graphics card with 6GB of memory. Drive C is the main drive, which is a Samsung evo 250 SSD.
Tried both with the latest stable release of QuickMiner and the latest Release Candidate. 

My quick work around was to limit the page size on C to just 900-1000MB and create a windows-managed page file on a much larger HDD. A better permanent solution would be GREATLY appreciated :)

**Comment by nicehashdev** [comment]
Unfortunately, it is by design Windows+NVIDIA that you need Virtual memory commited (either in physical RAM or virtual - pagefile on HD) same amount of memory as it is allocated on all GPUs. This means above 4 GB gets allocated. But it is interesting why yours get allocated on HDD immediately considering you have 16 GB of RAM. Unless your 16 GB of RAM is full always?
