### ISSUE TITLE
[FEATURE] make task icon 'light theme friendly'

### ISSUE THREAD

**Issue by Jurgen1980** [nicehash/NiceHashQuickMiner#508]
**Is your feature request related to a problem? Please describe.**
The icon is almost not visabel when light theme is enabled on the windows task bar

**Describe the solution you'd like**
Give the icon a fine black/dark border?

**Describe alternatives you've considered**

**Additional context**

**Comment by Dohtar1337** [comment]
Obsolete. Will not implement, resolved or will the issue is too old. Closing.
