### ISSUE TITLE
[BUG] Quickminer Excavator turning in shares but Rig Desktop reporting offline!

### ISSUE THREAD

**Issue by objecttothis** [nicehash/NiceHashQuickMiner#509]
**Describe the bug**
Quickminer Excavator turning in shares but Rig Desktop reporting offline!

**Screenshots**
![image](https://user-images.githubusercontent.com/17935339/117874857-947bdb80-b2b2-11eb-99e2-8bbf6ac835d7.png)

After about 2 hours the device came back online... so were my submitted shares being credited to me?  the rig manager itself appears pretty buggy ATM.  The exchange rate for BTC is listed at $0.00 and page loads are fairly unresponsive.

**Version affected (please complete the following information):**
 - Version number 0.5.1.6
 - RC or STABLE? RC

**NVIDIA driver version**
Which one do you use? 466.11 Standard

**Hardware**
Describe GPUs used and how are GPUs connected to the motherboard. Single 1080ti direct connected
CPU? 9900k not mining

**Logs**
Activate logging first, then record event - bug - then export logs into a .zip file and attach it when submitting this issue.

**Additional context**

**Comment by objecttothis** [comment]
Yeah the subreddit is blowing up right now.

**Comment by nicehashdev** [comment]
This was a backend issue which is already fixed. Nothing to do on QM side. Closing.
