### ISSUE TITLE
Hour freeze under windows 10

### ISSUE THREAD

**Issue by Zapnico** [nicehash/NiceHashQuickMiner#51]
Since i have install, the hour freeze some times in the task bar.
To resolve, i just touch the hour ( with the icon mous ) and it's good

**Comment by nicehashdev** [comment]
That cannot be related to NiceHash QuickMiner - it isn't operating with display of the hour ;)

**Comment by Zapnico** [comment]
I install NHQM on 2 computers with win10, same issue... I'm just say. 3.0.7 . it's not important for me. But fun. I miss 2 appointments ^^
Great product so. Easy, light with everything you need.
