### ISSUE TITLE
[QUESTION] OC setting impact on other application

### ISSUE THREAD

**Issue by musahi0128** [nicehash/NiceHashQuickMiner#510]
Hi,

I have been mining using RTX 3060 laptop (TDP: 70 Watt), tuning the OC and successfully run at steady ~38 MH/s and GPU temp below 60℃.

The setting is Core clock max=960 and Memory clock delta=1420.

This setting, will it also improve my experience if it used for gaming?

**Comment by nicehashdev** [comment]
No, usually, the mining optimization will lower your gaming performance due to limitations (needs low clock speed, not high).

**Comment by musahi0128** [comment]
Cool, thanks!!
