### ISSUE TITLE
Missing optmize button in the rig gestor dash

### ISSUE THREAD

**Issue by xztaizx** [nicehash/NiceHashQuickMiner#511]
Missing optmize button in the rig gestor dash

![image](https://user-images.githubusercontent.com/84061074/117921220-bf702a80-b2c6-11eb-9b07-b2b4c595c853.png)

**NVIDIA driver version**
Which one do you use?

**Hardware**
GTX 1660 TI
**Logs**
Activate logging first, then record event - bug - then export logs into a .zip file and attach it when submitting this issue.

**Additional context**

**Comment by nicehashdev** [comment]
Your GPU is Laptop version, which is officially not supported (yet). You will have to do manual tuning using OCTune.
