### ISSUE TITLE
Cant get second *new* GPU to be detected by my computer

### ISSUE THREAD

**Issue by nickdemart** [nicehash/NiceHashQuickMiner#513]
**Has the question been answered in [Wiki](https://github.com/nicehash/NiceHashQuickMiner/wiki)? There is no such question in [FAQ](https://github.com/nicehash/NiceHashQuickMiner/wiki/FAQ) or [Troubleshooting collection](https://github.com/nicehash/NiceHashQuickMiner/wiki/Troubleshooting)?**
Yes/No.

**Your question is...**
What is...
I have been running a 2070 super chip in my mining rig, I added a 3070 evga and put it in the spot that the original 2070 super was in, and relocated the 2070. My computer only detects the 3070 even tho my 2070 is powered and running. Any ideas on what to do to get my computer to detect the 2070? my PC is for gaming but i just started to mine on it. let me know if that can be part of the issue?

**Comment by nicehashdev** [comment]
Always install drivers after putting in new video card. In many cases, this solves the issue. Use latest non DCH version.

**Comment by nickdemart** [comment]
Im all up to date with my drivers

**Comment by nicehashdev** [comment]
If the card is not visible in Device Manager not even as some other device (unknown or anything), then you probably put it in a slot that is disable or PCIe lanes used by something else (for example, an M2 drive). You should consult your motherboard manuals for that.

**Comment by Futte-dk** [comment]
You might need to open your Windows - Controlpanel, and see if it is activade. " right click on it"

and  GPU-Z  is a fine to use.
