### ISSUE TITLE
Can i modify GPU usage?

### ISSUE THREAD

**Issue by PBTIE** [nicehash/NiceHashQuickMiner#514]
Hey, I use nicehash on my casual PC, so I wanted to reduce my GPU usage to 50% ~ 60%, to be able to play my games and not "kill" so much of my device's life, can anyone help me? How do I do this?
![GPU 100%](https://user-images.githubusercontent.com/84153511/118180514-ff412a00-b40c-11eb-965c-4c4939d759c0.png)

**Comment by nicehashdev** [comment]
Unfortunately, NVIDIA does not support this feature. CUDA workload has lower priority compared to 3D rendering by default, but I understand that this may not be enough.
