### ISSUE TITLE
[FEATURE] Reset Auto OC settings on Stop Mining, Reapply on Start Mining

### ISSUE THREAD

**Issue by arcane99** [nicehash/NiceHashQuickMiner#515]
**Is your feature request related to a problem? Please describe.**
I start and stop mining using the API and this works well to run other GPU bound tasks on computer. However I have noticed that stopping mining does not reset the auto OC settings applied and hence everything I run on the GPU afterwards runs very slowly. Manually resetting OC settings or turning on game mode solves issue but this is not viable as I need to be able to do this automatically.

**Describe the solution you'd like**
When mining is stopped through API all OC settings are set to GPU default/reset. When mining is started through API the OC settings are reapplied first. If not the default option, then an option should exist to enable this functionality. 

**Describe alternatives you've considered**
Not sure what to do. Going to play around with power setting available through API (not sure what this does though) or perhaps some other robotics type solution to turn game mode on/off automatically.

**Additional context**
In my case the auto OC on QuickMiner start sets max clock to 945 and memory clock to -400. I have a GTX3090.

**Comment by nicehashdev** [comment]
This is already done. Please take a look into Excavator API: https://github.com/nicehash/excavator/tree/master/api
Use events on mining start/stop in commands.json file to implement your specific overclocks when starting and stopping.

**Comment by arcane99** [comment]
Thanks nicehashdev for the quick response. 

In case anyone else finds this, this is what I configured in commands.json. Seems to replicate what nicehash does by default with the Lite OC profile on a GTX3090.

```
       , {
		"event": "on_quickminer.start",
		"commands": [
				{"id":1,"method":"device.set.oc_reset","params":["0"]},
				{"id":1,"method":"device.set.tdp.simple","params":["0","2"]},
				{"id":1,"method":"device.set.core_abs","params":["0","945"]},
				{"id":1,"method":"device.set.memory_delta","params":["0","-400"]},
				{"id":1,"method":"device.smartfan.set","params":["0","3","62","94"]}
			]
	}, {
		"event": "on_quickminer.stop",
		"commands": [
				{"id":1,"method":"device.smartfan.reset","params":["0"]},
				{"id":1,"method":"device.set.oc_reset","params":["0"]}
			]
	}
```
