### ISSUE TITLE
[BUG] Could you provide/disable HotSpotTemp sensor for Excavator

### ISSUE THREAD

**Issue by ftw3evga** [nicehash/NiceHashQuickMiner#516]
hash rate being degraded because of temperature. My card have already replaced the thermal pad and watercool. Core & Vram temp keep as 60C.

**Comment by nicehashdev** [comment]
I do not fully understand your question? HotSpot is always exposed when using Excavator API, it just isn't always displayed in OCTune (if there is no room).

**Comment by ftw3evga** [comment]
the excavator degrade my hash rate 

is it possible to disable/ unlock the temp limit. There is a detection error GPU temperature after Quick miner 0.5.1.x, the difference was 20C in Hwinfo and GPUZ sensor reading. 

I just have one 3080 with water cool, GPUZ and qucik miner 0.4.1.x show GPU VARM temp as ~60C but hot spot is 105C.

**Comment by nicehashdev** [comment]
Looks like you are using incompatible octune files. Please, when updating NHQM, make sure you replace all files.

**Comment by ftw3evga** [comment]
very helpful and professional. Thanks
