### ISSUE TITLE
3.1.2_RC - Cannot install as service

### ISSUE THREAD

**Issue by tlamming** [nicehash/NiceHashQuickMiner#52]
The new unstable version cannot be installed as windows 10 service. Is this by design?

![image](https://user-images.githubusercontent.com/9162505/108396779-3a083d00-71e5-11eb-8c87-29f002cfdb21.png)

**Comment by nicehashdev** [comment]
Yes, service method is going out, because Task scheduler method is better and there is no need for service method anymore.

**Comment by tlamming** [comment]
My main issue with this is for machines that do not log in automatically.
Does the task run if there is no interactive session running? Say, at the
login screen for a machine?

**Comment by nicehashdev** [comment]
Service mode would not run either; NiceHash QuickMiner needs interactive session to be launched (under some user - it cannot launch under SYSTEM).

**Comment by tlamming** [comment]
Ah bummer, would love to run a headless system using quickminer. Thanks for
the info!

**Comment by nicehashdev** [comment]
For such purposes, there is Excavator which is console based. If you are doing headless stuff, you do not need QuickMiner.

**Comment by nicehashdev** [comment]
Closing.
