### ISSUE TITLE
Can not change "Memory clock delta" while Lite optimization in 5.1.3

### ISSUE THREAD

**Issue by Basicqwe** [nicehash/NiceHashQuickMiner#521]
I select Lite optimization here (https://www.nicehash.com/my/mining/rigs/) and try to change "Memory clock delta" here (NiceHash QuickMiner OCTune \ Classic method for overclocking (works for all cards)
i had an error:

Cannot modify value fot device #1: GeForece RTX 3060...

In previos version of miner i did it.

**Comment by nicehashdev** [comment]
Check this please: https://www.nicehash.com/blog/post/modify-existing-optimization-profiles
