### ISSUE TITLE
[BUG] Excavator randomly restarts throughout the day

### ISSUE THREAD

**Issue by samfishersam** [nicehash/NiceHashQuickMiner#528]
**Describe the bug**
I would be using my PC as normal and Excavator would randomly restart itself for no reason that I can find.  It also auto restarts throughout the night when not in use as well, I woke up and it has restarted a bunch of times while I was asleep.

**To Reproduce**
1. Run NHQM
2. Let it mine
3. It will randomly restart the entire program

**Expected behavior**
Expect no random restarts perhaps

**Screenshots**

**Version affected (please complete the following information):**
 - Version number 0.5.13 Stable and 0.5.20 RC.  I switched to RC as I saw one of the fixes was for OCTune, but it did not help.
 - Both Stable and RC

**NVIDIA driver version**
462.59 Standard

**Hardware**
1x 3080

**Logs**
https://drive.google.com/file/d/14ee6y2we4mNptmt5i9-cwJs5As8-l9sZ/view?usp=sharing

**Additional context**
Doing my own digging I see it is being shut down gracefully and it happens many times throughout the day/night

> [2021-05-18 23:59:05:613] [DEBUG] [watchdog] Getting memory info (is enough?) and CPUs
> [2021-05-18 23:59:05:613] [TRACE] [watchdog] HTTP API GET: /devices
> [2021-05-18 23:59:05:619] [DEBUG] [watchdog] Enough virtual memory
> [2021-05-18 23:59:05:619] [TRACE] [watchdog] HTTP API GET: /devices_cuda
> [2021-05-18 23:59:05:670] [TRACE] [dnsoverhttps] Resolved DNS over HTTPS nhmp-ssl.eu-west.nicehash.com to: 172.65.226.105
> [2021-05-18 23:59:05:670] [INFO] [watchdog] Starting/stopping with: /quickstart?id=REMOVED FOR PRIVACY=172.65.226.105
> [2021-05-18 23:59:05:670] [TRACE] [watchdog] HTTP API GET: /quickstart?id=REMOVED FOR PRIVACY=eu-west&ip=172.65.226.105
> [2021-05-18 23:59:05:673] [TRACE] [watchdog] HTTP API GET: /disablecpu
> [2021-05-18 23:59:06:199] [TRACE] [Program] Graceful shutdown handled
> [2021-05-18 23:59:06:199] [DEBUG] [nhmws] Stopping
> [2021-05-18 23:59:06:485] [DEBUG] [nhmws] OnClose, reason: 
> [2021-05-18 23:59:06:486] [DEBUG] [nhmws] Stopped
> [2021-05-18 23:59:06:486] [DEBUG] [watchdog] Finishing
> [2021-05-18 23:59:06:676] [INFO] [watchdog] Shutting down excavator.exe
> [2021-05-18 23:59:06:677] [TRACE] [watchdog] HTTP API GET: /quit
> [2021-05-18 23:59:07:980] [INFO] [watchdog] Excavator.exe has been shut down
> [2021-05-18 23:59:07:981] [DEBUG] [watchdog] Ending thread
> [2021-05-18 23:59:08:013] [DEBUG] [updater] Quit thread
> [2021-05-18 23:59:08:060] [DEBUG] [optimizeprofiles] Quit thread
> [2021-05-18 23:59:08:082] [INFO] [Program] Shutting down
> [2021-05-18 23:59:08:082] [TRACE] [Program] Graceful shutdown handled

**Comment by nicehashdev** [comment]
I suggest you to upgrade your NVIDIA drivers to version 466+. Your current driver is known for causing issues with stability.
