### ISSUE TITLE
Excavator crashes after error message "unable to obtain power consumption" eventual BSOD[BUG] 

### ISSUE THREAD

**Issue by shoofl** [nicehash/NiceHashQuickMiner#529]
**Describe the bug**
crashes after error message "unable to obtain power consumption"

**To Reproduce**
random hours/days/weeks

**Expected behavior**
not crash, not BSOD

**Screenshots**

**Version affected (please complete the following information):**
 - Version number 0.5.1.3
 -STABLE?

**NVIDIA driver version**
466.47 release date 5/18/21

**Hardware**
GPU #0 is 3090 FE connected to PCIE x16 slot
GPU #1 is 3070 FE connected via PCIE x1 riser
GPU#2 is 3070 GIGABYTE gaming OC connected via PCIE x1 riser
[exported_logs.zip](https://github.com/nicehash/NiceHashQuickMiner/files/6505611/exported_logs.zip)

**Logs**
Activate logging first, then record event - bug - then export logs into a .zip file and attach it when submitting this issue.

**Additional context**

**Comment by wlyx99** [comment]
<img width="720" alt="Snipaste_2021-05-20_16-58-33" src="https://user-images.githubusercontent.com/84502002/118950927-3c696700-b98d-11eb-86bc-92930a97a50c.png">
<img width="720" alt="Snipaste_2021-05-20_16-43-07" src="https://user-images.githubusercontent.com/84502002/118951023-5145fa80-b98d-11eb-8841-ce9c08787c2e.png">
<img width="688" alt="Snipaste_2021-05-20_16-40-15" src="https://user-images.githubusercontent.com/84502002/118951064-59059f00-b98d-11eb-90f0-aeafc8d0f742.png">


Me too.The PC always crash with blue screen.GPU is Colorful iGame 3080 Vulcan OC.

**Comment by wlyx99** [comment]
I changed GPU1 to LITE mode a few hours ago,it seems to be normal,but it lossed 5MH.

**Comment by shoofl** [comment]
I didn't notice any loss in hash rate.  I only did it for my cards attached by PCIE risers.

**Comment by wlyx99** [comment]
Before two weeks ago,everything is good.I don't know if it's bios setting problem.

**Comment by herecomesmaggi** [comment]
same issue, happening after i changed slot of my 2060

**Comment by shoofl** [comment]
Well, I have been stable for 4 days now after changing the speed of my PCIE slots in the BIOS to GEN 1.  I have even cranked up the power on all of my cards to get more production.  I have even been able to go back and forth to gaming where my primary card is used for gaming and my other two cards are still mining.  I am undoing all of the other changes that I have made in the past.  IO am trying everything in the past that I thought was crashing my system so, it is looking like it is the BIOS settings.  I am going to keep watching.

**Comment by shoofl** [comment]
![image](https://user-images.githubusercontent.com/84429721/119263160-c1719d80-bb92-11eb-8da6-918fe43ea8a3.png)

**Comment by herecomesmaggi** [comment]
I fixed it by using beta version and changing bios settings. I choose pcie 2,3 as gen 2 in bios and enable 4g settings also setting dram to 3.5Gb I have Asrock mobo.

**Comment by nicehashdev** [comment]
Unable to obtain power consumption issue has nothing to do with stability - however it can give you a hint, that there was an issue with installation for your drivers (it is not complete). Some laptops have no support for power management - it is normal to get this message in such case. For stability guide, check this out: https://github.com/nicehash/NiceHashQuickMiner/wiki/Mining-Rig-with-QuickMiner-in-one-hour
