### ISSUE TITLE
OCTune: fan speed for GPU temperature is not reliable and leads to over-heating

### ISSUE THREAD

**Issue by TerryFrench** [nicehash/NiceHashQuickMiner#53]
version 0.3.2.0
I tried to let OCTune adjust fan speed for GPU Memory Temperature (RTX3080). 
GPU temp set to 60 C GPU memory temp set to 90C (tried 85 C also). 
Real GPU Memory temp is 92 C when mining with 100% fans. So I knew it would not be able to lower the temperature, and it would reach 100% fan speed. 

First, it's too slow to catch up, so start at say 48C, the memory goes over 100 C before the fan reaches 100%. 
I recommend that you start aggressively with high fan speed (on auto i's 48%-53% fan speed before mining), and only after a few seconds, say 20 seconds, you let your PID algorithm take over. That or you tune the PID settings very aggressively. 

Then, at one point the fan speed was likely adjusted down. I'm using that PC to work from home, so when I use it the GPU only mines at around 30-40MHs instead of 95MHs. Mining was able to catch up, and the gpu completely overheated for a short time. 
Excavator stopped with a message about the overheat. 

HWnfo64 v6.43.4380 (latest) showed: 
GPU Temperature reaching 68.4C (that's high for that card, even playing video games for hours, it's in the 65C max) 
GPU MEmory Junction Temperature went to 110 C. That one is not ok at all. It should stay for my gear from 84-92C depending on the ambient room temperature. 
GPU Hotspot Temperature went to 83.0C This is a new measurement for me, so not sure what to expect, but that's high. 

I moved to fixed fan speed to 100% with OCTune to fix the problem. 

Please check my recommendation, as letting the temperature goes too high (that goes really fast no a 3080) should be prevented, even if that makes the fan start at a higher speed then adjust down (unlikely, maybe for water-cooled gear, or with better memory cooling). 

Thank you.

**Comment by nicehashdev** [comment]
I will adjust some params in the meantime you can increase frequency of fan processing. Open commands.json file and for method `devices.smartfan.exec` adjust `loop` (default is 4) to lower value. If you set it to 1, then temperatures and fan speeds will be adjusted every second. That may greatly improve your situation.

**Comment by TerryFrench** [comment]
Thanks

**Comment by nicehashdev** [comment]
The algorithm has been greatly improved now. Please check it out and report back what you think about it.
