### ISSUE TITLE
[FEATURE] Run without NVIDIA card

### ISSUE THREAD

**Issue by wpedrak** [nicehash/NiceHashQuickMiner#530]
**Is your feature request related to a problem? Please describe.**
I wanted to install QuickMiner on a PC that has CPU only and it fails with a message that it needs at least one NVIDIA card.

**Describe the solution you'd like**
As CPU mining is one of the QuickMiner options, I'd expect it to install and work.

**Describe alternatives you've considered**
Right now I'm using regular NiceHashMiner, but I like the idea of having own open-sourced miner. I also find web reporting much nicer when it comes from QuickMiner than NiceHashMiner

**Comment by nicehashdev** [comment]
I suggest you to use either NiceHash Miner or standalone XMRig miner. In both cases you do not risk anything, because both programs are fully open sourced.
