### ISSUE TITLE
[BUG] Unmanaged Rig

### ISSUE THREAD

**Issue by Goky24** [nicehash/NiceHashQuickMiner#531]
My rig shows Unmanaged and im dont know if this is normal or just happening to me, i just started mining a few day ago and this is the first time that this happens to me 

 - Version number 0.5.1.3
 -  STABLE
 - Windows 10 

I use a 3060 Ti on a motherboard by PCI

This is the first time that this happens and i don't know what to do, when i firts started in the morning was all good but i reopened the NCQM and opened my rigs then it happened to show unmanaged

![image](https://user-images.githubusercontent.com/84478671/118887207-a6b3d600-b8bf-11eb-8ef9-b49719406126.png)

**Comment by Pinaccio72** [comment]
Me too!
It seems that mining is continuing regularly, but the rig management shows the rig to be inactive!
The same on the app (Android)

Well... jus now while I was writing it seems solved! Now it semms to be OK! :-D

**Comment by Rueda2803** [comment]
I have the same issue! One rig shows offline but still mining and the other one is unmanaged but still mining. I dont know what to do!

**Comment by nicehashdev** [comment]
This issue is being looked into by the backend side. There is nothing NHQM can do about it.
