### ISSUE TITLE
[QUESTION] 

### ISSUE THREAD

**Issue by c0dezer019** [nicehash/NiceHashQuickMiner#532]
**Has the question been answered in [Wiki](https://github.com/nicehash/NiceHashQuickMiner/wiki)? There is no such question in [FAQ](https://github.com/nicehash/NiceHashQuickMiner/wiki/FAQ) or [Troubleshooting collection](https://github.com/nicehash/NiceHashQuickMiner/wiki/Troubleshooting)?**
No.

**Your question is...**
Can QuickMiner be installed on Linux without the use of a VM? (If not, I do recommend a Linux version!)

**Comment by nicehashdev** [comment]
No. Currently, It is possible only if you virtualize it and make GPUs PCIe passthrough.
