### ISSUE TITLE
v0.5.2.0 RC Additional Mining Locations

### ISSUE THREAD

**Issue by davidhooau** [nicehash/NiceHashQuickMiner#534]
Hi. It appears that the auto-select code is still only checking the EU and US locations. How do we access the new mining locations?

**Comment by nicehashdev** [comment]
There are 4 locations currently available with two extra coming soon. Once available, 0.5.2.0 will auto pick them up, test and select if giving better latency. More about locations is here: https://github.com/nicehash/NiceHashQuickMiner/wiki/Tips-&-tricks#2-choose-your-service-location-to-improve-your-latency-and-reduce-number-of-stale-shares

**Comment by davidhooau** [comment]
So the comments about additional locations mentioned for 0.5.2.0 RC don't relate to that downloadable version? Grrr. Why mention it on github?

**Comment by nicehashdev** [comment]
They do, software support is there, but it also needs to be available by the service (which is not yet).

**Comment by davidhooau** [comment]
Thanks. Any ETA and locations for the new services?

**Comment by samfishersam** [comment]
> They do, software support is there, but it also needs to be available by the service (which is not yet).

I really hope we get Asian servers back!

**Comment by nicehashdev** [comment]
Asian server never existed. There was only proxy. Now there is no need for proxies anymore, because Cloudflare has taken over this part of the service, including DDOS protection. Any bigger city worldwide is a proxy for NiceHash. The only question remains which marketplace gives you lowest latency. Plan is to introduce two more marketplaces for Daggerhashimoto.

**Comment by samfishersam** [comment]
Interesting.  I did remember HK being one of the proxies we used many many years back, like 7-8 years when I started on NH.  Lowest latency for all of Asia is at least 180-200ms right now as the closest is usually California ^^ Thank you NHdev for considering more marketplaces, hopefully they are nearer to us in Asia :D

**Comment by Dohtar1337** [comment]
New locations will be implemented. Obsolete issue. Closing
