### ISSUE TITLE
Support for Nvidia A30 

### ISSUE THREAD

**Issue by polka87** [nicehash/NiceHashQuickMiner#535]
Hello,

Any chance if A30 support can be added? 

![a30_dev_id](https://user-images.githubusercontent.com/84724609/119360090-209ce400-bc5f-11eb-96ab-bc0c837d2d56.jpg)

Thanks

**Comment by polka87** [comment]
Let me know if there is more information needed?
Is there a source code available which I could compile myself to include this dev id ?

Thank you

**Comment by nicehashdev** [comment]
Yes, you can help it doing following: https://github.com/nicehash/NiceHashQuickMiner/wiki/One-click-Optimizations#is-it-possible-to-slightly-modify-optimization-profiles

Latest 0.5.2.0 RC uses version 7 already which can ID devices according to PCI ID - get PCI ID of your device and you can make Enterprise profile for your card so you can optimize it with a click of a button just like other cards.

Once you figure out best numbers, pass them back to me. I would suggest you to try A40 as a starting point: https://github.com/nicehash/NiceHashQuickMiner/wiki/Enterprise-mining

**Comment by polka87** [comment]
Hello,

I was able to get the following hash rate. I am still working on fine tuning the profiles.

![hashrate](https://user-images.githubusercontent.com/84724609/120512071-d95dd400-c37f-11eb-8544-d8030e9a9537.jpg)

**Comment by polka87** [comment]
I have updated the optimizeProfilesCustomDataURL filed in the "nhqm.conf" with the path for "data_007.json".
Now how do I use the profile ?

**Comment by polka87** [comment]
With Core clock of 900. Hash rate gets reduced to around 97.7MHs. However with this power consumption is reduced to about 35W per card. While the efficiency increases to around 770kH/J, which seems pretty significant. Attaching more screen shots.

![Screenshot 2021-06-06 212202](https://user-images.githubusercontent.com/84724609/120959123-f858bf00-c70d-11eb-9c5e-979194483760.jpg)

**Comment by polka87** [comment]
@nicehashdev . Please let me know what else I can do further optimize the performance.

**Comment by Nufflee** [comment]
```

**Comment by Dohtar1337** [comment]
No response. Closing
