### ISSUE TITLE
Connection error 

### ISSUE THREAD

**Issue by RigRTX3090** [nicehash/NiceHashQuickMiner#536]
I have 4 rig, Since I update them they are not able to connect screenshot attached.
Return to previous version they are working. 
![Screenshot_20210520-083642_TeamViewer](https://user-images.githubusercontent.com/82683718/119494704-f35a4e00-bda4-11eb-829c-681ead9bbe93.jpg)

**Comment by nicehashdev** [comment]
Can you resolve `nhmp-ssl.br.nicehash.com`?
