### ISSUE TITLE
[FEATURE] Option to disable animated icon in Windows 

### ISSUE THREAD

**Issue by Presence-Eternal** [nicehash/NiceHashQuickMiner#537]
**Is your feature request related to a problem? Please describe.**
I find the animated notification area icon of recent versions distracting.

**Describe the solution you'd like**
I would like to be able to disable the animation. I didn't see any obvious way to do so in the configuration file. 

**Describe alternatives you've considered**
Hiding the icon: I use the icon regularly; hiding it would be an annoyance.  
Manually disabling all notification area animations in windows: As far as I know this is impossible.

**Comment by nicehashdev** [comment]
This will stay as it is one of the requirement of AV companies - when mining, it should be visible that it is mining.
