### ISSUE TITLE
Mining stuck every time after unexpected power off

### ISSUE THREAD

**Issue by Magister-Ice** [nicehash/NiceHashQuickMiner#538]
Hello there.

Every time, when happening unexpected power off the miner is displaying an error message and is not mining (and can't be managed by web interface, even I don't have a possibility to look what happened until connected to RIG by RDP).
I don't found an option how to disable this annoying error message.

Could you please fix this issue (because I and you lose a money every time when unexpected power off is happening)?

![image](https://user-images.githubusercontent.com/84991299/120031566-a3c48e00-c001-11eb-8f89-2dafcbdda387.png)

Thanks.

**Comment by nicehashdev** [comment]
How did you configure autostart? You should use autostart method by NiceHash QuickMiner which adds `-count` command line when starting so you get count down dialog before NHQM is launched.

**Comment by tulup4ik** [comment]
reported this bug to support since v0.4.7.1. asked to disable this user interaction when autostart is enabled. autostart feature is useless and broken. how supportdev answer is help us with this problem? autostart is configured using the interface NHQM provided for this feature to enable it.

**Comment by SHristov92** [comment]
I found a workaround: Start the miner and close it normally.  In that state "bLastRunCrashed" should be false. 
Now make the nhqm.conf file read only (Properties on the file -> read only check). 

That won't allow the flag to be set, but in the same time you won't be able to make any modifications. 
If your configuration is stable and you don't change it so much that should do the trick.

**Comment by Dohtar1337** [comment]
This issue should be resolved with countdown. 

Is the issue still persistent on the latest release?
