### ISSUE TITLE
Github server not Found : the remote server returned an erorr :(404) not found

### ISSUE THREAD

**Issue by livingdeathz** [nicehash/NiceHashQuickMiner#539]
hey i cant download nicehashquickminner .. when i want to download and install it. i will take this erorr(404)
i think github removed data sourse for nicehash in github server... anyone know something about it ?

**Comment by Gunzthegeek** [comment]
> hey i cant download nicehashquickminner .. when i want to download and install it. i will take this erorr(404)
> i think github removed data sourse for nicehash in github server... anyone know something about it ?

Same here it worked for me the first time months ago but now its error(404)

**Comment by livingdeathz** [comment]
> > hey i cant download nicehashquickminner .. when i want to download and install it. i will take this erorr(404)
> > i think github removed data sourse for nicehash in github server... anyone know something about it ?
> 
> Same here it worked for me the first time months ago but now its error(404)

its telling me the remote server returned an erorr :(404) not found

**Comment by CortanaTheUseful** [comment]
Also have the same error, was fine a a couple of days ago?

**Comment by shastablasta55** [comment]
Dear miners,

Downloads from GitHub are temporarily unavailable while the full external security audit is being completed from last week's attempted intrusion. The files have already been checked for integrity by our team and this is simply part of an additional secondary stage audit that was advised by our external experts.

Downloads will be available again soon!

We thank you for understanding.

Your NiceHash team

**Comment by livingdeathz** [comment]
> Dear miners,
> 
> Downloads from GitHub are temporarily unavailable while the full external security audit is being completed from last week's attempted intrusion. The files have already been checked for integrity by our team and this is simply part of an additional secondary stage audit that was advised by our external experts.
> 
> Downloads will be available again soon!
> 
> We thank you for understanding.
> 
> Your NiceHash team

hi . thank you for answer . so what we have to do i am  a nicehash miner and just made my windows fresh last day... so i had to change my pool ?
do u have any idea when  it will be available ? any sure time ? cause if i got on other pools.. i never will come back on nicehash

**Comment by poutinemcsween** [comment]
same thing for me, "error 404 this is not the website you were looking for"
WHY DOWN YOUR WEBSITE SAY EVERYTHINGS NORMAL THEN, WHY IS THERTE NO NOTIFICATION WHATSOEVER ON NICEHASH. PUT A FKING WARNING THAT TELLS PEOPLE WHAT THE FK IS GOING ON.

**Comment by lgomesdix** [comment]
Same thing here. You have to warning the people about this issue. 
and "What is Soon"? because i have this issue since yesterday.

**Comment by renowijoyo** [comment]
its been 10 hours. no fix yet?

**Comment by shastablasta55** [comment]
I do not work with them, just copied it from their site as I was having the same issue

**Comment by kolja-io** [comment]
Its been 24h and there is no fix? Can somebody help me with this or recommend me a other mining platform that i don’t have to just wait till it works again thats money i am wasting!! Lg

**Comment by poutinemcsween** [comment]
Support Team
2021-05-31 04:12

Hello!

Thank you for your message.

Downloads from GitHub are temporarily unavailable while the full external security audit is being completed from last week's attempted intrusion. The files have already been checked for integrity by our team and this is simply part of an additional secondary stage audit that was advised by our external experts.

Downloads will be available again soon!


Kind regards,
NiceHash Team
you
2021-05-31 08:49

Hello and thank you for the reply. Shouldn't there be some sort of prominent notification of some sort to let users know that this is the case? There was a lot of confusion and actually would have prevented me from having to even reach out to you and open a support case. When I search anything about operation it indicates that everything is "Normal" which is definitely not the case. You leading user astray by not informing them. Again, Thank you for your time.

**Comment by poutinemcsween** [comment]
That is what they responded with as I was frantically opening up support tickets yesterday on both nicehash and github.

**Comment by kolja-io** [comment]
And? Is there a fix yet?

**Comment by Dohtar1337** [comment]
resolved. Closing
