### ISSUE TITLE
XMRIG not starting on v0.3.02 "connect error"

### ISSUE THREAD

**Issue by Madgamerz22** [nicehash/NiceHashQuickMiner#54]
Getting a "connect error" operation canceled status. Any way to fix this?

**Comment by nicehashdev** [comment]
You will have to explain a bit more. What exactly are you trying to do? Where do you see this? Perhaps give full log or at least screenshot?

**Comment by Madgamerz22** [comment]
Right in the application itself. I'm trying to mine with my CPU. But could get it working seems like a connect issue with the server maybe?
![xmrig screenhot](https://user-images.githubusercontent.com/79297771/108463961-4fb14d00-724d-11eb-8622-adcf1af41083.JPG)

**Comment by nicehashdev** [comment]
I'd say something is blocking your connection to our RandomXMonero stratum servers.

Check your routers, firewalls, ISP.

You can also try with VPN.

**Comment by Madgamerz22** [comment]
Using a VPN fixed it thanks!
