### ISSUE TITLE
Error while Downloading Quick Miner

### ISSUE THREAD

**Issue by adarshx11** [nicehash/NiceHashQuickMiner#541]
**Has the question been answered in [Wiki](https://github.com/nicehash/NiceHashQuickMiner/wiki)? There is no such question in [FAQ](https://github.com/nicehash/NiceHashQuickMiner/wiki/FAQ) or [Troubleshooting collection](https://github.com/nicehash/NiceHashQuickMiner/wiki/Troubleshooting)?**
Yes/No.

**Your question is...**
how can i download nicehash quick miner ??? it's showing some error** 404 NOT FOUND

**Comment by water221c** [comment]
i got the same issue, anyone else got the problem or has a solution?

**Comment by BIOGAMER2468** [comment]
i have this issue as well

**Comment by Sinful1966** [comment]
Same issue here! File not found for .exe and .zip files.

**Comment by Boumzer** [comment]
same for me .. 404 not found .. Please help us :)

**Comment by the-mr-matt** [comment]
Same issue for me, except it extends to every download on the nicehash website. I can't download quickminer or any of the alternative downloads/installers, and I can't download miner either. 404 for all of it.

**Comment by FarnamAdelkhani** [comment]
+1 - 404 for all dl links including QuickMiner

**Comment by Most85** [comment]
All download links are down

**Comment by hieunguyenmsft** [comment]
Same issue

**Comment by adarshx11** [comment]
I think they have some kind of audit, so that's why they have shutdown this quickminer page, they Will open soon, You all can check this on nicehash official site in press section.

**Comment by tapanpadhi** [comment]
Maybe it's on maintenance

**Comment by adarshx11** [comment]
> Maybe it's on maintenance

No, It's Audit*** full Examination like someone try to hack or do something so they updating it*

**Comment by tapanpadhi** [comment]
Yah just fix that issu as soon as possible so we can again mine through
nicehash.

**Comment by JessicaX83** [comment]
I believe their definition of "soon" is much different than what most people would accept as "soon".

**Comment by adarshx11** [comment]
> I believe their definition of "soon" is much different than what most people would accept as "soon".

haha 
![2ee2ee](https://user-images.githubusercontent.com/62538058/120283654-099e6780-c2d9-11eb-869b-3d604cbde287.JPG)

**Comment by Dohtar1337** [comment]
Resolved. Closing.
