### ISSUE TITLE
[QUESTION] 

### ISSUE THREAD

**Issue by darProfitTrailer** [nicehash/NiceHashQuickMiner#543]
Hello, my rigs weren't showing optimization profiles yesterday, so I uninstalled to redownload as I never had that problem. Except now I can't find proper download anywhere for quickminer, even the old install file is broken as I guess it back links to the .github install. If we could get a proper link refresh and proper download page would be awesome! Thanks.

**Comment by Blazed-24** [comment]
I did the same, so frustrating they not giving a ETA when the new download link will be available

**Comment by Dex-M** [comment]
Same here guys... I went nuclear and reinstalled OS and checked the whole rig ... swapped PSU and stuff.... so frustrated... The whole day wasted...

**Comment by poutinemcsween** [comment]
I did the same thing. opening up tickets, reinstalling drivers, deleting files, searching online and their sites said everything is online and normal.. I was so pissed earlier.

**Comment by WhiteStoneRev217Miner** [comment]
All the same here too, retired military and just got into this stuff. But i got frustrated then read your post and felt better. I got good results using the OCtune for the first time when mining rigs that have no optimize button. So least that solved the short term problem, 7 gaming rigs/computers running 24hr  no problems. 

WhiteStone

**Comment by Dohtar1337** [comment]
Resolved. Closing.
