### ISSUE TITLE
[BUG] Cuda core erorr in nicehash

### ISSUE THREAD

**Issue by livingdeathz** [nicehash/NiceHashQuickMiner#544]
hi guys. my rig were good before i try to turn off RGB LED of my card... , when i were trying to turn off msi RGB light .. the dragon center app ask me for running as adminestator.. and i accept it ... after it i cant run all of my 5 cards. i can turn on only 4 of 5 cards and when i trying to run last card its telling cuda core erorr , my system was fine before this. but now i am getting 0 Mgh from one of the cards when i trying to run 5 cards and its difrend .. one time 3070 is getting 0 mgh and one time 3060 and its difrend between all of them . but if i run only 4 from 5 cards it will work so good with even one crash
my Confing is  : 3x3070 and 2x3060
Nvidia driver 470.5
Windows 10 (64Bit)
8 GB ram 
i3-10100F Cpu

**Comment by matheuspiculi** [comment]
I have same problem

**Comment by Dohtar1337** [comment]
Is the issue still happeninig?
