### ISSUE TITLE
[BUG] Download 404

### ISSUE THREAD

**Issue by ThePhychoKid** [nicehash/NiceHashQuickMiner#545]
**Describe the bug**
Link to installer (https://github.com/nicehash/NiceHashQuickMiner/releases/tag/v0.5.1.3) returns a 404- not found.

**To Reproduce**
1. Go to 'https://github.com/nicehash/NiceHashQuickMiner/releases/tag/v0.5.1.3'
2. Click on 'Download Installer Here'
4. See error 404

**Expected behavior**
I expect a working link to the installer 

**Version affected (please complete the following information):**
 - Version number [e.g. 0.5.13]
 - RC or STABLE? I assume stable

**Comment by ThePhychoKid** [comment]
Just saw other bug report for same issue, feel free to close this one. Maybe add a disclaimer that download is temporarily unavailable? Unfortunate time to be down, HoneyMiner just closed today and many people are looking for a new one-click miner

**Comment by stricq** [comment]
All Download links for the latest stable appear to still be broken.

**Comment by ratdago** [comment]
hasnt worked for days, how are people supposed to start new rigs?

**Comment by DenisAlliswell** [comment]
No one link on download doesn't work...

**Comment by Dohtar1337** [comment]
Resolved. Closing.
