### ISSUE TITLE
[FEATURE] Game mode for SLI setups

### ISSUE THREAD

**Issue by ecast040** [nicehash/NiceHashQuickMiner#546]
**Is your feature request related to a problem? Please describe.**
When I activate game mode it only disables mining on the GPU connected to the display and doesn't disable mining on other gpu that's in SLI 
**Describe the solution you'd like**
Game mode to detect if there's an SLI bridge installed. If it's installed, add a checkbox to disable mining on cards that are SLI'd to the gpu connected to external display

**Describe alternatives you've considered**
Create a feature to have game profiles, so you can disable mining on however many cards you want per game but this might be more difficult than the feature requested above. 

**Additional context**

**Comment by Dohtar1337** [comment]
Added to our backlog
