### ISSUE TITLE
[FEATURE] Undervolting for game mode

### ISSUE THREAD

**Issue by ecast040** [nicehash/NiceHashQuickMiner#547]
**Is your feature request related to a problem? Please describe.**
I cannot undervolt my GPU for game mode, let alone for two GPUs in SLI to make sure they are both undervolted AND have a GPU frequency cap to make sure both gpus are using the same max frequency. 

**Describe the solution you'd like**
Game mode have an option to set an undervolt curve like MSI afterburner. For example, say the max voltage I want to run on both cards is 0.900 mv and cap the frequency to 1800 Mhz as an example, this would provide users with the ability to have lower temps and excellent performance on their GPUs considering a lot of new 30 series cards don't have proper cooling or thermal pads. 

**Describe alternatives you've considered**
Set a flat undervolt value like in nicehash's main interface so that the undervolt scales with gpu frequency and continues as long as the gpu is kept cool. I would still recommend the solution described above because that would also cap the GPU frequency in one go.

**Comment by Dohtar1337** [comment]
We will not implement this feature now. Setting TDP, core and memory for game mode covers 99.9% of the users.
