### ISSUE TITLE
[FEATURE] Alarm or notification if temps go above a certain threshold

### ISSUE THREAD

**Issue by ecast040** [nicehash/NiceHashQuickMiner#548]
**Is your feature request related to a problem? Please describe.**
Sometimes the fan profile doesn't apply properly to the GPU and the Vram temps start getting hotter than what I set in nicehash to max out the fans when it reaches 92C for example. 

**Describe the solution you'd like**
Would like the option to either enable an audible alarm if the VRAM temps go above a certain threshold (GPU temps too if it's not too much trouble) OR send a push notification to nicehash app to let user know their GPU is overheating or above their selected threshold.

**Describe alternatives you've considered**
Add an option to give an alternative power limit or gpu clock speed to run at if the vram temp goes above a certain point (like 92C) to let the gpu cool down a little before reverting back to original power limit set in nicehash

**Comment by samfishersam** [comment]
> **Is your feature request related to a problem? Please describe.**
> Sometimes the fan profile doesn't apply properly to the GPU and the Vram temps start getting hotter than what I set in nicehash to max out the fans when it reaches 92C for example.
> 
> **Describe the solution you'd like**
> Would like the option to either enable an audible alarm if the VRAM temps go above a certain threshold (GPU temps too if it's not too much trouble) OR send a push notification to nicehash app to let user know their GPU is overheating or above their selected threshold.
> 
> **Describe alternatives you've considered**
> Add an option to give an alternative power limit or gpu clock speed to run at if the vram temp goes above a certain point (like 92C) to let the gpu cool down a little before reverting back to original power limit set in nicehash

There already is such a function to lower clocks when fan is already at selected max and when the temps are above what you've selected.  Use OCTune, and set fan profile to "Target plus decrease MCC".

**Comment by ecast040** [comment]
That feature doesn't seem to be working reliably. I set hwinfo64 to alarm me if temps go above 94C and I set Target plus decrease MCC to 92C, I go to sleep hearing the alarm all night either because it doesn't throttle enough or it's not properly applying the increased fans. Maybe the aggressiveness of the fans ramping up or down needs to get looked at. I pretty much use fixed fan speed now cause it doesn't apply the fan speed quickly enough.

**Comment by ecast040** [comment]
I'll probably test this feature later tonight and see. I still see value in adding push notifications to this however, there are situations where you aren't home and ambient temps rise which leads to higher temps or a water pump goes bad for example.

**Comment by ecast040** [comment]
> > I'll probably test this feature later tonight and see. I still see value in adding push notifications to this however, there are situations where you aren't home and ambient temps rise which leads to higher temps or a water pump goes bad for example.
> 
> 94c with a waterblock seems really high regardless tho.

I agree, that would be really high. I think even passively you would get at most like 75 C

**Comment by Dohtar1337** [comment]
High temp push notifications are on a to-do list.
