### ISSUE TITLE
Temp and VRAM-temp switched in web-page.

### ISSUE THREAD

**Issue by fdoving** [nicehash/NiceHashQuickMiner#55]
From web-page:
![image](https://user-images.githubusercontent.com/26197922/108506210-b881df00-72b8-11eb-9bfc-13a771c28190.png)

From octune:
![image](https://user-images.githubusercontent.com/26197922/108506285-d2bbbd00-72b8-11eb-9730-64c340b30068.png)

octune is correct.

**Comment by nicehashdev** [comment]
This is fixed.
