### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by leborncoin** [nicehash/NiceHashQuickMiner#550]
Can I get help quick miner won’t install 
![BCF1EA03-D184-4417-8B5C-C0102C1869B9](https://user-images.githubusercontent.com/85150405/120274607-ed60e300-c264-11eb-9f72-d07cc9bc13dc.jpeg)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version affected (please complete the following information):**
 - Version number [e.g. 0.4.5.5]
 - RC or STABLE?

**NVIDIA driver version**
Which one do you use?

**Hardware**
Describe GPUs used and how are GPUs connected to the motherboard.
CPU?

**Logs**
Activate logging first, then record event - bug - then export logs into a .zip file and attach it when submitting this issue.

**Additional context**

**Comment by Dohtar1337** [comment]
Solved.
