### ISSUE TITLE
[BUG] Unmanaged Rigs & Rig Offline But Still Getting Share " QuickMiner "

### ISSUE THREAD

**Issue by pjkenixqz** [nicehash/NiceHashQuickMiner#551]
**Describe the bug**
my rig  "Unmanaged"  when i tried to add new rig
my rig "Offline" but excavator still working

**Expected behavior**

**Screenshots**
![photo_2021-06-01_14-07-02 (2)](https://user-images.githubusercontent.com/74605318/120287082-19be4300-c2e9-11eb-9cdd-e9f6b8cafbcc.jpg)
![photo_2021-06-01_14-07-02](https://user-images.githubusercontent.com/74605318/120287084-1aef7000-c2e9-11eb-9d4a-36d4825a635a.jpg)

**Version affected (please complete the following information):**
 - NHQM_v0.5.2.0_RC

**NVIDIA driver version**
Gaming Ready Driver 466.47

**Hardware**
RTX 2070 PCIe
i7 8700 

**Logs**
[exported_logs.zip](https://github.com/nicehash/NiceHashQuickMiner/files/6574590/exported_logs.zip)

**Additional context**

**Comment by Dohtar1337** [comment]
Should be solved in the next release.
