### ISSUE TITLE
quickminer files all missing from github

### ISSUE THREAD

**Issue by Kazlehoff** [nicehash/NiceHashQuickMiner#553]
cant download any recent installer or zip package. 404 file not found for all of em.

**Comment by yellowpuppy** [comment]
It Does! It let people suspect NiceHash want run away with your money.

**Comment by Kazlehoff** [comment]
Nah. read here.

https://www.nicehash.com/blog/post/github-secondary-stage-security-audit

They answered me on Reddit faster than on Git, which is kind of lol in and of its self.

TLDR: files are down while they examine everything to find out where the recent hack attempt came from.
