### ISSUE TITLE
[BUG] LINK FOR DOWNLOADER DOESNT WORK

### ISSUE THREAD

**Issue by mattr474** [nicehash/NiceHashQuickMiner#556]
**Describe the bug**
When you go to download nicehash quick miner recomended for nvidia, the link for Stable release v0.5.1.3 doesnt work, all links taake you to a page saying web page not found. I just built my mining rig and cant even download the software.

**Comment by barryw** [comment]
They had an attempted intrusion and they've been auditing their software for the last week. Don't worry though, they said downloads will be available again soon. 🙄

**Comment by imsidz** [comment]
when it will available for downloads

**Comment by Bribroute** [comment]
Jesus will be back before it's available

**Comment by qergo** [comment]
404!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by Therzdae** [comment]
I am also getting a 404 page, cleared everything in my browser, tried another browser, tried another computer.. all same :( I just want to make monies.

**Comment by skeddles** [comment]
> They had an attempted intrusion and they've been auditing their software for the last week. Don't worry though, they said downloads will be available again soon. 🙄

They should definitely put a notice on the site or download page...

**Comment by barryw** [comment]
> > They had an attempted intrusion and they've been auditing their software for the last week. Don't worry though, they said downloads will be available again soon. 🙄
> 
> They should definitely put a notice on the site or download page...

Absolutely agree with you. The fact that people are **still** filing bugs a week after they started their audit is completely unacceptable. This should be displayed at the top of the console when you log in.

**Comment by killerkris14** [comment]
for the record, I have 3 different installers for Nicehash Quick installer. but due to the audit, they wont install, they run into a Error
![image](https://user-images.githubusercontent.com/83150055/120750880-f0a1dc00-c4bb-11eb-91c0-9abdfa107391.png)

**Comment by andrewlaw08** [comment]
I have the same issue! "Error installing"

**Comment by Cheemonstonzo** [comment]
This seems to be fixed now?  QM now mining stable and not giving mem-oc errors.  There's definitely some concerning hidden hand-holding with the online source code for QM to function properly.

**Comment by samfishersam** [comment]
> This seems to be fixed now? QM now mining stable and not giving mem-oc errors. There's definitely some concerning hidden hand-holding with the online source code for QM to function properly.

The installer downloads from Git, that's it.  Doesn't require Git to run.

**Comment by Dohtar1337** [comment]
Solved
