### ISSUE TITLE
Rejected Speed

### ISSUE THREAD

**Issue by polka87** [nicehash/NiceHashQuickMiner#557]
Hello,

Nicehash portal is reporting:

Total Speed as 395.54 MH/s
Accepted Speed: 237.2110 MH/s
Rejected Speed: 56.0727 MH/s

Why there is such a big difference in total speed vs accepted speed?
How to avoid rejected speed?

Thank you

**Comment by samfishersam** [comment]
All depends on what kind of rejected shares you are getting.  Share above target?  Unstable OC.  Job not found?  Your latency to the closest NH server is bad.

**Comment by Dohtar1337** [comment]
https://www.nicehash.com/blog/post/what-are-accepted-and-rejected-shares
