### ISSUE TITLE
[QUESTION] No way to autostart on boot with non-admin account?

### ISSUE THREAD

**Issue by DILeak** [nicehash/NiceHashQuickMiner#559]
**Has the question been answered in [Wiki](https://github.com/nicehash/NiceHashQuickMiner/wiki)? There is no such question in [FAQ](https://github.com/nicehash/NiceHashQuickMiner/wiki/FAQ) or [Troubleshooting collection](https://github.com/nicehash/NiceHashQuickMiner/wiki/Troubleshooting)?**
No.

**Your question is...**

I can't seem to get quickminer to autostart on my Windows 10 PC. I just moved from the regular miner to the QuickMine, but I have about a dozen PC's that start/restart every morning and I'd like to make use of them when they're on. Unfortunately, the only way I can seem to do that is by VNC'ing into each and manually running QuickMiner when they reboot, as the autostart feature doesn't seem to work.

The only thing I can think would be causing it is that the default user that the computer boots into is non-administrator. But I did install QuickMiner and enable the autostart with admin privileges.

I've tried:
- On multiple PC's
- Both stable and RC
- Disabling and re-enabling autostart
- Starting from a batch file in startup folder

To avoid confusion I'm referring to the application starting in the system tray, not that mining starts automatically.

**Comment by fmiqbal** [comment]
Did you try autostart with Task Scheduler ? I have mine running on "startup" not on logon
![image](https://user-images.githubusercontent.com/8409391/123533756-2e53f680-d742-11eb-8d39-0e03b68c54d0.png)
![image](https://user-images.githubusercontent.com/8409391/123533742-1c725380-d742-11eb-81ac-a391a3005ef2.png)

the only downside is the tray icon didn't show up, so If I ever need to meddle with it (like gaming mode), I quit via Task Manager, and start again (with nicehash then warning about unsafe exit and reset)

**Comment by Dohtar1337** [comment]
What windows version and build are you using?

**Comment by Dohtar1337** [comment]
No response, closing
