### ISSUE TITLE
Overclocking software not working as expected

### ISSUE THREAD

**Issue by TrickyT19641964** [nicehash/NiceHashQuickMiner#561]
![image](https://user-images.githubusercontent.com/85564282/121192745-94bac700-c8b0-11eb-8d4d-ed3a268d9695.png)

Overclocking software was working on my Asus Zephyrus G15 3070 laptop, OC was 100core, 1100 mem (52mh 70W). It now fails when attempting to OC over 100, 300, giving me error=-4 in the minner and the image error.

Is this an error due to the miner or an error due to my laptop? i dont believe any updates were done to the laptop.
Driver: 466.63 (But it happened on an earlier driver too, i updated it to see if itd be fixed)

**Comment by iamkucuk** [comment]
I'm experiencing that one too
