### ISSUE TITLE
bug à l installation avec rtx2070

### ISSUE THREAD

**Issue by Barlatshi** [nicehash/NiceHashQuickMiner#563]
j'ai une rtx2070 et le logiciel me dit que j'ai besoin d'un carte nvidia.
![needed nvidia](https://user-images.githubusercontent.com/31375873/121435613-7e2f7100-c97f-11eb-9745-b32f2baf6faa.png)

**Comment by YF974** [comment]
bonjour , dans le bios,  4kdecoding activer ??

**Comment by Barlatshi** [comment]
Bonjour,
je ne sais pas comment l'activer.
Vous avez des tutos pour une carte mère btc110?
Merci du retour,

**Comment by YF974** [comment]
slt moi non , je suis qu'un simple utilisateur,  peut être d'autre personne , mais normalement touche ( suppr delete ou une touche comme , F1 ou F2 , F3 etc.... ) pour accéder au bios selon carte la mère . lire le manuel .

**Comment by YF974** [comment]
https://github.com/nicehash/NiceHashQuickMiner/wiki/Mining-Rig-with-QuickMiner-in-one-hour

**Comment by Dohtar1337** [comment]
Please try this: https://www.nicehash.com/blog/post/how-to-correctly-uninstall-and-install-gpu-drivers

**Comment by Dohtar1337** [comment]
no reponse
