### ISSUE TITLE
[BUG] CUDA error 'all CUDA-capable devices are busy or unavailable' in func 'cudahelp::device_thread_init' line 160

### ISSUE THREAD

**Issue by matheuspiculi** [nicehash/NiceHashQuickMiner#564]
[[2021-06-09 20:20:17.872614] [thread=0x0000208c] [warning]]

	device #2 | Failed init cuda (2) ctx: CUDA error 'all CUDA-capable devices are busy or unavailable' in func 'cudahelp::device_thread_init' line 160

[[2021-06-09 20:20:17.875613] [thread=0x0000208c] [debug]]

	wrkr2-2 | Worker thread ended

[[2021-06-09 20:20:17.875613] [thread=0x000022cc] [info]]

	Shutting down

[[2021-06-09 20:20:17.879610] [thread=0x000022cc] [debug]]

	cpu-miner | Stopping

[[2021-06-09 20:20:17.886632] [thread=0x000022cc] [info]]

	http | Closing

[[2021-06-09 20:20:17.911332] [thread=0x00002098] [trace]]

	wrkr3-3 | Uninit CUDA

[[2021-06-09 20:20:17.911332] [thread=0x00002098] [debug]]

	wrkr3-3 | Worker thread ended

**Comment by Dohtar1337** [comment]
No compatible devices has been recognized. Make sure that the GPU is supported. https://www.nicehash.com/support/mining-help/general-help/is-my-hardware-supported
