### ISSUE TITLE
[BUG I am having issues with getting my GTX 1650 OC GPU to work with NiceHash. The NiceHash Excavator starts mining successfully (it claims), but when I look at the excavator log, tells me "no compatible device not found." Yet, I have the correct driver installed (Nvidea v. 466.63) and Windows v. 10 Device Manager sees the card fine. Checked the CUDA version. It's v. 7.1. So I'm really stumped. It should be working. I'm already mining on another machine using an RTX 2080, so I know how to mine on NiceHash. Can anyone help me? Here's a link to my card specs... https://techpowerup.com/gpu-specs/zotac-gtx-1650-oc.b6894] 

### ISSUE THREAD

**Issue by AKwebmaster151** [nicehash/NiceHashQuickMiner#565]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version affected (please complete the following information):**
 - Version number [e.g. 0.4.5.5]
 - RC or STABLE?

**NVIDIA driver version**
Which one do you use?

**Hardware**
Describe GPUs used and how are GPUs connected to the motherboard.
CPU?

**Logs**
Activate logging first, then record event - bug - then export logs into a .zip file and attach it when submitting this issue.

**Additional context**

**Comment by Bronsens** [comment]
You're Problem is the amount of memory on that GPU 4GB is not enough for Eth anymore.

**Comment by AKwebmaster151** [comment]
Thanks for the info. However, I am mining BTC, not ETH. I get it though. The same logic probably applies to BTC as well. I just moved up to a RTX 1080 ti GPU, and that one works really well, almost equal to my RTX 2080 GPU.

**Comment by Dohtar1337** [comment]
1650 does not have enough memory to run Daggerhashimoto algorithm.
