### ISSUE TITLE
Different system-tray icons for when mining is enabled/disabled.

### ISSUE THREAD

**Issue by Timorio** [nicehash/NiceHashQuickMiner#567]
It should be possible to tell when the app is mining with a glance at the system tray rather than having to click on the tray icon.

**Comment by Jurgen1980** [comment]
+1

**Comment by Dohtar1337** [comment]
Yes, the icon is animated when the mining is happening. Use the latest Release Candidate.

**Comment by Timorio** [comment]
This is definitely an improvement, but it'd be ideal if there were no point in the animation cycle where it looks as though it's not mining while it is mining.
