### ISSUE TITLE
[BUG] Totally No Optimize Button!! RTX 3080ti

### ISSUE THREAD

**Issue by kueh88** [nicehash/NiceHashQuickMiner#568]
**Describe the bug**
I just change new GPU Palit RTX3080ti, after i installed No Optimize button shown at Rig Manager . I had try to reinstall QuickMiner and GPU driver.

![image](https://user-images.githubusercontent.com/85797982/121780579-97306000-cbd3-11eb-92a1-8a3744df00fd.png)

*

**Version affected :**
 - Version number v0.5.1.3
 - Tried both RC and STABLE

**NVIDIA driver version**
466.7

**Hardware**
I only got one GPU and is directed connected to the motherboard.

CPU i7 4770
RAM 16gb
PSU 750W
MOBO : Maximum Vi Hero

**Comment by andylsc57** [comment]
I'm using 3070ti and I can't see the Optimize button as well. Is there a solution to this?

**Comment by Dohtar1337** [comment]
We have added the optimization after your bug report. It should be working now. If not, please let us know.

**Comment by laohanlinux** [comment]
I also not found the Optimize Button

<a href="https://ibb.co/hXfGWr4"><img src="https://i.ibb.co/hXfGWr4/Screen-Shot-2021-11-16-at-5-12-36-PM.png" alt="Screen-Shot-2021-11-16-at-5-12-36-PM" border="0"></a>
