### ISSUE TITLE
After Update my profile in OCTune is gone

### ISSUE THREAD

**Issue by Norrit1** [nicehash/NiceHashQuickMiner#57]
Hi,
everytime I update my NHQM all my OCTunes profiles are gone?Is there any way to avoid this?

**Comment by nicehashdev** [comment]
This only happens when going to ver 0.3.2.x from older due to some changes. Updates from current latest RC will not do that anymore.

**Comment by nicehashdev** [comment]
As explained, future versions will not have this issue.
