### ISSUE TITLE
[BUG] NiceHash keeps resetting my GPU to default after each "quick-swap DAG to ..."

### ISSUE THREAD

**Issue by Yibo-de** [nicehash/NiceHashQuickMiner#570]
Hello, i'm new to NiceHash. i'm using msi afterburner to overclock and undervolt my 1070 ti. i never touched OCTune and config file of QuickMiner. After every "generating DAG cache" or "quick-swap DAG to..." the afterburner settings was overridden and i must re-apply them. Similar problems here: https://github.com/nicehash/NiceHashQuickMiner/issues/19, it seemed to be fixed after v0.3.1.2_RC. but this is what i am experiencing. please have a look. Thanks!

**NVIDIA driver version**
466.77

QuickMiner version v0.5.1.3

**Comment by YF974** [comment]
bonjour mise a jour de quikminer 5.1.6 ou 5.0.2rc, ne pas utiliser msiafterburner ! utiliser oc tune pour overclock , activer msi  interruption . utiliser nvidia driver non dhc !!!!! , synchronisation de l'heure windows, en espérant vous avoir aider

**Comment by Yibo-de** [comment]
> bonjour mise a jour de quikminer 5.1.6 ou 5.0.2rc, ne pas utiliser msiafterburner ! utiliser oc tune pour overclock , activer msi interruption . utiliser nvidia driver non dhc !!!!! , synchronisation de l'heure windows, en espérant vous avoir aider

Thanks for the reply, i'll give a try. I'm using the nivida driver but what do you mean about "dhc"?

**Comment by YF974** [comment]
https://github.com/nicehash/NiceHashQuickMiner/wiki/Mining-Rig-with-QuickMiner-in-one-hour
https://www.nvidia.com/Download/Find.aspx?lang=en-us 
utilise le standard ( non dhc )

**Comment by Yibo-de** [comment]
ok, thank you very much!

**Comment by Intoxicus** [comment]
They want you to use their OC Tune and the devs won't hear that how they're going about things is causing problems for people that want to do it manually.

**Comment by Yibo-de** [comment]
I tried OCTune a bit. Is there any way to just let msi afterburner handle the overclocking/undervolting and prevent QuickMiner from changing the setting after each "quick-swap DAG to..."? That would be very helpful, thanks!

**Comment by Intoxicus** [comment]
> I tried OCTune a bit. Is there any way to just let msi afterburner handle the overclocking/undervolting and prevent QuickMiner from changing the setting after each "quick-swap DAG to..."? That would be very helpful, thanks!

Nope, I tried to raise this issue and they're being all Expert's Mind about it and don't realize that they are causing crashes and problems for people with their refusal to let manual actually be manual.

**Comment by YF974** [comment]
bonjour , je suis un simple utilisateur , pour moi Nicehash quickminer fonctionne obligatoirement avec OCtune . 
mais avez vous essayer  msi afterburner  avec nice hashminer .
(nicehash miner,  est different , de , nicehash quickminer )

**Comment by Yibo-de** [comment]
ok. for now i'm just using OCTune, it does do the necessary work.

**Comment by Dohtar1337** [comment]
It is not recommended to use any OC tool if you are using OCTune for optimization. If you are not using OCtune or optimization profiles, then you should be fine using 3rd party tools like MSI afterburner.
