### ISSUE TITLE
Quickminer is crashing my laptop to shutdown with a Critical Event ID 41 error in Event Viewer

### ISSUE THREAD

**Issue by randommemer** [nicehash/NiceHashQuickMiner#571]
I've got a Legion 5 with a 2060 with OCtune set up at 900Mhz Core, 0.606V on the core, 6001(+500)Mhz Memory, drawing around 55W and 29MH/s. Temps are 55/65 core/hotspot. Driver version 466.27.

It usually doesn't crash for days, running it 24/7, but tonight, it was the 2nd time it crashed the laptop to shutdown for the past 4 days. I've seen QM crash but it's so rarely I can't ever catch it and since I can't read the logs myself, I decided to set up the crash behavior to "Do nothing" with the hopes of catching the error but so far it's only crashed 2 times, both during the night and when I wake up the laptop is shut down.

Interestingly, when I turn it on after the crash it boots up so much faster than usual, it doesn't even show the Lenovo logo. From shut down to password screen it takes around 3-4 seconds and usually on a regular day it much more.

Interestingly, even though I am pretty sure I pressed the full logging button, it didn't have any logs, so I only have one from just now which I am pretty sure is from too high of an OC. I had a higher wattage Vbios I installed myself and It used to be able to OC to +1000 memory but after I messed around with the Vbios versions again, it suddenly(I installed a new one and went back to the previous one) no longer could OC that high, and now everything above +500(a bit on the safe side) is unstable. The two shutdown crashes happened at +500 OC.

Here are the logs I have, even though they show only the crash I think is from high OC: https://drive.google.com/file/d/1g52xPZsvdeOvaDj2bPOmCgySxm6tBd7m/view?usp=sharing

**Comment by Dohtar1337** [comment]
This seems like a too aggressive overclock. This issue does not resemble issues related to QM directly.
