### ISSUE TITLE
[QUESTION] evga 3090 temps w/ fixed before and after opening/closing EVGA Precision X1

### ISSUE THREAD

**Issue by RobertLowe** [nicehash/NiceHashQuickMiner#573]
**Describe the bug**
After waking, I noticed my miner had crashed and reboot it as is the case very very seldomly. However after reboot, I noticed my temps were not my typical 100c, but were reaching 110c, I started to worry. I downclocked from 10001 to 9501, temps were 96c/98c. Here's where it gets weird. After closing nicehash, opening EVGA Precision X1, closing EVGA Precision X1, and launching NiceHash, my temps returned to their normal 100c at 10001.

Something about EVGA Precision X1 or nicehash's fan control is doing something weird. 

**To Reproduce**
1. Reboot
2. Start nicehash, use fixed fans at 100% on an evga 3090
3. Wait for temps to max out, record temps
4. Stop nicehash
5. Open EVGA Precision X1
6. Set fans to 100% 
7. Close EVGA Precision X1
8. Open nicehash again
9. Wait for temps to max out, record temps

Compare temps.

**Expected behavior**
Temps should be consistent

**Version affected (please complete the following information):**
 - Version number [e.g. 0.4.5.5]
 - RC or STABLE?

**NVIDIA driver version**
466.11

**Hardware**
EVGA 3090 XC3

**Comment by Dohtar1337** [comment]
Are you using optimizatio profiles? You should not. Instead, modify profile and edit the fan speed in OCTune. https://www.nicehash.com/blog/post/modify-existing-optimization-profiles

**Comment by RobertLowe** [comment]
@Dohtar1337 

I set speeds in `commands.json`, nothing out of the ordinary here. 

```json
[{
		"time": 0,
		"commands": [{
				"id": 1,
				"method": "device.smartfan.set",
				"params": ["GPU-b9ea769e-XXXX-XXXX-XXXX-XXX", "1", "100"]
			}, {
				"id": 1,
				"method": "device.set.oc_profile2",
				"params": ["GPU-b9ea769e-XXXX-XXXX-XXXX-XXX", "1065", "10001"]
			}]
	}, {
		"time": 20,
		"commands": [{
				"id": 1,
				"method": "workers.reset.all",
				"params": []
			}]
	}, {
		"time": 30,
		"loop": 30,
		"commands": [{
				"id": 1,
				"method": "worker.print.efficiencies",
				"params": []
			}]
	}, {
		"time": 1,
		"loop": 4,
		"commands": [{
				"id": 1,
				"method": "devices.smartfan.exec",
				"params": []
			}]
	}, {
		"event": "on_quit",
		"commands": [{
				"id": 1,
				"method": "devices.smartfan.reset",
				"params": []
			}]
	}, {
		"event": "on_quickminer.start",
		"commands": []
	}, {
		"event": "on_quickminer.stop",
		"commands": []
	}, {
		"time": 10,
		"commands": []
	}]
```

This is either NiceHash not engaging the 3rd fan (unlikely) or that EVGA Precision X1 does something sneaky, but the effect remains after closing EVGA Precision X1 and re-opening NiceHash.
