### ISSUE TITLE
bonjour , sur la rtx 3060ti de asus rog , il y a deux (2 ) connecteur a l'arrière pour deux (2) ventilateur 4pin , quel paramètre pour que sa fonctionne ??? merci pour l'aide  

### ISSUE THREAD

**Issue by YF974** [nicehash/NiceHashQuickMiner#574]
**Has the question been answered in [Wiki](https://github.com/nicehash/NiceHashQuickMiner/wiki)? There is no such question in [FAQ](https://github.com/nicehash/NiceHashQuickMiner/wiki/FAQ) or [Troubleshooting collection](https://github.com/nicehash/NiceHashQuickMiner/wiki/Troubleshooting)?**
Yes/No.

**Your question is...**
What is...

**Comment by Dohtar1337** [comment]
English only please.
