### ISSUE TITLE
[FEATURE] Add Custom Optimize setting 

### ISSUE THREAD

**Issue by Robert-Saiter** [nicehash/NiceHashQuickMiner#577]
Currently the optimize settings on the 3090 work well but Extreme reboots my PC.   I normally use High but can squeeze a bit more out with custom settings.  

In the app if I select an optimize profile (high for example) then I would like the ability to apply my customized settings.  Currently if I select Manual from the Optimize list my cards settings are defaulted to stock settings? It would be useful to have a custom profile option that I can select from the Optimize list instead.

**Comment by Dohtar1337** [comment]
You can modify optimization profiles: https://www.nicehash.com/blog/post/modify-existing-optimization-profiles
