### ISSUE TITLE
OCTune no longer works after update

### ISSUE THREAD

**Issue by RashadBasharat** [nicehash/NiceHashQuickMiner#58]
After updating to the latest revision of the RC, the OCTune as usual gets wiped (Perhaps these settings should be stored elsewhere?).
However, now whenever attempting to do the OC Tune, it can no longer properly attempt to mine and thus just defaults to 480MHz as the core clock.

![image](https://user-images.githubusercontent.com/43777028/108537404-7ca94280-72d5-11eb-9412-a582a2f18976.png)

**Comment by RashadBasharat** [comment]
To add to this, redownloading the fixed OCTune (which worked beforehand) also no longer works, with the exact same result.
My drivers haven't been updated in the meantime.
Perhaps a workaround for now is to the an older version to find the correct OCTune values then implement them into the current version of NiceHash?

**Comment by nicehashdev** [comment]
I just double checked if autotune works on latest RC and it does for me, so it must be something specific in your case.

**Comment by RashadBasharat** [comment]
> 
> 
> I just double checked if autotune works on latest RC and it does for me, so it must be something specific in your case.

Manually applying an undervolt/OC in Afterburner seems to work fine? I've got everything else turned off when OC Tuning.
Really strange as there's no difference between my setup yesterday and today

**Comment by Phosseh** [comment]
Having similar issues, everytime the miner restarts the OCTune values reset to default. Was fine before last update. A friend is reporting the same as well

**Comment by nicehashdev** [comment]
Make sure you click `Save current configuration`. If you do not do that, then OC values will not be applied next time you start miner. Also, on Rig Manager, you need to choose profile `Manual`. If you choose any other, then your OC values may be overwritten.

**Comment by nicehashdev** [comment]
Consider this not being an issue anymore. Closing.

**Comment by krilled** [comment]
I am experiencing this as well. 
![Screenshot 2021-02-24 103127](https://user-images.githubusercontent.com/74858449/109048392-e20d8280-768b-11eb-8a63-2b12d9c400e1.png)
