### ISSUE TITLE
[BUG] NiceHash not recognising my NVIDIA GeForce GTX1070

### ISSUE THREAD

**Issue by MystHairious** [nicehash/NiceHashQuickMiner#584]
**Describe the bug**
I download NiceHash but after i click "yes" to start the installation, I have a crash message saying there is no compatible graphic card/no NVIDIA. I really don't get it.. It[s a great gaming Pc (Predator G3). Should i try an older driver? or wait for the next one...?

**NVIDIA driver version**
Which one do you use?

**Hardware**
Name	NVIDIA GeForce GTX 1070
PNP Device ID	PCI\VEN_10DE&DEV_1B81&SUBSYS_1071174B&REV_A1\4&34CF19A9&0&0008
Adapter Type	GeForce GTX 1070, NVIDIA compatible
Adapter Description	NVIDIA GeForce GTX 1070
Adapter RAM	(1,048,576) bytes
Installed Drivers	C:\WINDOWS\System32\DriverStore\FileRepository\nvae.inf_amd64_bf0744701c56f1e7\nvd3dumx.dll,C:\WINDOWS\System32\DriverStore\FileRepository\nvae.inf_amd64_bf0744701c56f1e7\nvwgf2umx.dll,C:\WINDOWS\System32\DriverStore\FileRepository\nvae.inf_amd64_bf0744701c56f1e7\nvwgf2umx.dll,C:\WINDOWS\System32\DriverStore\FileRepository\nvae.inf_amd64_bf0744701c56f1e7\nvwgf2umx.dll
Driver Version	21.21.13.7319

**Logs**
Activate logging first, then record event - bug - then export logs into a .zip file and attach it when submitting this issue.

**Additional context**

**Comment by Dohtar1337** [comment]
Try reinstalling the GPU drivers: https://www.nicehash.com/blog/post/how-to-correctly-uninstall-and-install-gpu-drivers

**Comment by Dohtar1337** [comment]
no response
