### ISSUE TITLE
Disable GPU 0

### ISSUE THREAD

**Issue by HalbGott123** [nicehash/NiceHashQuickMiner#59]
With the stable release v0.3.0.2 i was able to disable my GPU 0 and only mine on GPU1 by entering:

"disabledDevices":["0"],

in nhqm.conf. 
But in the latest release v0.3.2.1 it seems like it´s not working and my GPU0 is always also mining.

**Comment by nicehashdev** [comment]
Does it work stopping it using Rig Manager?

**Comment by nicehashdev** [comment]
I see this feature was accidentally removed from website. Will be re-added on Monday.

**Comment by nicehashdev** [comment]
I just double checked disabledDevices feature by modifying config, It works on latest 0.3.2.1 RC. Make sure you don't forget to include quotes "".

**Comment by HalbGott123** [comment]
Okay looks like i forgot the quotes. With the quotes it is working as expected after restart. 
Thanks for the help

**Comment by nicehashdev** [comment]
The Rig Manager has reintroduced ability to Enable/Disable or Start/Stop devices. Issue resolved.
