### ISSUE TITLE
[FEATURE] Have the ability to add localised currency & electricity costs to get better profit estimation in Quickminer

### ISSUE THREAD

**Issue by HouseRoKKa** [nicehash/NiceHashQuickMiner#598]
**Is your feature request related to a problem? Please describe.**
Not having a clear profit estimation feature (like the Nicehash client has) is a problem!

**Describe the solution you'd like**
To have the facility to add a localised currency of our choice and then have the option to also add power costs, to get a better idea of what we are earning.  Currently, power costs are not taken into account when CURRENT ACTUAL PROFITABILITY / 24H is worked out, as far as I know.

**Describe alternatives you've considered**
Not sure of any alternatives except for adding in this feature, just like the Nicehash client has.

**Additional context**
-

**Comment by Dohtar1337** [comment]
Thank you for your feedback. We will think about adding this.
