### ISSUE TITLE
Start mining when idle [QUESTION] 

### ISSUE THREAD

**Issue by sepivip** [nicehash/NiceHashQuickMiner#599]
**Has the question been answered in [Wiki](https://github.com/nicehash/NiceHashQuickMiner/wiki)? There is no such question in [FAQ](https://github.com/nicehash/NiceHashQuickMiner/wiki/FAQ) or [Troubleshooting collection](https://github.com/nicehash/NiceHashQuickMiner/wiki/Troubleshooting)?**
Yes/No.

**Your question is...**
after asking for this feature, answer was it is implemented... its not woking if it is, but I cant find it... anu ideas?

**Comment by Dohtar1337** [comment]
We have this in our backlog.
