### ISSUE TITLE
Can find the option to change the service location to Brazil

### ISSUE THREAD

**Issue by ffebertt** [nicehash/NiceHashQuickMiner#6]
Can find the option to change the service location, its always using EU/USA servers. The nicehash miner has the BR option

**Comment by tlamming** [comment]
Read the readme file. there are two locations for now, 0 for europe 1 for usa. Use usa as its likely a faster connection.

**Comment by nicehashdev** [comment]
There is no more Brazil location; If you are from Brazil, I suggest you to choose USA. Soon, there will be USA East also and you might check it out which one is better then.

How to change mining location: https://github.com/nicehash/NiceHashQuickMiner/wiki/Tips-&-tricks#1-choose-your-service-location-to-improve-your-latency-and-reduce-number-of-stale-shares
