### ISSUE TITLE
Tons of job not found

### ISSUE THREAD

**Issue by Disparatado** [nicehash/NiceHashQuickMiner#60]
Hi, i just started getting very many jobs not found and the online dashboard is 0.00000
1 share found, 1 not found, but still at 0 profitability
Is something happening on server? dont see any issues on status

**Comment by Disparatado** [comment]
looks ok now, some site update i presume, seeing optimize button on the web page

**Comment by Disparatado** [comment]
![obraz](https://user-images.githubusercontent.com/78882077/108561273-3ddbb280-72fe-11eb-90d0-3dca0d3e48f9.png)
and again tons of not found :(

**Comment by yungleballz** [comment]
Can confirm this.
First i got 40minutes of duplicates then, after a restart of excavator, job not found.

**Comment by Disparatado** [comment]
i think they are doing something and have to restart some services, and now the new optimize button is gone that appeared during previous crashes, but its just my observation

**Comment by Disparatado** [comment]
ok, now server error fails, going to stop mining now and play a game :)

**Comment by nicehashdev** [comment]
This is not an issue if QuickMiner but servers. And these isssues were fixed yesterday. Closing.

**Comment by Disparatado** [comment]
its BACK!

**Comment by Disparatado** [comment]
you could at least drop some info on the status page when you are doing something, so we don't start resetting all devices and routers for gods sake!
