### ISSUE TITLE
Running installer errors saying "unable to connect to remote server"

### ISSUE THREAD

**Issue by WolfwalkerRSC** [nicehash/NiceHashQuickMiner#601]
so, i downloaded the installer for NH and I allow my AV to continue running the file and afterward, it errors out saying unable to connect to remote server, what does this mean and how do I fix it.

**Comment by WolfwalkerRSC** [comment]
![image](https://user-images.githubusercontent.com/86278639/124876998-79121180-df7f-11eb-8a27-030048f811bf.png)

**Comment by WolfwalkerRSC** [comment]
oh ok, i will look into it and see what the issue is

**Comment by tgnade** [comment]
I'm getting the same error this morning. It won't even install - which port do I need to open up? I can't find any reference to a specific port or protocol that might need to be open for this to work. Please assist.

**Comment by Dohtar1337** [comment]
@tom-gnade what router are you using? Have your tried my previous reply?

**Comment by Dohtar1337** [comment]
No response, closing

**Comment by klack** [comment]
I got the same error.  I use Bitdefender.  You need to disable items in "Online Threat Prevention".  I'm not sure what to allow through the exception list yet.  Maybe a dev can chime in on that?
