### ISSUE TITLE
updates

### ISSUE THREAD

**Issue by neo-jubil** [nicehash/NiceHashQuickMiner#603]
**Has the question been answered in [Wiki](https://github.com/nicehash/NiceHashQuickMiner/wiki)? There is no such question in [FAQ](https://github.com/nicehash/NiceHashQuickMiner/wiki/FAQ) or [Troubleshooting collection](https://github.com/nicehash/NiceHashQuickMiner/wiki/Troubleshooting)?**
Yes/No.

**Your question is...**
What is... 
 Hello, I have version v0. 5. 1. 3 is it worth making updates to v0. 5. 2. 0 RC

**Comment by Dohtar1337** [comment]
It wont make difference performance wise. But there could be some new features/bug fixes. Check release page for differences.

**Comment by neo-jubil** [comment]
> Это не будет иметь значения с точки зрения производительности. Но там могут быть некоторые новые функции/исправления ошибок. Проверьте страницу выпуска на наличие различий.

ок
