### ISSUE TITLE
[QUESTION] Did this project die?

### ISSUE THREAD

**Issue by amore514** [nicehash/NiceHashQuickMiner#605]
When the NiceHashQuickMiner Project started I saw lots of updates, bug fixes, questions answered, etc. Now it seems there is a slowdown? No new releases, no comments on questions, Bug reports, Feature requests, What happened? Is the NHQM project dead?

**Comment by xantari** [comment]
sure seems that way...

**Comment by Dohtar1337** [comment]
No, the project did not die. It did slow down. We will slowly release more updates, but for now, they wont be as frequent as before.
