### ISSUE TITLE
Nicehash Quickminer won't start

### ISSUE THREAD

**Issue by ukj0nada** [nicehash/NiceHashQuickMiner#606]
Every morning for 3 months now, I wake up, turn the computer on and start NHQM, this morning I get a windows message error 
"windows cannot access the specified device path or file. You may not have the appropriate permissions to access the item"

My windows defender and webroot antivirus software are always turned off.

I check the permissions all ok.
I check quarantines, nothing in them.
I have included as exceptions anyway should they start up.

I go to uninstall, I get the same message on that command.

I go to github to download again and I get the same message on the program file when I click it.

Please help.

**Comment by Dohtar1337** [comment]
Most likely something is blocking it. Do you have PUA enabled in Windows Defender? Disable it and try again.

**Comment by Dohtar1337** [comment]
No response, closing

**Comment by PP123456678** [comment]
dude mine says i do not have appropriate perms to open the file and a random avast file opens up. I even tried uninstalling avast but it wont work. Any solutions?
