### ISSUE TITLE
[FEATURE] Add a way to enable "Game Mode" in the NiceHash app.

### ISSUE THREAD

**Issue by LaserLag** [nicehash/NiceHashQuickMiner#607]
It would be great if we could enable Game Mode from the app. Or if the "Stop" mining button also set your GPU clock back up to stock settings - mine stay on the mining optimized clocks when I click Stop either on the tray icon or the app.

I play a lot of games on my TV with a controller via streaming from my PC. It can be a hassle to minimize the game I launched and then click the tray icon to enable game mode. And then I have to remember to disable game mode afterwards. It would be great if this could all be viewed and controlled from the app.

**Comment by Dohtar1337** [comment]
Thanks for the feedback. For now, we will not implement this.
