### ISSUE TITLE
Nvidia 1650 ti max q worker crashing [BUG] 

### ISSUE THREAD

**Issue by mpacek12** [nicehash/NiceHashQuickMiner#608]
Nicehash worker not runing on Nvidia 1650ti max q 4GB RAM
crashing with No compatible dvices found! message see output below:

=========================== www.nicehash.com =========================
           Excavator v1.7.1d GPU Miner for NiceHash.
           Copyright (C) 2021 NiceHash. All rights reserved.
=========================== www.nicehash.com =========================

Build time: 2021-04-19 22:09:27
Build number: 880
Provided startup commandline: -c commands.json -qx -qm -d 2 -f 6 -wi localhost -wp 18000 -wa 736EA0A2518B1E1986AE4307

[18:19:33][0x00002ffc][info] Log started, build v880
[18:19:34][0x00002ffc][error] core | No compatible devices found!
[18:19:34][0x00002ffc][info] http | Listening on [::1]:18000
[18:19:34][0x00002ffc][info] core | Initialized!

Tried on differnet Nvidia dirver, curently 670.05

**Comment by Dohtar1337** [comment]
4GB cards are not supported.
