### ISSUE TITLE
[BUG] GTX 1080 Efficient Profile - Crashes when switching

### ISSUE THREAD

**Issue by TimSirmovics** [nicehash/NiceHashQuickMiner#610]
**Describe the bug**
I have a GTX 1080, and the efficient profile is the best performing profile for my card.
This profile can run 24/7 without issue.

The issue comes when I need to:
1. Restart mining after having it stopped, or
2. Switch from Manual to Efficient mode

What I have observed is after mining in efficient mode, then stopping, then re-starting, there is some % chance that it will restart fine, and some % chance that the PC will crash.
To reduce the chance of this, I stop the miner, change to manual mode, and then mine for a small mount of time in manual mode with a reduced hash rate.
Then I stop the miner and go to the web interface.
The first hurdle is switching it back to efficient mode. This has roughly a 50% chance of the PC crashing, 50% chance it will switch ok.
The second hurdle is then re-starting mining. This will always run ok at 0 hash rate for about 10 seconds, until something happens and it either successfully switches to the normal hash rate, or the PC crashes, again roughly a 50% chance of each.

I have tried lots of different combinations to reduce the % it crashes, but I can't pinpoint what it is.
The fact that it occurs even when switching profiles, not mining, seems to indicate it is something to do with applying the memory timings when the GPU / system is in a certain state.

**To Reproduce**
I don't know if this is specific to the 1080, or just some 1080s, or just my particular setup.
Try:
1. Mining with the efficient profile, stopping, restarting.
2. Mining with the manual profile, stopping, applying the efficient profile and restarting mining

**Expected behavior**
Because the issue is not consistently reproducible, I suspect that it is to do with the current state of the card's memory, or some other variable, at the time of switching. I am hoping that this invalid memory state / variable could be detected. Or at least some logs could be produced which might point to the problem.

**Screenshots**
N/A

**Version affected (please complete the following information):**
v0.5.1.3 Stable

**NVIDIA driver version**
471.11 DCH
(Issue does not change between driver versions)

**Hardware**
GTX 1080, connected directly to PCIe slot.
i7-3770k

**Logs**
I exported the logs but they didn't look to contain anything relevant.
I can attach if required.

**Comment by Alterston** [comment]
Hi friend. I ran into exactly the same problem as yours.

In my case, Titan x (Pascal) video cards are 2 pieces.
When the "effective" profile is applied, the system crashes and you have to reboot the computer manually.

How do I get to solve this on reboot.

1) I start the miner and select the "manual" profile

After a few minutes I select the "effectively low" profile, it tries to work with some kind of CUDA error in the "Excavator" log file. And after this error, the miner will reboot. After the error disappears. Then I switch to the "effective" profile. And there is a high probability that the rally will not happen. But this does not always help, as I understand it, the problem arises when changing memory timings.  
I hope the developers will help solve this problem and we will finish dancing with a tambourine around the video cards.
p.s
Forgive me my English, I use google translate * (

**Comment by Alterston** [comment]
update!

Friend! By the method of a long search in forums and other resources, I found a solution to this problem.

1) run the program "Nvidia Profile Inspector"
2) when you are running that, go down to section 5: there is a setting "CUDA - Force P2 State". Set this to "Off" and click "Apply Settings" button on the top right.

3) Done! now in the riga, switching to the "effective" profile will occur without crashing.


Sorry for my English, I use google translate

**Comment by TimSirmovics** [comment]
Fantastic.. so far so good.
Will see in a couple of days if this has fixed the issue permanently.

**Comment by TimSirmovics** [comment]
I believe it has fixed the issue. Thanks!
