### ISSUE TITLE
[FEATURE] OCTune logging

### ISSUE THREAD

**Issue by gwurb** [nicehash/NiceHashQuickMiner#613]
**Is your feature request related to a problem? Please describe.**
I would like a sufficiently long record of GPU temperatures, OC settings, and fan speeds. 

**Describe the solution you'd like**
An API to poll OCTune/Quickminer for data, and have a json return. This would allow something like a python script to retrieve the current GPU temp, VRAM temp, fan speed, GPU utilisation, and OC setting to be retrieved and stored in a place of choice. For example that data could be stored in a CSV or SQL. It would also allow for later plotting and analysis. Additionally it could allow for a warning system where the script can be used to alert when a particular value breaches a threshold. Given an API the end user could write scripts for their needs.

**Describe alternatives you've considered**
I am not aware of any other utility that provides an API for remote monitoring of gpu fan and vram temp information. I have looked at options given by HWInfo but that has extra costs and does not provide OCTune set OC values. Given this data is shown on OCTune monitoring webpage I have considered trying to write my own JavaScript to log the data. But, I would prefer a more universal approach that can be used across a number of programming languages.

**Comment by Dohtar1337** [comment]
We have already discussed some way of implementing longer mining stat history. Unfortunately, it would take a lot of resources to track everything on our servers, so we might do this locally. Thank you for reaching out!

**Comment by gwurb** [comment]
Hi,
I do not mean via nicehash servers.

Right now a webpage polls local instance of OCTune for information. A JavaScript is used? Is it possible to poll local instance of OCTune with python? What would be the calls to use?

My request is to have published calls or API to poll local instance of OCTune as OCTune is able to report fan and temperature information.

Is it possible to obtain information from OCTune via python?

**Comment by xr1140** [comment]
You can get the info via Excavator API. Look for the "device.get".

**Comment by Dohtar1337** [comment]
Yes, this all is possible through excavator API. https://github.com/nicehash/excavator/blob/master/api/README.md

We do plan to implement something similar.
