### ISSUE TITLE
[QUESTION] Usa Option?

### ISSUE THREAD

**Issue by conetopia** [nicehash/NiceHashQuickMiner#614]
**Has the question been answered in [Wiki](https://github.com/nicehash/NiceHashQuickMiner/wiki)? There is no such question in [FAQ](https://github.com/nicehash/NiceHashQuickMiner/wiki/FAQ) or [Troubleshooting collection](https://github.com/nicehash/NiceHashQuickMiner/wiki/Troubleshooting)?**

Looked at the links here, not seeing any documentation on how to switch the Miner from EU Default, to USA.

serviceLocation -1 = auto
serviceLocation 0 = eu west
serviceLocation 1 = usa west
serviceLocation 2 = eu north
serviceLocation 3 = usa east

"launchCommandLine" : "-qx -qm -d 2 -f 6",

So in the NHQM file, I would just take that defaulted 2 before the -f , and change it to -1 for fun, otherwise 1 or 3 ? how to know whats best if living in USA-Wisconsin? kinda central, assumeing US east would be better.

How Ever when i change from 2 to 3, and then go to start, the command Prompt log only shows excavator v1.7.1d
== Nicehash.com==
excavator
copyright
===
build time ....
build number 880
provided startup commandline : -c commands.json qx qm -d 3 -f 6 -wi localhost ect...

Nothing else.
 but when i change it back to 2, it tells me everything like... Speed/wattts newjob ect ect.
Online view it seems that the miner is working at 27MH on a gtx 1080 vs 18mh with a 2 instead of the 3.
so changing that to 3 is way better mining on usa, than eu, i assume location changed, just sad that there is no active command prompt???

**Comment by conetopia** [comment]
serviceLocation -1 = auto
serviceLocation 0 = eu west
serviceLocation 1 = usa west
serviceLocation 2 = eu north
serviceLocation 3 = usa east

"launchCommandLine" : "-qx -qm -d 2 -f 6",

So in the NHQM file, I would just take that defaulted 2 before the -f , and change it to -1 for fun, otherwise 1 or 3 ? how to know whats best if living in USA-Wisconsin? kinda central.

**Comment by paulpv** [comment]
This bug report makes little sense.
https://github.com/nicehash/excavator#-command-line-parameters
```
-d | 0-6 | Console log level | 2
-f | 0-6 | File log level | 6
```

@conetopia changed `-qx -qm -d 2 -f 6` to `-qx -qm -d 3 -f 6`

-d just changes the console log level...which probably keeps it from printing speed/watts/newjob/etc.

To change the service location just change the authorization serviceLocation field:
```
{
	"CPUMinerELP" : "--cpu-max-threads-hint 50 --print-time 15",
	"authorization" : {
		"BTC" : "...",
		"groupName" : "",
		"serviceLocation" : -1, <-- change this
		"uniqueID" : "...",
		"workerName" : "..."
	},
        ...
```

**Comment by conetopia** [comment]
@paulpv What im saying is, option 3 doesn't work.

**Comment by paulpv** [comment]
Option `3` does not work in the `launchCommandLine` that you mentioned.
`-d 2` to `-d 3` only changes the console logging level.

Option `3` does work in the `authorization`.`serviceLocation` field.

**Comment by Dohtar1337** [comment]
Wont be needed in the future. We will implement auto locations. Closing
