### ISSUE TITLE
GDDR6 VRAM temperature reported by QuickMiner appears to be bogus

### ISSUE THREAD

**Issue by gigaplex** [nicehash/NiceHashQuickMiner#616]
I have a 3070 that uses GDDR6 VRAM. The release notes for v0.5.1.3 added support for VRAM temperatures for GDDR6, yet the number reported doesn't look remotely accurate. A VRAM temperature of 42 Celsius does not look plausible when mining ETH, especially when the GPU itself is warmer than that (44C average, 57C hot spot). We know from AMD cards that use GDDR6 that VRAM temps frequently exceed 80C when mining ETH.

https://imgur.com/Q19SAda

Expected outcome:
Any of the following:
- An explanation of where this number is reported from when these cards don't have a sensor
- A way to disable this and have QuickMiner revert back to the old behaviour of reporting the Hot Spot temperature instead. That measurement has value but it was removed in favour of the ambiguous VRAM measurement. The fan control options also seem to ignore the hot spot when it thinks it knows the VRAM temperature.
- VRAM measurement accuracy to be fixed if possible

**Comment by ngoue** [comment]
I've got a Gigabyte 3070 Vision (LHR) that's doing the same thing.

**Comment by Dohtar1337** [comment]
Is this issue still ongoing with the latest QM version?

**Comment by gigaplex** [comment]
Yes, issue persists in 0.5.3.5 RC

**Comment by DasIstWalter** [comment]
Still present on 0.5.3.6 RC. VRAM sensor actually reports the gpu hotspot temp on my 6700 XT
![nh](https://user-images.githubusercontent.com/80215729/166856411-da51c07a-6807-4214-a6a6-e5eca7d5f224.png)

**Comment by tjayz** [comment]
Per the initial poster, I concur this reading on Nvidia GDDR6 is bogus, it is actually giving readings for the VR VDDC which is useless next to the GPU hotspot temp, given there is no VRAM sensor on GDDR6. No clue why such would be implemented but please put the GPU hotspot temp back in its stead. Thanks.

**Comment by Dohtar1337** [comment]
We will fix this. Closing
