### ISSUE TITLE
[QUESTION] How to set all power modes via api?

### ISSUE THREAD

**Issue by bondiblueos9** [nicehash/NiceHashQuickMiner#625]
The Nicehash API allows settings power mode via POST to '/main/api/v2/mining/rigs/status2' to LOW, MEDIUM, or HIGH, which then shows up on the web interface as "Optimize", Lite, and Medium.  It doesn't seem to accept any other obvious values, so I can't figure out how to use the API to set the power mode to High, Efficient, Efficient Low, Extreme, etc.  Is there a different API call to use, or are there different power modes that are accepted to get the same results as with the web interface?

**Comment by Dohtar1337** [comment]
This question is already being answer on here 
https://github.com/nicehash/rest-clients-demo/issues/38#issuecomment-897089592
