### ISSUE TITLE
[QUESTION] Quick miner dosnt work with a rtx 3050 gpu?

### ISSUE THREAD

**Issue by Vithujap** [nicehash/NiceHashQuickMiner#626]
**Has the question been answered in [Wiki](https://github.com/nicehash/NiceHashQuickMiner/wiki)? There is no such question in [FAQ](https://github.com/nicehash/NiceHashQuickMiner/wiki/FAQ) or [Troubleshooting collection](https://github.com/nicehash/NiceHashQuickMiner/wiki/Troubleshooting)?**
No.

**Your question is...**
Hello, does rtx 3050 work with quickminer?  i downloaded quickminer for my laptop and whenever i run the software, i get an error saying "No compatible devices found".

**Comment by Dohtar1337** [comment]
No, 4GB cards are not supported as they are not able to mine DaggerHashimoto
