### ISSUE TITLE
[FEATURE] enable/disable game mode with a (keyboard) shortcut & auto game mode

### ISSUE THREAD

**Issue by adi170-alt** [nicehash/NiceHashQuickMiner#627]
**Is your feature request related to a problem? Please describe.**
I think that it is more easy to have a shortcut that u can press/it auto enabling it to a chosen application(/game) to go game because enable it every time when u go game

**Describe the solution you'd like**
The most user-friendly way I think to add it to the settings ui, I think that it would be good to have a shortcut(for example: ctrl+shift+g), I also thought that it would be a good idea to ask to add auto game mode, so u just chose an exe/application/folder(each time something runs in a specific folder) and each time u turn game mode on by a shortcut or auto game mode, a little green popup comes up in a chosen location(I would like it to be in the right bottom of my screen)

**Describe alternatives you've considered**
auto game mode

**Additional context**
none

**Comment by ZexMaxwell001** [comment]
I would like this feature. but at minimum, it should auto turn off game mode the moment you start hashing. currently in v0.5.1.3 stable, when you start up hashing, game mode remains on with un-optimal settings for the task.

**Comment by adi170-alt** [comment]
owh yea ik, thats the reason why I thought about auto game mode, start u game, it knows you play a game, it starts game mode, you exit the game game mode turns of becouse it knows, if it wouldnt do that then i think it would be not as usefull

> I would like this feature. but at minimum, it should auto turn off game mode the moment you start hashing. currently in v0.5.1.3 stable, when you start up hashing, game mode remains on with un-optimal settings for the task.

owh yea ik, that's the reason why I thought about auto game mode, start u game, it knows you play a game, it starts game mode, you exit the game, game mode turns of because it knows, if it wouldn't do that then I think it would be as useful.

**Comment by PabloDons** [comment]
I often forget to enable game mode before I start a fullscreen game, which I then have to tab out of in order to access my taskbar so I can enable game mode from the nicehash icon. A bit annoying. Some way of enabling game mode without tabbing out would be nice. Like a keyboard shortcut

**Comment by brbornia** [comment]
Looks like the same feature recently launched in Nicehash Miner: 
https://www.nicehash.com/blog/post/new-nicehash-miner-feature-pause-mining-when-playing-steam-games.
This would be a huge improvement.

**Comment by adi170-alt** [comment]
> Looks like the same feature recently launched in Nicehash Miner: https://www.nicehash.com/blog/post/new-nicehash-miner-feature-pause-mining-when-playing-steam-games. This would be a huge improvement.

I updated my nicehash quick miner today, and I was surprised for an update because there weren't any in a long time, but could not find anything new related to auto game mode or hotkey for gamemode, it seems like they have added it only to the full miner

**Comment by limacohen** [comment]
I, for one, don't need any fancy "game detection" thing. Lots of my games/programs are outside of Steam, so it's doomed to fail. Just give me a keyboard shortcut and/or make single clicking the traybar icon also pause the miner.

**Comment by adi170-alt** [comment]
> I, for one, don't need any fancy "game detection" thing. Lots of my games/programs are outside of Steam, so it's doomed to fail. Just give me a keyboard shortcut and/or make single clicking the traybar icon also pause the miner.

Yea, that's the main thing that I want them to add, because the detection thing will probably never be perfect at all.
A shortcut for things like game mode should already been added, I don't think that it is very hard to add it if u know how to make a whole miner.

**Comment by Dohtar1337** [comment]
We will implement the same feature as NHM has to stop mining if steamgame is launched. 

This shortcut feature will not be implemented

**Comment by adi170-alt** [comment]
Doesnt work becouse I have wallpaper engine on, and it thinks that it is a game running

**Comment by limacohen** [comment]
It really is a terrible idea trying to automatically detect games just because they are launched by Steam. It opens up so many points of failure and it will inevitably result in more issues being open. Not to mention it won't work for Battlenet/Origin/Uplay/Epic/GOG, etc.
Off the top of my head, here are some better ideas/implementations to control Game Mode:
- Keyboard shortcut.
- Clicking the taskbar icon.
- (Proper, simple) API access.
 - Command-line switch, so you can launch the QM .exe with a flag just to switch GM.
 - And the fanciest, if you want to go fully automated: Detect when a process is eating a certain % of the GPU and pause the miner. Resume when it's down that threshold for X seconds or if it's killed.
