### ISSUE TITLE
[FEATURE] MQTT Publishing for GPU stats/Mining Stats

### ISSUE THREAD

**Issue by Lollitoe** [nicehash/NiceHashQuickMiner#632]
If we could have MQTT publishing made available that would be pretty awesome for custom dashboards and integration into a variety of systems.

Parameters to be exposed to MQTT

GPU ID | GPU Name | MinKT | AvgKT | UMedKT | HWerr | HWok | CoreDelta | MemDelta | PowerLim (W) | TDPLim (%) | PowerReal (W) | Speed(MH/s) | Eff. (kH/J)

GPU ID | GPU Name | Temperature(℃) | Utilization(%) | Fan(RPM) | Fan level | Fan settings | Core(MHz) | Core Limit(MHz) | Core Volt.(mV) | Memory(MHz)

**Comment by sparkiesweden** [comment]
+1

**Comment by Dohtar1337** [comment]
Obsolete. Will not implement or will the issue is to old. Closing.
