### ISSUE TITLE
NVIDIA Titan X Pascal

### ISSUE THREAD

**Issue by Alterston** [nicehash/NiceHashQuickMiner#636]
Hello friends. I wanted to know. What overclocking settings to use for overclocking NVIDIA Titan X Pascal. What is the hashrate of your Titan x Pascal? Recently, I have dropped hasreate to 38 MH / s and does not rise above 39. And before it kept 40 - 42 MH / s. The rig settings are now on the "effective" bar. post temp 70 - 75 degrees. Tell me how to overclock the card efficiently and correctly. Thanks!

P.S Sorry for my English, I use google translate.

**Comment by Dohtar1337** [comment]
These GPUs tend to drop performance over time due to increasing DAG size.
