### ISSUE TITLE
Mining Stop with Power Consumption issue

### ISSUE THREAD

**Issue by HtinKyaw84** [nicehash/NiceHashQuickMiner#637]
one GPU is on board (1060 6GB Zotac)
another GUP connect with Riser with separate power supply (1060 6GB igame)

Now issue is riser GPU and show " could not obtain power consumption"
already tried
**Driver uninstall with DDU
Riser Changed
power supply changed
Nicehash Third party miner software changed
different  OC setting but issue still in there.**
 Pls help
![Nicehash Miner issue](https://user-images.githubusercontent.com/89276179/131223413-2b70986e-3c00-4de8-8dec-052e730a7725.jpeg)

**Comment by Dohtar1337** [comment]
Does GPUz show the power reading?
Is the issue still persisting or can we close this?
