### ISSUE TITLE
What is OTHER?

### ISSUE THREAD

**Issue by Disparatado** [nicehash/NiceHashQuickMiner#64]
![obraz](https://user-images.githubusercontent.com/78882077/108603349-b9456e80-73a7-11eb-87ad-4983ceda5d5c.png)

**Comment by Disparatado** [comment]
there was no mention in the guide about other shares rejected, please elborate

**Comment by nicehashdev** [comment]
It is a stale share, but market a bit differently on the backend because it happens a bit different.

**Comment by Disparatado** [comment]
What might be the cause of them, and is there any way to counter them? or are they just random?

**Comment by nicehashdev** [comment]
Like I said, it is a form of stale which means your miner was too late.
