### ISSUE TITLE
[BUG]  Removed inactive rig comeback and can not remove it

### ISSUE THREAD

**Issue by aestu71** [nicehash/NiceHashQuickMiner#640]
Hi since last update removed inactive rig comeback and can not remove it.
When try to remove, may b 1-2 rig can be removed but after reflesh page, it comeback again.

**Comment by LinoDi** [comment]
Same problem here. This problem has slightly changed for me.  Before I wasn't able to delete them at all.  Now I am able to delete them and the deleted rigs just keep reappearing.  Tried several times through the day.  I tried reinstalling the quick mining software and there was no change.
