### ISSUE TITLE
[BUG] Notification that rig is off-line when game mode is activated

### ISSUE THREAD

**Issue by MarcusUA** [nicehash/NiceHashQuickMiner#643]
**Describe the bug**
After activating game mode, in around 30 minutes I receive on-site, email and push notification that NS detected rig is offline.
In Rig Manager on nicehash.com rig is reported as Stopped (which is correct), but notification still appears.

**To Reproduce**
1. Activate Game Mode
2. Notification email/push arrives in around 30 minutes.

**Expected behavior**
Once Game Mode is activated NiceHash Rig Manager should not send a notification about.

**Version affected (please complete the following information):**
 - v0.5.2.0 RC (but previous versions also has this issue

**OS**
Windows 10/11

**Comment by MarcusUA** [comment]
v0.5.3.3 RC still has this issue.

**Comment by Dohtar1337** [comment]
We are aware of the bug, but will not fix it now.
