### ISSUE TITLE
[BUG] Error on bios Palit_GTX1660SUPER-6G 90.16.59.00.28

### ISSUE THREAD

**Issue by lonelymyp** [nicehash/NiceHashQuickMiner#644]
After flashing to a more recent BIOS, 90.16.59.00.28 the mining speed is not displayed, writes the error of power.
But the mining speed is displayed normally in the popup menu.
[22:47:12][0x00002680][warning] core | Device #0-0 could not obtain power consumption!
![image](https://user-images.githubusercontent.com/2085051/132256921-d9b26f38-4e11-4ca6-b31a-4eb63aac8287.png)
![image](https://user-images.githubusercontent.com/2085051/132256949-469a82fd-bfd4-4444-ac1a-e523e32a0705.png)

**To Reproduce**
Flash new bios

**Version affected (please complete the following information):**
 - Version number [0.5.2.0] RC

**NVIDIA driver version**
465.89

**Hardware**
Palit 1660 SU Hynix

**Comment by YF974** [comment]
hello reinstal driver , DDU, update DRIVER NON DCH
