### ISSUE TITLE
Cannot Exit, Stop, etc.

### ISSUE THREAD

**Issue by Disparatado** [nicehash/NiceHashQuickMiner#65]
![obraz](https://user-images.githubusercontent.com/78882077/108605144-a84e2a80-73b2-11eb-9751-83c3915401f4.png)

I cannot use the taskbar options, it does not register any click on it :/ i have to force shutdown from manager :/

**Comment by nicehashdev** [comment]
Please, activate logs and submit them here (remove your personal BTC address).

How to activate logs: https://github.com/nicehash/NiceHashQuickMiner/wiki/Tips-&-tricks#4-enable-logging-for-better-troubleshooting
