### ISSUE TITLE
[BUG] One gpu's frequency and hashrate reduced by Windows 10 OS

### ISSUE THREAD

**Issue by soundguy0** [nicehash/NiceHashQuickMiner#650]
**Describe the bug**
Using Windows 10 with Quickminer 0.5.1.3 stable there are moments, when 1 gpu is underclocking way too much and this issue reduces hashrate of the cards. I am speaking of multiple 3070s usage in two different rigs.

I thought and i guess this is related to Windows OS, maybe the OS is switching power regimes of the primary card, used for graphical output to display (even when no display is connected) and rendering the desktop.

I have tried changing Power settings in Nvidia control panel from "normal" to "adaptive" and to the "prefer max performance" which resulted no change or any sign of improvement.

Multiple 3070 are running 1300-1500 mhz on gpu core, but one is always running on 600 mhz and this reduces the performance and the final hashrate (3-5mhs). Memory frequency is not affected.

**Expected behavior**
All same vendor cards and type running similar gpu core frequency.

**Screenshots**
I think it is well explained

0.5.1.3

**NVIDIA driver version**
471.11 and below

**Hardware**
multiple 3070 from asus tuf oc, connected via pcie 1x using risers and short usb cable
intel celeron g5900

**Logs**
-

**Additional context**
If the windows behaviour could not be changed, maybe quickminer could support also setting the lowest frequency limit for gpu core of each card.

Thank you

**Comment by Dohtar1337** [comment]
Please update the drivers.
Please confirm that the issue is still present with the latest version. I will reopen the ticket if the issue is still persistent
