### ISSUE TITLE
[BUG] Game Mode doesn't restore TDP if set to 114%

### ISSUE THREAD

**Issue by bluehallu** [nicehash/NiceHashQuickMiner#651]
**Describe the bug**
Activating game mode if TDP is configured to 114% doesn't set the TDP at all, leaving users with the mining TDP setting regardless of game mode. Configuring it to 113% produces expected behaviour. 

The miner doesn't error either, it sets memory and core clock but omits TDP. 

**Expected behavior**
Error of invalid setting and/or automatically setting to max valid value

**Version affected (please complete the following information):**
0.5.1.3 STABLE

**NVIDIA driver version**
472.12

**Hardware**
3070

**Comment by Dohtar1337** [comment]
You should not be able to set TDP to more than 100%.

Not a bug.
