### ISSUE TITLE
GTX titan 6gb Help me!! 

### ISSUE THREAD

**Issue by githubway2us** [nicehash/NiceHashQuickMiner#658]
**Has the question been answered in [Wiki](https://github.com/nicehash/NiceHashQuickMiner/wiki)? There is no such question in [FAQ](https://github.com/nicehash/NiceHashQuickMiner/wiki/FAQ) or [Troubleshooting collection](https://github.com/nicehash/NiceHashQuickMiner/wiki/Troubleshooting)?**
Yes/No.

**Your question is...What's The driver for GTX Titan 6gb for  mining**
What is...What v.? Driver for GTX titan 6bg for nicehash

**Comment by Dohtar1337** [comment]
need additional info. Please comment below if the issue still persists
