### ISSUE TITLE
QuickMiner does not start

### ISSUE THREAD

**Issue by lucs100** [nicehash/NiceHashQuickMiner#66]
![image](https://user-images.githubusercontent.com/59773132/108606516-758f3c80-7388-11eb-9da0-5f810aaff428.png)

QuickMiner does not start mining while it is running. The "open" button opens a tab linking to my list of active rigs (not sure if this is intended behavior or if it's supposed to open the mining cmd window). As well, the OCTune window doesn't show any information.

**Comment by avileena** [comment]
make sure you excluded QuickMiner folder in your antivirus app.

**Comment by nicehashdev** [comment]
Yes, make sure that you have all files and that AV did not delete any. If there is no Excavator, then you must be getting periodic warning that Excavator does not exist!

**Comment by nicehashdev** [comment]
Consider this not being an issue anymore since there was no response. Closing.
