### ISSUE TITLE
why does  my mining rig show unmanaged and offline for the past 1 month 

### ISSUE THREAD

**Issue by ajhkHD** [nicehash/NiceHashQuickMiner#661]
i was mining for a few day then 1 morning i started mining, so then i went on the webpage for nicehash then i showed offline after 1-2 days i checked back in then it showed unmanaged i checked all of the plugs that connected my pc to my motherboard then i plug it in again but still unmanaged i deleted nicehash quick miner and nicehash miner still it stills show  either offline or unmanaged i do not know why. please help me i checked support that didn't help  and YT videos still no help.

**Comment by Dohtar1337** [comment]
Are you using ASUS or microtrend router? Please try disabling it.

Also, please contact your ISP provider and ask to whitelist nicehash.com or ask them what traffic are they blocking. 
We have seen reports where ISP or router does only allow part of the nicehash traffic to go through.

Please let me know what ISP are you using in case that the ISP was the issue.
