### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by SeemsToMe** [nicehash/NiceHashQuickMiner#670]
I am new to NiceHash Mining software and attempting to download the installer.  All of my attempts to download are failing and I do not see any visible reason why.   When I hover over the downloaded file in Firefox it says failed and when I look at the file in my downloads folder it is 0 bytes.   I have tried both the installer app and the zip file.

I am at this web site when I click the link to go to downloads:
https://github.com/nicehash/NiceHashQuickMiner/releases

It does not seem to matter which version (one of the pre-releases or the latest stable version), I cannot seem to download the installer.

I have tried in both Firefox and in Chrome, so I do not think it is a problem on my end.

**Comment by Dohtar1337** [comment]
Check this: https://www.nicehash.com/support/mining-help/nicehash-miner/my-browser-antivirus-software-reports-nhm-as-a-virus

Is the issue still persistent?
