### ISSUE TITLE
[BUG] Wrong Detect the power

### ISSUE THREAD

**Issue by WaiTangHK** [nicehash/NiceHashQuickMiner#671]
**Describe the bug**
My rig is installed two 3060 non-LRH
the mining is keeping normal, but after running around 2-3 hrs, Device #0-0 will wrong detect the power to 1000.00W
and that time nicehash mining page will can't check the status of this rig, but no any offline notice, because the mining is keeping normal, just can't view the rig status only

**Version affected (please complete the following information):**
v0.5.1.3

**NVIDIA driver version**
470.05

**Hardware**
i3-4150T 
GA-Z97X-Gaming 3 1.0
two 3060 connected  to the motherboard 16x slot (run to 8x)

**Logs**
uploaded to Log
[exported_logs.zip](https://github.com/nicehash/NiceHashQuickMiner/files/7424536/exported_logs.zip)

**Comment by Dohtar1337** [comment]
Does the issue persist on the latest QM 0.5.3.6 RC?

**Comment by WaiTangHK** [comment]
Hi 
I just running QM 0.5.3.3 before, but the issue persists but has some change
1. mining page will show an error for this rig and will send the notice 
2. the issue cycle is long, now only will appear around by week or month.

I just updated to QM 0.5.3.6 RC and testing again now, thanks

**Comment by Dohtar1337** [comment]
Please let me know if 0536 resolves the issues completely. Else I will close this ticket

**Comment by WaiTangHK** [comment]
start the run 0536 at last reply 
until to 17 Apr still has same case by QM 0.5.3.3
and restart again
then also get issue today

here is my Log here 
[https://drive.google.com/file/d/17CG0hIDJa8FSoyUq4C6ILWO6C0REtlZi/view?usp=sharing](url)

thanks for following my issue.

**Comment by Dohtar1337** [comment]
This issue should be solved in the upcoming release. Please follow NHQM updates and see if the next release solves the issue for you.
