### ISSUE TITLE
Failed init cuda

### ISSUE THREAD

**Issue by vitto97** [nicehash/NiceHashQuickMiner#672]
after a couple of minutes of mining with the excavator, the rig crashes. i have updated nvidia drivers and mining sw.

tried different oc with nh oc tune but problem persists.
thank you in advance.
[exported_logs.zip](https://github.com/nicehash/NiceHashQuickMiner/files/7428805/exported_logs.zip)
t

**Comment by ismael12345678** [comment]
تبقى فى موقع mining Pool ولا تنتقل الى المحفظة الا بعد أن تقوم بتجميع قيمة معينة قدرها 0.05 من عملة Ethereum على الأقل ويمكن تحديد قيمة العملة التى تنتقل الى المحفظة عن طريق تبويب Settings و وضع الحد الأدنى لانتقال العملة الى المحفظة من خلال Payment Threshold وحفظ الاعدادات بعد وضع أخر ارقام لعنوان IP لمنصة التعدين لديك. يمكن معرفة عنوان IP لمنصة التعدين من خلال فتح المتصفح فى جهاز التعدين وكتابة فى محرك البحث My IP Address أو من خلال الموقع https://whatismyipaddress.com/ وستجد عنوان الجهاز بسهولة.
الخطوة الرابعة: كيفية متابعة تطورات منصة Mining
فى تلك المرحلة أنت تريد أن تتابع مجريات عملية التعدين من حيث معرفة معدل Hashrates للمنصة لديك والتحويلات التى تمت على المحفظة الالكترونية لديك. سيتم ذلك من خلال موقع المحفظة https://www.myetherwallet.com/ وكذلك الموقع https://ethermine.org/.

أولاً من خلال التبويب Dashboard تستطيع متابعة مجريات منصات التعدين ومعدل Hashrates لها.

التعدين Mining Ethereum Bitcoin

من خلال التبويب Payments ستجد التحويلات التى تمت من Mining Pool الى المحفظة Wallet ومواعيدها وكمية العملة المنتقلة التى قمت بتحديدها من الخيار Settings كما ذكرنا الحد الأدنى لها 0.05 من عملة Ethereum.

التعدين Mining Ethereum Bitcoin

يمكنك متابعة عمليات التحويل من موقع سحابة التعدين الى المحفظة بالضغط على عنوان المحفظة وسوف تدخل الى الموقع https://www.etherchain.org لترى أخر Transactions التى تمت مع قيمتها وتاريخها

 

بمكن متابعة كمية العملة من المحفظة عن طريق التبويب View Wallet Info من الموقع https://www.myetherwallet.com/ وبعد ذلك ستقوم بعمل نفس الخطوات من رفع الملف والرقم السرى كما فعلنا فى الخطوة الأولى فى بداية المقال.
الخطوة الخامسة: كيفية تحويل العملات Ethereum الرقمية الى مشتريات
هناك طريق عديدة لتحويل العملات الرقمية الى طرق للدفع أو الشراء:

يمكن أن تشترك لأحد تجمعات التعدين Groups  الموثوق بها على مواقع التواصل الاجتماعي و التحويل من المحفظة لديك.
التعدين Mining Ethereum Bitcoin

استخدام أحد مواقع التبادل والمضاربة على العملات مثل https://www.coinbase.com/ أو https://bittrex.com/Home/Markets وربط المحفظة بهم وتأكيد بيانات حسابك ومن ثم عرض قيمة العملات التى تريدها وتحويلها الى حسابك البنكي أو بطاقات شراء من مواقع الشراء مثل Amazon وهكذا.
التعدين Mining Ethereum Bitcoin

الأمر ليس صعباُ لبداية عملية التعدين كل ما عليك فعله هو الحرص وعدم استخدام الانترنت بكثرة من جهاز التعدين حتى لا تقع فى مواقع سرقة البيانات و احتفظ بعناوين وملفات الرقم السرى للمحفظة فى مكان أمن و قم بتفعيل عملية Two Way Authentication فى مواقع التبادل التى تخبرك بمحاولة الدخول الى الموقع وحسابك عن طريق البريد الإلكتروني ورقم هاتفك.

حيث ان طوفان التعدين يحدث بك أو بدونك فلا ضرر من اللحاق بذلك القارب و بدء ذلك المشروع الاستثماري الناجح
