### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Moradabdelkader** [nicehash/NiceHashQuickMiner#677]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version affected (please complete the following information):**
 - Version number [e.g. 0.4.5.5]
 - RC or STABLE?

**NVIDIA driver version**
Which one do you use?

**Hardware**
Describe GPUs used and how are GPUs connected to the motherboard.
CPU?

**Logs**
Activate logging first, then record event - bug - then export logs into a .zip file and attach it when submitting this issue.

**Additional context**

A

**Comment by AZEVEDOTC** [comment]
![ERRO INSTALAÇÃO NICEHASH](https://user-images.githubusercontent.com/93600739/139871350-1844ffbd-9cb2-4fb0-a84d-d02f918ec829.png)


OLÁ BOM DIA!

BAIXEI A NOVA VERSÃO DO NICEHASH E QUANDO VOU INSTALAR ELE DA UM ERRO DIZENDO QUE O PROGRAMA NÃO CONSEGUIU CONTINUAR A INSTALAÇÃO.
