### ISSUE TITLE
[QUESTION] 

### ISSUE THREAD

**Issue by Shriyanshu1** [nicehash/NiceHashQuickMiner#678]
**Has the question been answered in [Wiki](https://github.com/nicehash/NiceHashQuickMiner/wiki)? There is no such question in [FAQ](https://github.com/nicehash/NiceHashQuickMiner/wiki/FAQ) or [Troubleshooting collection](https://github.com/nicehash/NiceHashQuickMiner/wiki/Troubleshooting)?**
Yes/No.

**Your question is...**
Why isn't NiceHash mining not yet compatible with RTX 3050 and AMD Ryzen 5600H.? Will they be compatible in the future?

**Comment by Dohtar1337** [comment]
QuickMiner is compatible with both devices.
