### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by cook4015** [nicehash/NiceHashQuickMiner#683]
I recently upgraded to Windows 11 and been having hash rate issues since the upgrade. I have a MSI RTX 3090 Suprim. I was getting 122+ MH/s now i'm only getting 55-56 MH/s max. 

I can get it to mine 122+ MH/s for a bit before it drops down to that 55-56 range randomly. All temps are within spec and it's not thermal throttling at all. 

Restarting the PC fixed the problem for a bit. Closing the QuickMiner and restarting it doesn't fix the problem. I run "High" overclock settings on Nicehash. 

Any ideas on what the problem is???

![Nicehash ss](https://user-images.githubusercontent.com/94235909/141651517-62cf366c-707b-440a-b912-c47834c35641.jpg)
![Nicehash ss2](https://user-images.githubusercontent.com/94235909/141651519-742b3bde-7772-4ff5-828f-c60c13d282e9.jpg)

**Comment by Dohtar1337** [comment]
Probably related to drivers https://www.nicehash.com/blog/post/psa-mining-with-nvidia-drivers-v511-23-or-newer

If not, please update QM to the latest RC 0535
