### ISSUE TITLE
Feature Request: Mining Percentage (Mine on 50% speed)

### ISSUE THREAD

**Issue by sepivip** [nicehash/NiceHashQuickMiner#69]
It will be amazing to have the ability to mine on f.e. half speed... So I can mine while using light apps. Is that possible?

**Comment by nicehashdev** [comment]
Unfortunately no. NVIDIA did not make this possible for eg. to utilize only certain SM. It is always full power or no power. There are some ways to lower utilization and make everything smoother, such as reducing kernel execution time (by reducing number of executed threads).

I will see what I can do with low execution threads coupled with extremely precise timers. This could in turn simulate certain % of load. But currently this is not a high priority task.

**Comment by nicehashdev** [comment]
Added to the TODO list: https://github.com/nicehash/NiceHashQuickMiner/wiki/Planned-features

**Comment by sepivip** [comment]
> Added to the TODO list: https://github.com/nicehash/NiceHashQuickMiner/wiki/Planned-features

Perferct Thanks <3

**Comment by nicehashdev** [comment]
Closing.
