### ISSUE TITLE
[BUG] Cannot download ZIP package for v0.5.2.0.

### ISSUE THREAD

**Issue by den1n** [nicehash/NiceHashQuickMiner#690]
Download link leads to "Not found" page.

https://github.com/nicehash/NiceHashQuickMiner/releases/download/v0.5.2.0/NiceHash_QuickMiner_v0.5.2.0.zip

**Comment by matthewhartstonge** [comment]
@den1n looks like the asset name has been altered:

From `NiceHash_QuickMiner_v0.5.2.0.zip` to `NHQM_v0.5.2.0.zip`

https://github.com/nicehash/NiceHashQuickMiner/releases/download/v0.5.2.0/NHQM_v0.5.2.0.zip

**Comment by gingertrol** [comment]
Fixed
