### ISSUE TITLE
Nvidia GTX 1060 3GB stopped working - no compatible devices found

### ISSUE THREAD

**Issue by reed128** [nicehash/NiceHashQuickMiner#691]
It worked before, but now it doesn't.  WIndows 10 recognizes the GPU fine.  The latest Nvidia driver is installed (496.76).  Removing and reinstalling the display drivers didn't help.  Removing and reinstalling Nicehash didn't help.
Excavator v1.7.1.d build 880

![image](https://user-images.githubusercontent.com/3371016/142736854-c7b29367-80fd-4ab2-ad67-387457fca15c.png)

![image](https://user-images.githubusercontent.com/3371016/142736835-da772cf0-f13c-4265-9ed2-0818bd56d4df.png)

![image](https://user-images.githubusercontent.com/3371016/142736823-0feed058-45c8-4aac-b7c1-881e42f01a09.png)

**Comment by reed128** [comment]
I am able to use NiceHash Miner instead of the QuickMiner successfully.  
Running lolMiner 1.32

**Comment by Dohtar1337** [comment]
It is a 3GB card. 3GB cards are not supported
