### ISSUE TITLE
Disable animation in the system tray icon

### ISSUE THREAD

**Issue by TiZCrocodile** [nicehash/NiceHashQuickMiner#695]
the animation in the system tray icon of the nice hash quick miner disrupts me, if you could please add maybe a setting in the config file for disabling it, it would be nice.

**Comment by dinfinity** [comment]
Agreed. Adding animation in the systray that can't be disabled is a terrible terrible idea.

**Comment by Dohtar1337** [comment]
Thanks for the feedback. We were required to add it. We will see if we can do anything about it.

Closing this issue in the meantime.
