### ISSUE TITLE
Confused what to install - You have two products called "Quick Miner"

### ISSUE THREAD

**Issue by xantari** [nicehash/NiceHashQuickMiner#7]
You have this: https://www.nicehash.com/quick-miner

Which is version 5.50. It is also called quick miner. The link on that page is this: https://files.nicehash.com/nhminer/quickminer/NicehashQuickMinerv550.exe

Then you have the one here in this repo announced on your blog post. Which is currently version 0.3.0.2

Really confused, which "Nice Hash Quick Miner" to use. You should really have named them something different.

**Comment by nicehashdev** [comment]
The QuickMiner on link https://www.nicehash.com/quick-miner is a tryout tool only and not meant for permanent mining, rather just for trying out.

They both use the same core for mining - Excavator.

**Comment by xantari** [comment]
Ohh ok. Still think you should change the names to differentiate the tools.
