### ISSUE TITLE
Is there a way to start mining when idle, then stop when we use the computer again?

### ISSUE THREAD

**Issue by seanmowz** [nicehash/NiceHashQuickMiner#70]
It would be nice to have mining kick in when we leave the computer in idle automatically, but when we come back to have it shut off and turn the fans lower. 

Also for feature improvements would it be possibly to save multiple OCTune profiles, eg a high OC profiles, then a quiet profile that we can easily switch between automatically based on time of day/idle period so that we dont need afterburner installed in addition.

**Comment by nicehashdev** [comment]
Not yet, but the plans are being laid down for this feature already. Check planned features: https://github.com/nicehash/NiceHashQuickMiner/wiki/Planned-features

**Comment by nicehashdev** [comment]
Closing. WIll be implemented one day.
