### ISSUE TITLE
[FEATURE] Toggle to disable tray icon animation

### ISSUE THREAD

**Issue by pwtdo** [nicehash/NiceHashQuickMiner#700]
The new tray icon animation is annoying and distracting. I'd like a toggle or checkbox that would disable the animation. Otherwise I'll have to hide the icon completely, which prevents me from easily starting and stopping QuickMiner.

Doesn't need to be anything fancy. Just a toggle that stops the animation in the tray icon.

**Comment by KingNewbs** [comment]
Took me a while to get used to the previous animated icon, and I still don't love it. But at least it isn't flashing colors like this new one. This is a real distraction. And while it's nice to be able to tell at a glance if QM is mining, the icon doesn't need to be flashing or animating at all to communicate that.

At the very least, provide an option to disable the animation. Two static icons would work, one for Running, one for Stopped.

Bearing in mind, I understand it's easy to ignore the blinking for most people, but not for everybody. And while just hiding the tray icon would eliminate the distraction element, it also removes the "at-a-glance" feature entirely. In short, it's an accessibility issue.

Please consider changing this.

**Comment by fmiqbal** [comment]
If you don't mind having an alternative, 
I use Open Hardware monitor, and make the gpu core, show in tray, and this is what you see when its mining 
![image](https://user-images.githubusercontent.com/8409391/144696221-cc6c3201-0923-4e15-a5d0-0efbe44ec7ad.png)

and when its not
![image](https://user-images.githubusercontent.com/8409391/144696225-3087291f-7089-4b70-bf25-7e01aaef086c.png)

**Comment by limacohen** [comment]
If we are listing alternatives, I use HWiNFO to show the MH/s in the system tray alongside the temps. It's way more functional for me than the original icon.

![rjFEXcK5rl](https://user-images.githubusercontent.com/541169/144767414-f1dca57a-8c30-4db0-b079-9c31dc6df936.png)

**Comment by crafty35a** [comment]
Please do change this, the flashing icon is very distracting for some people.

@limacohen I know how to get sensor info into the system tray with HWiNFO, but how do I get it to access the hashrate?

**Comment by Dohtar1337** [comment]
We will not change this.
