### ISSUE TITLE
[OPTIMIZATION] v0.5.3.0 RC LHR profiles and power

### ISSUE THREAD

**Issue by wabbaquake** [nicehash/NiceHashQuickMiner#702]
**Are you aware of the latest [Optimization data](https://github.com/nicehash/NiceHashQuickMiner/tree/main/optimize) being used?**
Yes.

**I am suggesting new optimization or modification of existing optimization?**
New/Modification

**For GPU:** NVIDIA GeForce RTX 3080 LHR
**Optimization name:** Lite/Medium/High/Extreme (Does Efficient still exist?)
**Special VRAM & Manufacturer:** No

**My suggested optimization data is following:**
Some observation info, and thank you for producing the LHR unlock.

On Lite profile, Excavator encountering LHR locking is relatively more frequent than other profiles. Hitting the LHR locks too frequently is causing mining efficiency losses as well temperature swings. Toying with the LHR Intensity/Ratio in Manual has been inconclusive, so please document the purpose of the Intensity/Ratio. 
Edit: Found the blog post about it. Was expecting it in the README.
https://www.nicehash.com/blog/post/quickminer-0-5-3-0-rc-with-lhr-unlock

Across all profiles, there have been noticeable power spikes of at least 20W every few seconds that cause the VRAM temperature to spike as well, fluctuating between 94C and 100C. This phenomenon has not been observed with v0.5.20 and older. For the sake of our hardware longevity please look into this.

**Comment by Dohtar1337** [comment]
I do not understand the issue. Will close if no followup is made.

**Comment by Dohtar1337** [comment]
This is how LHR unlock works, this is expected behavior.
