### ISSUE TITLE
[FEATURE] Total Power Usage (KWh)

### ISSUE THREAD

**Issue by Tea-Ice** [nicehash/NiceHashQuickMiner#706]
**Is your feature request related to a problem? Please describe.**
Hard to really know how much electricity I am using over time.

**Describe the solution you'd like**
Start capturing electricity usage data, and save it for aggregation. Then in excavator when you press 's', you show something along the lines of:
```
Usage in the current Session: 0.434KWh
Usage in the last Hour: 0.220KWh
Usage in the last Day: 4.902KWh
Usage in the last Week: 32.022KWh
Usage in the last Month: 130.003KWh
...
Total Usage on Machine: 4.557MWh
```
Then have the data available in the graphs on the Mining Stats page of the Web Portal.

**Describe alternatives you've considered**
If the above will take too long to implement, you can just have it on Current Usage, which should be easy enough in excavator, as I have seen it in other mining software before.

**Comment by uhliksk** [comment]
@Tea-Ice It will be very innacurate if you are using low power LHR strategy with floating power consumption. NHQM is sampling power draw in 30 seconds interval by default which is too long period for accurate measurement. If you want to watch your energy consumption you can use NQHM API to read GPU power draw in intervals you need and calculate electricity usage more accurately. You can find GPU power usage in _device.get_ API call as _gpu_power_usage_:

`http://localhost:18000/api?command={"id":0,"method":"device.get","params":["1"]}`
