### ISSUE TITLE
[QUESTION] Norton is blocking quickminer and I can't make an exception

### ISSUE THREAD

**Issue by DiegoEFeP** [nicehash/NiceHashQuickMiner#709]
Hello all.

I tried to install and use quickminer today, but I couldn't. I have Norton 360 Deluxe and that sh$& blocks even shadows, never seen something like that. It's annoying.

First of all I downloaded the installer and I had to deactivate sonar and other active responses of Norton, then I could install the quickminer, but after that I couldn't execute it, because Norton was blocking it.

Then I found a thread in nicehash, from the company's creator and he was saying to try to find the nicehash directory in Windows and put the folder as an exception on Norton. But I couldn't find the directory at my system. Tried some folders, including the one he told to locate, but I really didn't find it.

Another solution I found was to try the zip files to install, but also, before I could make an exception, Norton blocks it at once and I can't even install the program by following this way.

Please, help me, 'cause I wanna mine, but with this shitty program that seems to be kinda impossible.

Thanks in advance.

**Comment by Dohtar1337** [comment]
Do not use Norton. It implemented its own miner, but it blocks all the rest.
