### ISSUE TITLE
update notification

### ISSUE THREAD

**Issue by thecoolkogut4** [nicehash/NiceHashQuickMiner#71]
Not really a bug, just a text problem. After every automatic update, the notification says I will need to re-enable auto startup after NHQM is updated. This is not the case, NHQM still autostarts up without me touching that setting so I believe you can remove that line from the update notification.

**Comment by nicehashdev** [comment]
This was needed for the old service startup method. Now that service method is not in anymore, it will be removed slowly.

**Comment by nicehashdev** [comment]
Resolved. Closing.
