### ISSUE TITLE
[BUG] startup dialog won't close.

### ISSUE THREAD

**Issue by iplayfast** [nicehash/NiceHashQuickMiner#714]
**Describe the bug**
When quickminor starts, it shows 2 consoles. The first is a dialog
![qm](https://user-images.githubusercontent.com/751306/144472580-252bb9ec-8dfd-462b-a7e7-ae0194f88bdc.png)
Which tells me to do something that isn't available on my windows system. or with the taskbar icon.
It asks that I test it, (which I can't) and the button to close it, is not enabled. 

The second console is the actual miner, which is fine. 

**To Reproduce**
start quickminer

**Comment by iplayfast** [comment]
Found it. The way to do it is in the hidden icons, not the ones that are being shown on the taskbar. Perhaps make this a bit more clear. I've been using it like this for months.

**Comment by Dohtar1337** [comment]
Resolved
