### ISSUE TITLE
[FEATURE] Gigabyte 3070ti Gaming OC (LHR). Hashrate stable 52,40MH/s-52,90MH/s

### ISSUE THREAD

**Issue by hamdycam** [nicehash/NiceHashQuickMiner#717]
driver version: 497.09-desktop-win10-win11-64bit-international-dch-whql
nicehash version: NiceHash QuickMiner v0.5.3.0. stable
My configuration: 
Fan mode: Fixed speed, 100%
Core clock delta: -430
Memory clock delta: 1125
Power limit (W): 177

LHR Unlock ratio (60-90): 71
LHR Intensity (25-50): 34

Feature in spanish:

He detectado que para conseguir este resultado de hash es necesario inicializar el minado con la configuración siguiente:
Fan mode: Fixed speed, 100%
Core clock delta: -430
Memory clock delta: 1125
**Power limit (W): 150**

LHR Unlock ratio (60-90): 71
LHR Intensity (25-50): 34

Una vez que la gráfica se inicializada y llega al máximo hashrate 44MH/s, tu puedes subir la potencia y la gráfica no detectará el bloqueo LHR, si no lo haces de esta forma no conseguirás aumentar de 44MH/s sin que se reinicie.
(tras un tiempo de 60 segundos)

Fan mode: Fixed speed, 100%
Core clock delta: -430
Memory clock delta: 1125
**Power limit (W): 177**

LHR Unlock ratio (60-90): 71
LHR Intensity (25-50): 34

Se podría implementar un retraso al inicio para aplicar la configuración final de minado? estaría bien implementar un timer con limitación de potencia.

BUG: No guarda los valores LHR Unlock ratio (60-90) y LHR Intensity (25-50) en la base de datos.

Muchas gracias, buen trabajo.

P.D. con una rtx3060ti LHR  y diferentes valores he conseguido estable 42,1MH/s a 42,4MH/s y 133W

**Comment by armstr87** [comment]
Hi, Your 3070Ti Nvidea driver is an DCH version. You can get better performance with the older driver version 472.84.

![Screenshot 2022-01-02 114608](https://user-images.githubusercontent.com/96969827/147867819-2396db75-1b7c-4098-a044-eff5083dcf1f.png)


Try this link for the original driver:
https://www.nvidia.com/Download/Find.aspx

**Comment by Dohtar1337** [comment]
Solved by @armstr87
