### ISSUE TITLE
[BUG] Adjust "disabledDevices" in nhqm.conf causes reset to default values

### ISSUE THREAD

**Issue by mikeroygray** [nicehash/NiceHashQuickMiner#718]
**Describe the bug**
Whenever I try to disable device 2 in the config file, QM resets nhqm.conf to default values.

**To Reproduce**
I have two GPUs, I only want to mine on one of them. (Specifically, device 0)
But when I change 

"disabledDevices" : [],
to 
"disabledDevices" : 1,

QM resets the nhqm.conf file. I have to re-enter my NH address and go through the entire setup procedure again.

**Notes:**

1) I'm not using a protected folder. QM is running from "D:\mining\NHQM_v0.5.3.0_RC"
2) Alternatives tried:
2a) If I change the config file directly when QM is off, QM resets the next time I start it.
2b) If I use Settings / Edit Command File, the reset happens the moment I press the save button - i.e., while I'm mining.

**Expected behavior**
I expect to able to adjust settings in the config file. I ALSO expect to be able to mine on device 0 only!

**Screenshots**

**Version affected (please complete the following information):**
RC 0.5.30 (device 1 is LHR!)

**NVIDIA driver version**
472.12 Standard

**Hardware**
device 0: 3090 (Gigabyte Gaming OC)
device 1: 3080 TI (Gainward Phoenix = Reference Board)

**Comment by Dohtar1337** [comment]
A typo. 
Should be "disabledDevices" : [1],
