### ISSUE TITLE
How To - Enable OCTune AutoTune automatically

### ISSUE THREAD

**Issue by LanceMcCarthy** [nicehash/NiceHashQuickMiner#720]
**Has the question been answered in [Wiki](https://github.com/nicehash/NiceHashQuickMiner/wiki)? There is no such question in [FAQ](https://github.com/nicehash/NiceHashQuickMiner/wiki/FAQ) or [Troubleshooting collection](https://github.com/nicehash/NiceHashQuickMiner/wiki/Troubleshooting)?**
No.

**Your question is...**
How do I automatically have NHQM start up with a preset of OCTune's AutoTune setting? Can I edit nhqm.conf or commands.json to automatically enable it?

![image](https://user-images.githubusercontent.com/3520532/145593728-34779fbc-fab9-46d9-aa49-8a59017c0581.png)

### Problem Explanation
I wish I could use OPTIMIZE High or Extreme settings, but they always crash my 3090. Also, if I leave NHQM to the defaults, it wastes a ton of power and overheats the RAM (105Mh/s at 350 watts, RAM temps at 104)

### Solution
However, if I enable OCTune's AutoTune, it gives me a perfect performance (110 Mh/s, 250 watss, RAM temps at 90). This is why I would like it to always start up using this OC setting.

**Comment by Riccorbypro** [comment]
Use the "Alternative method for overclocking" section with the settings that AutoTune gives you.

For example my 3070 defaults to 1935/7000/54MH/62C, but with AutoTune it goes to 1110/8170/62MH/46C. So I set my settings under the "Alternative method" section to 1110 and 8171 (There seems to be a 1MHz offset bug with the RAM clock, 8171=8170, 8170=8169) and click apply, then save. Starts up like that every time and with Game Mode I can reset my card back to my gaming OC settings as well.

![image](https://user-images.githubusercontent.com/13792979/145691151-71fb9808-1130-42e3-92df-0bcb8d453dcf.png)

**Comment by LanceMcCarthy** [comment]
@Riccorbypro Thank you! Switching to Alternative method let me use the save button, which saved the config to the commands.json file to the following:

```json
[{
		"time": 0,
		"commands": [{
				"id": 1,
				"method": "device.smartfan.set",
				"params": ["GPU-e227bc3d-6628-ca0e-6461-8bd323cde81d", "1", "100"]
			}, {
				"id": 1,
				"method": "device.set.oc_profile2",
				"params": ["GPU-e227bc3d-6628-ca0e-6461-8bd323cde81d", "1605", "9501"]
			}]
	}, {
...
```

It is a bit weird that although I get the same hash rate, it uses 50 more watts (105.8 Mh/s). This generates an extra 8 degrees (98)... is there an undervolt value that would keep the same hashrate while not getting so hot?

**Comment by Dohtar1337** [comment]
Old ticket
