### ISSUE TITLE
[QUESTION] v0.5.3.0 RC

### ISSUE THREAD

**Issue by neo-jubil** [nicehash/NiceHashQuickMiner#725]
**Has the question been answered in [Wiki](https://github.com/nicehash/NiceHashQuickMiner/wiki)? There is no such question in [FAQ](https://github.com/nicehash/NiceHashQuickMiner/wiki/FAQ) or [Troubleshooting collection](https://github.com/nicehash/NiceHashQuickMiner/wiki/Troubleshooting)?**
Yes/No.

**Your question is...**
What is...
проблемы с v0.5.3.0 RC ооочень много реджектов и не стабильно работает то 50 то 256 то 1250 mc
![реджекты2](https://user-images.githubusercontent.com/83059335/146506921-49b08a89-44ed-4fb1-b33f-b76f789b6c09.jpg)

**Comment by neo-jubil** [comment]
пока нормальной разблокировки нет одни реджекты ,все красное!

**Comment by zenon8888** [comment]
Co kurwa?
