### ISSUE TITLE
Gracefully Kill NHM - C#/.NET

### ISSUE THREAD

**Issue by jeffreykramey** [nicehash/NiceHashQuickMiner#727]
I am trying to automate the closing of NiceHash but I am running into a couple issues. Using process.Close() or process.CloseMainWindow() only temporarily closes the miner but it restarts immediately. Using process.Kill() successfully stops the program but does so abruptly causing NiceHash to think the entire PC/GPU crashed. This leads to NiceHash giving me an error message upon restarting which causes issues with other automation tasks.

![image](https://user-images.githubusercontent.com/70029983/146868429-9bdc8a0a-5b38-4bf6-b5d3-2f233f516661.png)

Are there other options to kill the program that simulate a more natural death like what happens when you right click the tray icon and select "Exit"? I figure just turning that warning message off would work for me but that doesn't seem to be an option. For what it's worth I have the error handling setting set at "do nothing."

![image](https://user-images.githubusercontent.com/70029983/146868542-31d722e2-7da1-4e9c-9de3-3f204bbc115d.png)

**Comment by CrazyLayKer** [comment]
#722 
I have a similar problem.

**Comment by xr1140** [comment]
I circumvented this by killing the app and editing the conf file to trick the app to not show the messages on next start.

**Comment by jeffreykramey** [comment]
> 

Clever, thanks.

**Comment by meadowsjared** [comment]
for anybody looking to do this, the file is located in:
`"C:\NiceHash\NiceHash QuickMiner\nhqm.conf"`
and you need to replace
`"bLastRunCrashed" : true,`
with
`"bLastRunCrashed" : false,`
