### ISSUE TITLE
Excavator restarting every few minutes for last few days

### ISSUE THREAD

**Issue by midnightminers** [nicehash/NiceHashQuickMiner#728]
Excavator is shutting down and restarting every few minutes causing a loss in efficiency.  This started a few days ago.  I am not sure what changed.  any trouble shooting steps would be appreciated.

**Comment by khrukawa** [comment]
me too

**Comment by Dohtar1337** [comment]
Not enough information. Closing.
Open a new ticket if neccesarry.
