### ISSUE TITLE
Excavator -> Terminal scroll holding is causing shares to be rejected

### ISSUE THREAD

**Issue by noomade** [nicehash/NiceHashQuickMiner#73]
Hello,
Wwhen the miner is running, and you want to check the previous lines, if you drag the terminal scroll and hold it, at any point in the log, the current jobs running will be "delayed" or "stopped". Causing shares to be rejected. I will be posting the full log(without telemetry/personal data) on a few minutes when the log file is complete.

Replication Process:

1. *Open* `NiceHashQuickMiner.exe`;
2. *Await* `Excavator v1.6.3c` start mining;
3. *Click and Drag* the terminal *scroll* for 10 ~ 15 seconds;
4. See your shares getting reject in your face.

SO: Windows 10 Pro Build 19042.804;
GPU: EVGA RTX 3070 XC3 Ultra;
nVidia driver: v461.40;
NiceHash_QuickMiner: v0.3.0.2;

If any more information is needed, please let me know.
Also, it would be nice if the repository had template issues.

**Comment by nicehashdev** [comment]
This has already been reported and for now, no plans to fix it: https://github.com/nicehash/excavator/issues/293

If you wish to view history, enable file logging and search in files.
