### ISSUE TITLE
[QUESTION] My Graphic Card is not deteched by NiceHash Miner v3.0.6.9

### ISSUE THREAD

**Issue by Manu-945137** [nicehash/NiceHashQuickMiner#730]
**Has the question been answered in [Wiki](https://github.com/nicehash/NiceHashQuickMiner/wiki)? There is no such question in [FAQ](https://github.com/nicehash/NiceHashQuickMiner/wiki/FAQ) or [Troubleshooting collection](https://github.com/nicehash/NiceHashQuickMiner/wiki/Troubleshooting)?**
Yes/No.

**Your question is...**
What is...
My Graphic Card is not deteched by NiceHash Miner v3.0.6.9
My Graphic Card is Nvidia GTX 710 2GB
and My Processor power used by only 50% .
Email to me - manusingh945137@gmail.com

**Comment by imdarkk** [comment]
As far as I know that GPU is not supported by NiceHash for mining

**Comment by Shubh-796** [comment]
Yes

**Comment by Dohtar1337** [comment]
Not supported GPU
