### ISSUE TITLE
[BUG] Anti-LHR getting enabled in my non-LHR 3090

### ISSUE THREAD

**Issue by ShikiGami** [nicehash/NiceHashQuickMiner#731]
**Describe the bug**
Anti-LHR gets enabled in my non-LHR RTX 3090, and the hash-rate takes a big hit from it.

**To Reproduce**
It happens mostly when for some reason QuickMiner resets.

**Expected behavior**
To be able to mine with full HR without the Anti-LHR enabled, since my card isn't LHR.

**Screenshots**
![image](https://user-images.githubusercontent.com/3926168/148046218-2c71e21f-63a8-4ebe-a825-6c31d6d8a64d.png)

**Version affected (please complete the following information):**
v0.5.3.0

**NVIDIA driver version**
497.29

**Hardware**
Custom Water Cooled Zotac Trinity RTX 3090
Ryzen 9 5900X

**Comment by Hyrules** [comment]
I'm having the same issue as well. On startup when quickminer starts with Windows the first run my 3090 gets detected as a LHR card and qm applies the LHR protocol. If I close qm and restart it the problem does not reproduce in my case and I get the full mining speed.

**Comment by ageisen2000** [comment]
Same issue here

**Comment by Alesund** [comment]
Same for my RTX 3090 msi gaming x trio, I'm back to v0.5.2.0 to fix this problem.

**Comment by fudun** [comment]
Same problem with a MSI 3080 Gaming X Trio with Suprim X firmware

**Comment by jges42** [comment]
Have the same bug with my GigaByte10GB D6X RTX 3080 Eagle OC 10G.
The bug causes a significant mining efficiency decrease (from 100MH to 66 MH) 

Thx for the tip to revert to 0.5.2.0 @Alesund that  restored my efficiency.

**Comment by SamuelLeclerc33** [comment]
This still seems to be an issue on 0.5.3.3

**Comment by jges42** [comment]
Fixed for me in 0.5.3.4

**Comment by Dmugs1** [comment]
Same on my 3070. Tried the latest fixed RC release, but that one restarts itself after some short time for no reason.

**Comment by Dohtar1337** [comment]
Solved on latest release candidate

**Comment by HaydenOtto** [comment]
0.5.3.5 RC solved problem for me.
