### ISSUE TITLE
NiceHashQuickMine dosent open[QUESTION] 

### ISSUE THREAD

**Issue by tebe22** [nicehash/NiceHashQuickMiner#732]
i can download miner but when i try to open installation it just do nothing`?

**Comment by mavslab** [comment]
same there, WINDOWS 11

**Comment by Richefforts** [comment]
Me2

**Comment by giudiceanto** [comment]
same on windows10 (fresh install)
quickminer installer won't start

Firma del problema
Nome evento problema:	CLR20r3
Firma problema 01:	NiceHashQuickMinerInstaller.exe
Firma problema 02:	0.5.3.3
Firma problema 03:	cf3b0859
Firma problema 04:	NiceHashQuickMiner
Firma problema 05:	0.5.3.3
Firma problema 06:	cf3b0859
Firma problema 07:	b8
Firma problema 08:	d5
Firma problema 09:	System.IO.FileNotFoundException
Versione SO:	10.0.19043.2.0.0.256.48
ID impostazioni locali:	1040
Informazioni aggiuntive 1:	cce7
Ulteriori informazioni 2:	cce71d5a003e2cecbb06ee1e6f2e7242
Ulteriori informazioni 3:	e91f
Ulteriori informazioni 4:	e91f51170912cdc94671ed0adba3b637

Ulteriori informazioni sul problema
ID bucket:	69a0a200cf0676cdd92a05c815a1a8d2 (1813268156884560082)

**Comment by Dohtar1337** [comment]
Is this issue still relevant?

**Comment by giudiceanto** [comment]
> Is this issue still relevant?

I'm still using the standalone QM because the installer does not open.

**Comment by Dohtar1337** [comment]
What antivirus software are you using? Most likely the issue is related to AV blocking QM from running.

**Comment by giudiceanto** [comment]
> What antivirus software are you using? Most likely the issue is related to AV blocking QM from running.

just the basic windows defender. I've tried to whitelist the installer but without luck. The fact is, I used to use the installed versione of QM, but after I formatted and reinstalled windows I've got this issue. Still using the standalone with no issues thou

**Comment by Dohtar1337** [comment]
@giudiceanto Please try disabling defender alltogether. Not just whitelisting it.

**Comment by giudiceanto** [comment]
> @giudiceanto Please try disabling defender alltogether. Not just whitelisting it.

yes I tried that too, unfortunately with the same result. The event log is as follows:

Nome registro: Application
Origine:       Application Error
Data:          01/04/2022 10:56:09
ID evento:     1000
Categoria attività:(100)
Livello:       Errore
Parole chiave: Classico
Utente:        N/D
Computer:      DESKTOP-IR82TUD
Descrizione:
Nome dell'applicazione che ha generato l'errore: NiceHashQuickMinerInstaller.exe, versione: 0.5.3.3, timestamp: 0xcf3b0859
Nome del modulo che ha generato l'errore: KERNELBASE.dll, versione: 10.0.19041.1566, timestamp: 0x0833f2d4
Codice eccezione: 0xe0434352
Offset errore 0x0000000000034f69
ID processo che ha generato l'errore: 0x3324
Ora di avvio dell'applicazione che ha generato l'errore: 0x01d845a65467c9b4
Percorso dell'applicazione che ha generato l'errore: C:\Users\giudi\Downloads\NiceHashQuickMinerInstaller.exe
Percorso del modulo che ha generato l'errore: C:\Windows\System32\KERNELBASE.dll
ID segnalazione: 0472e4a3-4b6e-426e-80b4-0a675020d89e
Nome completo pacchetto che ha generato l'errore: 
ID applicazione relativo al pacchetto che ha generato l'errore: 
XML evento:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-04-01T08:56:09.4863783Z" />
    <EventRecordID>5587</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>DESKTOP-IR82TUD</Computer>
    <Security />
  </System>
  <EventData>
    <Data>NiceHashQuickMinerInstaller.exe</Data>
    <Data>0.5.3.3</Data>
    <Data>cf3b0859</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.19041.1566</Data>
    <Data>0833f2d4</Data>
    <Data>e0434352</Data>
    <Data>0000000000034f69</Data>
    <Data>3324</Data>
    <Data>01d845a65467c9b4</Data>
    <Data>C:\Users\giudi\Downloads\NiceHashQuickMinerInstaller.exe</Data>
    <Data>C:\Windows\System32\KERNELBASE.dll</Data>
    <Data>0472e4a3-4b6e-426e-80b4-0a675020d89e</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

hope it helps.

**Comment by Messiahbe** [comment]
Same here can't open the installer on W11 & W10 both machines same issue

**Comment by giudiceanto** [comment]
> Same here can't open the installer on W11 & W10 both machines same issue

I think it's a random curse related to some windows updates. I tried lately the installer and now it works with no problem. In any case I have other types of issues with QM now.
