### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by asianpro4** [nicehash/NiceHashQuickMiner#733]
**Describe the bug**
Starting NHQM will randomly cause BSOD that do not produce windows minidumps. Problem is consistent, though time to BSOD varies from hours later to instantly after opening the app. Problem was first noticed when BSOD occurred during gaming sessions while in Gaming mode that stopped mining on GPU-0.

**To Reproduce**
1. Click "Start mining" on NHQM
2. Use computer as normal.
3. BSOD inevitable.

**Expected behavior**
To be able to mine and actively use my computer without crashes, or to mine and game while in gaming mode without crashes.
**Screenshots**

**Version affected (please complete the following information):**
 - Version number 0.5.3.0 and 0.5.3.2 RC (only available version with LHR unlock). This also happens with Nicehash Miner as well.

**NVIDIA driver version**
497.29

**Hardware**
Describe GPUs used and how are GPUs connected to the motherboard.
CPU?
2 GPUs: MSI 3080 Sea Hawk LHR, Zotac 3070 Twin Gaming OC FHR
1 CPU: Ryzen 5600x

**Logs**
Activate logging first, then record event - bug - then export logs into a .zip file and attach it when submitting this issue.
[exported_logs.zip](https://github.com/nicehash/NiceHashQuickMiner/files/7810937/exported_logs.zip)
**Additional context**

**Comment by nieXas** [comment]
I have same issue, as soon as quickminer starts, BSOD, latest drivers windows 11, 3060 v2
