### ISSUE TITLE
[BUG] Disabled setting for a card is not respected after regaining internet access

### ISSUE THREAD

**Issue by xr1140** [nicehash/NiceHashQuickMiner#735]
**Describe the bug**
I have a laptop with a 1080 and attached to the laptop I have a Raizer thunderbolt dock equipped with a 3080. By default, the 1080 is disabled because it gets too hot. Every time the laptop loses and regains wifi internet access, upon restart the miner will mine with both cards even if the 1080 is marked as disabled (including on the website).

**Expected behavior**
The expected behavior will be for the miner to respect the disabled status of the card.

**Version affected (please complete the following information):**
 - Version number [every version since jan 2020]
 - RC or STABLE? both

**NVIDIA driver version**
Which one do you use? Does not matter, the behavior is the same no matter.

**Comment by Hukuma1** [comment]
I see this behavior as well sometimes when disabling a device. Wasn't sure it had to do anything with internet, since mine is via ethernet.

**Comment by Dohtar1337** [comment]
We are aware of the bug.
