### ISSUE TITLE
[error] core | no compatible devices found

### ISSUE THREAD

**Issue by felhie** [nicehash/NiceHashQuickMiner#74]
![image](https://user-images.githubusercontent.com/7336198/108620625-49e38380-7468-11eb-8a62-eeac4280f2aa.png)
i have msi 1650 super , i can use nicehash , but it cannot detect in nicehasquickminer

**Comment by nicehashdev** [comment]
Unfortunately 1650 is not supported, because it has less than 6 GB of VRAM.

**Comment by felhie** [comment]
> Unfortunately 1650 is not supported, because it has less than 6 GB of VRAM.

oh i see. thank for your quick reply
