### ISSUE TITLE
[QUESTION] seperate Uninstall file

### ISSUE THREAD

**Issue by TimyIsCool** [nicehash/NiceHashQuickMiner#743]
**Has the question been answered in [Wiki](https://github.com/nicehash/NiceHashQuickMiner/wiki)? There is no such question in [FAQ](https://github.com/nicehash/NiceHashQuickMiner/wiki/FAQ) or [Troubleshooting collection](https://github.com/nicehash/NiceHashQuickMiner/wiki/Troubleshooting)?**
Yes/No.

**Your question is...**
Is there a uninstall.exe download because my AV removed it from the folder now I cant reinstall the miner

**Comment by TimyIsCool** [comment]
![image](https://user-images.githubusercontent.com/74112751/151237174-c0927efa-ea83-4e11-9a1d-df43009d779f.png)

**Comment by Dohtar1337** [comment]
Just delete the folder.  It will work as uninstall.
