### ISSUE TITLE
[BUG] UNMANAGED Rig

### ISSUE THREAD

**Issue by DarkmanTC88** [nicehash/NiceHashQuickMiner#746]
My rig started showing UNMANAGED rig. It still mines and was working fine for months. Tried to reinstall quick miner, clean install, tried to install nicehash miner, but still same problem. I have also tried both quick miner versions 0.5.2.0 and beta version

[exported_logs.zip](https://github.com/nicehash/NiceHashQuickMiner/files/7965707/exported_logs.zip)

**Comment by Dohtar1337** [comment]
Your router is probably blocking NiceHash traffic. Please whitelist nicehash.
