### ISSUE TITLE
Will Intel Alchemist/Arc GPU's be supported by Quickminer after they launch?

### ISSUE THREAD

**Issue by HouseRoKKa** [nicehash/NiceHashQuickMiner#747]
Hi,

As the question in the title asks, will the Intel GPU's be supported soon after they launch?  I am hoping that they will be decent at mining, and also even a way BIGGER hope, that they will sell around MSRP, but that is another story altogether...

Thanks.

**Comment by Dohtar1337** [comment]
We do plan to support it asap.
