### ISSUE TITLE
[BUG] QuickMiner wont install on Windows 11 (nothing happens)

### ISSUE THREAD

**Issue by AppElent** [nicehash/NiceHashQuickMiner#748]
**Describe the bug**
Installer wont start on Windows 11. 

**To Reproduce**
Just doubleclick the installer or right-click execute (also execute as admin doesnt work)

**Expected behavior**
Opening the installer of course!

**Screenshots**

**Version affected (please complete the following information):**
Latest stable

I found this in event viewer (my OS is in dutch, sorry for that):
Naam van toepassing met fout: NiceHashQuickMinerInstaller.exe, versie: 0.5.3.0, tijdstempel: 0x964214fb
Naam van module met fout: KERNELBASE.dll, versie: 10.0.22000.434, tijdstempel: 0x72a6f702
Uitzonderingscode: 0xe0434352
Foutmarge: 0x000000000004478c
Id van proces met fout: 0x2260
Starttijd van toepassing met fout: 0x01d816b8d0197af5
Pad naar toepassing met fout: D:\NiceHashQuickMinerInstaller.exe
Pad naar module met fout: C:\WINDOWS\System32\KERNELBASE.dll
Rapport-id: 733d33e0-088a-405d-9b07-229beb153b5c
Volledige pakketnaam met fout: 
Relatieve toepassings-id van pakket met fout: 

Toepassing: NiceHashQuickMinerInstaller.exe
Framework-versie: v4.0.30319
Beschrijving: het proces is beëindigd als gevolg van een onverwerkte uitzondering.
Uitzonderingsinformatie: System.IO.FileNotFoundException
   bij watchdog2.Logger.LogEvent(SeverityLevel, System.String, System.String)
   bij watchdog2.config.parse_config_file()
   bij watchdog2.UI.lang.language.Initialize(System.String)
   bij watchdog2.UI.lang.language.GetAvailableLanguages()
   bij watchdog2.Form3.UpdateLanguageComboBox()
   bij watchdog2.Form3..ctor(watchdog2.latest_version, watchdog2.latest_version, Boolean)
   bij watchdog2.installer.try_install(System.String, Boolean)
   bij watchdog2.Program.Main(System.String[])

**Comment by Dohtar1337** [comment]
Works on our tests. Please reopen the ticket if the issue persists.

**Comment by rsimenok** [comment]
Win 11 Pro version 21H2, build 22000.613

Can't install, nothing happens...

**Comment by bArAbAts** [comment]
same problem, same stopcode

**Comment by sundappen** [comment]
Same here. Regular Nicehash miner works, the quickMiner installation won't even run/open on my Win 11

**Comment by Samppahy** [comment]
Same problem here. Win 11 ver 21H2
