### ISSUE TITLE
[BUG] RC 0.5.3.3 AMD - GPU starts up even if disabled

### ISSUE THREAD

**Issue by yesterdays-jam** [nicehash/NiceHashQuickMiner#749]
**Describe the bug**
This happened once.

Installed quickminer RC 0.5.3.3 since it was released.

I have a 6900XT and Vega 56 installed. 

I'm only mining on the Vega 56 so have the 6900XT disabled in rig manager. Everything seemed to be running fine, with expected hashrate. 

Today I came home to find the 6900xt fans had been running on maximum and it turns out it somehow had been activated in quickminer. Rig manager remains to show the 6900xt as disabled. Hashrate reported as total for both GPUs.

I stopped qm, and restarted the qm. Mining again and it's respecting the disabled status for my 6900xt.

**To Reproduce**

I am not sure.

**Expected behavior**

Not sure

**Screenshots**

**Version affected (please complete the following information):**
 - Version number [e.g. 0.4.5.5]
 - RC 0.5.3.3

**NVIDIA driver version**
Which one do you use?

AMD Radeon Pro Diver Q3 2022.

**Hardware**
Describe GPUs used and how are GPUs connected to the motherboard.
CPU?

X570
5800x
6900XT
Vega 56

**Logs**
Activate logging first, then record event - bug - then export logs into a .zip file and attach it when submitting this issue.

Not logged.

**Additional context**

**Comment by yesterdays-jam** [comment]
It's happened again and I'm wondering if an unexpected excavator restart triggers this?

**Comment by Dohtar1337** [comment]
Not enough info. The fan controller will be fixed in one of the next releases

**Comment by danmcmyler** [comment]
I've just had this issue also on version 6.1.2. Not ideal as I'm off grid using mining to heat the house. Overnight such an occurrence could completely drain the battery.
