### ISSUE TITLE
[BUG] 3080TI (FE) unable to get stable LHR unlock

### ISSUE THREAD

**Issue by J3G0** [nicehash/NiceHashQuickMiner#759]
**Describe the bug**
Using FE 3080TI and the efficient optimization I am not able to achieve a stable unlock. Using lite, it is possible but it runs to hot for me that way

**To Reproduce**
1. use 5.3.3
2. Start QM
3. Optimize profile efficient
4. Try to find stable LHR unlock
5. Fail

**Expected behavior**
I expect it should be possible to get a stable LHR unlock

**Screenshots**

**Version affected (please complete the following information):**
 - Version number v0.5.3.3
 - STABLE?

**NVIDIA driver version**
472.12

**Hardware**
FE 3080TI direct in PCI-e slot

**Comment by J3G0** [comment]
No overclock, just using the NiceHash profiles.

**Comment by Drake-W** [comment]
I had this same issue after updating to Version number v0.5.3.3, the issue continues with v0.5.3.5 RC as well. 
Driver version 511.79
[exported_logs.zip](https://github.com/nicehash/NiceHashQuickMiner/files/8165383/exported_logs.zip)

**Comment by Dohtar1337** [comment]
I will check the 3080ti Profile.

**Comment by J3G0** [comment]
The issue still persists
