### ISSUE TITLE
Prerelease v0.3.2.3 RC - NOTEBOOKS !

### ISSUE THREAD

**Issue by m0LN4r** [nicehash/NiceHashQuickMiner#76]
I was using v.0.3.2.2 RC on four different Mobile GPUs without any problems.
Now I updated to version Prerelease v0.3.2.3 RC, to support the development, everything just got worse.

Prerelease v0.3.2.3 RC
1. Could not obtain power consumption Errors, in 0.3.2.2 was everything OK
2. Overclock via OC Tune are not applying - in 0.3.2.2 was working
3. Hashing speed is not Showing anymore

I will have to go back to 0.3.2.2. because in 0.3.2.3 everything is worse on Mobile GPUs

**Comment by nicehashdev** [comment]
Notebooks are officially not supported. But I am curious what could have made this issue. Please, replace excavator.exe from 0.3.2.3 with the one in 0.3.2.2 and report back if this solves your issue?

**Comment by m0LN4r** [comment]
I did an Automatic Update, so I will try tomorrow to roll back

**Comment by m0LN4r** [comment]
> 
> 
> Notebooks are officially not supported. But I am curious what could have made this issue. Please, replace excavator.exe from 0.3.2.3 with the one in 0.3.2.2 and report back if this solves your issue?

If I understand you, I whould lets say download the 0.3.2.2 and 0.3.2.3 and switch thee excavator.exe from .2.2 into .2.3 ?

**Comment by nicehashdev** [comment]
Yes, exactly.

**Comment by chrisngrod** [comment]
I had never tried 3.2.2, but as with the previous releases since 3.0.6, I have not been able to get power consumption to work on a MOBILE GTX 3080.

Tried both excavators with the new releases and it is the same.  I think there is only one driver release currently for this series of mobile graphics cards.

**Comment by nicehashdev** [comment]
You said you were using 0.3.2.2 on 4 laptops, now you are saying you never tried 0.3.2.2?

**Comment by chrisngrod** [comment]
Sorry, maybe I should have started my own thread from the beginning.  The response seems aimed at what I said vs OP's notes.

**Comment by nicehashdev** [comment]
Hah, I do not look who wrote something, but yes, you should start own thread.

**Comment by m0LN4r** [comment]
![grafik](https://user-images.githubusercontent.com/79415218/108638432-84144b80-748f-11eb-9298-f2de0ca72218.png)

Since update 18:00
![grafik](https://user-images.githubusercontent.com/79415218/108638504-db1a2080-748f-11eb-8afe-65a68670f77b.png)

I am also noticing, that the Rigs are unstable, the hashrate is fluctuating and restarting with the Updated version. I will have to go tomorrow on location to fix this.

**Comment by nicehashdev** [comment]
This was a server issue, nothing to do with QuickMiner. Everyone had dips around that time.

**Comment by hoakerk** [comment]
> ![grafik](https://user-images.githubusercontent.com/79415218/108638432-84144b80-748f-11eb-9298-f2de0ca72218.png)
> 
> Since update 18:00
> ![grafik](https://user-images.githubusercontent.com/79415218/108638504-db1a2080-748f-11eb-8afe-65a68670f77b.png)
> 
> I am also noticing, that the Rigs are unstable, the hashrate is fluctuating and restarting with the Updated version. I will have to go tomorrow on location to fix this.

Can confirm it:
![Screenshot_20210222_074746.jpg](https://user-images.githubusercontent.com/16647546/108677936-4b519200-74e2-11eb-9b5d-d914800fb28e.jpg)
Almost 24h later it continues. It's NHQM server issue or global?

**Comment by m0LN4r** [comment]
I just did copy the old excavator 162b to the newest RC and set to EU (Belgium). They are mining, HS seems fine, connection seems fine.

But something weird is going on. In my rig manager now for all rigs it displays STATUS UNKNOWN. I already did two restarts.

**Comment by Disparatado** [comment]
WE know its a server issue, it is written in the Excavator in fck yellow!!! Stop copy/pasting the same  "This was a server issue, nothing to do with QuickMiner. Everyone had dips around that time." crap everywhere and say something tangible!

**Comment by nicehashdev** [comment]
Not everything may work correctly when you mix older version of Excavator into new NHQM, but it was just as a confirmation whether issue appeared just recently or long time ago.

Currently, I am still investigating this issue as there seems to be some non working functionalities when non-DCH drivers are being used.

**Comment by hoakerk** [comment]
12h ago all seems to get back to normal. No issues so far.

**Comment by nicehashdev** [comment]
My investigation so far has shown that it is actually better to use DCH drivers, because some power information is not available in non-DCH drivers. If you have issues, try to experiment with different variants of same version of the drivers. Why NVIDIA made such a mess with drivers it is unknown.

**Comment by nicehashdev** [comment]
Following issue is identical: https://github.com/nicehash/NiceHashQuickMiner/issues/75
Closing this one.
