### ISSUE TITLE
OCTune Core lock limit not working in Alternative method for overclocking v0.5.3.4_RC

### ISSUE THREAD

**Issue by tuntin2022** [nicehash/NiceHashQuickMiner#760]
The core lock limit is not working for 3080,3090.  Works fine for v0.5.3.3

**Comment by Masque** [comment]
Also fails on 1660Ti and 3070. Presumably just broken entirely, as would my cards be if I didn't notice this. Ouch.

**Comment by NeoQuixotic** [comment]
Can also confirm on core clock limit not working on this version. Good way to update and suddenly pull the max TDP from your card(s). This could be bad for unsuspecting people.

**Comment by chchia** [comment]
also fail on 1660s, 2060, 3060.

**Comment by ialexryan** [comment]
Core clock limit confirmed broken in v0.5.3.4_RC on my LHR 3080 and non-LHR 3070. Installing 0.5.3.3 again fixed the problem. Imho, .4_RC should be pulled from distribution until this is fixed...cc @gingertrol

**Comment by SteadVex** [comment]
2080 super and 3070 non LHR both unable to change core clock, only noticed as I kept getting warnings on high temps

**Comment by edb666** [comment]
Yeah, core clock limit (and undervolt) are not working on either of my cards; 2060 super or 3060 Ti LHR.
After update, those fans went crazy, power usage went through teh roof and efficiency of the 2060 super went from >500 kH/J to about 150!
Lookig forward to the day when LHR is properly defeated, and I can see similar efficiency from the 3060 Ti. Both cards mining  at around 43.3 Mh/s now I've gone back to 0.5.3.3

**Comment by ZexMaxwell001** [comment]
QM: V0.5.3.4
OCtune: V1.0.0a
Driver: 511.79
Once installed QM was running my 3080(no LHR) a little hot. looking at the settings it pick some random core clock (I did not write it down.) using the "alt method for OC" to limit my core limit didn't push and save the settings. it kept it at an old setting.  looks like the Autotune is doing the same thing. it found a core clock but did not apply the limits. but it did apply the memory limit.
