### ISSUE TITLE
v0.5.3.4 QM "does not start mining automatically anymore"

### ISSUE THREAD

**Issue by The-Descendant** [nicehash/NiceHashQuickMiner#762]
I've not yet tried this RC but the notes say "QM does not start mining automatically anymore".

Is this only upon the first time launching the program or has the feature stopped automatic mining every time windows starts?

AutoStart mining is a very useful feature for when you have a power cut and you are away from your rig and also if your rig is unstable and reboots from time to time.

If I've misunderstood this change, no worries, if I'm correct, it would be great to be able to keep the AutoStart mining, maybe as an option.

**Comment by ZexMaxwell001** [comment]
Looks like the setting moved. right click the icon in the taskbar go to settings > start mining automatically

**Comment by Dohtar1337** [comment]
> Looks like the setting moved. right click the icon in the taskbar go to settings > start mining automatically

This.
