### ISSUE TITLE
Nicehash keeps forgetting mining address

### ISSUE THREAD

**Issue by tangcla** [nicehash/NiceHashQuickMiner#764]
I have ten NHQM machines and today they have continued to forget the mining address.
I haven't been watching the machines so I am not sure of the cause or trigger why these occur.

**Comment by HouseRoKKa** [comment]
I have a PC with 2 gpus that does the same thing since latest Quickminer update... must be some sort of bug?

**Comment by Ezzassin** [comment]
Same here...all miners reset after power loss
