### ISSUE TITLE
"Medium" optimize setting for 3080 Ti is too high

### ISSUE THREAD

**Issue by jonathanhoskin** [nicehash/NiceHashQuickMiner#765]
Hi - there appears to be an error with the Medium `"id": 2` setting for the 3080 Ti, in this file:

https://github.com/nicehash/NiceHashQuickMiner/blob/dd48cec8e05458cade780bd3b6c2cd4818968e9c/optimize/data_008.json#L82-L87

The clocks of that setting seem way too high for the card. 

If I select Medium, it immediately causes my PC to hang. The "Lite" and "High" settings look more reasonable, and don't cause my PC to hang or crash. I am have been experiencing this issue in the last couple of RC releases. 

If I was to guess, I would say that dmc and mcc should fall in between those of Lite and High. I have a good 3080 Ti for testing on, and am happy to open a PR if you need help with this; let me know?

Thanks in advance.

**Comment by Dohtar1337** [comment]
Thanks! Will fix this.
