### ISSUE TITLE
SERVER FAILURE

### ISSUE THREAD

**Issue by Disparatado** [nicehash/NiceHashQuickMiner#77]
guys, nothing on status...

**Comment by Disparatado** [comment]
![fail](https://user-images.githubusercontent.com/78882077/108635951-82905680-7482-11eb-82c5-ae9f03b90f8f.png)

**Comment by Goran456** [comment]
Same here... +1

**Comment by WinnME** [comment]
same here +1

**Comment by Goran456** [comment]
Don't lose money until you wait for the fix. Download standard miner and use different plugin.

**Comment by Disparatado** [comment]
looks back online now, but still waiting why there is no info on status, you could give us some heads up!

**Comment by nicehashdev** [comment]
Not an issue of QuickMiner. I suggest you to use USA server for the time being.
