### ISSUE TITLE
game mode broke 0.5.3.4RC to 0.5.3.5RC

### ISSUE THREAD

**Issue by shackleford92** [nicehash/NiceHashQuickMiner#770]
prior to 0.5.3.4RC on my rig game mode was non functional spitting out an error about connected display.
0.5.3.4RC is started working which was awesome, it recognized the gpus/displays, halted mining, and appropriately switched clock states. 
0.5.3.5RC the familiar error doesnt appear, xmrig gets closed, excavator stays open/mining, and the overclock unchanged.
i am an edge case on a laptop but i feel the 500+kh/j i get makes my use case a feasible application
![image](https://user-images.githubusercontent.com/84883724/154597355-1ede59fe-75cf-423c-988c-fab9f8536648.png)

**Comment by Dohtar1337** [comment]
This is edge case. Thanks for reporting. This will issue is lower priority. Will not work on it now.
