### ISSUE TITLE
[QUESTION] 

### ISSUE THREAD

**Issue by MaverickBlue** [nicehash/NiceHashQuickMiner#773]
**Has the question been answered in [Wiki](https://github.com/nicehash/NiceHashQuickMiner/wiki)?  No.
There is no such question in [FAQ](https://github.com/nicehash/NiceHashQuickMiner/wiki/FAQ) or [Troubleshooting collection](https://github.com/nicehash/NiceHashQuickMiner/wiki/Troubleshooting)?**
Correct, nothing.

**Your question is...**
What does the changing colour of the tray icon mean? It just seems to flip back and forth between green and yellow as regular as a metronome, and I can't find anything on the internet other than a single reddit comment mentioning it changed color after a certain version. It doesn't appear to be related to the status or function of the program, and there's no discernable difference in the hash rate being reported.

**Comment by TheOriginalHop** [comment]
I assumed it was just an easy way to see it is still active without having to bring up the screen for it. Some rigs crash a lot. One of mine is. Trying to work out which card is the issue by slowly disabling them and the lil mouse over is easy way to see it has not crashed.

**Comment by Dohtar1337** [comment]
This means that the QuickMiner is actively mining. If you stop the mining, flipping will stop.
