### ISSUE TITLE
Add option to force enable/disable LHR optimization on selected GPU

### ISSUE THREAD

**Issue by uhliksk** [nicehash/NiceHashQuickMiner#776]
**Is your feature request related to a problem? Please describe.**
I'm using custom LHR solution which is incompatible with NHQM LHR solution. I need to disable LHR optimization implemented in NHQM to run my custom solution which is not possible since v0.5.3.3 release.

**Describe the solution you'd like**
Option to manually enable/disable LHR optimization should be added in config and API.

**Describe alternatives you've considered**
There is a way to use alternative miner with Nicehash but this way I'll lose control (i.e. restart rig, etc.) of miners thru Nicehash web.

**Additional context**
Optionally you can allow to set intensity and unlock ratio to zero* to disable LHR optimization for specified GPU.
_Edit: *You can use zero or 100%. I'm not sure what is technically reasonable in the current implementation._

**Comment by hryksbt** [comment]
I am facing this problem too.
I am using a non-LHR GPU, but since 5.3.3 it has been mis-detected as an LHR version and the hash rate has dropped significantly.

Applying 5.3.5RC does not improve the problem.

If this cannot be fixed, then the problem can be solved by adding an option to enable or disable the function to check if it is the LHR version at startup.
If it is not the LHR version, just disable the function of this check.

We hope to have this fixed as soon as possible.

**Comment by Dohtar1337** [comment]
We are investigating this feature. For now, not many users require it as most of LHR users use the LHR unlocker from inside the Excavator.

We will discuss it internally. If we will add it, it will be a low-priority task. 

@hryksbt Please use latest RC version of QM, it solves the false LHR detections. https://github.com/nicehash/NiceHashQuickMiner/releases

**Comment by hryksbt** [comment]
Thank you for your reply.
But my issue was not resolved when I installed RC version.
So an option to avoid LHR confirmation is essential.

**Comment by Dohtar1337** [comment]
Forwarded this request to backlog. Might implement.

Closing.

**Comment by uhliksk** [comment]
@hryksbt As a workaround I found the NHQM API will allow to set Unlock ratio to more than 60-90 and LHR intensity to more than 25-50, but even with 99/99 settings it's slower than with the previous Excavator version and also much less power efficient.

![image](https://user-images.githubusercontent.com/37454226/161402580-a43a0054-83d0-4b3b-89f0-6a08cdf93d93.png)

![image](https://user-images.githubusercontent.com/37454226/161402725-5995efb5-6c76-4330-9bb0-1b80d93badce.png)

**Comment by hryksbt** [comment]
@uhliksk 
Thank you for your reply.
If the NHQM API sets the Unlock ratio to 60-90 or higher and the LHR intensity to 25-50 or higher, the value will still be lower than the original capacity.
We still need the ability to skip the LHR check.

**Comment by codsec** [comment]
Im having the same problem i think, how do i fix?
![image](https://user-images.githubusercontent.com/44205014/161676816-3530b13b-8b98-44ff-99f9-ba35931f8d7f.png)

**Comment by uhliksk** [comment]
@codsec The easiest way to achieve full speed again is to downgrade to NHQM v0.5.2.0.

https://github.com/nicehash/NiceHashQuickMiner/releases/tag/v0.5.2.0

**Comment by hryksbt** [comment]
> @codsec The easiest way to achieve full speed again is to downgrade to NHQM v0.5.2.0.
> 
> https://github.com/nicehash/NiceHashQuickMiner/releases/tag/v0.5.2.0

But v0.5.2.0's hash rate is lower than 5.3.3.
Still you need to add skip LHR check function option.
Thanks,

**Comment by hryksbt** [comment]
Since the installer downloads and installs 5.3.3 or the latest version of each RC version, it is not possible to install 0.5.2.0.
You still need to take urgent action to avoid the LHR check by upgrading your version.
