### ISSUE TITLE
[BUG] NICEHASH QM when start my PC is randomly Freezes

### ISSUE THREAD

**Issue by Dmovi365** [nicehash/NiceHashQuickMiner#777]
I have 10 Asus 1660 super TUF gaming with Asus B250 Mining expert motherboard.
When is start NICEHASH QM my PC is Freezes randomly but when i remove 3 GPU from my setup Nicehash QM work Nice. 
I tested nicehash miner Version 3.0.7.1 with 10 GPU and its work fine. that's mean my hardware is fully fine and there is no problem.
i just face this problem when i start Nicehash QM v0.5.3.3 with my 10 GPU. And the problem is gone when i remove 3 GPU from setup.
I think it is software BUG. 

Device- 10 Asus 1660 super (Now Running 7GPU)
Motherboard- Asus B250 mining expert
1300W Power supply 
Windows 10  64 bit

**Comment by raocasio** [comment]
Same problem here.  5.3.3 turns my rig to a brick after a few seconds.  5.2.0 runs perfectly.

**Comment by Dmovi365** [comment]
can you plz give me v5.2.0 link

**Comment by raocasio** [comment]
> can you plz give me v5.2.0 link

This is the release page by NiceHash.  You will find the release history there.  Download the zip fileand run it out of the folder. https://github.com/nicehash/NiceHashQuickMiner/releases

**Comment by Dmovi365** [comment]
Thank you.

**Comment by Dmovi365** [comment]
What is Device setup bro?
how many GPU you have in one rig?

**Comment by raocasio** [comment]
> What is your Device setup bro? how many GPU you have in one rig?

My pleasure. 
7 GPUs- 264 MH/s
1 Aorus 3080 Extreme, 3 ASUS 2060 Dual, 3 MSI 1660 Ventus
B250 MB with 12 slots
8GG ram, 120 GB SSD
1050W Power supply
Windows 10 64 bit

**Comment by Dmovi365** [comment]
Thank you Mr. raocasio 
After installed NHQM v5.2.0 my rig now work nice. all GPU (10*1660 Super) work well.
Now there is no issue :)

**Comment by raocasio** [comment]
> Thank you Mr. raocasio After installed NHQM v5.2.0 my rig now work nice. all GPU (10*1660 Super) work well. Now there is no issue :)
My pleasure.  That's good to hear it worked for you.
I was able to get 5.3.3 to work a few weeks ago after a clean Windows install.  It only worked for a few weeks before it started to freeze.  I started using 5.2.0 again and the problem was solved.
I friend of mine has 2 rigs.  He is able to use 5.3.3 on one rig, but the other one freezes on 5.3.3 so he has to use 5.2.0 on that one.  He can't figure out why.
I am using NVIDIA 472.12 Standard driver on all GPU's.

**Comment by x010d** [comment]
Same bug. 5.3.3 turns my rig to a brick after a few seconds after start mining.
Win10 64 BIOS, 6x3070, 1155 socket board with Pentium Gold CPU

Another rig Win10 64 UEFI - b450/AMD2200G  6xNVIDIAGPU - work's fine

NVIDIA 471.xx Standard Game Ready driver on both rigs.
