### ISSUE TITLE
[BUG] "whenDeviceSpeedZero" option in nhqm.conf doesn't work

### ISSUE THREAD

**Issue by asakiasako** [nicehash/NiceHashQuickMiner#778]
**Describe the bug**
The NHQM will not restart excavator as expected, when device speed continues to be 0.
I confirmed that `whenDeviceSpeedZero` is set to `2` in `nhqm.conf`. It is the default config and I didn't change it.

I found this issue both in NHQM `v0.5.3.5_RC` and `v0.5.3.3 stable`
As a comparison，when I use `v0.5.1.3`, NHQM is able to restart excavator when speed is 0, so I think this issue is brought in after `v0.5.1.3`.

**To Reproduce**
1. make some connection error (e.g. disconnect the ethernet wire).
2. it can be observed that the speed continues to be zero, but no restart performed.

**Expected behavior**
NHQM should restart excavator when speed is zero, since `whenDeviceSpeedZero` is set to `2`

**Screenshots**
![capture](https://user-images.githubusercontent.com/20571168/156874961-09fce9d6-5c2d-4a85-9446-50042a8d29e3.png)

**Version affected (please complete the following information):**
 - v0.5.3.5 RC 
 - v0.5.3.3 stable
 
 as comparision, v0.5.1.3 stable NOT affected 

**NVIDIA driver version**
472.84

**Hardware**
Nvdia Geforce RTX 3080/Nvdia 3060 ti

**Comment by Faginux** [comment]
Same problem.
I'm on v0.5.3.5 RC, when occasionally my internet get cut down, and Excavator looses the server connession, resulting in speed 0, even with whenDeviceSpeedZero is set to 2, nothing happens.
NVIDIA driver version
511.79

Hardware
Nvdia Geforce RTX 2080ti/Nvdia 1660 ti/Nvdia 1660 Super/Nvdia 1660

**Comment by asakiasako** [comment]
> can you attached log file from QM when this happens. Thanks in advance

Sorry for the late reply. Here is the exported_logs of 0.5.3.3 stable.
I closed the internet so the speed continued to be 0, but no restart of excavator.
[exported_logs.zip](https://github.com/nicehash/NiceHashQuickMiner/files/8426361/exported_logs.zip)

**Comment by djmnice** [comment]
ok from what I see from the log, is that NHQM is choking on "Failed to get DNS res. for nhmws.nicehash.com error", so it doesn't attempt to restart the miner because for NHQM the problem is not the miner but the connection....

**Comment by asakiasako** [comment]
Thanks, I will try the new version.

Some times, when internet get cut down for a moment, it can not re-connect itself, but a restart solves the problem.

**Comment by asakiasako** [comment]
Unfortunately, this issue still there on 0.5.3.6 RC. The speed is 0 for 3 hours but no restart performed. And when I restart the excavator everything works well. Now I'm recording logs in real production env, I will share the logs next time the issue occurs.

**Comment by asakiasako** [comment]
This is the log of 0.5.3.6 RC.
[exported_logs.zip](https://github.com/nicehash/NiceHashQuickMiner/files/8468635/exported_logs.zip)

**Comment by asakiasako** [comment]
@Dohtar1337 Thanks for your help! I'm hopping this problem could be solved so I can enjoy the advanced features of the newest versions.

But it seems that 0.0.0.0 is not a valid DNS setting on Windows. So I set it to 1.1.1.1 & 1.0.0.1 suggested by the link. Does that make sense?

By the way, I have some informations might be helpful to make the situation clear:
1. The root cause is the internet connection: I found that there is a network change every hour on the hour (e.g. 3:00, 4:00), the excavator get a internet connection break at that moment.
2. The internet is actually ready for use after that moment, but sometimes, the excavator can not reconnect itself. Maybe because the internet environment has changed? If I restart the excavator to force it reconnect, everything works well. 
3. I did some experiment and believe that the problem is caused by the ONU (Optical Network Unit) of the internet service provider, I don't have full control of it.
4. The point is if we can make some workaround for that particular situation, such as restart excavator or disconnect & reconnect? We can see some other people have this issue as well, so I'm not alone 😀

**Comment by Bars026** [comment]
Do nothing 1
Restart Excavator 2
Restart PC 3
Restart driver 4
When I see it in instruction. I see something wrong.
I don`t see "do nothing" 
And set all = 1 (do nothing)
because I Think
Restart Excavator 1
Restart PC 2
Restart driver 2
https://github-wiki-see.page/m/nicehash/NiceHashQuickMiner/wiki/Tips-%26-tricks
Someone must edit it

**Comment by aramor** [comment]
> @Dohtar1337 Thanks for your help! I'm hopping this problem could be solved so I can enjoy the advanced features of the newest versions.
> 
> But it seems that 0.0.0.0 is not a valid DNS setting on Windows. So I set it to 1.1.1.1 & 1.0.0.1 suggested by the link. Does that make sense?
> 
> By the way, I have some information that might be helpful to make the situation clear:
> 
> 1. The root cause is the internet connection: I found that there is a network change every hour on the hour (e.g. 3:00, 4:00), the excavator get a internet connection break at that moment.
> 2. The internet is actually ready for use after that moment, but sometimes, the excavator can not reconnect itself. Maybe because the internet environment has changed? If I restart the excavator to force it reconnect, everything works well.
> 3. The problem might be caused by the Openwrt Router, or the ONU (Optical Network Unit) device of the internet service provider, but it is difficult to pinpoint, since I'm not proficient on that area.
> 4. The point is if we can make some workaround for that particular situation, such as restart excavator or disconnect & reconnect? I can see some other people have this issue as well, so I'm not alone 😀

same problem 0.5.4.1 RC. you found fix?

**Comment by asakiasako** [comment]
@aramor Not yet, the issue still remains

**Comment by djmnice** [comment]
this issue shouldn't happen anymore in latest version

**Comment by pickmao** [comment]
thanks a lot



发自我的iPhone


------------------ Original ------------------
From: djmnice ***@***.***&gt;
Date: Thu,Jul 14,2022 6:52 PM
To: nicehash/NiceHashQuickMiner ***@***.***&gt;
Cc: pickmao ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [nicehash/NiceHashQuickMiner] [BUG] "whenDeviceSpeedZero" optionin nhqm.conf doesn't work (Issue #778)

**Comment by asakiasako** [comment]
> this issue shouldn't happen anymore in latest version

Yes, I think it's fixed.
Thanks a lot.
