### ISSUE TITLE
[QUESTION] 安装后连接一直提示连接主机没有反应错误代码10060

### ISSUE THREAD

**Issue by ykxingchen** [nicehash/NiceHashQuickMiner#779]
![D953CE8513](https://user-images.githubusercontent.com/101080993/156969946-b4d67d63-e4db-422d-bc96-bc24fbc53fa7.png)

**Comment by Dohtar1337** [comment]
Seems like an issue related to ISP or router blocking NiceHash. 

Please disable AIprotection or whitelist NiceHash traffic in your router settings
