### ISSUE TITLE
Server location changes to EU, even with US selected in Config (Legacy and QuickMiner)

### ISSUE THREAD

**Issue by AmmoArnie** [nicehash/NiceHashQuickMiner#78]
I've been noticing unusually high ping on a few rigs. Turns out they've been hitting EU servers instead of US servers, even with the config options configured correctly in the UI and config file (QuickMiner). 

Changing the value to USA, EU and back to USA fixes the issue most of the time.

![image](https://user-images.githubusercontent.com/12128352/108636876-33780080-7445-11eb-88d1-7132e498ee5c.png)

**Comment by nicehashdev** [comment]
What do you mean with Legacy? Are you talking about NiceHashMiner?

Can you provide exact steps how to trigger this bug?

**Comment by nicehashdev** [comment]
I have informed sysadmin team to check all domain configurations and in fact, a bug in configuration was found and fixed. Let me know if everything is fine now.

**Comment by AmmoArnie** [comment]
thnx for quick fix. I'll monitor behavior and report any issues.

**Comment by thecoolkogut4** [comment]
I also experienced this issue, everything is fine now.

**Comment by nicehashdev** [comment]
Closing.
