### ISSUE TITLE
[BUG] AutoTune Memory OC settings RTX3070

### ISSUE THREAD

**Issue by bissaga** [nicehash/NiceHashQuickMiner#783]
**Describe the bug**

**To Reproduce**
1. Go to 'Autotune settings'
2. Click on 'Set absolute GPU clock and memory absolute settings'
I set absolute clock 1110 and memory absolute to 8200

- Settings saved, applied correctly and no issue. Reboot the system, NHQM will start with the correct settings 1110/8200 no problem.
Shutdown the system and the issue will start, the NHQM will apply wrong memory clock (2800) instead of (1400) and system will instantly crash.
If I use the saved profile Extreme preset which sets 1110/8170. The shutdown doesn't have problem and NHQM will always apply the correct settings on next boot after shutdown.
Is that a bug or limitation with the memory clock to 8170 and any setting over that value will cause that issue? I think so.
I can always replicated the issue.
I tried everything possible, new reinstall, reset profiles, reinstall drivers.
At the moment I switched to NiceHash miner and set my own launch parameters without issue but I would like to use NHQM.

**Expected behavior**

**Screenshots**

**Version affected (please complete the following information):**
 - Version number [e.g. 0.4.5.5]
 - RC or STABLE?
Tried latest stable and RC

**NVIDIA driver version**
Tried 472.12 and 496.49

**Hardware**
Describe GPUs used and how are GPUs connected to the motherboard.
1 GPU RTX 3070
CPU?
ThreadRipper 2950x

**Logs**
Activate logging first, then record event - bug - then export logs into a .zip file and attach it when submitting this issue.

**Additional context**

**Comment by Dohtar1337** [comment]
Please provide more info, I will reopen the ticket if provided.
