### ISSUE TITLE
[BUG] New version make computer frozen

### ISSUE THREAD

**Issue by PH9** [nicehash/NiceHashQuickMiner#784]
**Describe the bug**
Computer frozen

**To Reproduce**
1. Upgrade to newer versions.
2. When the excavator is started the computer is frozen.
The older version is fine.

**Expected behavior**

**Screenshots**

**Version affected (please complete the following information):**
- NHQM_v0.5.3.3
- Excavator_v1.7.6.2_Build_1001

**NVIDIA driver version**
Any version

**Hardware**
- Motherboard H110ProBTC+
- CPU Intel G4400 @3.3- GHz
- Windows 10 Enterprise
- 3 x 1660 Ti
- 2 x 1660 Super
- 2 x 1660 (Optional) I moved to another rig.
- 2 x 4GB of RAM @2400Mhz
- 1 x SSD 120GB Kingston
- Please ask if needed more.

**Logs**
N/A

**Additional context**
N/A Please ask

**Comment by PH9** [comment]
Is any body know how to install older version?

**Comment by Dohtar1337** [comment]
Please use the latest QM version: https://github.com/nicehash/NiceHashQuickMiner/releases/tag/v0.5.3.6_RC

**Comment by raocasio** [comment]
> Please use the latest QM version: https://github.com/nicehash/NiceHashQuickMiner/releases/tag/v0.5.3.6_RC

Highly agreed. All problems are solved with my rig.
