### ISSUE TITLE
[QUESTION]  1050 ti GO 

### ISSUE THREAD

**Issue by Srgtaq** [nicehash/NiceHashQuickMiner#787]
**Has the question been answered in [Wiki](https://github.com/nicehash/NiceHashQuickMiner/wiki)? There is no such question in [FAQ](https://github.com/nicehash/NiceHashQuickMiner/wiki/FAQ) or [Troubleshooting collection](https://github.com/nicehash/NiceHashQuickMiner/wiki/Troubleshooting)?**
Yes/No.

**Your question is...**
What is...
Hello , i want to add my CG for mining but in Nicehash , she don't want launch , i see her but she don"t want farm

**Comment by Dohtar1337** [comment]
CG? Please elaborate the question.
