### ISSUE TITLE
[BUG] quickminer resets overclock for disabled gpu

### ISSUE THREAD

**Issue by nginYthough** [nicehash/NiceHashQuickMiner#788]
**Describe the bug**
One of my gpus (rx580) is disabled in the nhqm.conf, but still shows up in OCTune and my current overclock gets removed when starting and exiting quickminer. This also leads to a reset at some times, when the internet connections cuts out and quickminer has to reinitialize.

**To Reproduce**
1. Disable GPU in config
2. Apply overclock/undervolt for disabled GPU in external tool
3. Start NHQM
4. Overclock/Undervolt is removed on disabled GPU

**Expected behavior**
Disabled gpu should be left alone and not configured in any way. Ideally not even show up in OCTune.

![grafik](https://user-images.githubusercontent.com/97574316/159604706-a46c1ad3-e94b-4f59-af46-60147e00d497.png)

**Version affected (please complete the following information):**
0.5.3.3 Stable, 0.5.3.5 RC

**Hardware**
1080 Ti and RX580 directly on mb

**Comment by nginYthough** [comment]
A current workaround is to replicate the settings of the disabled gpu as closely as possible in quickminer, so that it won't reset to 100% tdp and overheat the gpu.
Still not ideal, because the fan control in quickminer doesn't work 100% for AMD cards and memory voltage is not controllable and also, because I'm using other software for my disabled gpu on purpose.

**Comment by Dohtar1337** [comment]
No response. Closing

**Comment by nginYthough** [comment]
> 

I simply added the device id for `disabledDevices` in NHQM.conf, since there was no obvious option to do it. It is okay for OCTune to see it, but it would be nice to not have it set overclocks for disabled devices.
