### ISSUE TITLE
[BUG] 0.5.3.3 causes low hashrate

### ISSUE THREAD

**Issue by jdack41** [nicehash/NiceHashQuickMiner#789]
**Describe the bug**
0.5.3.3 3090 hashrate is too low.
0.5.2.0 could get 100MH around with lite setting.
but now only 80MH or under.

**Comment by darkmanlv** [comment]
> **Describe the bug** 0.5.3.3 3090 hashrate is too low. 0.5.2.0 could get 100MH around with lite setting. but now only 80MH or under.

i have updated only excavator.exe from 0.5.3.6 RC, now all ok :) hashrate is back

**Comment by Dohtar1337** [comment]
https://www.nicehash.com/blog/post/psa-mining-with-nvidia-drivers-v511-23-or-newer?lang=en
