### ISSUE TITLE
Wrong rig ID interpretation if uniqueID contain plus sign

### ISSUE THREAD

**Issue by uhliksk** [nicehash/NiceHashQuickMiner#79]
If uniqueID contain "+" (plus sign) character it'll create UNMANAGED worker on nicehash.com dashboard.

I switched to Quick Miner from NHM and I want to preserve uniqueID to keep old stats but my uniqueID contain plus sign and it can't be used in quick miner because of that bug.

**Comment by nicehashdev** [comment]
Unfortunately, + signs as RIG ID for QuickMiner do not work. This is a low priority issue and we cannot promise to be fixed anytime soon.

**Comment by uhliksk** [comment]
But there is same problem with "-" (minus sign) generated by QuickMiner itself, For example "0-aySgwHZzOkC-P6aWIflPKw" was generated by QuickMiner and it's causing same problem with "UNMANAGED" rig in dashboard. Will you change UniqueID generator to prevent special characters in UniqueID?

**Comment by uhliksk** [comment]
@nicehashdev Can you remove "done" label and check the issue with QuickMiner UniqueID generator, please?

**Comment by nicehashdev** [comment]
Give me more details about UNMANAGED case. Can you provide full detailed logs of both QuickMiner and Excavator? Thanks.

**Comment by uhliksk** [comment]
@nicehashdev Ok, here is a screenshot from Dashboard, logs and config file - miner address is anonymized, anything else is untouched.

This time "0-z9FzNqNVY0OD-uLKnvya9w" UniqueID was generated, see config file included. I'm able to reproduce this bug easy because for me it's about 1 of 10 new IDs generated with "-" in it.

Logs and config: [logs.zip](https://github.com/nicehash/NiceHashQuickMiner/files/6025526/logs.zip)

![image](https://user-images.githubusercontent.com/37454226/108777618-5f3dd800-7564-11eb-822e-3f444798d8da.png)

**Comment by uhliksk** [comment]
**Note:** For plus sign I tried to replace "+" with "%2B" and it was working partially - stats were preserved but actual profitability was always zero and duplicate "shadow" rig was created in dashboard. Then I was not able to remove duplicate rig using web dashboard. Fortunately mobile app was able to remove it. I know it's not supported to change characters in UniqueID manually but still very interesting mess has been done this way. I think you should reject "invalid" IDs on server side to prevent this.

**Comment by uhliksk** [comment]
**Note 2:** I was able to create "UNMANAGED" rig even with "normal" ID - 0-ZUXi987eUEqvWFMSIhwINQ ... I don't see any special characters there. Now I'm not sure what exactly is causing a Rig name and other parameters are not transfered sometimes.

![image](https://user-images.githubusercontent.com/37454226/108780577-f0af4900-7568-11eb-988c-3e515632d565.png)

If you don't find any issue on your side, you can close this issue for now and I'll try to investigate and collect more info later.

**Comment by nicehashdev** [comment]
Looking into it.. it seems like a server issue. If that is the case, will be fixed tomorrow.

**Comment by nicehashdev** [comment]
Also, perhaps there is no issue, you just have to wait a bit. Wait 5min and see if you have MANAGED rig then?

**Comment by nicehashdev** [comment]
I believe this was just a temporary issue - you need to wait a bit, sometimes up to 2 minutes for Rig to be fully integrated into Rig Manager. Closing it.
