### ISSUE TITLE
[BUG] NiceHashQuickMiner.exe in v0.5.3.6 RC is no longer digitally signed

### ISSUE THREAD

**Issue by Arvenies** [nicehash/NiceHashQuickMiner#790]
As in subject, NiceHashQuickMiner.exe in v0.5.3.6 RC is no longer digitally signed by H-BIT, d.o.o. as it has been for over a year. Interestingly, excavator.exe is still signed by H-BIT, d.o.o. with date 2022.03.23.

**Comment by Dohtar1337** [comment]
Thank you for reaching out. We will fix this asap.
