### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Ishuoksi** [nicehash/NiceHashQuickMiner#791]
My rigs appear as "Unmanaged". This means i can't use the optimizations profiles

Version number - Version v0.5.3.3
latest RC  QuickMiner 
Windows 10 Pro

I use the AV integrated with windows, where i allowed QuickMiner to run.

any suggestions on how i can rectify this problem

**Comment by asakiasako** [comment]
It might because that you cannot connect to some of the address of nicehash, and `raw.githubusercontent.com`. You can try if you can open the link below:

https://raw.githubusercontent.com/nicehash/NiceHashQuickMiner/main/optimize/data_008.json

**Comment by Dohtar1337** [comment]
Sometimes ASUS router are blocking NiceHash traffic. Please make sure that router firewall is disabled (for testing purposes only)

Also, make sure your ISP is not blocking anything mining related

**Comment by Dohtar1337** [comment]
No response. Closing.
