### ISSUE TITLE
My Rig Displays STOPPED on the STATUS

### ISSUE THREAD

**Issue by ZaSa17** [nicehash/NiceHashQuickMiner#793]
i am confused if i should ignore this problem or not. The status of my RIG displays STOPPED even after i press START MINING and refresh the NiceHash Website, but on the CMD it doesn't stop it keeps on mining. Can anyone help me on my little problem?
Your answer is a very big help for me. Thank you and Godbless!!

![Problem](https://user-images.githubusercontent.com/104017799/164037771-f401c732-b686-4473-b3e6-64a9540abf40.JPG)
![proof 1](https://user-images.githubusercontent.com/104017799/164037776-17bb6a42-6963-435c-a2da-da9701749f35.jpg)
![proof 2](https://user-images.githubusercontent.com/104017799/164037781-56d37c8c-0a2f-4945-9494-08eca1402f0b.jpg)
![proof 3](https://user-images.githubusercontent.com/104017799/164037791-53f0c4b0-0d47-4014-b7ed-7143520ee9ce.jpg)

**Comment by Dohtar1337** [comment]
Is the QuickMiner mining or is it not? Based on the load, there seems to be no mining. 

Please make sure that the QuickMiner is actually mining by right clicking on QM icon in Windows tray menu and clicking START.
