### ISSUE TITLE
[FEATURE] Please update XMRig

### ISSUE THREAD

**Issue by randommemer** [nicehash/NiceHashQuickMiner#799]
The current version which is used in QM 5.3.6 is 6.7.0. The latest XMRig update is 6.17.0. That's at least 20 updates. Many bugs have been solved like for example the messages "Failed to start WinRing0 driver, error 183" and "Failed to apply MSR Mod, hashrate will be low" which popup when I try to use my fan utility even though I am running everything as admin!

I tried manually updating the XMRig exe but you guys made it specifically impossible to do so as launching HQ overrides the file and restores the 6.7.0. I'm not sure why you chose to do this, probably so your config doesn't break. Nevertheless that version is close to 1.5 years OLD!

Please update it. Thank you!

**Comment by Dohtar1337** [comment]
Thanks for reaching out. We will update it in the future
