### ISSUE TITLE
AMD GPUs support Please😁

### ISSUE THREAD

**Issue by NYRican73** [nicehash/NiceHashQuickMiner#8]
I really think this is an awesome project you guys put together and I am hoping you will support AMD GPUs too.  If so please let us know.  Team Red would love to know.

**Comment by xantari** [comment]
Yeah, bit odd to only support excavator when none of the documentation here states it supports AMD.

**Comment by nicehashdev** [comment]
It is on todo list already: https://github.com/nicehash/NiceHashQuickMiner/wiki/Planned-features
