### ISSUE TITLE
SERVER ERROR... again without any info

### ISSUE THREAD

**Issue by Disparatado** [nicehash/NiceHashQuickMiner#80]
![obraz](https://user-images.githubusercontent.com/78882077/108696060-5536bd80-7501-11eb-8e8e-eb933ab3c658.png)
+

**Comment by Disparatado** [comment]
it is getting old
![obraz](https://user-images.githubusercontent.com/78882077/108696234-8f07c400-7501-11eb-8046-862db9cce284.png)

**Comment by Disparatado** [comment]
NO UPDATE ON STATUS NOTHING! BULL DONG!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by nicehashdev** [comment]
This is not related to QuickMiner but server issue.

**Comment by Disparatado** [comment]
day after day server issues, its not ok, and stop fkn copy paste the same crap about "not related to QuicMiner", nobody asked for this info!!! INFORM ON STATUS PAGE WHEN SERVER IS DONW!!! INFORM ON TWITTER FOR CRYING OUT LOUD!!!
