### ISSUE TITLE
[QUESTION] Will there be native Linux support?

### ISSUE THREAD

**Issue by Fornball** [nicehash/NiceHashQuickMiner#800]
**Has the question been answered in [Wiki](https://github.com/nicehash/NiceHashQuickMiner/wiki)? There is no such question in [FAQ](https://github.com/nicehash/NiceHashQuickMiner/wiki/FAQ) or [Troubleshooting collection](https://github.com/nicehash/NiceHashQuickMiner/wiki/Troubleshooting)?**
Kinda, Kinda

**Your question is...**
Right now the wiki is suggesting to use virtualization for Linux users. This is for one not as easy to setup as downloading one exe file and secondely not a good solution for Linux desktop users with only one gpu.

My quesion is, will there every be a native app for Linux? If so, is there any rough eta on that?

**Comment by Dohtar1337** [comment]
No, there is no plan for QM to work on linux.

We are developing an ubuntu based mining OS.
