### ISSUE TITLE
Quickminer OCTune won't detect all GPUs 

### ISSUE THREAD

**Issue by mkelly1717** [nicehash/NiceHashQuickMiner#802]
Can't get OCTune to detect and show all GPUs, current parameters, and allow changing parameters in Manual mode.

Lite and Medium are great for using a canned set of settings, and in Manual I used to be able to change settings with OCTune, but now OCTune no longer detects my GPUs, shows current parameters, or allows changing of parameters.  Plus, changing to Manual automatically changes to Optimize.  I can change settings in Optimize with Afterburner, but I wish to have still OCTune available to view the settings of all my GPUs in real time, and to control my GPUs if I don't want to use Afterburner.

I have already tried completely uninstalling Nicehash Miner, Quickminer, and Afterburner, then reinstalling each.  OCTune still shows just 2 GPUs but no new readings.  I'm still integrating my rig, so I have had between 2 and 6 GPUs during many experiments.

**Versions:**
 - Nicehash 3.0.7.2
 - QM 0.5.3.3
 - Afterburner v4.6.4.16255

**NVIDIA driver version**
472.12

**Hardware**
Nvidia 1660 Super Gaming X (between 4 and 6 cards) powered with 6&8 pin, no Sata
Biostar TB360-BTC Pro 2.0
Intel i3-9100 3.6ghz
Ram 16gb
W10 Home
Samsung ssd 870 Evo 250gb
Evga 1300w supernova platinum (2x, just 1 hooked up)
Febsmart v006c risers

**Comment by gbrow004** [comment]
Using QM 05.3.6RC and it doesn't detect my Radeon VII. Device manager sees it, and the GPU outputs video.

**Comment by Dohtar1337** [comment]
Please reinstall your GPU drivers. Use DDU first.

**Comment by Aungsanoo234** [comment]
#802

**Comment by mkelly1717** [comment]
> Please reinstall your GPU drivers. Use DDU first.

Thanks, that was the very first thing I tried, many times.  All other Nicehash and Quickminer utilities see all my Cards, but when I open OCTune in either of the ways to open it, it opens with just 2 GPUs showing, and with stale data.  I would have thought uninstalling and reinstalling Nicehash and Quickminer would fix this, but it didn't.  A computer expert friend suggested reinstalling Windows, but this should not require such a severe action to fix.  My guess would be there's a data file hidden somewhere that OCTune uses when it comes up, and that file is incomplete or corrupted somehow.

**Comment by Dohtar1337** [comment]
I just noticed that you are using NHM 3.0.7.2. Note that OCTune only works with QuickMiner. NHM will not send data to OCTune.

Also, if this is not the case, try using another browser.
