### ISSUE TITLE
Nicehash Miner and Quickminer both cause CPU to rise to 70%-100% from 20%

### ISSUE THREAD

**Issue by mkelly1717** [nicehash/NiceHashQuickMiner#803]
I was having issues with CPU usage up near 80%-100% while running Nicehash Miner and Quickminer both, which caused my rig to sometimes crash.  It suddenly dropped to 20% for some days, but now it's back high, settling in at around 70%, only when one of those programs is running.  In Task Manager, I can see that it is System Interrupts and Service Host: Diagnostic Policy Service which are consuming that CPU usage, as well as Very High power usage.  I've reloaded GPU drivers multiple times and no changes.

What would cause this, and how can it be fixed.  With high CPU usage, my mouse is slow to move and the rig sometimes crashes.

Versions:
    Nicehash 3.0.7.2
    QM 0.5.3.3
    Afterburner v4.6.4.16255

NVIDIA driver version
472.12

Hardware
Nvidia 1660 Super Gaming X (between 4 and 6 cards) powered with 6&8 pin, no Sata
Biostar TB360-BTC Pro 2.0
Intel i3-9100 3.6ghz
Ram 16gb
W10 Home
Samsung ssd 870 Evo 250gb
Evga 1300w supernova platinum (2x, just 1 hooked up)
Febsmart v006c risers

**Comment by Dohtar1337** [comment]
This issue should be solved in the upcoming release. Please follow NHQM updates and see if the next release solves the issue for you.
