### ISSUE TITLE
[BUG] can't launch a game with QM running

### ISSUE THREAD

**Issue by ProMehdi** [nicehash/NiceHashQuickMiner#810]
**Describe the bug**
I installed QM and everything is running fine I got lhr unlocked successfully but I can't launch a game and my Logitech Ghub is disconnected my mic doesn't work but the headset working fine
about the game I tried to launch dota2, it immediately crushes and doesn't run-up, I also tried to open the GeForce experience
it crushed immediately even the Nvidia control panel But I still can use chrome

**Version affected (please complete the following information):**
 - Version number 0.5.4.0
 - RC

**NVIDIA driver version**
512.59

**Hardware**
1x 3060ti LHR Palit
1x 2070super inno3d
1x Ryzen 3600

**Comment by SirDalavar** [comment]
This is the same problem i"m having,
Driver: 496.13
3060 LHR V2
3070 (not actively mining)

Nvidia control panel crashed after 1 second, tried to launch world of warcraft and it behaved the same way, crashing instantly when activating the miner. not even running the desktop/games from the 3060 despite it being the only card mining.

**Comment by SirDalavar** [comment]
This guys fix solved my problems, i suspect it might work for you too.
https://www.reddit.com/r/NiceHash/comments/ukxoyh/fix_for_qmexcavator_054_rc_closing_hwmonitor_nvcp/

**Comment by Dohtar1337** [comment]
This is the way QM works right now. Some programs will not able to work while mining with latest RC if you are using LHR GPUs.
