### ISSUE TITLE
MSI RTX 3070TI TRIO 8G not working correctly

### ISSUE THREAD

**Issue by oemMartin353** [nicehash/NiceHashQuickMiner#811]
`=========================== www.nicehash.com =========================
           Excavator v1.7.7.0 GPU Miner for NiceHash.
           Copyright (C) 2022 NiceHash. All rights reserved.
=========================== www.nicehash.com =========================

Build time: 2022-05-06 19:35:59
Build number: 1020
Provided startup commandline: -c commands.json -qx -qm -d 2 -f 6 -wi localhost -wp 18000 -wa 6C4BD9D54B4B322C79EEA9CF

[15:47:14][0x000025a0][info] Log started, build v1020
[15:47:14][0x000025a0][error] OpenCL error 'Unknown' in func 'openclhelp::init' line 3957`

Tried all the troubleshooting, but still not working

NHQM_v0.5.4.0_RC.zip
Drivers: 472.12

**Comment by shadowwzw** [comment]
I have the same problem

**Comment by Dohtar1337** [comment]
Please do this and let me know if it fixed the issue: https://www.nicehash.com/blog/post/how-to-correctly-uninstall-and-install-gpu-drivers

**Comment by shadowwzw** [comment]
> Please do this and let me know if it fixed the issue: https://www.nicehash.com/blog/post/how-to-correctly-uninstall-and-install-gpu-drivers

Thanks! It works!
