### ISSUE TITLE
[BUG] After I press shutdown, PC crashes with blue screen

### ISSUE THREAD

**Issue by xrtw** [nicehash/NiceHashQuickMiner#814]
After I press shutdown PC, crashes with blue screen CRITICAL PROCESS DIED

**Comment by nieXas** [comment]
I have same issue, as soon as quickminer starts, BSOD, latest drivers windows 11, 3060 v2

**Comment by adagirjr** [comment]
Aqui Win11, 3060 v1 e v2 ambas tela azul ao abrir na versão 4.0 
A antiga 0.5.3.6 funcionando OK.

**Comment by nieXas** [comment]
tried two different cards

> I have similar issue with v0.5.4.0 RC , as soon as quickminer starts, BSOD, latest drivers windows 11, 3060 v2
> 
> all good with v0.5.3.6
> 
> edited, monitor plugged into the card (DP)

same happened with asus and inno3d cards

**Comment by jonasguerra** [comment]
> After I press shutdown PC, crashes with blue screen CRITICAL PROCESS DIED

Same happening here!

**Comment by 1arghavan** [comment]
Same here
RTX3080Ti - Windows 11

**Comment by richardzed** [comment]
same RTX 3080 Vision 10 GB  Win 10

**Comment by 1arghavan** [comment]
For anyone still having problem, NBMiner has a 100% LHR unlock too and you can use it with NiceHash.

**1**. Download [NiceHash Legacy Fork](https://github.com/angelbbs/NiceHashMinerLegacy)
**2**. Download the lastest version of [NBMiner ](https://github.com/NebuTech/NBMiner)(v41 or newer)
**3**. replace the files from old NBminer in NiceHash Legacy Fork folder:
C:\Users\_XXX_\AppData\Roaming\NHML Fork Fix\miners\NBMiner
with the new ones from NBMiner v41 you just downloaded
**5**. Run Nicehash Legacy, Go to Settings, Devices/Algorithms and disable every algorithm except NBMiner
**6**. Enter your mining address in Bitcoin address of NiceHash Legacy Fork
**7.** Click Start
**8**. Profit!

Mine is Aorus RTX 3080 Ti mining at 120MH/s with 10600Mhz on Memory, 1215Mhz on Core and 300W power limit.
