### ISSUE TITLE
[BUG] PC freezes even with the QuickMiner on pause

### ISSUE THREAD

**Issue by NecroRAM** [nicehash/NiceHashQuickMiner#815]
**Describe the bug**
PC (at least the screen output) freezes indefinitely. Doesnt go into a BSOD, just freezes until i have to restart.
First i thought it was my OC settings but then why should it freeze if the miner is on pause.
Also crashes Geforce Experience when i try to lookup the driver version, was ok after i closed the miner.

**To Reproduce**
My OC settings through OC Tune:
Alt OC method
Core: 1200
Mem absolute: 10000
Undervolt: crashed on both enabled and disabled
LHR: 100
Intensity: 55-100
Fan: 80 fixed

**Expected behavior**
No crashes/freezes at least during the paused period

**Screenshots**

**Version affected (please complete the following information):**
 - Version number: 0.5.4.0 RC

**NVIDIA driver version**
512.59

**Hardware**
EVGA 3080Ti FTW3 directly in PCIe 4.0 slot.
Ryzen 3700X

**Logs**
Not sure how to do this or what exactly should be logged.

**Additional context**

**Comment by moops44** [comment]
Logs
Not sure how to do this or what exactly should be logged.

https://github.com/nicehash/NiceHashQuickMiner/wiki/Tips-&-tricks#5-enable-logging-for-better-troubleshooting

**Comment by Dohtar1337** [comment]
Please try uninstalling NVIDIA experience.

**Comment by Dohtar1337** [comment]
A new release is coming with fixes. This bug report is obsolete.

If the issue repeats, please reopen a new issue.

Thank you for reaching out anyway!
