### ISSUE TITLE
extreme overclock put as high overclock

### ISSUE THREAD

**Issue by squally2k47** [nicehash/NiceHashQuickMiner#816]
isnt this line supposed to be like this?:
"id": 4, etc.

https://github.com/nicehash/NiceHashQuickMiner/blob/2dee4c6a9bb022684247e6ad7fa6159b7cd299a9/optimize/data_009.json#L140

**Comment by Dohtar1337** [comment]
Thanks! This will be fixed soon.

**Comment by squally2k47** [comment]
isnt 1350 dmc and 1530 mcc too high for 3060?
it fails on all my 4 3060s
