### ISSUE TITLE
[BUG] v0.5.4.0 RC - BSOD on Windows 11 - CRITICAL_PROCESS_DIED

### ISSUE THREAD

**Issue by crobotco** [nicehash/NiceHashQuickMiner#817]
The follow BSOD instantly occurs following launch of NHQM RC as soon as miner address is inputted confirmed:
```
 ==================================================
            Dump File         : 050722-5296-01.dmp
            Crash Time        : 5/7/2022 1:19:49 PM
            Bug Check String  : CRITICAL_PROCESS_DIED
            Bug Check Code    : 0x000000ef
            Parameter 1       : ffffba01`49fa90c0
            Parameter 2       : 00000000`00000000
            Parameter 3       : 00000000`00000000
            Parameter 4       : 00000000`00000000
            Caused By Driver  : ntoskrnl.exe
            Caused By Address : ntoskrnl.exe+4169a0
            File Description  : 
            Product Name      : 
            Company           : 
            File Version      : 
            Processor         : x64
            Crash Address     : ntoskrnl.exe+4169a0
            Stack Address 1   : 
            Stack Address 2   : 
            Stack Address 3   : 
            Computer Name     : 
            Full Path         : C:\Windows\Minidump\050722-5296-01.dmp
            Processors Count  : 20
            Major Version     : 15
            Minor Version     : 22000
            Dump File Size    : 3,018,556
            Dump File Time    : 5/7/2022 1:20:20 PM
            ==================================================
```
Windows 11 Pro Intel 12700k DDR4 @ 3600 3070, 512.59 drivers Clean install of NHQM RC

**Troubleshooting steps taken:**

Closed ALL running programs besides QM
Confirmed stable QM runs fine
Re-installed QM RC, optimize option checked
Re-installed QM RC, optimize option de-selected
NHQM folder added to Windows Defender exclusions
Clean install of latest NV drivers (512.59)

```
NVIDIA System Information report created on: 05/07/2022 13:25:12

[Display]

Operating System:	Windows 10 Pro, 64-bit
DirectX version:	12.0 
GPU processor:		NVIDIA GeForce RTX 3070
Driver version:		512.59
Driver Type:		DCH
Direct3D feature level:	12_1
CUDA Cores:		5888 
Resizable BAR		No
Core clock:		1905 MHz 
Memory data rate:	14.00 Gbps
Memory interface:	256-bit 
Memory bandwidth:	448.06 GB/s
Total available graphics memory:	24462 MB
Dedicated video memory:	8192 MB GDDR6
System video memory:	0 MB
Shared system memory:	16270 MB
Video BIOS version:	94.04.46.40.F2
IRQ:			Not used
Bus:			PCI Express x16 Gen4
Device Id:		10DE 2488 882C1043
Part Number:		G142 0012

[Components]

nvui.dll		8.17.15.1259		NVIDIA User Experience Driver Component
nvxdplcy.dll		8.17.15.1259		NVIDIA User Experience Driver Component
nvxdbat.dll		8.17.15.1259		NVIDIA User Experience Driver Component
nvxdapix.dll		8.17.15.1259		NVIDIA User Experience Driver Component
NVCPL.DLL		8.17.15.1259		NVIDIA User Experience Driver Component
nvCplUIR.dll		8.1.940.0		NVIDIA Control Panel
nvCplUI.exe		8.1.940.0		NVIDIA Control Panel
nvWSSR.dll		30.0.15.1259		NVIDIA Workstation Server
nvWSS.dll		30.0.15.1259		NVIDIA Workstation Server
nvViTvSR.dll		30.0.15.1259		NVIDIA Video Server
nvViTvS.dll		30.0.15.1259		NVIDIA Video Server
nvLicensingS.dll	6.14.15.1259		NVIDIA Licensing Server
nvDevToolSR.dll		30.0.15.1259		NVIDIA Licensing Server
nvDevToolS.dll		30.0.15.1259		NVIDIA 3D Settings Server
nvDispSR.dll		30.0.15.1259		NVIDIA Display Server
nvDispS.dll		30.0.15.1259		NVIDIA Display Server
PhysX			09.21.0713		NVIDIA PhysX
NVCUDA64.DLL		30.0.15.1259		NVIDIA CUDA 11.6.134 driver
nvGameSR.dll		30.0.15.1259		NVIDIA 3D Settings Server
nvGameS.dll		30.0.15.1259		NVIDIA 3D Settings Server

```

**Comment by crobotco** [comment]
**Additional troubleshooting step:**

Enabled Resizable BAR - no change

**Comment by 19Micke71** [comment]
Same issue here on win 10, nvidia driver 512.59 on an Asus 3070 Ti.

The logfile is full of these kind of entries  "Failed to establish communication channel with Excavator!"
[log.txt](https://github.com/nicehash/NiceHashQuickMiner/files/8645721/log.txt)

**Comment by rxszcn** [comment]
Win11，v0.5.4.0 RC，3080Ti，同样一开就蓝屏重启

**Comment by matteoflavi** [comment]
Same problem:
Win11，v0.5.4.0 RC，3080 LHR

**Comment by adagirjr** [comment]
Resolvido aqui.
Instalado ultima versão do QM. (remover pasta antiga do QM anterior - instalação limpa)
Removido driver antigo Nvidia com DDU e instalado 512.59.
Não colocar a otimização ALTA. Deixar padrão

**Comment by sundappen** [comment]
Same thing here. Repeatedly BSOD Win11 CRITICALPROCESS_DIED , 3080LHR

**Comment by charnet3d** [comment]
Same. BSOD Win11 CRITICALPROCESS_DIED. Palit Gaming Pro 3080 10GB LHR

**Comment by stevoinco** [comment]
Same here, Win11 (21H2, build 22000.652), Nvidia driver 512.59, single 3080ti, NHQM v0.5.4.0RC.

**Comment by nacoc2012** [comment]
Same. Win11 22000.652, driver 512.59, 1 x 3080 10GB LHR, v0.5.4.0 RC, "Critical Process Died" BSOD.

**Comment by DeviLs1-TA** [comment]
Same here, win11, 3080lhr

**Comment by waello** [comment]
same here

**Comment by charnet3d** [comment]
If this happens to you and you want a workaround for the Full Hashrate you can try bypassing the quickminer GUI and running excavator directly. I describe the steps I used in my comment on reddit: https://www.reddit.com/r/NiceHash/comments/uk9w2n/nicehash_manages_to_unlock_lhr_cards_to_100/i7r5f0g/

**Comment by KingDerpDeDerp** [comment]
Same issue. Blue screen with "critical process died" immediately after entering wallet address. Windows 11. 9900k Asus 3080ti

**Comment by davidbukit** [comment]
Same here. Spec Win10 driver 472.1
After start mining, 2 things may occur:
1. suddenly restart PC, and one of PSU with its all gpu attached just stop working (need to full shut down to makes them working again)
2. blue screen critical process died, and same number 1 above

**Comment by 19Micke71** [comment]
> Same issue here on win 10, nvidia driver 512.59 on an Asus 3070 Ti.
> 
> After crash excavator is no longer working, crashes within seconds over & over again. The logfile is full of these kind of entries "Failed to establish communication channel with Excavator!" [log.txt](https://github.com/nicehash/NiceHashQuickMiner/files/8645721/log.txt)

More isues, when i stop mining on my primary card so i can play some games, every game launched from Origin crashes on load & Gpu Tweak III monitor stops working or crashing.
Closing any app/Browser etc while mining causes this BSOD  too,

**Comment by spajdrEX** [comment]
Same. Win11 22000.652, driver 512.59, 1 x 3070Ti, v0.5.4.0 RC, "Critical Process Died" BSOD.

**Comment by MrTechGadget** [comment]
Same here, Windows 10, RTX 3060. Reinstalling stable works fine no crash and starts.

**Comment by touhoku-japan** [comment]
Same here, Windows 11 Pro, RTX 3070 Ti, stable is OK but RC is crash.

**Comment by spajdrEX** [comment]
Installed NBMiner, crashes gone, 84MH/s.
Issue solved

**Comment by sundappen** [comment]
No updates on this issue? My Win11 won't even run the NiceHashQuickInstaller file. Doing it manually still crashes on the screen when BTC mining  address is entered.

**Comment by floristics** [comment]
Problem solved by downloading zip archive from github instead of download installer from site. No BSOD there

**Comment by MexLi** [comment]
![image](https://user-images.githubusercontent.com/105333613/167761075-6328fb4d-81bd-4fb4-938e-7a7dba930b23.png)
1. Open the properties of NiceHashQuickMiner.exe
2.  Go to the compatibility tab.
3. Under Settings check the box for Disable fullscreen optimizations. 

I would never have believed this was the issue but I saw this post on the main github page for the download and sure enough it worked for me and a few others. I am running windows 11 and the current nvidia driver.

**Comment by 19Micke71** [comment]
> ![image](https://user-images.githubusercontent.com/105333613/167761075-6328fb4d-81bd-4fb4-938e-7a7dba930b23.png)
> 
> 1. Open the properties of NiceHashQuickMiner.exe
> 2. Go to the compatibility tab.
> 3. Under Settings check the box for Disable fullscreen optimizations.
> 
> I would never have believed this was the issue but I saw this post on the main github page for the download and sure enough it worked for me and a few others. I am running windows 11 and the current nvidia driver.

This seems to have solved the BSOD, but excavator keeps crashing over & over again.

**Comment by Dohtar1337** [comment]
A new release is coming with fixes. This bug report is obsolete.

If the issue repeats, please reopen a new issue.

Thank you for reaching out anyway!
