### ISSUE TITLE
IS THERE ANY WAY TO OPEN OTHER MINERS FOR NON LHR CARDS AT THE SAME TIME?[QUESTION] 

### ISSUE THREAD

**Issue by HeraklesTR** [nicehash/NiceHashQuickMiner#818]
**Has the question been answered in [Wiki](https://github.com/nicehash/NiceHashQuickMiner/wiki)? There is no such question in [FAQ](https://github.com/nicehash/NiceHashQuickMiner/wiki/FAQ) or [Troubleshooting collection](https://github.com/nicehash/NiceHashQuickMiner/wiki/Troubleshooting)?**
Yes/No.

**Your question is...**
What is...
Hi guys, since quickminer doesn't support dual mining, i only want to use it for lhr cards in my rig. some of the cards in my rig are not lhr so i want to use lol miner or gminer instead to dual mine on them. Hovever even i disable these gpus in quickminer, it still crashes the miner if you try to open other miners with quickminer at the same time. So sadly quickminer forcing me to use only itself for all cards... Isthere any way to solve this?

**Comment by moops44** [comment]
https://www.nicehash.com/blog/post/100-lhr-unlock-at-nicehash-its-here



Does 100% unlock only work on NiceHash?

Yes, the 100% unlock only works on NiceHash. You cannot use it to mine elsewhere.

**Comment by Dohtar1337** [comment]
No, this is not possible
