### ISSUE TITLE
[BUG] LHR remover beta resets core clock to stock

### ISSUE THREAD

**Issue by jesuschrist4202** [nicehash/NiceHashQuickMiner#819]
**Describe the bug**
I am using the new rc quickminer and it is resetting core clock to stock curve on launch despite having optimize set to manual. My overclock is +240 and 0.9v limit. Power limit and memory clock seems to be unaffected by this.

**To Reproduce**
1. Make a msi afterburner overclock with a custom core curve
2. Start quickminer
3. Watch the core clock revert to stock, while memory clock and powerlimit should stay what you set. It does not visually change the slider in msi afterburner, the core will just behave stock until you apply profile again in msi afterburner.

**Expected behavior**
I expected core clock to remain behaving as specified by my msi afterburner profile

**Version affected (please complete the following information):**
0.5.4.0 RC

**NVIDIA driver version**
512.59

**Comment by moops44** [comment]
Why u dont use OC TUNE only , u can set everything you like there even voltage limit 🙄
![sdfsdfewerwerwerwererw](https://user-images.githubusercontent.com/40867557/167273158-d661810d-baed-471b-9e16-4e34f0be1a5d.PNG)

**Comment by jesuschrist4202** [comment]
> Why u dont use OC TUNE only , u can set everything you like there even voltage limit 🙄 ![sdfsdfewerwerwerwererw](https://user-images.githubusercontent.com/40867557/167273158-d661810d-baed-471b-9e16-4e34f0be1a5d.PNG)

Because in oc tune you cant make a unique offset for every voltage step and it also doesn't have automatic profile switching. furthermore msi is reliable and universal so I don't have to change software anytime I switch mining software.

**Comment by Dohtar1337** [comment]
MSI Afterburner will not work correctly with QM. Use OCTune instead. Closing the issue.
