### ISSUE TITLE
OCTune: minimum fan speed at target GPU Temp

### ISSUE THREAD

**Issue by patonic** [nicehash/NiceHashQuickMiner#82]
When setting the target to a certain temperature, situations arise when the fan starts to stop and turn on cyclically (negatively affects the fan resource and noise). If it were possible to limit the minimum permissible rotation speed, then such situations could be avoided.

**Comment by nicehashdev** [comment]
Will add this as a feature request on TODO list.

**Comment by nicehashdev** [comment]
Added, closing.
