### ISSUE TITLE
[BUG] LHR unlock not working on GIGABYTE 3080 VISION 

### ISSUE THREAD

**Issue by kotgeee** [nicehash/NiceHashQuickMiner#821]
![image](https://user-images.githubusercontent.com/105130565/167271968-e30d5ec9-2cee-4ebb-8c46-188a92994085.png)

hashrate ~48-50
on the previous version ~70-72

**Comment by moops44** [comment]
if its a 12GB Version, it will not work

**Comment by kotgeee** [comment]
> 

No, 10G

**Comment by moops44** [comment]
> 

did you set a optimized profil in OC TUNE ?

**Comment by kotgeee** [comment]
> did you set a optimized profil in OC TUNE ?

I tried everything, there is always an warning as in the picture 
On the previous version everything works without additional settings

**Comment by moops44** [comment]
> 

that warning is total normal , also appear on my 2x 3070 Ti and LHR Unlock works

**Comment by Leowinterhill** [comment]
I have massive issues on my LHR cards. Almost half as normal hashrates. Such as the photo posted, same issue as mine. 50% of normal hashrate of RTX 3080. Some of my RTX 3080 Ti only goes 60. I don't know why and still working on that now.

**Comment by kotgeee** [comment]
> that warning is total normal , also appear on my 2x 3070 Ti and LHR Unlock works
> ignore the one with lower hashrate , im connected through teamviewer etc etc
> ![dinnggdinnng](https://user-images.githubusercontent.com/40867557/167273026-50f76095-c2b5-41cd-9f02-9bd206acd118.PNG)

then I have absolutely no idea why unlock lhr doesn’t work in my 3080

**Comment by kotgeee** [comment]
> I have massive issues on my LHR cards. Almost half as normal hashrates. Such as the photo posted, same issue as mine. 50% of normal hashrate of RTX 3080. Some of my RTX 3080 Ti only goes 60. I don't know why and still working on that now.

So I'm not the only one with such a problem

**Comment by Leowinterhill** [comment]
> > I have massive issues on my LHR cards. Almost half as normal hashrates. Such as the photo posted, same issue as mine. 50% of normal hashrate of RTX 3080. Some of my RTX 3080 Ti only goes 60. I don't know why and still working on that now.
> 
> So I'm not the only one with such a problem

Seem like you are not alone. I have my issues with my RTX 3080 Ti, RTX 3070 Ti so far.
However, my troublesome RTX 3070 Ti is ASUS and my Gigabyte RTX 3070 Ti works well.
My RTX 3060 and RTX 3060Ti work perfectly.
Moreover, my Gigabyte RTX 3080 Ti doesn't work as well. So I don’t think it's brand's issue so far.
Still DDU now, but they both use 472.12, so no progress so far.

**Comment by Leowinterhill** [comment]
Saw the comments online saying due to it's a RC version, which means not all cards were supported properly. 
Understood and accepted.
Roll back to non RC version then for those cards.

**Comment by bettimms** [comment]
Two of my three Gigabyte 3080 cards have the same issue as well. I've 2 Gigabyte Aorus Waterforce WB exactly the same, one gives 98MHs one 54Mhs(usually with other mining software these two cards give same performance). And another Gigabyte Aorus Master 3080 that gives 54Mhs.

1) Gigabyte Aorus Waterforce WB = 98 MHs
2) Gigabyte Aorus Waterforce WB = 54 MHs
3) Gigabyte Aorus Master 3080 = 54 Mhs.

**Comment by Leowinterhill** [comment]
Prove from my end that cards themselves decide whether they can fully unlock. Here's the successful examples:
RTX 3080 Ti:
Brand: Gigabyte 
Model: Gaming OC
Result: Fail. Half Hashrate Only.

RTX 3070 Ti:
Brand: Gigabyte
Model: Gaming OC
Result: Successful

Brand: ASUS
Model: TUF Gaming
Result: Fail. Half Hashrate Only.

RTX 3060:
Brand: Zotac
Model: Too lazy to check. But it's the lowest end card.
Result: Superb. Easy over 50.

**Comment by Leowinterhill** [comment]
> ![image](https://user-images.githubusercontent.com/105130565/167271968-e30d5ec9-2cee-4ebb-8c46-188a92994085.png)
> 
> hashrate ~48-50 on the previous version ~70-72

Problem solved. Don't mix cards. Use it in one rig.

**Comment by richardzed** [comment]
This did not solve it for me I have the 3080 Vision 10gb , whether on it's own or mixed with another card locked to 66% .
Hash rate high 40's low 50's .
Tried everything , Going back to release version and back to low 60's in hashrate .

**Comment by Dohtar1337** [comment]
A new release is coming with fixes. This bug report is obsolete.

If the issue repeats, please reopen a new issue.

Thank you for reaching out anyway!
