### ISSUE TITLE
Only the first one card works in my 6 3080 lhr rig！

### ISSUE THREAD

**Issue by sosme2012** [nicehash/NiceHashQuickMiner#822]
NHQM_v0.5.4.0_RC

Only the first one card works in my 6 3080 lhr rig！

**Comment by Leowinterhill** [comment]
> NHQM_v0.5.4.0_RC
> 
> Only the first one card works in my 6 3080 lhr rig！

Your first 3080 must be different from other cards?
Brand is different? Model is different?

**Comment by phanijsp** [comment]
I can confirm this. I have 5 gigabyte 3080 s in which 1 is a different model. Only that card is mining at full hash rate.

**Comment by Leowinterhill** [comment]
> I can confirm this. I have 5 gigabyte 3080 s in which 1 is a different model. Only that card is mining at full hash rate.

My MSI Sea Hawk RTX 3080 also can only achieve 50% hashrate. Nothing can be done now. The first wave of unlock does not cover those cards though.

**Comment by sosme2012** [comment]
> 12gb not works... only 10gb. read article

yes ,mine is gigabyte 3080 10g

**Comment by phanijsp** [comment]
Yep all 5 of mine are 10g too

**Comment by phanijsp** [comment]
Nbminer is working fine

**Comment by Dohtar1337** [comment]
A new release is coming with fixes. This bug report is obsolete.

Thank you for reaching out anyway!
