### ISSUE TITLE
Immediate crash [BUG] 

### ISSUE THREAD

**Issue by basil107** [nicehash/NiceHashQuickMiner#824]
After installing Nicehash Quickminer and starting it I immediately get a bluescreen and My Rig Restarts. 

The blue screen says : windows 10 error code critical_process_died 

I tried reinstalling. 

I tried resetting all my over clocks 

I tried stopping msi Afterburner 

I updated to the latest Nvidia Driver 

and still I'm faced with the same blue screen as soon as I start the Quickminer  

Ps. I have an Inn3d 3080Ti with an evga Bios reflash.

**Comment by basil107** [comment]
I forgot to mention that using the stable version will not crash the pc and it will work normally without any issues

**Comment by DeviLs1-TA** [comment]
Exact same issue here

**Comment by Nonbr** [comment]
Almost immediate bluescreen crash after entering my wallet id on windows 11

**Comment by charnet3d** [comment]
If this happens to you and you want a workaround for the Full Hashrate you can try bypassing the quickminer GUI and running excavator directly. I describe the steps I used in my comment on reddit: https://www.reddit.com/r/NiceHash/comments/uk9w2n/nicehash_manages_to_unlock_lhr_cards_to_100/i7r5f0g/

**Comment by KingDerpDeDerp** [comment]
Same issue. Blue screen with "critical process died" immediately after entering wallet address. Windows 11. 9900k Asus 3080ti

**Comment by euphoric45** [comment]
Same issue.  If I go into the quickminer folder and try to run excavator by itself I get the same crash so it appears the issue is with excavator.  Same bluescreen as everyone else.  Stable version of quickminer runs with no issues.

**Comment by Nonbr** [comment]
> If this happens to you and you want a workaround for the Full Hashrate you can try bypassing the quickminer GUI and running excavator directly. I describe the steps I used in my comment on reddit: https://www.reddit.com/r/NiceHash/comments/uk9w2n/nicehash_manages_to_unlock_lhr_cards_to_100/i7r5f0g/

I was able to get it to "work" and it claims it is at 100% LHR unlock but I am only getting 52 MH/s which is only an 10 MH/s more than what I usually get which is 42 MH/s (at all times I have a 950Mhz memory OC).

**Comment by euphoric45** [comment]
I changed over from windows 11 to windows 10 and that seems to fix this issue for me.

**Comment by Dohtar1337** [comment]
A new release is coming with fixes. This bug report is obsolete.

Thank you for reaching out anyway!
