### ISSUE TITLE
[MSI 3060Ti LHR can not lock core frequence low frequence now] 

### ISSUE THREAD

**Issue by newbee008** [nicehash/NiceHashQuickMiner#825]
My 2X MSI 3060Ti LHR can only get 47/44 MH/s. I found the reason is that the core frequence is too low, only 600 MHz, I can't change the frequence with OC tune. I reset them, then it creaes. But when I set core freqency, it drops to 600 MHz again, and Afterbuner can't change it either. Anyone has a solution?
![Capture](https://user-images.githubusercontent.com/81838115/167278826-fdee228b-d1d7-47ee-a53a-36d85815b740.PNG)

**Comment by kumoilain** [comment]
try ’reset overclock‘？

**Comment by newbee008** [comment]
> 



> 

I tried. Core clock increases, but when I try to tune it again, it goes back to low frequecy again

**Comment by Dohtar1337** [comment]
This issue should be solved in the upcoming release. Please follow NHQM updates and see if the next release solves the issue for you.
