### ISSUE TITLE
Seems to have adverse reaction to certain software[BUG] 

### ISSUE THREAD

**Issue by kyle4nia** [nicehash/NiceHashQuickMiner#826]
**Describe the bug**
If I try to monitor gpu temp either through armory crate or speccy, they either crash or stop showing data

**To Reproduce**
1. open armory crate or speccy
2. wait until temp values are displayed
3. run nicehash quickminer 5.4
4. armory crate quits displaying temps and speccy crashes

**Expected behavior**
when running the latest stable quickminer, I was able to monitor temps in armory crate (didnt try speccy because there was no issue

**Screenshots**

**Version affected (please complete the following information):**
 - 5.4
 - RC

**NVIDIA driver version**
studio

**Hardware**
rtx 3060 directly on mobo

**Logs**
sorry, not possible at the moment

**Additional context**
![spec2](https://user-images.githubusercontent.com/99437545/167279345-464dce2d-f4aa-4e4b-b562-20f29b28f6b6.png)

**Comment by Dohtar1337** [comment]
A new release is coming with fixes. This bug report is obsolete. 

If the issue repeats, please reopen a new issue.

Thank you for reaching out anyway!
