### ISSUE TITLE
[BUG]Geforce Experience not working while QM is on, If you open experience or control panel and you have QM open it will force close the application not allowing you to use the overlay nor the app itself until you exit QM. Using the recent NVIDIA drivers on windows 10.

### ISSUE THREAD

**Issue by Chonkaachuu** [nicehash/NiceHashQuickMiner#827]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version affected (please complete the following information):**
 - Version number [e.g. 0.4.5.5]
 - RC or STABLE?

**NVIDIA driver version**
Which one do you use?

**Hardware**
Describe GPUs used and how are GPUs connected to the motherboard.
CPU?

**Logs**
Activate logging first, then record event - bug - then export logs into a .zip file and attach it when submitting this issue.

**Additional context**

**Comment by lokewaieu** [comment]
Yeah, looks like if you have the QM running, anything else that uses GPU resources will instantly crash (games, HWinfo, Geforce Experience etc)... But that's just my guess based on my own observations too

**Comment by FRPlastic** [comment]
Same problem here !

**Comment by SirDalavar** [comment]
This guys fix worked for my problems, i suspect it might work for you guys too,
https://www.reddit.com/r/NiceHash/comments/ukxoyh/fix_for_qmexcavator_054_rc_closing_hwmonitor_nvcp/

**Comment by FRPlastic** [comment]
> This guys fix worked for my problems, i suspect it might work for you guys too, https://www.reddit.com/r/NiceHash/comments/ukxoyh/fix_for_qmexcavator_054_rc_closing_hwmonitor_nvcp/

Thanks it works.

**Comment by Dohtar1337** [comment]
A new release is coming with fixes. This bug report is obsolete. 

If the issue repeats, please reopen a new issue.

Thank you for reaching out anyway!

**Comment by WhiteSpa** [comment]
How do I do it? Send me a link. Send me a file. How do you do it? Tell me.

ส่งจาก จดหมาย<https://go.microsoft.com/fwlink/?LinkId=550986> สำหรับ Windows

จาก: ***@***.***>
ส่งแล้ว: 18 พฤษภาคม 2565 15:47
ถึง: ***@***.***>
สําเนาถึง: ***@***.***>
ชื่อเรื่อง: Re: [nicehash/NiceHashQuickMiner] [BUG]Geforce Experience not working while QM is on, If you open experience or control panel and you have QM open it will force close the application not allowing you to use the overlay nor the app itself until you exit...


Closed #827<https://github.com/nicehash/NiceHashQuickMiner/issues/827>.
