### ISSUE TITLE
ADMIN CLOSING POSTS ABOUT SERVER ISSUES! SOMETHING IS WRONG HERE! LOOK OUT!

### ISSUE THREAD

**Issue by Disparatado** [nicehash/NiceHashQuickMiner#83]

**Comment by Disparatado** [comment]
not letting people read and learn about! constant drops!

**Comment by Disparatado** [comment]
you could also post a schedule of expedted mainteneace schedules and times, im leaving NH!

**Comment by NHareLiars** [comment]
No they did not DELETE, i removed myself from this page! YOU ARE A BUNCH OF LAIRS! GHOST HERE!
