### ISSUE TITLE
[BUG] Windows11 crashes after you put in the adres with nhqm rc

### ISSUE THREAD

**Issue by MrTechno84** [nicehash/NiceHashQuickMiner#831]
**Describe the bug**
Windows11 crashes after you put in the adres with nhqm rc
**To Reproduce**
1. Go to '...' install nhqm rc 
2. Click on '....' copy adres in
4. See error windows11 BSOD critical_process_died

**Expected behavior**

**Screenshots**

**Version affected (please complete the following information):**
 - Version number [e.g. 0.4.5.5]
 - RC or STABLE?
Latest RC for 100% unlock
**NVIDIA driver version**
Which one do you use? 
512.29
**Hardware**
Describe GPUs used and how are GPUs connected to the motherboard.
CPU?
Gigabyte 3060Ti LHR in the motherboard
**Logs**
Activate logging first, then record event - bug - then export logs into a .zip file and attach it when submitting this issue.

**Additional context**

**Comment by FRPlastic** [comment]
Same, Windows11 crashes after i put my minning address.

**Comment by charnet3d** [comment]
A workaround you can do to get the Full Hashrate is by running excavator directly. I describe the steps I used in my comment on reddit: https://www.reddit.com/r/NiceHash/comments/uk9w2n/nicehash_manages_to_unlock_lhr_cards_to_100/i7r5f0g/

**Comment by Dohtar1337** [comment]
Try uninstalling the NVIDIA experience and see if that helps.

**Comment by clarocha** [comment]
I'm having the same problem! Don't have NVIDIA experience installed...

**Comment by mutsukisnow** [comment]
I met the same issue before. Now it resolved.
I did this:
1, Uninstall quick miner.
2, download Nvidia Driver v.512.29 game ready.
3, turn off internet connection and using D.D.U to Clean Uninstall GUP driver.
4, Install Nvidia Driver v.512.29 game ready.
5, Install NiceHash Quick miner RC with uncheck all box.
6, Make sure have not any software or app running.

Then I put my mining address in and it is working now.

**Comment by Dohtar1337** [comment]
A new release is coming with fixes. This bug report is obsolete. 

If the issue repeats, please reopen a new issue.

Thank you for reaching out anyway!
