### ISSUE TITLE
[QUESTION]  RTX 3060 V2 GA104 FHR not support

### ISSUE THREAD

**Issue by BradChou** [nicehash/NiceHashQuickMiner#832]
QuickMiner V 0.5.4.0 RC
Nvidia Driver : 512.59

PC1:
RTX 3060 V1, GA106 -> FHR Working
RTX 3080 V2, GA102(lhr) -> FHR Woking

PC2:
RTX 3060 V2, GA106(lhr) -> FHR Working
RTX 3060 V2, GA104 -> FHR not working
RTX 3060 Ti V2, GA104(lhr) -> FHR Working

RTX 3060 V2 GA104 version not support?

**Comment by adagirjr** [comment]
Tentativa com diversos drivers NVDIA inclusive a ultima versão 512.29
Não funciona de jeito nenhum na minha Placa de vídeo NVIDIA RTX 3060 - Code Name GA106-302 Revisão A1 Board Manuf. Dell

**Comment by 3unnyXU** [comment]
I also got a RTX3060 w/ GA104. LHR unlock seems not working for all driver versions I tested.
The card can only get around 50% hash rate  on 0.5.4.0 RC, and 70% rate on 0.5.3.6

**Comment by vengadam2001** [comment]
> QuickMiner V 0.5.4.0 RC Nvidia Driver : 512.59
> 
> PC1: RTX 3060 V1, GA106 -> FHR Working RTX 3080 V2, GA102(lhr) -> FHR Woking
> 
> PC2: RTX 3060 V2, GA106(lhr) -> FHR Working RTX 3060 V2, GA104 -> FHR not working RTX 3060 Ti V2, GA104(lhr) -> FHR Working
> 
> RTX 3060 V2 GA104 version not support?

I too have the same issue, GA-104 (lhr) is not unlocking , struck in lhr lock.

**Comment by saulob** [comment]
Same here, RTX 3060 V2 GA104 no working LHR unlocking on 0.5.4.0 RC
My card: Gigabyte 3060 Eagle LHR 12GB (GV-N3060EAGLE-12GD REV 2.0)

**Comment by MineNdesign** [comment]
Same issue on Ga104. all other LHR cards are unlocked but the Ga104 3060 reverts to full LHR locked at 50% and 65% memory controller load.

**Comment by Dohtar1337** [comment]
A new release is coming with fixes. This bug report is obsolete. 

If the issue repeats, please reopen a new issue.

Thank you for reaching out anyway!

**Comment by WhiteSpa** [comment]
How do I do it? Send me a link. Send me a file. How do you do it? Tell me.

ส่งจาก จดหมาย<https://go.microsoft.com/fwlink/?LinkId=550986> สำหรับ Windows

________________________________
จาก: Dohtar1337 ***@***.***>
ส่ง: Wednesday, May 18, 2022 3:48:27 PM
ถึง: nicehash/NiceHashQuickMiner ***@***.***>
สำเนาถึง: Subscribed ***@***.***>
ชื่อเรื่อง: Re: [nicehash/NiceHashQuickMiner] [QUESTION] RTX 3060 V2 GA104 FHR not support (Issue #832)


Closed #832<https://github.com/nicehash/NiceHashQuickMiner/issues/832>.

**Comment by WhiteSpa** [comment]
How do I do it? Send me a link. Send me a file. How do you do it? Tell me.

ส่งจาก จดหมาย<https://go.microsoft.com/fwlink/?LinkId=550986> สำหรับ Windows

จาก: ***@***.***>
ส่งแล้ว: 18 พฤษภาคม 2565 15:48
ถึง: ***@***.***>
สําเนาถึง: ***@***.***>
ชื่อเรื่อง: Re: [nicehash/NiceHashQuickMiner] [QUESTION] RTX 3060 V2 GA104 FHR not support (Issue #832)


Closed #832<https://github.com/nicehash/NiceHashQuickMiner/issues/832>.

**Comment by MarcusUA** [comment]
> How do I do it? Send me a link. Send me a file. How do you do it? Tell me.

How do you do what? 
You can download RC version from here: https://github.com/nicehash/NiceHashQuickMiner/releases
