### ISSUE TITLE
[BUG] Blue Screen as soon as Excavator loads

### ISSUE THREAD

**Issue by Elosin12** [nicehash/NiceHashQuickMiner#834]
**Describe the bug**

3080 LHR - Most current Nvidia driver - Installed quick miner - Launch QM with admin and anti-virus off - Blue Screen of Death
Windows 10 3080 10gb from MSI
AMD processor 32gb Ram

**Comment by Jennifer1818** [comment]
I am having the same issue when I try to run version 4.5.0 RC.

**Comment by ackatack** [comment]
I am having the same issue. Rig specs:

- Windows 11
- Nvidia driver 472.12
- Dual display adapter, 3060 Ti and 3070
- AMD Ryzen 5 3600

[log.txt](https://github.com/nicehash/NiceHashQuickMiner/files/8648095/log.txt)

**Comment by Drofzz** [comment]
I have the same problem.

Stop Code: Critical Process Died

- Windows 11
- Zotac RTX 3060 AMP Twin Edge OC LHR (GA106-302 (LHR))
- Intel Core i5-8400
- ASRock Z370 Extreme4
- RAM
  - Corsair CMK16GX4M2A666C16
  - Corsair CMK16GX4M2A666C16
  - Corsair CMK16GX4M2A666C16
  - Corsair CMK16GX4M2A666C16

**Comment by Dohtar1337** [comment]
Try uninstalling NVIDIA experience and see if that helps.

**Comment by xinombr** [comment]
Unninstalling NVidia EXP didn't work for me
Downloaded latest driver (512.59) and did a clear install;
nothing worked
Windows 11
Ryzen 7 3700x
rtx 3070 FHR
rtx 3060 LHR
2x8 corsair DDR4
SAMSUNG NVME EVO PLUS ;
Now i'll trying to install nvidia driver studio instead of game ready driver... lets see

**Comment by xinombr** [comment]
> Unninstalling NVidia EXP didn't work for me Downloaded latest driver (512.59) and did a clear install; nothing worked Windows 11 Ryzen 7 3700x rtx 3070 FHR rtx 3060 LHR 2x8 corsair DDR4 SAMSUNG NVME EVO PLUS ; Now i'll trying to install nvidia driver studio instead of game ready driver... lets see

Also didn't work, 
i'm downgrading to 5.3.6 until this gets solved, i'm out of options

**Comment by Josephur** [comment]
Also having the same BSOD here.  Analyzed dump file output:

`
Microsoft (R) Windows Debugger Version 10.0.22000.194 X86
Copyright (c) Microsoft Corporation. All rights reserved.


Loading Dump File [C:\Temp\MEMORY.DMP]
Kernel Bitmap Dump File: Kernel address space is available, User address space may not be available.

Dump completed successfully, progress percentage: 100

Symbol search path is: srv*
Executable search path is: 
Windows 10 Kernel Version 22000 MP (24 procs) Free x64
Product: WinNt, suite: TerminalServer SingleUserTS
Edition build lab: 22000.1.amd64fre.co_release.210604-1628
Machine Name:
Kernel base = 0xfffff806`49c00000 PsLoadedModuleList = 0xfffff806`4a829c70
Debug session time: Mon May  9 15:55:29.368 2022 (UTC - 4:00)
System Uptime: 0 days 0:07:39.022
Loading Kernel Symbols
...............................................................
................................................................
................................................................
................................................................
..................
Loading User Symbols
..........................
Loading unloaded module list
..........................
For analysis of this file, run !analyze -v
11: kd> !analyze -v
*******************************************************************************
*                                                                             *
*                        Bugcheck Analysis                                    *
*                                                                             *
*******************************************************************************

CRITICAL_PROCESS_DIED (ef)
        A critical system process died
Arguments:
Arg1: ffffb98959924080, Process object or thread object
Arg2: 0000000000000000, If this is 0, a process died. If this is 1, a thread died.
Arg3: 0000000000000000
Arg4: 0000000000000000

Debugging Details:
------------------


KEY_VALUES_STRING: 1

    Key  : Analysis.CPU.mSec
    Value: 9015

    Key  : Analysis.DebugAnalysisManager
    Value: Create

    Key  : Analysis.Elapsed.mSec
    Value: 30071

    Key  : Analysis.Init.CPU.mSec
    Value: 3484

    Key  : Analysis.Init.Elapsed.mSec
    Value: 137332

    Key  : Analysis.Memory.CommitPeak.Mb
    Value: 98

    Key  : CriticalProcessDied.ExceptionCode
    Value: 5cd6e080

    Key  : CriticalProcessDied.Process
    Value: _excavator.exe

    Key  : WER.OS.Branch
    Value: co_release

    Key  : WER.OS.Timestamp
    Value: 2021-06-04T16:28:00Z

    Key  : WER.OS.Version
    Value: 10.0.22000.1


DUMP_FILE_ATTRIBUTES: 0x1800

BUGCHECK_CODE:  ef

BUGCHECK_P1: ffffb98959924080

BUGCHECK_P2: 0

BUGCHECK_P3: 0

BUGCHECK_P4: 0

PROCESS_NAME:  _excavator.exe

CRITICAL_PROCESS:  _excavator.exe

ERROR_CODE: (NTSTATUS) 0x5cd6e080 - <Unable to get error code text>

STACK_TEXT:  
fffff08d`b6022918 fffff806`4a5aeef3     : 00000000`000000ef ffffb989`59924080 00000000`00000000 00000000`00000000 : nt!KeBugCheckEx
fffff08d`b6022920 fffff806`4a48f7bb     : ffffb989`59924080 fffff806`49ec67cd 00000000`00000002 fffff806`49ec66bb : nt!PspCatchCriticalBreak+0x11b
fffff08d`b60229b0 fffff806`4a3290e4     : ffffb989`59924080 00000000`c0000005 ffffb989`59924080 00000000`00000001 : nt!PspTerminateAllThreads+0x1b5fff
fffff08d`b6022a20 fffff806`4a328ec0     : ffffffff`ffffffff ffffb989`59924080 ffffb989`5cd6e080 00000000`00000001 : nt!PspTerminateProcess+0xe0
fffff08d`b6022a60 fffff806`4a028f78     : 00000000`00003a40 ffffb989`5cd6e080 ffffb989`59924080 ffffb989`00000000 : nt!NtTerminateProcess+0xb0
fffff08d`b6022ae0 00007fff`a09c3cd4     : 00007fff`a0924886 00000000`00000000 00000000`00000000 00000000`00000000 : nt!KiSystemServiceCopyEnd+0x28
0000000a`3735fed8 00007fff`a0924886     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : ntdll!NtTerminateProcess+0x14
0000000a`3735fee0 00000000`00000000     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : ntdll!RtlUserThreadStart+0x56


SYMBOL_NAME:  ntdll!NtTerminateProcess+14

MODULE_NAME: ntdll

IMAGE_NAME:  ntdll.dll

IMAGE_VERSION:  10.0.22000.527

STACK_COMMAND:  .thread ; .cxr ; kb

BUCKET_ID_FUNC_OFFSET:  14

FAILURE_BUCKET_ID:  0xEF__excavator.exe_BUGCHECK_CRITICAL_PROCESS_5cd6e080_ntdll!NtTerminateProcess

OS_VERSION:  10.0.22000.1

BUILDLAB_STR:  co_release

OSPLATFORM_TYPE:  x64

OSNAME:  Windows 10

FAILURE_ID_HASH:  {8d196be5-b7be-c523-3bfa-f8242de2886a}

Followup:     MachineOwner
---------
`

**Comment by rlandolt** [comment]
This might sound like the most stupid proposal, but it worked for me with the same issue:
Open the properties of the NiceHashQuickminer.exe (should be located in C:\NiceHash\NiceHash QuickMiner)
Then go to the Compatibility Tab and disable the full screen optimisations.

Save with OK and then restart the QuickMiner.... My RTX 3070 Noctua is now up from around 40 MH/s to 61 MH/s

**Comment by ackatack** [comment]
The steps that @mutsukisnow shared did not work for me. However, the steps that @rlandolt shared did work. I am seeing an increase from about 40MH/s to 60MH/s on a 3070 and a 3060 Ti.

**Comment by galaxy1999** [comment]
> This might sound like the most stupid proposal, but it worked for me with the same issue: Open the properties of the NiceHashQuickminer.exe (should be located in C:\NiceHash\NiceHash QuickMiner) Then go to the Compatibility Tab and disable the full screen optimisations.
> 
> Save with OK and then restart the QuickMiner.... My RTX 3070 Noctua is now up from around 40 MH/s to 61 MH/s

it works Good job

**Comment by wildcard5** [comment]
Worked for me too. Thanks

> This might sound like the most stupid proposal, but it worked for me with the same issue: Open the properties of the NiceHashQuickminer.exe (should be located in C:\NiceHash\NiceHash QuickMiner) Then go to the Compatibility Tab and disable the full screen optimisations.
> 
> Save with OK and then restart the QuickMiner.... My RTX 3070 Noctua is now up from around 40 MH/s to 61 MH/s

**Comment by wks2307** [comment]
> This might sound like the most stupid proposal, but it worked for me with the same issue: Open the properties of the NiceHashQuickminer.exe (should be located in C:\NiceHash\NiceHash QuickMiner) Then go to the Compatibility Tab and disable the full screen optimisations.
> 
> Save with OK and then restart the QuickMiner.... My RTX 3070 Noctua is now up from around 40 MH/s to 61 MH/s

works for me 3060ti win11

**Comment by Dohtar1337** [comment]
A new release is coming with fixes. This bug report is obsolete. 

If the issue repeats, please reopen a new issue.

Thank you for reaching out anyway!
