### ISSUE TITLE
error  105

### ISSUE THREAD

**Issue by Dulcidi** [nicehash/NiceHashQuickMiner#835]
Hello, with the new 0.5.4.0 RC, I get an error 105, and Excavator starts and stop all the time.
AV disabled.
it works correctly with 0.5.3.6 or when I disable my 3080 ( the other cards are 5x 10XX )
does anyone know why it do that ?
thanks

**Comment by neubauet** [comment]
Same issue with my gigabyte 3080ti. It immediately crashes with error 105.

**Comment by DonutK1ng** [comment]
Same issue for my MSI Gaming Z Trio 3080 - Excavator constantly closing and reopening.

**Comment by clarocha** [comment]
I had the same issue in my rig!

**Comment by Sohron** [comment]
Même problème pour moi et j'ai peut etre trouvé la solution je fais encore des test mais essayer de désactiver le controle des applications et du navigateur pour moi maintenant cela focntionne. mais sur un autre RIG impossible meme avec les memes valeurs ! avez vous trouvez ?
