### ISSUE TITLE
Prerelease v0.5.4.0 RC [BUG] unable to use with NicehasMiner v3.0.8.1

### ISSUE THREAD

**Issue by Alevale** [nicehash/NiceHashQuickMiner#839]
**Describe the bug**
After installing both programs because I have AMD and NVIDIA in the same device the programs start being unstable

**To Reproduce**
1. Install Quickminer v0.5.4.0 RC
2. Install NicehasMiner v3.0.8.1 (last stable version)
3. Start one (Quickminer)
4. Start one (NicehasMiner)
5. Either Quickminer or Nicehashminer will start closing themselves

**Expected behavior**
Both programs should be able to coexist

**Version affected (please complete the following information):**
 - v0.5.4.0
 - RC

**NVIDIA driver version**
497.29

**Hardware**
Describe GPUs used and how are GPUs connected to the motherboard.
CPU 4770K
GPU 1080 Ti
GPU 3070 Ti
GPU 6700X

**Logs**
-

**Additional context**
-

**Comment by Dohtar1337** [comment]
A new release is coming with fixes. This bug report is obsolete.

If the issue repeats, please reopen a new issue.

Thank you for reaching out anyway!
