### ISSUE TITLE
Setting temp and fan speed

### ISSUE THREAD

**Issue by ben1628** [nicehash/NiceHashQuickMiner#84]
How do we do that, previously one can set the fan speed like this

				"method": "device.set.oc_profile2",
				"params": ["0", "1515", "8100", "65", "62"]

which set fan speed to 65%, but power is not set to 62%.

I like the fan to run at a constant speed, instead of on and off, from what I understand, running the fan at 24/7 won't hurt if it is less than say 85%

**Comment by nicehashdev** [comment]
Fan management was split from OC profiles and is now separate. I haven't had time to update API specs for Excavator, but you can observe how commands.json file gets changed when you apply certain fan profile and save configuration. It is easy to figure it out.
