### ISSUE TITLE
[BUG] v0.5.4.0 RC LHR+nonLHR mixed rig, lhr card not fully unlocked 

### ISSUE THREAD

**Issue by MarcusUA** [nicehash/NiceHashQuickMiner#840]
I have two rigs, one with just 3070ti LHR - now it does 80MH/s at 190W
Second rig is 3070ti LHR and 3070 non-LHR. 3979ti only does 44MH/s at 130W with same overclock settings as in first rig. 3070 does 62MH/s (same as on older QuickMiner).
Wattage and temperature for 3070ti in second rig is now much less now, so unlock does have some effect.  

System: 
both rigs have same build of Win10 installed
QM v0.5.4.0 RC

**NVIDIA driver version**
v487.29   - both rigs

**Hardware**
first rig is intel (actually its a vm with gpu pass-though, works as expected without any issues)
second rig is AMD 2700X on MSI B450M Mortar 

**Additional context**
I've tried to move as much settings from rig1 to rig2: nhqm.conf, commands.json and LHRsettings.conf - partially, changing gpu guids, no change.
I'm going to try newer driver on second rig and will report if there are any changes to behavior.
Both rigs were auto-upgraded from v0.5.3.4. I tried unpacking and running RC zip from github, but it would not let me apply neither OC nor FAN settings in OCTune.

**Comment by JoonasMykkanen** [comment]
Hello, I have this problem also. If my rig only has 3080 Ti, I get 120mh/s and full unlock. If I plug in my non LHR 3080 too, the unlock says to be still 100 but 3080 Ti hashrate drops to ~60mh/s.

Any ideas?

**Comment by JScCrypt** [comment]
Hi,

I have same problem.. RTX 3070Ti + 3070 nonLHR = NO unlock LHR card

**Comment by e17vi** [comment]
Same problem with LHR 3080 TI and LHR 3080 12GB OC

**Comment by MarcusUA** [comment]
> Any ideas?
Try with just 1 LHR card in the rig. 
If that works than until this issue gets a workaround, we have to stick to separate rig for each LHR GPU. For example setting up separate VMs with GPU passthrough, so each GPU gets its own virtual rig.
Maybe using new unlocked miners on linux don't have this issue (you can still use them to mine to NiceHash, just no fancy data and rig control from web)

**Comment by gambastyle** [comment]
I'm having the exact same problem

**Comment by bissy47** [comment]
I have the same problem with LHR RTX3080 and non-LHR RTX3070.
(NBMiner has been lifted by the above combination.)
In addition, the restrictions have been lifted on the LHR RTX3080 and GTX1660Ti.

**Comment by MarcusUA** [comment]
v0.5.4.1 resolved the issue for me. Good luck everyone!
