### ISSUE TITLE
[BUG]  gigabyte 3080 10g ver.2 can only works with 55% LHR unlock

### ISSUE THREAD

**Issue by mutsukisnow** [nicehash/NiceHashQuickMiner#843]
**Describe the bug**

I have 2 gigabyte 3080 10g ver.2 cards and they can only works with 55% LHR unlocked.

**Version **
 - QuickMiner v0.5.4.0 RC

**NVIDIA driver version**
512.15 game ready.

**Hardware**
My rig is consist of 6 cards: 2 3060TI + 1 3090 + 1 3070 Ti + 2 3080 10g LHR.

**Comment by MarcusUA** [comment]
hey,
can you try your rig with only one gigabyte 3080 10g card?
I have this issue, too with rig that has 2 cards, and another other has just one and unlock works.
My rigs are remote, so I can't check it myself.

**Comment by Leowinterhill** [comment]
> hey, can you try your rig with only one gigabyte 3080 10g card? I have this issue, too with rig that has 2 cards, and another other has just one and unlock works. My rigs are remote, so I can't check it myself.

Actually, it's a good point, even though it looks strange. My LHR card inside a 6 GPU rig cannot work 100% unlock, but my LHR card inside a 3 GPU rig is fine. Although they are not the same cards, it makes me think the same thing as your ones.

**Comment by richardzed** [comment]
I have a Gigabyte RTX 3080 Vision 10 GB that is locked  like yours had to go back to release version.
Did you resolve this at all.?

**Comment by Chronos54** [comment]
Just to add to the conversation, I see the same with my Gigabyte 3080 I just tried RC 5.4.1 and It seems ever worst with dips down to the single digits. I have a MSI 3080 that's advertised as LHR it opened up immediately 89-100MH\s with the Gigabyte I maybe hit 56

**Comment by richardzed** [comment]
I also tried RC 5.4.1 and down to single digits as well with a message "unable to unlock this card , restart to try again" so again back to the stable version.
Gigabyte RTX 3080 Vision 10 GB

**Comment by barnowan** [comment]
I'm also seeing about 50 MH/s on 4 different Gigabyte 3080 10GB cards using both RC 5.4.0 and 5.4.1.

**Comment by Dohtar1337** [comment]
A new release is coming with fixes. This bug report is obsolete.

If the issue repeats, please reopen a new issue.

Thank you for reaching out anyway!
