### ISSUE TITLE
[BUG] Process using OpenCL killed by excavator.exe

### ISSUE THREAD

**Issue by ptaahfr** [nicehash/NiceHashQuickMiner#844]
Hello,

I'm using a machine with a 3080 LHR to also develop OpenCL software. I use QuickMiner 0.5.4 RC (very good job by the way)

The problem was that when I ran my software it was killed after a command queue execution.

It's hard to reproduce because it's software i cannot expose here, using the Windows GFLAGS to troubleshoot, I discovered that the process was killed by excavator.exe, even when the mining is stopped.

I don't know what menachism is beging that but it would be great to have a whitelist of processes to never kill.

Best Regards

**Comment by Dohtar1337** [comment]
A new release is coming with fixes. This bug report is obsolete.

If the issue repeats, please reopen a new issue.

Thank you for reaching out anyway!

**Comment by WhiteSpa** [comment]
Cock your father is dead. Komku 3060

ส่งจาก จดหมาย<https://go.microsoft.com/fwlink/?LinkId=550986> สำหรับ Windows

จาก: ***@***.***>
ส่งแล้ว: 18 พฤษภาคม 2565 15:53
ถึง: ***@***.***>
สําเนาถึง: ***@***.***>
ชื่อเรื่อง: Re: [nicehash/NiceHashQuickMiner] [BUG] Process using OpenCL killed by excavator.exe (Issue #844)


Closed #844<https://github.com/nicehash/NiceHashQuickMiner/issues/844>.

**Comment by ptaahfr** [comment]
> A new release is coming with fixes. This bug report is obsolete.
> 
> If the issue repeats, please reopen a new issue.
> 
> Thank you for reaching out anyway!

Thanks a lot !
Will it be 0.5.4.2 ? or is it supposed to be fixed in 0.5.4.1 ?
