### ISSUE TITLE
[BUG] RC 0.5.4.0 excavator stops and restarts continually

### ISSUE THREAD

**Issue by dandanciu** [nicehash/NiceHashQuickMiner#845]
NiceHash QuickMiner Excavator continually stops and restarts .

**To Reproduce**
1. Install QuickMiner latest RC 0.5.4.0 and run it with defaults

**Expected behavior**
QuickMiner excavator should not stop/crash

**Screenshots**

**Version affected (please complete the following information):**
 - Version number 0.5.4.0
 - RC

**NVIDIA driver version**
471.11 and 472.12 GameReady have same problem

**Hardware**
Motherboard Mining BTC-S37 8 GPU
GPU Nvidia Geforce RTX 3060TI 
CPU Intel(R) Celeron(R) CPU 847 @ 1.10GHz   1.10 GHz

**Logs**
[exported_logs.zip](https://github.com/nicehash/NiceHashQuickMiner/files/8664743/exported_logs.zip)

**Additional context**
Same config works fine with QuickMiner STABLE v0.5.3.6 @40Mh
The same GPU works fine with another PC with QuickMiner 0.5.4.0 Nvidia 472.12, fully unlocked @60Mh

Thanks

**Comment by h33fn** [comment]
same issue after todays rc update

**Comment by artemisgneuro** [comment]
Updated to the latest NVIDIA driver (version 512.59), the problem has been fixed :)

**Comment by kumarhiranya** [comment]
Driver update didn't help me. But closing Nvidia Broadcast worked!

**Comment by barnowan** [comment]
> Updated to the latest NVIDIA driver (version 512.59), the problem has been fixed :)

This worked for me as well.  DDU first to remove old drivers, installed newest drivers, and problem was fixed.

**Comment by Dohtar1337** [comment]
A new release is coming with fixes. This bug report is obsolete.

If the issue repeats, please reopen a new issue.

Thank you for reaching out anyway!

**Comment by jmerc77** [comment]
i get this before installing available win10 updates
