### ISSUE TITLE
how to exclude amd cards in nicehash quickminer[QUESTION] 

### ISSUE THREAD

**Issue by vlezo1** [nicehash/NiceHashQuickMiner#846]
**Has the question been answered in [Wiki](https://github.com/nicehash/NiceHashQuickMiner/wiki)? There is no such question in [FAQ](https://github.com/nicehash/NiceHashQuickMiner/wiki/FAQ) or [Troubleshooting collection](https://github.com/nicehash/NiceHashQuickMiner/wiki/Troubleshooting)?**
Yes/No.

**Your question is...**
What is...

**Comment by Dohtar1337** [comment]
This is not possible. You can disable them though
