### ISSUE TITLE
[BUG] RC 0.5.4.0 excavator memory Leak?

### ISSUE THREAD

**Issue by Ekster-powerplay** [nicehash/NiceHashQuickMiner#847]
**Describe the bug**
Windows  hangs after a couple of hours of mining with RC 0.5.4.0 excavator, a reboot is necessary to continue. (win 10 full lockup)

**To Reproduce**
Latest win 10 updates, latest Nvidia driver, RC 0.5.4.0 excavator. Let it run for a day or so

**Behavior**
The page file keeps growing until it reaches 29 Gb, then win crashes. 

Winlog:
2004: Resource-Exhaustion-Detector
A virtual memory problem was found during the check. The following programs consumed the most virtual memory: excavator.exe (132) consumed 32260808704 bytes, esrv_svc.exe (6740) consumed 1044869120 bytes, and MsMpEng.exe (5128) consumed 258588672 bytes.

**Version affected (please complete the following information):**
RC 0.5.4.0

**NVIDIA driver version**
472.12

**Hardware**
1x Zotac 3060 V1
3x Asus 3060 V2
1x msi 1060
1x Vega 56

**Additional context**
I have manually set the page file to 150GB, And I will report if it grows beyond that.

Update: 

pagefile set to 64gb-84gb after a few hours of mining the system becomes unresponsive, same error.

**Comment by Dohtar1337** [comment]
This is a known issue. Normally if OCTune is running for longer period of times, the memory leak is higher.

Also, DCH drivers are known to make the issue more noticeable. Try using standard drivers.

**Comment by i1itione** [comment]
> This is a known issue. Normally if OCTune is running for longer period of times, the memory leak is higher.
> 
> Also, DCH drivers are known to make the issue more noticeable. Try using standard drivers.

Is there a standard drivers for LHR 100% unlock? I can't find standard version driver of 512.77.

**Comment by Dohtar1337** [comment]
No, unfortunately, NVIDIA only releases DCH drivers since 511.xx
