### ISSUE TITLE
[BUG] 0.5.4.1 RC Keeps restarting Excavator on my LHR rig.

### ISSUE THREAD

**Issue by MakeL0VENotW4R** [nicehash/NiceHashQuickMiner#848]
Had to manually install 0.5.4 RC to avoid this problem. Had full logs but was logging no error.

**Comment by InquisitorM** [comment]
Having the same issue on a single 3080ti. Did you have a copy of 0.5.4 already? I can't locate an archive function.

**Comment by barnowan** [comment]
DDU and install latest drivers.  Worked for me.

**Comment by delirious18** [comment]
+1

new update makes excavator open and close on endless loop, and this is before I set it to start mining.

uninstalled 0.5.4.1 and reinstalled - no change.
472.12 was already installed. DDU and reinstall - no change.
running excavator as it is in the QM folder just restarts the computer. (why?)

looking forward to full lhr unlock stable release :)

first time poster, thanks to the great work done by the nicehash team :)

**Comment by Leowinterhill** [comment]
> +1
> 
> new update makes excavator open and close on endless loop, and this is before I set it to start mining.
> 
> uninstalled 0.5.4.1 and reinstalled - no change. 472.12 was already installed. DDU and reinstall - no change. running excavator as it is in the QM folder just restarts the computer. (why?)
> 
> looking forward to full lhr unlock stable release :)
> 
> first time poster, thanks to the great work done by the nicehash team :)

Hi. Here's the solution.
1. Install the latest driver, I mean the latest, I installed the 512.77 driver, I didn't DDU and I don't think you need to either unless it still does not work for you. 
2. Open 0.5.4.1 RC, no matter you installed the NHQM before upgrading the driver or after.
3. Problem solved. Work for my four different PC with all 472.XX driver.

**Comment by MakeL0VENotW4R** [comment]
> 3\. e

Did not work for me.

**Comment by MakeL0VENotW4R** [comment]
> > +1
> > new update makes excavator open and close on endless loop, and this is before I set it to start mining.
> > uninstalled 0.5.4.1 and reinstalled - no change. 472.12 was already installed. DDU and reinstall - no change. running excavator as it is in the QM folder just restarts the computer. (why?)
> > looking forward to full lhr unlock stable release :)
> > first time poster, thanks to the great work done by the nicehash team :)
> 
> Hi. Here's the solution.
> 
> 1. Install the latest driver, I mean the latest, I installed the 512.77 driver, I didn't DDU and I don't think you need to either unless it still does not work for you.
> 2. Open 0.5.4.1 RC, no matter you installed the NHQM before upgrading the driver or after.
> 3. Problem solved. Work for my four different PC with all 472.XX driver.


Did not work for me.

**Comment by delirious18** [comment]
> > +1
> > new update makes excavator open and close on endless loop, and this is before I set it to start mining.
> > uninstalled 0.5.4.1 and reinstalled - no change. 472.12 was already installed. DDU and reinstall - no change. running excavator as it is in the QM folder just restarts the computer. (why?)
> > looking forward to full lhr unlock stable release :)
> > first time poster, thanks to the great work done by the nicehash team :)
> 
> Hi. Here's the solution.
> 
> 1. Install the latest driver, I mean the latest, I installed the 512.77 driver, I didn't DDU and I don't think you need to either unless it still does not work for you.
> 2. Open 0.5.4.1 RC, no matter you installed the NHQM before upgrading the driver or after.
> 3. Problem solved. Work for my four different PC with all 472.XX driver.

RE: 512.77 - Those are DCH drivers. Somehow, are they the correct drivers to install now? DCH drivers aren't meant to be good for mining, and Nicehash Miner will let you know about it. Is it somehow different for Quick Miner?

I resolved the problem by reinstalling 0.5.4.0 in the meantime

**Comment by InquisitorM** [comment]
Updating the driver did fix the restarting issue, but 0.5.4.1 is still unstable for me. OCTuner won't accept changes to manual OCs. Something just isn't right.

I have rolled back to 0.5.4.0 again and everything works just fine.

**Comment by hmoraes** [comment]
I'm also having the same problem in version 0.5.4.1. I have seen in version 0.5.4.0 the "fail" message all the time.

The error in the new version may be related to the message displayed in version 0.5.4.0, just guessing.

FYI:
- Driver NVIDIA 472.84
- RTX 3060 TI (LHR)
- GTX 1080 TI
Ps.: All in the same machine
