### ISSUE TITLE
[BUG] RC causing instability in Wi-Fi

### ISSUE THREAD

**Issue by Staminblack** [nicehash/NiceHashQuickMiner#849]
**Describe the bug**
Downloaded the QM RC today and whenever NiceHash was running, my Internet was constantly going in and out. Excavator kept disconnecting and re-connecting.

WiFi connection on an Alienware m15r5 3070, Windows 11.

**Comment by Dohtar1337** [comment]
Thanks for reaching out! 

Can you contact us on Discord? https://discord.com/invite/nicehash

You can contact Marko_NiceHash or Djm34 and tell them that about this ticket.

**Comment by Fisheiyy** [comment]
sounds like a hardware problem not a software issue
