### ISSUE TITLE
[BUG] blue screen on win 11

### ISSUE THREAD

**Issue by Masz999** [nicehash/NiceHashQuickMiner#851]
In version higher than 5.4.0, when the program starts, the system gives a **blue screen** with the message process central.

**Comment by artemisgneuro** [comment]
> In version higher than 5.4.0, when the program starts, the system gives a **blue screen** with the message process central.

#817

**Comment by Dohtar1337** [comment]
A new release is coming with fixes. This bug report is obsolete.

Thank you for reaching out anyway!

**Comment by WhiteSpa** [comment]
Ded u der

ส่งจาก จดหมาย<https://go.microsoft.com/fwlink/?LinkId=550986> สำหรับ Windows

จาก: ***@***.***>
ส่งแล้ว: 18 พฤษภาคม 2565 15:41
ถึง: ***@***.***>
สําเนาถึง: ***@***.***>
ชื่อเรื่อง: Re: [nicehash/NiceHashQuickMiner] [BUG] blue screen on win 11 (Issue #851)


A new release is coming with fixes. This bug report is obsolete.

Thank you for reaching out anyway!
