### ISSUE TITLE
[BUG ]blue screen when windows 10 shuts down (v0.5.4.0 and v0.5.4.1 RC )

### ISSUE THREAD

**Issue by PteroMaplePT** [nicehash/NiceHashQuickMiner#852]
windows 10 blue screen when I want to shut down.

**Comment by artemisgneuro** [comment]
Same issue on Windows 11.

**Comment by SimplycityOne** [comment]
Experienced BSOD also when Win starts and NHQM is set to start (and mine) automaticaly with Win. It is not happening all the time, but often when I login to system just after welcom screan appeared, b4 all services started.
Always get BSOD while closing down Win (11) with working NHQM; if I close NHQM manually b4 shutting down the system, no BSOD.

**Comment by Dohtar1337** [comment]
A new release is coming with fixes. This bug report is obsolete.

Thank you for reaching out anyway!
