### ISSUE TITLE
[BUG] Excavator 1.7.7.1 stop working

### ISSUE THREAD

**Issue by gandadil** [nicehash/NiceHashQuickMiner#853]
**Describe the bug**
Excavator suddenly stop working after update drivers to 512.77 and v1.7.7.1

I've tried restart on rig manager but not happens. Rig manager report the rig as stopped status.

![image](https://user-images.githubusercontent.com/48427120/168142706-2417b664-77de-4e23-a15f-5afb25ddb232.png)

I tried back to old nvidia and excavator versions but i have the same behavior.

Maybe the presence of MSI Afterburner installed is the problem?

Windows 11
RTX 3060
Nvidia Driver 512.77 (old was 512.59)
Excavator 1.7.7.1 (but back to 1.7.7.0 has the same problem)

**Comment by gandadil** [comment]
I just uninstall afterburnner but the problem persist.

**Comment by WhiteSpa** [comment]
เอาไปแปลไทยในGoogle แล้วส่งมาให้กุ

ส่งจาก จดหมาย<https://go.microsoft.com/fwlink/?LinkId=550986> สำหรับ Windows

จาก: ***@***.***>
ส่งแล้ว: 18 พฤษภาคม 2565 15:38
ถึง: ***@***.***>
สําเนาถึง: ***@***.***>
ชื่อเรื่อง: Re: [nicehash/NiceHashQuickMiner] [BUG] Excavator 1.7.7.1 stop working (Issue #853)


A new release is coming with fixes. This bug report is obsolete. Please reply to this ticket if the issue persists after the next release (0.5.4.2.)
