### ISSUE TITLE
[BUG] v0.5.4.1 RC Gigabyte 3080 10G only 54 mh, driver 512.59

### ISSUE THREAD

**Issue by earner2021** [nicehash/NiceHashQuickMiner#854]
v0.5.4.1 RC Gigabyte 3080 Gaming, Eagle, Turbo 10G only 54 mh, driver 512.59

**Comment by FerrumIrrumabo** [comment]
I have Gigabyte 3060 12 Gb and im around 21MH/s and it must be 49-50MH/s

**Comment by MineNdesign** [comment]
I put in a bug issue for this and it seems to be specific to gigabyte. For the 3060 it looks like its the GA104 for some reason.

**Comment by FerrumIrrumabo** [comment]
Do you think this problem can solved at the 0.5.4.x stable version or this problem can solved?

**Comment by MineNdesign** [comment]
> Do you think this problem can solved at the 0.5.4.x stable version or this problem can solved?

On the stable version of Nicehash Miner you can do a 74% unlock but when I try to use the rc NHQM and the standard miner, it Blue screens my computer

**Comment by earner2021** [comment]
With others miners (nb, t-rex) i have stable 97 mh on this card

**Comment by WhiteSpa** [comment]
Kuy ส่งห้้ไร ถาษไทยทีดิ !@!!!!!
ส่งจาก จดหมาย<https://go.microsoft.com/fwlink/?LinkId=550986> สำหรับ Windows

จาก: ***@***.***>
ส่งแล้ว: 18 พฤษภาคม 2565 15:35
ถึง: ***@***.***>
สําเนาถึง: ***@***.***>
ชื่อเรื่อง: Re: [nicehash/NiceHashQuickMiner] [BUG] v0.5.4.1 RC Gigabyte 3080 10G only 54 mh, driver 512.59 (Issue #854)


Closed #854<https://github.com/nicehash/NiceHashQuickMiner/issues/854>.
