### ISSUE TITLE
[BUG] 0.5.4.1 RC Always  minor  HW error no overclock card

### ISSUE THREAD

**Issue by blin25** [nicehash/NiceHashQuickMiner#856]
No overclocking minor hw  ..errors
![2022-05-12_22-44-56](https://user-images.githubusercontent.com/96530650/168171557-3eeb5762-d47a-4f45-bb49-701249bb1c7c.png)
c

**Comment by Dohtar1337** [comment]
Duplicate of https://github.com/nicehash/NiceHashQuickMiner/issues/861
