### ISSUE TITLE
 [BUG] Quickminer RC v0.5.4.1 whatever core limit and power is applied speed stays around 37 MH/s irrespective of memory overclocks in RTX 3070. This issue comes after the new update previously it was mining fully unlocked at 60MH/s. 

### ISSUE THREAD

**Issue by PriyadarshaanAshok** [nicehash/NiceHashQuickMiner#857]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
![New Bitmap image1](https://user-images.githubusercontent.com/105504151/168311876-917cf457-898b-4073-a3b3-4c8e4377d067.jpg)

**Version affected (please complete the following information):**
 - Version number [RC v0.5.4.1]
 - RC or STABLE?

**NVIDIA driver version**
Which one do you use?

**Hardware**
Describe GPUs used and how are GPUs connected to the motherboard.
CPU?

**Logs**
Activate logging first, then record event - bug - then export logs into a .zip file and attach it when submitting this issue.

**Additional context**

**Comment by Dohtar1337** [comment]
A new release is coming with fixes. This bug report is obsolete. 

Thank you for reaching out anyway!
