### ISSUE TITLE
[BUG] GA104 LHR cards are not unlocked. showing 65% Memory Controller Load

### ISSUE THREAD

**Issue by MineNdesign** [nicehash/NiceHashQuickMiner#858]
Using NHQM_v0.5.4.1_RC, the LHR unlock will not unlock the GA104 3060. The card reverts to full LHR lock with 65% memory controller load. 

Specifically seen on 3060 Gigabyte GA104 Revision A1 regardless of drivers.

**Comment by chiekku** [comment]
Experiencing the same issue; same Gigabyte cards, but mine are LHR v2s. Something about the GA104, because my GA106s fully unlock no problem.

**Comment by saulob** [comment]
Same here. Gigabyte too
Gigabyte 3060 Eagle LHR 12GB (GV-N3060EAGLE-12GD REV 2.0)

**Comment by Dohtar1337** [comment]
This should not be related to GA104. 

We will soon release a new RC which should have a full support.
