### ISSUE TITLE
How to remove card from QuickMiner?

### ISSUE THREAD

**Issue by donkurami** [nicehash/NiceHashQuickMiner#859]
I have 3 card,which i use for mining-2x3060ti and 1x1650.I use 3060s for etherium,1650 for rvncoin.They work on 2 different miners(trex and nb).NOW i use QuickMiner for my 3060s and it is better than new version of Trex,NB or LolMiner,so i want to continue using only quickminer for my 3060.But my problem is when Quick Miner is On,i can't use other miners for 1650!I try what i know to remove that card from the nicehash software,but with now success.On my batch file for 1650 is only this card --devices 2(in my case).When i used batch files for 3060ti's,when i mine with other miner i use --devisec 0,1 and that way i can run 2 miners on different cards and coins.So how can i to run my 1650 separately from quickminer?
![Untitled](https://user-images.githubusercontent.com/102884824/168378699-2997f9c2-a6da-4e3b-94dc-f0e60092f5d0.png)

**Comment by MineNdesign** [comment]
I use the web portal or the app to disable

**Comment by donkurami** [comment]
![image](https://user-images.githubusercontent.com/102884824/168394774-b3313766-a26f-4987-aa1a-05145497af1e.png)
Doesn't even there(my 1650)How to remove it from nowhere?

**Comment by blin25** [comment]
I think changing this line in the configuration file will help you.
![2022-05-15_20-15-38](https://user-images.githubusercontent.com/96530650/168485548-be179fbc-b357-4b7a-9868-d146ae160a61.png)

**Comment by donkurami** [comment]
yeah...i try that in different types... just 2 or 2-2 or [2] or 0-2 or #2....and nothing just restarts the QuickMiner
