### ISSUE TITLE
Linux WINE support

### ISSUE THREAD

**Issue by petermetz** [nicehash/NiceHashQuickMiner#86]
Does the quickminer support being executed on Ubuntu through WINE?
https://www.winehq.org/

**Comment by uhliksk** [comment]
Are you able to test QuickMiner under Wine?

**Comment by uhliksk** [comment]
@petermetz Are you able to test QuickMiner under Wine?

**Comment by petermetz** [comment]
> @petermetz Are you able to test QuickMiner under Wine?

@uhliksk Not at the moment unfortunately (I'm in-between GPUs), but if you are okay with keeping the issue open that eventually I will come around to it for sure (and update with more info at that time)

**Comment by uhliksk** [comment]
> @uhliksk Not at the moment unfortunately, but if you are okay with keeping the issue open that eventually I will come around to it for sure (and update with more info at that time)

@petermetz Sorry, I'm just same curious user as you, not a dev. I found CUDA under Wine is working fine but I'm not sure if OC tune or fan control is possible. I don't have Linux box available for testing right now.

**Comment by petermetz** [comment]
> @petermetz Sorry, I'm just same curious user as you, not a dev. I found CUDA under Wine is working fine but I'm not sure if OC tune or fan control is possible. I don't have Linux box available for testing right now.

@uhliksk Oh, okay, no worries at all. In that case, I'll report back with my findings as soon as I get around to it. Stay tuned. :-)

**Comment by nicehashdev** [comment]
Any NVIDIA device management probably will not work, because it uses NVAPI which Linux drivers don't have at all. If it works under Wine, it is probably very broken. and not worth using. Why don't you use NiceHashOS?

**Comment by petermetz** [comment]
> Any NVIDIA device management probably will not work, because it uses NVAPI which Linux drivers don't have at all. If it works under Wine, it is probably very broken. and not worth using. Why don't you use NiceHashOS?

@nicehashdev Cheers, guess you just saved me some time being wasted on trying it out with Wine! I don't have dedicated mining rigs. What I do have is a machine running Ubuntu LTS and wanted to see if I could run NiceHash there as a side project for fun. Could give NiceHashOS a try through KVM, but I'm guessing the GPU passthrough will have the same issues there as with Wine so likely just another can of worms... :-)

**Comment by nicehashdev** [comment]
Passthrough is a problematic thing... NVIDIA is doing all what is possible to make it available only for enterprise elite high paying customers.
