### ISSUE TITLE
[BUG] nhqm.conf Cant change location to 3, from -1, wont overwirte or save new updated config

### ISSUE THREAD

**Issue by WattaBinG** [nicehash/NiceHashQuickMiner#860]
When I edit the nhqm.conf and put the location to 3, changed from auto which is -1, then, save, it doesn't save/update. i tried editing it many times, thru nicehash and also went into properties in file explorer and made sure it wasn't read only, it wasn't. I also try and edit nhqm.conf file directly in file explorer by right clicking, editing in notepad, removing the -1 and adding 3, and saving, (not as text file) i choose all files from dropdown, and scroll to and double clicking the nhqm.conf file and asks if i want to save/overwrite i say yes, re run nicehash, , still uses auto location and then i try and edit config again and it still holds the -1, the 3 wont save...  Tried many things, even copied an old nhqm.conf but that set it back to -1 as well.. I've tried running nicehash as administrator and choosing edit config, still doesn't hold the 3, 

Anyone else not able to change location?   Thanks for any help!!!!

I have a 2070 super and a ROG ASUS PC. Thanks if you can help me fix this..

**Comment by Dohtar1337** [comment]
You cannot change locations anymore.

QuickMiner connects to auto location which automatically selects the closes location. This cannot be changed.

**Comment by WattaBinG** [comment]
Thanks for the prompt response! I was not aware of that change, thanks for informing me of it,  but most importantly, it is great to know that it's not an issue for my installation! Thanks so much again, love this community!  

> You cannot change locations anymore.
> 
> QuickMiner connects to auto location which automatically selects the closes location. This cannot be changed.
