### ISSUE TITLE
[BUG] QM v0.5.4.0 RC and v0.5.4.1 RC high reject rate

### ISSUE THREAD

**Issue by Arvenies** [nicehash/NiceHashQuickMiner#861]
Starting from version v0.5.4.0 RC the reject rate is much higher than on previous v0.5.3.6 RC. Return to previous version v0.5.3.6 RC reject are back at low level. Screen as a proof. Exactly same config files nhqm.conf and commands.json on every version. PC with single RTX 3090 and i9-11900K, nVidia driver 472.12 STD.

![obraz](https://user-images.githubusercontent.com/80607526/168453000-2e5661ee-c906-4ebc-8c47-097b9e70b103.png)

**Comment by nieXas** [comment]
same here, I have 1-2% of rejects with memories lower than 0.5.3.6, where I get 0 rejects.

**Comment by RRRRK** [comment]
The same issue here. After a few minutes, it shows HTTP closed and then full closed.

**Comment by Dohtar1337** [comment]
This is a known "issue". It is due to the job switching. We are still investigating how we should approach this issue.

Note that these are not actual HW errors due to high memory OC. There is nothing you can do on your side. 

Closing this issue as we are aware of it.
