### ISSUE TITLE
[BUG] Hwinfo64 7.24 closing 

### ISSUE THREAD

**Issue by tac-git** [nicehash/NiceHashQuickMiner#867]
Describe the bug

To Reproduce

1)update＆startup 0.5.4.1 RC
2)Hwinfo64 7.24 atartup
3)Hwinfo64  auto closing
Expected behavior
QM action　app close

Screenshots
Cannot shoot

Version affected (please complete the following information):

Version number [0.5.4.1]RC
NVIDIA driver version 512.77
GALAX　3090 HOF　＆ 3060Ti

Hardware
Describe GPUs used and how are GPUs connected to the motherboard.
CPU?
PCIe slot

Logs
Activate logging first, then record event - bug - then export logs into a .zip file and attach it when submitting this issue.
I can't leave a log

Additional context

**Comment by hwatt2** [comment]
For me, this issue described in this post (also #813 and #855) is completely resolved in brand new v0.5.4.2 RC.

This means, HWMonitor, HWInfo, CPUz, FanControl, games and NVIDIA GeForce Experience are all working fine while mining is running.

However, anti-LHR is **no longer working** for my Gen1 RTX3060, resulting in roughly 50% of usual MH/s.

**Comment by tac-git** [comment]
this issue described in this post is completely resolved in brand new v0.5.4.2 RC.

**Comment by hwatt2** [comment]
Indeed, Hwinfo64 is not closing with v0.5.4.2 RC, however, might be causing anti-LHR be disabled in some cases (#869).
