### ISSUE TITLE
[BUG] Incorrect VRAM temperature readings on 6700XT

### ISSUE THREAD

**Issue by Dolyfin** [nicehash/NiceHashQuickMiner#868]
**Describe the bug**
Incorrect VRAM temperature readings on 6700XT. It appears to report the  GPU Hot Spot Temperature as the VRAM temp shown in OCTune. And in accordance the fan speeds do not adjust properly to real Memory Junction Temperature. In general changing the fan modes is also very inconsistent.

Reading temps from Wattman and HWinfo64 and comparing it to the reported OCTune temperatures.

**Expected behavior**
Correct Memory/Memory Junction temperature should be reported

**Screenshots**
![image](https://user-images.githubusercontent.com/55581931/169268746-f34ccb83-2820-4695-a54f-40f9dba0a731.png)
![image](https://user-images.githubusercontent.com/55581931/169268776-822a434c-8086-43df-a02c-acab86e6cfb7.png)
![image](https://user-images.githubusercontent.com/55581931/169268826-a34870b2-a00b-43c6-a311-6dcbf6cbbe00.png)

**Version affected (please complete the following information):**
 - 5.4.2 RC (current)
 - Bug occurs in every previous version

**AMD driver version**
22.4.1
Bug had occurred in all past driver versions.

**Hardware**
Gigabyte oc 6700XT top slot

Overclocked r5 3600 on b450 mortar max.

**Logs**
Not sure if this is useful at all
[exported_logs.zip](https://github.com/nicehash/NiceHashQuickMiner/files/8728152/exported_logs.zip)

**Additional context**

**Comment by Dohtar1337** [comment]
Added on the backlog. Closing this issue.
