### ISSUE TITLE
[QUESTION] RTX 3080TI FE  drops to ~50MH/s after few minutes of mining.

### ISSUE THREAD

**Issue by rtx3080tiMiner** [nicehash/NiceHashQuickMiner#869]
Hi, I have a RTX 3080TI FE and i tried mining using nicehash quickminer (NHQM_v0.5.4.2_RC). The starting hashrate was ~110MH/s but suddenly drops to ~50MH/s after few minutes of mining. Tried with different optimize profiles on Nicehash but still the same. Also tried earlier releases of quickminer, still the same thing.

**Comment by hwatt2** [comment]
Probably the anti-LHR is being disabled for some unknown reason.

This also is happening with my Gen1 RTX3060 since the release of v0.5.4.2 RC (#867 ).

**Comment by akce59** [comment]
On my 3060TI it does in version 5.4.2 as well, in version 5.4.0 it works, version 5.4.1 doesn't work for me at all ...

**Comment by hwatt2** [comment]
My rashrate drops because of disabled anti-LHR only when I open HWMonitor in v0.5.4.2 RC.

@rtx3080tiMiner @akce59 check if HWMonitor or other software loaded in memory is not blocking Nicehash's anti-LHR.

**Comment by akce59** [comment]
I do not use any HWMonitor or run anything else. I have no idea what this might collide with.

**Comment by rtx3080tiMiner** [comment]
same as @akce59, I also dont have HWMonitor installed. @hwatt2 can you please tell me whether i can check whats blocking anti-LHR, i mean any other softwares that could possibly block.

**Comment by akce59** [comment]
The graphics card combination may be a problem - see below

My RIG:
1x 3060 Ti
1x 2060 Super
1x 2060 12G
2x 2060
1x 1660 Super

512.77 driver installed

Sorry for the bad English, this is a machine translation.

**Comment by rtx3080tiMiner** [comment]
I am using a single 3080ti with 750W power supply with latest drivers(512.77) installed.

**Comment by hwatt2** [comment]
@akce59 if only 3060Ti is dropping hashrate, it is certain the issue is anti-LHR being disabled, because 1000 and 2000 series don't have LHR.

**Comment by hwatt2** [comment]
Let's wait for v0.5.4.3 RC then...

**Comment by Dohtar1337** [comment]
This issue should be solved in the upcoming release. Please follow NHQM updates and see if the next release solves the issue for you.
