### ISSUE TITLE
core No Compatible devices found!

### ISSUE THREAD

**Issue by kingkongbeat** [nicehash/NiceHashQuickMiner#87]
core No Compatible devices found!
Excavator v1.6.2b gives me > core No compatible devices found!

My rig is a Asus ROG laptop with Geforce GTX 1050 (Driver updated) and i7-7700HQ CPU

Cpu mining works but not GPU. Protection is turned off, threats allowed and folder and files allowed. Any idea why? Is this GPU not supported?

**Comment by nicehashdev** [comment]
Unfortunately, GTX 1050 is not supported because it has only 4GB of VRAM. You will have more luck with NiceHash Miner.
