### ISSUE TITLE
[Bug]? Running nicehash QM at startup via task scheduler breaks when an update is released 

### ISSUE THREAD

**Issue by richardbaxterseo** [nicehash/NiceHashQuickMiner#871]
**Describe the bug**

I have been running QM at startup  [using these instructions] (https://myminingrig.com/run-nicehash-quickminer-at-startup-without-logging-in/). It works until an update is released. Under normal circumstances, the dialogue for update would appear in Windows but running at startup runs NH as a service. Mining continues (I think) but the web UI reports that the rig is offline. 

**To Reproduce**

Run NH at startup without user login 
Wait until an update is released! 

**Expected behavior**
Mining should continue as a service whether an update is available or not. 

**Version affected (please complete the following information):**
 Latest 

**NVIDIA driver version**
Latest 

**Hardware**
Minebox 8 server style rack miner 

**Logs**

**Additional context**

It would be nice to give permission for auto updates in the config.

**Comment by Dohtar1337** [comment]
This is out of scope for now. We intentionally do not allow users to start mining without logging in (a request from anti-virus companies).
