### ISSUE TITLE
[BUG] RTX 3080 PID fan control issue

### ISSUE THREAD

**Issue by MiXtap** [nicehash/NiceHashQuickMiner#872]
**Describe the bug**
The new PID fan control method is very unstable on RTX 3080 regardless of fan control set to Target GPU or Target GPU&VRAM/HotSpot T. resulting in very eradical fan speed and oscillations. 

**To Reproduce**
Mine with a RTX 3080
Set Fan mode of the RTX 3080 to any Target based mode.

**Screenshots**
![image](https://user-images.githubusercontent.com/106115508/169898302-70f52aee-d8f1-4bf4-acaf-c15fa01b5e3d.png)

**Version affected (please complete the following information):**
 - Version number v0.5.3.6
 - STABLE

**NVIDIA driver version**
512.77

**Hardware**
RTX 3080
RTX 2070 Super
GTX 1080 Ti
2x GTX 1060
AMD Athlon 220g
GPUs connected via risers in PCIe x1

This behaviour doesn't appear with other cards, only with RTX 3080.

**Comment by Dohtar1337** [comment]
This issue should be solved in the upcoming release. Please follow NHQM updates and see if the next release solves the issue for you.
