### ISSUE TITLE
[FEATURE] GPU Rename

### ISSUE THREAD

**Issue by Faysk** [nicehash/NiceHashQuickMiner#873]
Hello, I have 4 3090 and 3 3080 TI and as I am increasing my rig I have difficulty putting proper settings for each one, if I had a way to rename or at least differentiate them in the nicehash panel it would help a lot!

![image](https://user-images.githubusercontent.com/5545917/169910839-f4e3586e-2262-48e1-92a7-9d49c39bad50.png)

**Comment by Dohtar1337** [comment]
I will forward this request. It is a valid enhancement.

Thank you for reaching out!
