### ISSUE TITLE
[BUG] Problem with QM5.4.2 RC - QuickMiner & Windows crashes

### ISSUE THREAD

**Issue by jupixweb** [nicehash/NiceHashQuickMiner#874]
Hello! 

I'm new here and i have a problem with the QuickMiner. Everything seems to work correctly:

![image](https://user-images.githubusercontent.com/106179093/170102772-8c191603-fe53-44cd-a28e-f41bddbe3ce8.png)

After an undetermined amount of time (between 2 and 4 hours) Quickminer crashes, windows crashes and the graphics card settings are reset. (I can tell because I keep their LEDs off and they turn on by themselves). I also can't access Windows remotely, I can only reboot the rig by turning the power off and back on

Once rebooted, QuickMiner asks me to do the initial setup again: I have to enter the wallet address and Rig name again.

I use the 512.77 (DHC) driver. I understand that the DHC version is discouraged; but I have read that QuickMiner 5.2.x RC (with LHR unlock) requires at least version 512 and the most current Standard version of the driver is 472.x.

What I can do?

My rig data is:

Graphic-Cards: 2x RTX 2060 12GB & 2x RTX 3060 12 GB
Motherboard: GIGABYTE Z590 UD AC
Other: CPU Intel i3-10100F / RAM 8GB  / SSD 128GB
NVidia Driver: ver. 512 (DHC)
QuickMiner ver. 5.4.2. / Rig Optimization: Lite
Windows 10 64b

Thank you!

**Comment by Dohtar1337** [comment]
This issue should be solved in the upcoming release. Please follow NHQM updates and see if the next release solves the issue for you.
