### ISSUE TITLE
[BUG] v0.5.4.2 RC NVIDIA 512.95 Problem

### ISSUE THREAD

**Issue by Goran456** [nicehash/NiceHashQuickMiner#877]
Hi,

I have just updated my RTX 3060 v1 driver to the latest one from the GeForce Experience - the 512.95 version. However, after doing so, my MH/s halved - from 48 to 25 MH/s.

If anyone has a similar issue after updating to the latest NVIDIA driver, please let me know.

The strange thing is that it shows that the "unlock ratio is 100%". Here is a picture.

https://postimg.cc/yJx8pLh6

**Comment by Goran456** [comment]
UPDATE: I went to official NVIDIA website, downloaded the 512.15 driver and now it works like a charm. I have the previous 48 MH/s that I used to have before updating to 512.95.

**Comment by dandanciu** [comment]
Same issue with 3060TI, the 512.95 driver halved the hashrate to 30 MH/s, reinstalled 512.77 and its back to 60 MH/s.

**Comment by Dohtar1337** [comment]
https://www.nicehash.com/blog/post/psa-full-lhr-unlock-does-not-work-with-nvidia-512-95-driver
