### ISSUE TITLE
[BUG] PC restart around daily with 100% LHR unlock

### ISSUE THREAD

**Issue by isral** [nicehash/NiceHashQuickMiner#879]
**Describe the bug**
PC restart around daily with 100% LHR unlock.

**To Reproduce**
1. Use v0.5.4.0 or v0.5.4.1 or v0.5.4.2
2. Use PC like usual
3. Tomorrow, check PC, notice it that looks like freshly restarted, open applications gone
4. Up-time in task manager confirm that

**Expected behavior**
PC survive days or months without restart

**Screenshots**
N/A

**Version affected (please complete the following information):**
 - NHQM_v0.5.4.0_RC
 - NHQM_v0.5.4.1_RC
 - NHQM_v0.5.4.2_RC

**NVIDIA driver version**
512.15

**Hardware**
Asus 3060 Ti LHR Dual Mini connected directly to motherboard

**Logs**
N/A

**Additional context**
Not happened before 100% LHR unlock

**Comment by mntorq** [comment]
Mine will hang after stopping mining.

**Comment by isral** [comment]
> Mine will hang after stopping mining.

Mine BSOD

**Comment by elmajdal** [comment]
i' having the same with any version after 0.5.3.6 

version 0.5.3.6 works perfectly, however, any version after than even with the latest release 0.5.5.5 system is still crashing daily .

I have multiple rigs, the only issue is happening with 3060Ti

**Comment by Dohtar1337** [comment]
Do you use the installed version?

Please try uninstalling it completely and running the installer again.

Please let me know if this fixed the issue.

**Comment by isral** [comment]
> Do you use the installed version?
> 
> Please try uninstalling it completely and running the installer again.
> 
> Please let me know if this fixed the issue.

Looks OK for 3 days.
Using v5.4.2 portable version.

I think v4.5.2 > v5.4.3 >> v5.4.4 = v5.5.0
v5.4.4 and v5.5.0 destroy taskbar or hung, unusable.
v4.5.0 and v4.5.1 crash some 64 bit games, still usable.

**Comment by isral** [comment]
In v5.4.2, when I lost my in internet connection, my screen is blank for several minutes, back again, blank again, and so on.

**Comment by Dohtar1337** [comment]
Stop the mining first and edit the nhqm.conf

In the line with the command 'launcheCommandLine' , add the -CLS

"launchCommandLine" : "-qx -qm -d 2 -f 6 -CLS",

Start the mining again and the -CLS will be seen in the excavator console.

**Comment by elmajdal** [comment]
> Stop the mining first and edit the nhqm.conf
> 
> In the line with the command 'launcheCommandLine' , add the -CLS
> 
> "launchCommandLine" : "-qx -qm -d 2 -f 6 -CLS",
> 
> Start the mining again and the -CLS will be seen in the excavator console.


I have changed the command line and started version 0.5.5.5.0 

i will report later what happens with me

Thanks for the feedback.

**Comment by elmajdal** [comment]
24 hours passed and with the new line changes "launchCommandLine" : "-qx -qm -d 2 -f 6 -CLS",


version 0.5.5.5.0 is stable .

i will update after 72 if still stable.

**Comment by isral** [comment]
I try v0.5.5.0 with -CLS.
When I wake up at 5am, my screen is blank.
I restart nvidia driver using old octune connected to my android phone, and I can see my screen again.
Based on nicehash.com/my/mining/stats, my PC stopped mining until I restart nvidia driver..

BTW what is -CLS for? I can't find it in the wiki.

**Comment by elmajdal** [comment]
> BTW what is -CLS for? I can't find it in the wiki.

FEATURE - The LHRv3 unlock system has two algorithms: the first leading to a faster hash rate and the second being more stable. The default algorithm is the fastest one, switch to the more stable one can be achieved by using "-CLS" in the Excavator command line.

**Comment by elmajdal** [comment]
> 24 hours passed and with the new line changes "launchCommandLine" : "-qx -qm -d 2 -f 6 -CLS",
> 
> version 0.5.5.5.0 is stable .
> 
> i will update after 72 if still stable.

72 hours passed and the rig is stable with version 0.5.5.5.0 after applying  -CLS

**Comment by DEF29** [comment]
> Stop the mining first and edit the nhqm.conf
> 
> In the line with the command 'launcheCommandLine' , add the -CLS
> 
> "launchCommandLine" : "-qx -qm -d 2 -f 6 -CLS",
> 
> Start the mining again and the -CLS will be seen in the excavator console.

This recipe didn't work for me. I try nhqm 0.5.5.0 with "-CLS" and nvdr 512.77 and system crashed like before.

**Comment by DEF29** [comment]
I recommend everyone to try v0.5.5.1 RC
I uninstalled v0.5.5.0 and installed v0.5.5.1 RC and the system became more stable. However, version 0.5.5.1 of the RC did not resolve the BSOD issue after I quit the NHQM program or just stopped mining. I'll post later how testing goes.

**Comment by DEF29** [comment]
36 hours passed since I started using v0.5.5.1 RC.
**While mining is going on**, the system has never collapsed. The system is stable. I hope that the issue is resolved positively.

However, version 0.5.5.1 RC did not resolve the BSOD issue after I quit the NHQM program or just stopped mining.

**Comment by Mftic** [comment]
I have 4 ROG-STRIX-RTX3060-O12G-V2-GAMING Cards.  What I get in 8+h. with 0.08 rejected Is A Excavator crash, then it wont end the instance. A new Excavator will open. with a count down.  Saying close the the old one.  This will keep running until I reboot.  I have done this @ speeds  40mh 45mh and 49mh all the same.  This is the only BS I have had from NHQM_v0.5.4.4_RC on.  never had this when we had to set the lhr options in OCTune.

**Comment by ybop** [comment]
> A new Excavator will open. with a count down. Saying close the the old one. This will keep running until I reboot.

Exact same issue happening to me.
