### ISSUE TITLE
[BUG] EVGA RTX 3080 TI FTW3 at Efficient or Lite - Very high VRAM Temp (+- 105°c) since 30/05/2022

### ISSUE THREAD

**Issue by albertwesker6139** [nicehash/NiceHashQuickMiner#881]
**Describe the bug**
GPU : EVGA RTX 3080 TI FTW3
OC Profile : Efficient
While using the "Efficient" profile for weeks, my VRAM temp was always below 94°c, and my hashrate was about 70-80 MH/s

However, it's been a few hours that my new hashrate rose to 100-110 MH/s, and unfortunately, my VRAM temp rose to 100-104°c, with the fans running at 100%.
I guess that the "Efficient" profile may have been modified.

**To Reproduce**
1. Use an EVGA RTX 3080 TI FTW3
2. Use the "Efficient" or "Lite" profile
3. Wait 10 seconds
4. Check the VRAM temp.

**Expected behavior**
It won't bother me at all if my MH/s would be reduced. However, I believe that it's important to keep a VRAM temp below 95°c.

**Version affected (please complete the following information):**
 - Version number 0.5.4.1 and 0.5.4.2
 - RC

**NVIDIA driver version**
Which one do you use?

**Hardware**
EVGA RTX 3080 TI FTW3, watercooled, only card and on the first slot.
Intel Core i9-9900K @ 3.60GHz

**Logs**
I can provide one

Thank you very much ! :)

**Comment by mntorq** [comment]
I couldn't use Efficient, it wouldn't LHR.  I used Lite and it had stabilized at 94°.  Until recently, then it moved up to 98-100.  same video card, same miner version.

**Comment by djmnice** [comment]
It is normal with LHR unlock to have higher temperature, if fans is already running at 100% and temps continue to increase you should try to replace the thermal pad on memory chips, this can improve the temp.

**Comment by Dohtar1337** [comment]
No response. Closing.
