### ISSUE TITLE
[BUG] Prerelease v0.5.4.3 RC - 2060 12G - low hashrate - only 29 MH/s

### ISSUE THREAD

**Issue by akce59** [nicehash/NiceHashQuickMiner#882]
v0.5.4.3 RC - 2060 12G - low hashrate - only 29 MH/s, normal is 35 MH/s

**Comment by Fisheiyy** [comment]
not a bug, thats only a 6MH difference nothing major and a more than normal difference

**Comment by akce59** [comment]
RTX 2060 12G
not bug in v0.5.4.3 RC ?

v0.5.3.6  35 MH/s
v0.5.4.0 RC 34.3 MH/s
v0.5.4.1 RC   - err run
v0.5.4.2 RC   - err run
v0.5.4.3 RC 29 MH/s   ????
v0.5.4.4 RC 34.4 MH/s

**Comment by akce59** [comment]
optimize HIGH
standart  2060 6G no problem, problem v0.5.4.3 RC only cart 2060 12G

**Comment by namakeingo** [comment]
I have this issue too with a 2070 Super
v0.5.3.6 43MH/s
v0.5.4.4 40MH/s
I just installed the two versions one after the other multiple times with the same result. Each time v0.5.3.6 hash rate was consistently faster than v0.5.4.4.

Here is some screenshot taken in just a few minutes difference.
![nicehash 0 5 4 4](https://user-images.githubusercontent.com/22453858/173787149-8746ba0f-f947-4756-b0fd-a6051e4e1412.PNG)
![nicehash 0 5 3 6](https://user-images.githubusercontent.com/22453858/173787158-a8c82429-8671-48e2-a3ea-83d2f4f59b36.PNG)

The same manual overclock, same background applications, same everything except the version

**Comment by namakeingo** [comment]
might not be a significant difference but if there is that consistent and reproducible difference it means that the new version is less performant

**Comment by djmnice** [comment]
This issue should be corrected in upcoming release (5.4.5)

**Comment by namakeingo** [comment]
I tested with 5.4.5 and I get no hash rate losses now, so I can confirm the issue is fixed. This can be closed now imo

**Comment by Dohtar1337** [comment]
This issue should be solved in the upcoming release. Please follow NHQM updates and see if the next release solves the issue for you.
