### ISSUE TITLE
QuickMiner v0.5.4.3 RC How to enable stable algorithm

### ISSUE THREAD

**Issue by gabrielebranchi** [nicehash/NiceHashQuickMiner#883]
**Has the question been answered in [Wiki](https://github.com/nicehash/NiceHashQuickMiner/wiki)? There is no such question in [FAQ](https://github.com/nicehash/NiceHashQuickMiner/wiki/FAQ) or [Troubleshooting collection](https://github.com/nicehash/NiceHashQuickMiner/wiki/Troubleshooting)?**
No.

**Your question is...**
In the changelog of the Prerelease v0.5.4.3 RC it says: "The LHRv3 unlock system has two algorithms: the first leading to a faster hash rate and the second being more stable. The default algorithm is the fastest one, switch to the more stable one can be achieved by using "-CLS" in the Excavator command line" 
In what file do we set the "-CLS" parameter? Thank you

**Comment by mntorq** [comment]
I am wondering same.  I can't find any documentation on this.

**Comment by saulob** [comment]
You edit the nhqm.conf file (stop the mining first)

In the line with the command 'launcheCommandLine' , add the -CLS

`"launchCommandLine" : "-qx -qm -d 2 -f 6 -CLS",`

My line already had the "-qx -qm -d 2 -f 6" commands, so I added -CLS at the end. 

Start the mining again and the -CLS will be there

![image](https://user-images.githubusercontent.com/3660977/171521791-e005b8b4-729a-487a-b5d1-dc88b45405ac.png)
