### ISSUE TITLE
[FEATURE] Disable LHR driver warning on 0.5.4.3 RC

### ISSUE THREAD

**Issue by tangcla** [nicehash/NiceHashQuickMiner#884]
**Is your feature request related to a problem? Please describe.**
When Nicehash starts, I get the "Your driver version does not support LHR unlock, please download version 512.77 or earlier" - this occurs on every startup

**Describe the solution you'd like**
It would be good to have a 'do not show again' tick as this means after a reboot, my machines can not start mining straight away.

**Additional context**
My alternatives are to downgrade NHQM to 0.5.4.2 or to downgrade the drivers.

**Comment by Dohtar1337** [comment]
This issue should be solved in the upcoming release. Please follow NHQM updates and see if the next release solves the issue for you.
