### ISSUE TITLE
Different Mining Address

### ISSUE THREAD

**Issue by markfix1912** [nicehash/NiceHashQuickMiner#885]
**Has the question been answered in [Wiki](https://github.com/nicehash/NiceHashQuickMiner/wiki)? There is no such question in [FAQ](https://github.com/nicehash/NiceHashQuickMiner/wiki/FAQ) or [Troubleshooting collection](https://github.com/nicehash/NiceHashQuickMiner/wiki/Troubleshooting)?**
Yes/No.

**Your question is...**
What happen to my Mining Address? 

Original Address
![image](https://user-images.githubusercontent.com/106636488/171306129-16518c52-d9f1-40f0-81b2-a83d07e18e82.png)

every time I pasted to QuickMiner my original address was change to this 
![image](https://user-images.githubusercontent.com/106636488/171306070-2fcadd37-21ed-49d7-9b34-d7a6dd626afc.png)

this happen after the maintenance.
Please help me.

thanks

**Comment by Hydro-Bouy** [comment]
Facing the same...

**Comment by Riskyhsn** [comment]
Does it change whenever you paste any bitcoin address? I encounter that before and it is definitely a virus.

**Comment by 19Micke71** [comment]
https://www.nicehash.com/blog/post/psa-beware-of-clipboard-malware?fbclid=IwAR000Ui9nDJZ-Yye6Ue-JLMkhhIIVubR8-NaLFeBsfIXUyJdxBGz4jrvlAQ

**Comment by Dohtar1337** [comment]
https://www.nicehash.com/blog/post/psa-beware-of-clipboard-malware

Please be aware. I recommend formating your PC
