### ISSUE TITLE
GPU hash rate drops after upgrading to 0.3.0.6

### ISSUE THREAD

**Issue by palaima** [nicehash/NiceHashQuickMiner#9]
Started with 0.3.0.2v 

GTX 1060 hash rate ~20MH/s w/o OC

After upgrading to 0.3.0.6

GTX 1060 hash rate ~16MH/s w/o OC

what can cause such behaviour?

**Comment by nicehashdev** [comment]
Will try to investigate this. Please check your GPU memory clocks when you are running 0.3.0.2 and 0.3.0.6. Is there any difference? I suspect your GPU is stuck in P2 state and not in P0 state that is why you get low hashrate. There are tools that can help you set your GPU into P0 state when mining.

**Comment by palaima** [comment]
Seems no clock difference with 0.3.0.2 and 0.3.0.6. Indeed, P2 was set - after resetting to P0 hashrate increased to 17-18MH/s (with 0.3.0.6). Tried running 0.3.0.2 with P0 set, hashrate now is ~21MH/s

**Comment by nicehashdev** [comment]
I do not notice any issues. I can get almost 22 MHs, using +120 core, +600 memory and 78 W power limit. Try it (with forced P0 state).

**Comment by palaima** [comment]
With 0.3.0.2 and yours provided OC settings I do get 24-25MH/s - same results with NHM.

With 0.3.0.7 and yours provided OC settings as you said it only max up to 21-22MH/s 

so definitely there is an issue with newer NHQM versions

btw P0 state is already set

**Comment by giroberto** [comment]
When I start, my hashrates are correct, but after some time(maybe an hour) my hashrates drop to stock values, I have to go to afterburner and reapply my settings

GeForce GTX 1060 6GB DaggerHashimoto: 16.63 MH/s Status Mining Temp 57ºC Load 100% RPM 1479
GeForce RTX 3080 DaggerHashimoto: 86.6 MH/s Status Mining Temp 64ºC Load 100% RPM 41%
GeForce RTX 3060 Ti DaggerHashimoto: 51.67 MH/s Status Mining Temp 63ºC Load 100% RPM 39%
GeForce GTX 1070 DaggerHashimoto: 24.16 MH/s Status Mining Temp 64ºC Load 100% RPM 2020
GeForce RTX 3060 Ti DaggerHashimoto: 51.65 MH/s Status Mining Temp 62ºC Load 100% RPM 38%

After reapplying
GeForce GTX 1060 6GB DaggerHashimoto: 20.53 MH/s Status Mining Temp 61ºC Load 100% RPM 1537
GeForce RTX 3080 DaggerHashimoto: 99.22 MH/s Status Mining Temp 60ºC Load 100% RPM 53%
GeForce RTX 3060 Ti DaggerHashimoto: 59.96 MH/s Status Mining Temp 63ºC Load 100% RPM 39%
GeForce GTX 1070 DaggerHashimoto: 24.2 MH/s Status Mining Temp 64ºC Load 100% RPM 2050
GeForce RTX 3060 Ti DaggerHashimoto: 60.08 MH/s Status Mining Temp 62ºC Load 100% RPM 38%

**Comment by nicehashdev** [comment]
Okay, will take a deeper look into this shortly.

**Comment by nicehashdev** [comment]
Okay, I have put back the old kernel for pascal devices, and I noticed there was 1.5 MH/s improvement. Please, check this Excavator: https://github.com/nicehash/NiceHashQuickMiner/releases/download/v0.3.1.1_RC/excavator_b595.zip

With latest 0.3.1.1 RC and report back if you have previous performance. Thanks!

**Comment by nicehashdev** [comment]
Available in latest RC ver: https://github.com/nicehash/NiceHashQuickMiner/releases/tag/v0.3.1.2_RC

**Comment by nicehashdev** [comment]
Closing as fixed.
