### ISSUE TITLE
sequence number 40 not found in the dll cabinet.dll

### ISSUE THREAD

**Issue by verhtormashi** [nicehash/NiceHashQuickMiner#90]
I don`t know, how this error in English system. In russian - "порядковый номер 40 не найден в библиотеке dll cabinet.dll".
I`m testing 0.3.0.2, 0.3.2.5 rc. Excavator not start

**Comment by nicehashdev** [comment]
You will get this if you try to run it on Windows 7. It works **ONLY on Windows 10 x64.**

**Comment by BrianG61UK** [comment]
> You will get this if you try to run it on Windows 7. It works **ONLY on Windows 10 x64.**

You might want to make that clear by MENTIONING IT SOMEWHERE PEOPLE MIGHT SEE IT.
ARRRGH!
