### ISSUE TITLE
[BUG]  System hangs up every 7 or more hours on RC 5.4.2 and 5.4.3

### ISSUE THREAD

**Issue by to3mmm** [nicehash/NiceHashQuickMiner#904]
Trying to have full LHR unlock but my system hangs up on after 7 or more hours of runing on RC 5.4.2 or 5.4.3. I've tried NVIDIA drivers 512.15, 512.59, 512.77. No luck. When error is occured system is locked completely even RESET button on MB doesn't work. I have to switch it off by holding power button.
As workaround I made system tasks for reset every 6 hours and so far it works....

It run as a charm for many weeks before on drivers 470.05 and 5.3.6 Quickminer version without any restart.

**Hardware**
CPU G6400, 8GB RAM - Windows system
2x 3060 LHRv1 connected on motherboard
1x 3080Ti LHRv2 on riser (added to rig after change to RC 5.4.2)
2x 1660 Super on risers

MSI interrupts activated
GPU Hardware Acceleration activated
Virtual memory 56GB

LOG:
[[2022-06-03 04:00:14.011298] [thread=0x00002198] [info]] net | daggerhashimoto | New job '0000000031582308', diff=0.603674 (clean)

[[2022-06-03 04:00:14.388325] [thread=0x00002298] [error]] wrkr4-4 | Remove Algo reason: CUDA error 'an illegal memory access was encountered' in func 'cuda_daggerhashimoto::run' line 1335

[[2022-06-03 04:00:14.392317] [thread=0x00000e54] [error]] wrkr3-3 | Remove Algo reason: CUDA error 'an illegal memory access was encountered' in func 'cuda_daggerhashimoto::run' line 1335

[[2022-06-03 04:00:14.392317] [thread=0x00001ca0] [error]] wrkr2-2 | Remove Algo reason: CUDA error 'an illegal memory access was encountered' in func 'cuda_daggerhashimoto::run' line 1335

[[2022-06-03 04:00:14.394311] [thread=0x00000f9c] [error]] wrkr1-1 | Remove Algo reason: CUDA error 'an illegal memory access was encountered' in func 'cuda_daggerhashimoto::run' line 1335

[[2022-06-03 04:00:14.397301] [thread=0x00000e58] [error]] wrkr0-0 | Remove Algo reason: CUDA error 'an illegal memory access was encountered' in func 'cuda_daggerhashimoto::run' line 1335

**Comment by jupixweb** [comment]
Hello, I had the same problem until I downgraded the nvidia driver. With version 472.84 of the driver and the miner RC 5.4.0, everything works fine for more than ten days. Greetings ang good luck!

**Comment by Dohtar1337** [comment]
Reinstall the GPU drivers by following this guide:
https://www.nicehash.com/blog/post/how-to-correctly-uninstall-and-install-gpu-drivers
