### ISSUE TITLE
[BUG]  v0.5.4.3 RC Auto-start Malfunction

### ISSUE THREAD

**Issue by BioDuck123** [nicehash/NiceHashQuickMiner#905]
**Describe the bug**
The v0.5.4.3 RC version does not auto-start when PC is rebooted, turning back on from power outage, or just restarting. By auto-start, I am referring to the program popping up automatically when the PC is turned on, not the mining auto-starting once the program has popped up. Previous versions of the Quickminer have worked normally in this aspect. Most recently used version was  v0.5.4.0 RC which worked as expected. 

**To Reproduce**
1. Turn on auto-start when PC boot
2. Restart PC
3. QuickMiner fails to start up

**Expected behavior**
Expected QuickMiner to automatically start up after <2 minute after PC turns on and gets to Windows page.

**Version affected (please complete the following information):**
 - v0.5.4.3
 - RC

**NVIDIA driver version**
Used 512.77

**Hardware**
3 3060 Ti LHR connected directly to mining motherboard with Intel CPU.

**Comment by York868** [comment]
this bug has been there since the last few candidate releases already. looks like it's still hasn't been fixed.

**Comment by Dohtar1337** [comment]
No response. Closing.
