### ISSUE TITLE
Whea uncorrectable error

### ISSUE THREAD

**Issue by BeardedVater** [nicehash/NiceHashQuickMiner#907]
Windows crashes - whea uncorrectable error - does not recover

**To Reproduce**
Just happens

**Expected behavior**
see above

**Version affected (please complete the following information):**
 - 5.4.4
 - RC

**NVIDIA driver version**
Latest drivers

**Hardware**
LHR cards - 3070 TI - 3070 - 3060
No CPU mining

**Comment by Dohtar1337** [comment]
No response. Closing
