### ISSUE TITLE
nhmp.usa.nicehash.com could be pinged, but console shows disconnected

### ISSUE THREAD

**Issue by acewong7** [nicehash/NiceHashQuickMiner#908]
Hi, I am having some issue with the connection. I could ping to the server  "nhmp.usa.nicehash.com", but there was no connection after I started the mining program. Tried run openssl s_client command, here is the result. 
![Snipaste_2022-06-13_23-25-23](https://user-images.githubusercontent.com/16329701/173388822-cb3d1c81-4b0a-4c9e-a42a-4d1cdfc2e04f.png)

Does anyone know how can I fix this problem? Thx.

**Comment by Dohtar1337** [comment]
please use AUTO location instead. 
https://www.nicehash.com/blog/post/new-auto-locations-in-nicehash-mining-software-update-now
