### ISSUE TITLE
Quickminer 5.4.4 RC Task bar occassinaly dissapears when Excavator stop/restart

### ISSUE THREAD

**Issue by guillemercado** [nicehash/NiceHashQuickMiner#909]
**Describe the bug**
No way to reproduce the bug, happens spontaneously.
I was using the Version 5.4.3 and was very stable, after the upgrade to 5.4.4 the number of "automatic and unexpected" stop/start of quickminer increased dramatically and also causing the **windows task bar to disappear and other issues la preventing the screen to show any data, though the icons still function but can't see it.**

**Version affected (please complete the following information):**
5.4.4

**NVIDIA driver version**
512.77

**Hardware**
Windows 10 Pro - 21H1, os bild 19043.1706
Two graphic Cards NVIDIA 3060 and 3060Ti connected directly to the Motherboard
Mother board MSI MPG X570

**Comment by isral** [comment]
Still happen in v5.5.0.

**Comment by Dohtar1337** [comment]
Those are symptoms of a driver crash. Restart your PC to resolve the issues. It is a known issue for LHR unlock that will cause a driver crash.

Closing this issue for now.
