### ISSUE TITLE
group power mode unavailable after update

### ISSUE THREAD

**Issue by daimonkori** [nicehash/NiceHashQuickMiner#911]
Hello. I updated to the latest recommended version 0.5.3.6 and after that group power settings disappeared in my accounе
![Снимок](https://user-images.githubusercontent.com/79622605/176046278-ace40325-7342-4e27-9084-9b0d8f2ccb9e.JPG)

**Comment by Dohtar1337** [comment]
NiceHash QuickMiner does not support power modes. It supports optimization profiles instead.

Invalid ticket. Closing
