### ISSUE TITLE
[BUG] Fan control problem (AMD Radeon RX 6700 XT Subvendor: ASUS)

### ISSUE THREAD

**Issue by kadiev75** [nicehash/NiceHashQuickMiner#912]
I have a rig with 8 cards: (4 x AMD Radeon RX 6700 XT Subvendor: AMD) and (4 x AMD Radeon RX 6700 XT Subvendor: ASUS)
After setup, the (4 x AMD Radeon RX 6700 XT Subvendor: ASUS) fans do not start in any way while the (4 x AMD Radeon RX 6700 XT Subvendor: AMD) is working properly.

just run the miner and you will see that the fans do not start. Everyone works with the t-rex in the same configuration.

I expect you to correct the problem and be able to control the fans on (4 x AMD Radeon RX 6700 XT Subvendor: ASUS)

Version number 0.5.4.4 RC

AMD driver : 22.5.2

I have a rig with 8 cards: (4 x AMD Radeon RX 6700 XT Subvendor: AMD) and (4 x AMD Radeon RX 6700 XT Subvendor: ASUS)

**Comment by kadiev75** [comment]
There is a problem in 4 rigs where there are (AMD Radeon RX 6700 XT Subvendor: ASUS) cards with different configurations. The fans do not start at any option, even at a fixed speed.

**Comment by Dohtar1337** [comment]
Reinstall the GPU drivers by following this guide:
https://www.nicehash.com/blog/post/how-to-correctly-uninstall-and-install-gpu-drivers

Please try this first, if the issue is not resolved, please reply to this ticket

**Comment by LUISBTNGOTNGOERMGEIJ** [comment]
I have the same problem, but in my case the fans start spinning but after I while fans are turned off without notice
6700 xt asus 
NHQM_v0.5.5.1
Adrenalin 22.7.1 
512.77

I have a combine rig with nvidia 3080ti, 3070ti, 3060ti and 3x 6700, The problem only happens with 1 or 2 6700. The same rig runs perfectly with NBminer

**Comment by Dohtar1337** [comment]
No response. Closing.
