### ISSUE TITLE
Sli enabled error

### ISSUE THREAD

**Issue by xadonxander** [nicehash/NiceHashQuickMiner#914]
Excavator says sli is enabled I have a 3080ti and a 1070 installed in the pc. Sli is not enabled, 3080ti does not even support sli. Newest driver installed, along with newest NHQM. 

=========================== www.nicehash.com =========================
           Excavator v1.7.7.4 GPU Miner for NiceHash.
           Copyright (C) 2022 NiceHash. All rights reserved.
=========================== www.nicehash.com =========================

Build time: 2022-06-09 10:51:41
Build number: 1040
Provided startup commandline: -c commands.json -qx -qm -d 2 -f 6 -wi localhost -wp 18000 -wa 406D7EF947E93AF37EBF4D67

[17:12:36][0x000031d0][info] Log started, build v1040
[17:12:36][0x000031d0][info] core | CUDA memory allocation: std
[17:12:36][0x000031d0][error] core | SLI enabled, cannot continue

**Comment by Dohtar1337** [comment]
Reinstall the GPU drivers by following this guide:
https://www.nicehash.com/blog/post/how-to-correctly-uninstall-and-install-gpu-drivers

Maybe driver reinstall will help solve the issue.

**Comment by Dohtar1337** [comment]
Do you use the installed version?

Please try uninstalling it completely and run the installer again.

please let me know if this fixed the issue.

**Comment by xadonxander** [comment]
Tried that, Did not work. Also tried zip version. Tried a few different versions too. They all do the same thing.  Sent from Mail for Windows From: Dohtar1337Sent: Friday, July 15, 2022 5:23 AMTo: nicehash/NiceHashQuickMinerCc: xadonxander; AuthorSubject: Re: [nicehash/NiceHashQuickMiner] Sli enabled error (Issue #914) Do you use the installed version?Please try uninstalling it completely and run the installer again.please let me know if this fixed the issue.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Dohtar1337** [comment]
Some setting from the drivers must have been stucked somewhere. Make sure to delete all drivers and then reinstall them.

In worst case, if possible, try resetting Windows OS

**Comment by xadonxander** [comment]
I've done that too. Remember it does not do it with excavator in nicehash,
only QM

**Comment by Dohtar1337** [comment]
Can you try older QuickMiner releases? NHM uses a bit older Excavator version. It uses the same excavator version as in NHQM 0536.

**Comment by Dohtar1337** [comment]
No reply, closing.
