### ISSUE TITLE
[BUG] After starting NiceHashQuickMiner bluescreen on Windows 10

### ISSUE THREAD

**Issue by lucasscheepers** [nicehash/NiceHashQuickMiner#915]
**Describe the bug**
After starting NiceHashQuickMiner I'm getting a blue screen. I think it has something to do with the update of Windows 10 I did this weekend?

**Version Windows**
Windows 10 Enterprise 21H2 - OS build 19044.1766

**Version NiceHash**
Version 0.5.4.0

**NVIDIA driver version**
Version 516.59 - Release date 06/28/2022

**Hardware**
1 RTX 3080

**Comment by lucasscheepers** [comment]
I already tried this fix but did not work for me:
 - Open your Quickminer install Folder and Right-Click properties or 'NiceHashQuickminer.exe'
 - Then go to the Compatibility Tab and Disable the 'Full screen Optimizations'

**Comment by Dohtar1337** [comment]
Please check the event logs: https://www.nicehash.com/blog/post/how-to-send-windows-event-logs

What kind of error do you get there? This issue seems to be related you your hardware/software and might not be a bug of NHQM.

**Comment by lucasscheepers** [comment]
I've updated Windows and NiceHashQuickMiner and it's working again
