### ISSUE TITLE
V0.5.5.0 Old OCTune is garbled.

### ISSUE THREAD

**Issue by CrazyLayKer** [nicehash/NiceHashQuickMiner#917]
![image](https://user-images.githubusercontent.com/71445791/177994946-5da2d5ae-7315-4769-9048-2cb9e567e621.png)
In system language Traditional Chinese.

**Comment by Dohtar1337** [comment]
Please provide more information.

**Comment by CrazyLayKer** [comment]
> Please provide more information.

![image](https://user-images.githubusercontent.com/71445791/178967917-ffb093b3-7bab-4a11-9232-22841e2815d5.png)
I got a garbled OCTune html page when I clicked the OCTune option.
