### ISSUE TITLE
Gpu - 3080Ti issues with drivers?

### ISSUE THREAD

**Issue by ChewieTheOld** [nicehash/NiceHashQuickMiner#921]
I use MSI 3080TI Trio X and every time i Stop miner, screens freeze for a second and change color from warm to cool. Also after that every game i try to play have fps issues ever several minutes, massive frame drops, freezes etc.

**Comment by Dohtar1337** [comment]
Driver crashes are expected upon exiting QickMiner.

If driver crash happens, I suggest rebooting the PC before gaming

**Comment by Espionage724** [comment]
> Driver crashes are expected upon exiting QickMiner.

Since when? This has only became a regular ordeal with 0.5.5.0 as far as I know.
