### ISSUE TITLE
[QUESTION] Use old LHR tuning on newer NHQM versions instead of LHR unlock?

### ISSUE THREAD

**Issue by Espionage724** [nicehash/NiceHashQuickMiner#923]
**Has the question been answered in [Wiki](https://github.com/nicehash/NiceHashQuickMiner/wiki)? There is no such question in [FAQ](https://github.com/nicehash/NiceHashQuickMiner/wiki/FAQ) or [Troubleshooting collection](https://github.com/nicehash/NiceHashQuickMiner/wiki/Troubleshooting)?**
No.

**Your question is...**
I have a LHRv2 card and want to use the newest NVIDIA graphics drivers. The release notes for 0.5.5.0 claim the removal of "the old LHR unlock system and all associated functionalities". I'd like to use the old LHR tuning system.

Can the old LHR tuning functionality be restored/used on 0.5.5.0, or is it required to use an older version?

**Comment by Dohtar1337** [comment]
The old LHR tuning system only unlocks the card to 70%. Why would you want to use it?

**Comment by Espionage724** [comment]
> The old LHR tuning system only unlocks the card to 70%. Why would you want to use it?

I run graphics drivers that don't support the full LHR unlock. I'd rather have some LHR unlocked than none at all.

**Comment by Dohtar1337** [comment]
We will add partial unlock back in the future. Closing this ticket as the feature is already in the backlog
