### ISSUE TITLE
[FEATURE] No change of Core Clock Limit during DAG generation in Alterantive OC mode

### ISSUE THREAD

**Issue by Arvenies** [nicehash/NiceHashQuickMiner#924]
**Is your feature request related to a problem? Please describe.**
When using alternative OC, TDP limit is set to maximum possible value, sometimes more than 100% if BIOS of a card allows it, and actual power usage is determined only by Core Clock Limit set in this OC mode. But during DAG generation/change OC is reverted is such a way that Core Clock Limit is set to no limit (as this is default), and memory clock is set to default. It means that card is set to max possible TDP limit and max boost clock kicks in. Basically it means that card can change power draw almost twice, because well optimized card is using about 60-70% of it's nominal TDP, and when boosting it can go even to 120%. In a rig with multiple cards and PSUs optimized to this regular usage of about 60% TDP, this is problematic because power draw can be more than PSUs can provide, and provide PSUs with max power draw almost twice that is regularly used is just waste of PSU.

**Describe the solution you'd like**
Excavator have a command line option "-g" to not revert OC during DAG generation, providing no power usage spikes during DAG generation with alternative OC, but not lowering memory clock generates errors in DAG. The solution would be similar option that would not change Core Clock Limit during DAG generation, but would lower memory clock.

**Describe alternatives you've considered**
Alternative is not to use Alternative OC, but use Classic OC and set Power Limit (W) - it is still respected during DAG generation and disabled OC. Unfortunately Classic OC does not allow best possible OC optimization. Even when enabling "Unlock max core voltage", what changes Core Clock from Delta to Limit, so basically is very similar to Alternative OC, best optimization is not possible: I don't know why, but all cards in this mode have minimally lower hash rate, even when set to the same Core Clock Limit and same Memory Clock as in Alternative OC.

**Additional context**
PS. "Power Lim (%)" in new Excavator OC Tuner should be "Power Lim (W)".

**Comment by Dohtar1337** [comment]
DAG generation should not draw that much power. It normally takes just a couple of seconds. 

With ETH going PoS next month, we will not implement this.
