### ISSUE TITLE
[BUG] Lower hashrate than v0.5.4.3 RC on any newer version.

### ISSUE THREAD

**Issue by i1itione** [nicehash/NiceHashQuickMiner#925]
**Describe the bug**
Any newer version of NHQM got lower hashrate than v0.5.4.3 RC on my four RTX 3080 Ti cards rig.

**To Reproduce**
1. Using any newer version of NHQM than v0.5.4.3 RC.
2. OC value is 945 MHz (Core) and 9101 MHz (Mem).
3. The hashrate is about 101 Mh/s on v0.5.4.3 RC, but any newer version just got 90~95 Mh/s.

**NVIDIA driver version**
512.77, and OS is Windows 10 (21H2).

**Comment by Dohtar1337** [comment]
Have you tried latest Release Candidate? https://github.com/nicehash/NiceHashQuickMiner/releases/tag/v0.5.5.1_RC

**Comment by Dohtar1337** [comment]
No response. Closing.
