### ISSUE TITLE
There are no optimization settings for the MSI 3090 video card completely.[BUG] 

### ISSUE THREAD

**Issue by Wolfer91** [nicehash/NiceHashQuickMiner#926]
There are no optimization settings for the MSI 3090 video card completely.

Good afternoon! I ran into the problem that my optimization settings were missing in the rig manager a couple of months ago. I tried to study this topic and look for solutions myself, I even wrote to technical support, but they told me to do control procedures that did not help.
To begin with, I would like to report that I noticed something strange.
When I try to download the Quick Miner installer and run it, for some reason I am prompted to install version 0.5.1.3, while version 0.5.5.0 is now. I tried to uninstall Quick Miner then re-download to another directory and run... same thing. Now I run Quick Miner directly from the zip file so it shows that the latest version has started. But still, there are no optimization settings in the rig manager on the site. I am forced to use MSI afterburner and set up the graphics card myself. Video card drivers latest. MSI Supreme 3090 video card.
I admit that the business registry or something like that, when downloading through the official website of the launcher, I am informed that I downloaded the old version.
How can I solve this problem? It was very convenient for me to use automatic optimization through the rig manager.

**Comment by Dohtar1337** [comment]
Please download this version: https://github.com/nicehash/NiceHashQuickMiner/releases/tag/v0.5.5.1_RC

Extract it to your desktop/QuickMiner and try again.

Try to reinstall the drivers by following this guide.  https://www.nicehash.com/blog/post/how-to-correctly-uninstall-and-install-gpu-drivers

Maybe the drivers are not installed correctly and the drivers wrongly recognize/display the GPU name. The profiles work by recognizing the GPU name and mapping it to the profiles.

**Comment by Wolfer91** [comment]
> Please download this version: https://github.com/nicehash/NiceHashQuickMiner/releases/tag/v0.5.5.1_RC
> 
> Extract it to your desktop/QuickMiner and try again.
> 
> Try to reinstall the drivers by following this guide. https://www.nicehash.com/blog/post/how-to-correctly-uninstall-and-install-gpu-drivers
> 
> Maybe the drivers are not installed correctly and the drivers wrongly recognize/display the GPU name. The profiles work by recognizing the GPU name and mapping it to the profiles.

I did these steps but they do not fix this problem. When downloading the installer, my window displays the installation of the old version of the program 0.5.1.3. Whatever new version I would not download, he tries to install the old one ..

**Comment by Dohtar1337** [comment]
Try to download NHQM from here: https://www.nicehash.com/download-center

**Comment by Wolfer91** [comment]
> Try to download NHQM from here: https://www.nicehash.com/download-center

It does't work

**Comment by Dohtar1337** [comment]
Please provide more information like a screenshot or logs.

**Comment by Dohtar1337** [comment]
No response, closing.
