### ISSUE TITLE
Scheldune mining

### ISSUE THREAD

**Issue by fracii** [nicehash/NiceHashQuickMiner#929]
Hi,

I tried to create a schedule in windows with task scheduler and a .bat with taskkill command but this does not work with quickminer. The program won't shut down. Any other more accessible way to schedule mining (due to high electric prices)? Nice to have the setting in the program to choose auto start mine and auto stop mine every day.

This I was tested

.bat file: 

@echo off
taskkill /F /IM NiceHashQuickMiner.exe
taskkill /F /IM excavator.exe
cls

**Comment by elmajdal** [comment]
this is now available in NiceHash miner prerelease 3.1.0.0 pre-release

[
](https://www.nicehash.com/blog/post/nicehash-miner-3-1-0-0-pre-release-with-scheduler-and-extra-commands-is-available)


hopefully oneday we see it quickminer

**Comment by Dohtar1337** [comment]
We will eventually move it to the QuickMiner. It is not implemented yet.

For now only NHM supports scheduling via GUI
