### ISSUE TITLE
Nicehash 3.0.9.2 + Excavator 1.7.7.6 3080LHR resetting clocks [BUG] 

### ISSUE THREAD

**Issue by stg43x** [nicehash/NiceHashQuickMiner#930]
**Describe the bug**
Using Nicehash 3.0.9.2 with autodownload of Excavator 1.7.7.6
Start

**To Reproduce**
1. Download Nicehash 3.0.9.2
2. Set overclocking in MSI afterburner for your 3080LHR GPUs
3. Start mining DaggerHashimoto with Excavator 1.7.7.6 and 3080LHR10GB gpu
4. Look at gpu clocks in MSI afterburner (if you had custom clocks) 
5. After few seconds gpu core and mem clocks will be resseted to zero

**Expected behavior**
No resetting clocks

**Screenshots**

**Version affected (please complete the following information):**
Excavator 1.7.7.6

**NVIDIA driver version**
512.77

**Hardware**
10gb 3080 LHR gagabyte
10gb 3080 LHR zotac 
10gb 3080 LHR evga

**Logs**
Activate logging first, then record event - bug - then export logs into a .zip file and attach it when submitting this issue.

**Additional context**
I just don't know where to post this bug, sorry if I'm doing wrong

**Comment by stg43x** [comment]
![measure](https://user-images.githubusercontent.com/9459983/189605263-2f685cf1-e7cb-451e-b9e3-bfb465b3cb81.png)

**Comment by Dohtar1337** [comment]
Reported to backlog. Closing.
