### ISSUE TITLE
[BUG] The hashrate of Autolykos algorithm is a little lower than 3rd party miners.

### ISSUE THREAD

**Issue by i1itione** [nicehash/NiceHashQuickMiner#931]
**Describe the bug**
The hashrate of Autolykos algorithm is a little lower than 3rd party miners (e.g. lolMiner).

**Version affected (please complete the following information):**
 - 0.6.0.0
 - RC

**NVIDIA driver version**
512.77

**Hardware**
RTX 3080 Ti

**Additional context**
I tried NHQM and lolMiner or NBMiner and using the same OC settings, the hashrate is lower on NHQM.
I know NHQM is just begining to support Autolykos algorithm, maybe it would be optimized in the future?

**Comment by Dohtar1337** [comment]
Yes, we will optmize it in the future, right new we have higher priority tasks.

Thansk for reaching out anyway!
