### ISSUE TITLE
Please add Neoscrypt Support

### ISSUE THREAD

**Issue by dufflesterny** [nicehash/NiceHashQuickMiner#936]
Hi team,

Since Ethereum Merge re-balance the mining space, many old POW coins - GPU mined are back on the top of the list for profitability.
Would you mind adding Neoscrypt support. ccminer works well even with latest GPU.

Kind regards,

Ludovic

**Comment by Dohtar1337** [comment]
Neoscrypt is already supported on NiceHash. You need to connect to it manually. 

For now there are no plans on adding neoscrypt to QuickMiner

https://www.nicehash.com/algorithm/neoscrypt
