### ISSUE TITLE
[QUESTION] after 15 september mining values is really low

### ISSUE THREAD

**Issue by fradem72** [nicehash/NiceHashQuickMiner#937]
**Has the question been answered in [Wiki](https://github.com/nicehash/NiceHashQuickMiner/wiki)? There is no such question in [FAQ](https://github.com/nicehash/NiceHashQuickMiner/wiki/FAQ) or [Troubleshooting collection](https://github.com/nicehash/NiceHashQuickMiner/wiki/Troubleshooting)?**
Yes/No.

**Your question is...**
What is...
i have read the news that started 15 septembr but now even if hashrate is the same value of mining decreased drastically (from averavge 0.00006800 peer day at 0.00000620 per day means 10 time less, and it is not convenient to mine with these electricity prices in italy now...) do u have the same issue? is it possible to solve in some way? how to increase the value of mining?
thx for each kind of helps
now i use the new algorithm by default of quick miner

**Comment by stevekenney318** [comment]
definitely not profitable for me, I turned mine off ... https://i.imgur.com/T1RolbS.jpg

**Comment by Dohtar1337** [comment]
not an bug
