### ISSUE TITLE
[QUESTION] 

### ISSUE THREAD

**Issue by jakubsuchybio** [nicehash/NiceHashQuickMiner#938]
**Has the question been answered in [Wiki](https://github.com/nicehash/NiceHashQuickMiner/wiki)? There is no such question in [FAQ](https://github.com/nicehash/NiceHashQuickMiner/wiki/FAQ) or [Troubleshooting collection](https://github.com/nicehash/NiceHashQuickMiner/wiki/Troubleshooting)?**
No

**Your question is...**
Why quickminer doesn't auto switch? I'm using it instead of NH Miner on 2 of my gaming rigs because of security (i don't trust other miners). But now after ETH merge there is no single most profitable coin. So auto-switching makes much more sense now.

Please add it to NH QuickMiner too. Thx.

**Comment by stevekenney318** [comment]
> auto-switching makes much more sense now

I agree 100% on this.

**Comment by Dohtar1337** [comment]
This feature is coming soon.

**Comment by stevekenney318** [comment]
> This feature is coming soon.

That's great to hear... How will it be announced? I've stopped mining since the merge, but we'll try again with this feature.

**Comment by jakubsuchybio** [comment]
I already started mining with NH Miner, which seems to have more profit with more algos. But still not profitable, but heating our appartment for 20% of the electricity is ok with me :D (100% electric heater vs mining with 80% money return for electricity)
