### ISSUE TITLE
Suggestions after months of usign

### ISSUE THREAD

**Issue by Lysnyt** [nicehash/NiceHashQuickMiner#939]
1. While install you can choose the path where to install >when you choose different directory to install, the directory "nicehash x.y" will be erased from the selected path in setup and whole program files will be installed in to new choosen directory without "nicehash" name
2. if you graphic card is not present in the system, program will tell you "unable to start" without any option to disable autostart function till any compatible card will be installed
3. Unable to activate Game mode, as primary display could be CPU graphic and second is PCI-E 
4. No automatic solution to pause mining if steam game / game start recognized
5. In new OCtune (nicehash 0.6.0.1) the gpu keeps disappear / appear  ([16. 9. 2022 22:49:42] Connected [16. 9. 2022 22:49:40] Cannot connect..[16. 9. 2022 22:50:15] Connected) 
6. no autoupdate

**Comment by Dohtar1337** [comment]
Thanks for the feedback!

1. feature, not a bug
2. Users need to delete the quickminer in that case. It is also an edge case, reported for the first time
3. You should not be gaming on APU. Edge case
4. We might implement this in the future
5. We need more information about this. We have never experienced this before. It could be related to unstable rig
6. QuickMiner has autoupdate.
