### ISSUE TITLE
Device #0: Cannot perform without support for power consumption reporting!

### ISSUE THREAD

**Issue by cesarcgfg** [nicehash/NiceHashQuickMiner#94]
Hi after this recent update, my OC setting were reset. So I tried again the Autotune method again, but it no longer works. I get the following message: 

`Device #0: Cannot perform without support for power consumption reporting!.`

Card: Mobile RTX 2060 .

It was working great, had the best setup, lower power consumption and temps without loosing hash rate :/

Regards

**Comment by nicehashdev** [comment]
The old version is still available: https://github.com/nicehash/NiceHashQuickMiner/releases?after=v0.3.0.7_RC

You may try to experiment with drivers (DCH, non DCH etc) and see if it helps in any way. Do note that Mobile cards are officially not supported (yet).

**Comment by cesarcgfg** [comment]
Hi,
Yes I downloaded the old version. It is working fine.

This was to let you know the issue, you guys might consider it, because the power consumption is readble in the old version. So the way to obtian this info worked better (IMHO).
![imagen](https://user-images.githubusercontent.com/16925066/108916613-28170780-75f4-11eb-8a8a-2dc0f9a168fe.png)


Best Regards

**Comment by nicehashdev** [comment]
The trick is that this function did not change. We still use the same one. Something regarding NVIDIA drivers/libraries is causing this but I did not have time to check it out yet.

**Comment by sjaaq** [comment]
I am experiencing the same issue. Also tried the nvidia studio drivers, which did not help. I also have the GTX2060 mobile.

For now, I reinstalled the previous stable 0.3.0.2.

**Comment by nicehashdev** [comment]
I have linked part of the Excavator against another version of CUDA library, like it used to be with the older versions. Please, try it and let me know if this changes anything for you. Thanks!
[excavator_b644.zip](https://github.com/nicehash/NiceHashQuickMiner/files/6044419/excavator_b644.zip)

**Comment by chrisngrod** [comment]
Still the same here with 1.6.3a (excavator_b44.zip).

**Comment by nicehashdev** [comment]
Okay, now how about this one? This one should be closer to the solution of fixing "buggy" NVIDIA drivers and libraries.
[excavator_build645.zip](https://github.com/nicehash/NiceHashQuickMiner/files/6045041/excavator_build645.zip)

**Comment by chrisngrod** [comment]
Strange.  Starts up with the error and then outputs correctly after a moment.

![image](https://user-images.githubusercontent.com/79091904/109199659-5536f780-7765-11eb-8eda-59d46b3e235b.png)

Awesome!

**Comment by nicehashdev** [comment]
Great! So, we can consider this one fixed then :)

And yes, it is a bug in NVIDIA lib - it reports back that it does not have ability to provide power information, but then, it does provide power information.

**Comment by nicehashdev** [comment]
I have made new release with this fix: https://github.com/nicehash/NiceHashQuickMiner/releases/tag/v0.3.2.7_RC

**Comment by dvv47** [comment]
![image](https://user-images.githubusercontent.com/1726478/109207235-f2bc1680-77b9-11eb-848a-d98d1f321d8c.png)
same for me

**Comment by sjaaq** [comment]
I have tested with 0.3.2.7_RC and besides from the startup error it does report it again after a few seconds.

**Comment by StepGitHub** [comment]
Hi! Thanks for 1.6.4.b! But, error in gtx1070, OcTune set PowerLimit [->]
![error1](https://user-images.githubusercontent.com/79711330/109324147-551e2100-7865-11eb-9ec0-1a849815eb49.jpg)
Fix It, Please)

**Comment by nicehashdev** [comment]
On some devices, obtaining power limits is not possible. You can try to reinstall drivers, try different drivers. This is an issue with buggy nvml library. Please, open a new ticket, because this one is closing is the issue has been fixed.
