### ISSUE TITLE
[BUG] Typo in Optimize profiles files data_009.json and data_010.json for GeForce RTX 3070 medium profile.

### ISSUE THREAD

**Issue by s33butler** [nicehash/NiceHashQuickMiner#940]
Typo in Optimize profiles files 9 and 10 for GeForce RTX 3070 medium profile.

9100 listed instead of 100.  Line 137 in 010  and Line 132 for 009.

NiceHashQuickMiner/optimize/data_010.json
            { "name": "GeForce RTX 3070", "op": [
            { "id": 3, "pt": 0, "dmc": 1370, "mcc": 1110, "fm": 3, "ftg" : 56, "ftr": 68, "lhr": [55, 100]},
Line137        { "id": 2, "pt": 0, "dmc": 1170, "mcc": 1065, "fm": 3, "ftg" : 58, "ftr": 70, "lhr": [55, **_9100_**]},
            { "id": 1, "pt": 0, "dmc": 900, "mcc": 810, "fm": 3, "ftg" : 62, "ftr": 72, "lhr": [55, 100]}
            ]},

NiceHashQuickMiner/optimize/data_009.json
Line132        { "id": 2, "pt": 0, "dmc": 1170, "mcc": 1065, "fm": 3, "ftg" : 58, "ftr": 70, "lhr": [55, **_9100_**]},

Thank you for your time and assistance, keep up the great work.

**Comment by Dohtar1337** [comment]
This was fixed.

Thanks for letting us know!
