### ISSUE TITLE
Dont start on Linux MInt 19.3 x64

### ISSUE THREAD

**Issue by dj--alex** [nicehash/NiceHashQuickMiner#941]
**Describe the bug**
Absolutely nothing done after click on installer

**To Reproduce**
Install any Linux  + Wine 7.17.  Im 15 years using only linux.
Run "NiceHashQuickMinerInstaller.exe"
Where is Linux build  of miner? 

**Expected behavior**
Window of installer or miner process

**Screenshots**
Nothing to screenshot.

**Version affected (please complete the following information):**
6, latest

**NVIDIA driver version**
510.53

**Hardware**
RTX 3070 TI

**Logs**
None logs from start file. Only wine log
0c08:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION

Unhandled Exception:
System.TypeLoadException: Could not load type of field 'watchdog2.Logger:log' (5) due to: Could not load file or assembly 'log4net, Version=2.0.12.0, Culture=neutral, PublicKeyToken=669e0ddf0bb1aa2a' or one of its dependencies.
0c00:fixme:ver:GetCurrentPackageId (000000000068FDB0 0000000000000000): stub

**Additional context**

**Comment by Dohtar1337** [comment]
QuickMiner is for Windows based systems, not Linux
