### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by malahora** [nicehash/NiceHashQuickMiner#943]
on 522.30 drivers goes fine .. dont update  -- closed --

**Describe the bug**
after upddate drives on kapow algorith... crash !

**Version affected (please complete the following information):**
v 0.6.0.1 STABLE

**NVIDIA driver version**
526.47

**Hardware**
asus prime b365 plus
x3 rtx 2080ti
i5 8400
16 gb ram
hd ssd 250 gb
win 10 pro licensed
[exported_logs.zip](https://github.com/nicehash/NiceHashQuickMiner/files/9890981/exported_logs.zip)

**Comment by Dohtar1337** [comment]
NVIDIA drivers 526.47 are causing issues on some GPUs/Algorithms. Skip this version.
