### ISSUE TITLE
[BUG] NHQM v0.6.0.1 -> v0.6.1.2 No Compatible Devices Found

### ISSUE THREAD

**Issue by hoang51** [nicehash/NiceHashQuickMiner#945]
Prior to updating NiceHash QuickMiner from v0.6.0.1 (RC or stable) to v0.6.1.2, Nvidia GeForce GTX 1050 Ti 4 GB was capable of mining Autolykos (Ergo) as reported by Excavator v1.8.0.1:

`core | Found Supported CUDA device #0: GeForce GTX 1050 Ti         id: 0`

After updating to NHQM v0.6.1.2, Excavator v1.8.1.2 gives this error:

`[error] core | No compatible devices found!`

Currently, Nvidia drivers 526.98 (11/16/2022) are loaded into the system. Previously, Nvidia drivers 522.25 was loaded and still produced the error above with NHQM v0.6.1.2.

The changelog appears to not have anything that would indicate it would exclude the Nvidia GeForce GTX 1050 Ti 4 GB from mining. Was something overlooked or is this an actual issue that needs attention? NHQM v0.6.0.1 has been reinstated for the time being.

**Comment by HAL-JP** [comment]
I'm having a similar problem. AMD RX 5500 XT 4GB

**Comment by Dohtar1337** [comment]
The limit was increased from 4GB to 5GB for autolykos. This was to prevent the switching issues.

Minimum GPU VRAM size on QuickMiner is 5GB.
