### ISSUE TITLE
NiceHash QuickMiner Process Suspended

### ISSUE THREAD

**Issue by flyingahh** [nicehash/NiceHashQuickMiner#95]
Randomly, after some number of hours, Excavator will stop mining and no indication of why will be logged. Doesn't appear to be a hardware failure. The NiceHash QuickMiner process becomes suspended, and I have to manually kill it in Task Manager.
I have a RTX 3080 GPU with a Ryzen 5800x CPU.

**Comment by nicehashdev** [comment]
Which application becomes suspended? Excavator or NiceHash QuickMiner?

Can you please turn on full logging (both QuickMiner and Excavator) and send me logs (you can attach them here, just delete out your BTC address).

**Comment by flyingahh** [comment]
The QuickMiner process becomes suspended, not Excavator. I will turn on full logging and send when it happens again.

**Comment by nicehashdev** [comment]
Looks like it never happened again or it was related to AVs. Closing.
