### ISSUE TITLE
System Crash After using new Medium Optimization settings

### ISSUE THREAD

**Issue by LanceMcCarthy** [nicehash/NiceHashQuickMiner#96]
After updating to today's release ( `v0.3.2.6`?) everything was working great. Until I changed the rig settings to use the new Medium setting in the webpage's Rig Manager UI.

![image](https://user-images.githubusercontent.com/3520532/108907464-19c6ec80-75f0-11eb-88fb-4c38bf0e6282.png)

That nearly immediately crashed the system. Upon reboot, the Task Scheduler started QuickMiner again and immediately hard crahsed the system again.

After about 3-4 reboots, I was finally able to kill the QuickMiner process before the system crashed (I immediately manually deleted the Task Scheduler's task for starting quickMiner)

Looking at Event Viewer, I found the report

```
The computer has rebooted from a bugcheck.  The bugcheck was: 0x00000116 (0xffff9987ac35c010, 0xfffff8078a857440, 0xffffffffc000009a, 0x0000000000000004). A dump was saved in: C:\windows\MEMORY.DMP. Report Id: b90487be-4203-48cf-93b5-58cf43808f74.
```

I'm not going to attach the dump in a public location, but I can provide it to a team member via email

Repair
How can I get back to a default state? In the Rig dashboard, the UI is stuck on Medium because it is disabled.

![image](https://user-images.githubusercontent.com/3520532/108907669-601c4b80-75f0-11eb-9a9a-693e4cbd14bf.png)

**Comment by nicehashdev** [comment]
The easiest method to restore previous state is to simply reinstall QuickMiner. You can also delete nhqm.conf file.

Can you let me know which card you have?

And it is always best to choose Lite first and see if that works fine before applying Medium.

**Comment by LanceMcCarthy** [comment]
Here's the rig details:

![image](https://user-images.githubusercontent.com/3520532/108910218-8c859700-75f3-11eb-8528-cd59d31ff6b4.png)

I considered deleting the config file, but the settings inside it look like they were at the default. So I wondered if the settings might have been passed down to Octune and didnt want to take a chance of restarting the exe. (I'm using it as a portable)

I'll try the delete and re-download approach. Thanks for the prompt response.

**Comment by LanceMcCarthy** [comment]
In case it helps, here is the conf file's setting after the crash.

```
{"CPUMinerELP":"--cpu-max-threads-hint 50 --print-time 15",
"authorization":{"BTC":"REDACTED",
"groupName":"REDACTED",
"serviceLocation":1,
"uniqueID":"REDACTED",
"workerName":"myExcavator1"},
"bEnableCPUMining":false,
"bHideMiningConsole":false,
"bIsMining":true,
"bNoDNSOverHTTPS":false,
"bUpdateRCVersion":false,
"consoleLogLevel":6,
"disabledDevices":[],
"fileLogLevel":6,
"gameStateOverclock":{"TDP":100,
"coreClockDelta":0,
"memoryClockDelta":0},
"launchCommandLine":"-qm -wp 18000 -d 2 -f 6",
"maxDeviceSpeed":300,
"optimizeProfiles":"0=2;",
"productionLevel":0,
"whenDeviceSpeedTooHigh":2,
"whenDeviceSpeedZero":1}
```

**Comment by nicehashdev** [comment]
I would be more interested in commands.json file and logs generated by Excavator. If Excavator crashed, then it was too high memory OC most likely.

 ALso, which driver version do you have?

**Comment by LanceMcCarthy** [comment]
![image](https://user-images.githubusercontent.com/3520532/108919440-07a17a00-7601-11eb-9f32-421d6c48caf6.png)

> I also have the latest GameReady driver (v 461.40)

I'm not sure where to find excavator logs, the filer I am running nhqm from doesn't seem to have any form of log output files/folder

commands.json
```
[{
		"time": 0,
		"commands": []
	},{
		"time": 20,
		"commands": [{
				"id": 1,
				"method": "workers.reset.all",
				"params": []
			}]
	}, {
		"time": 30,
		"loop": 30,
		"commands": [{
				"id": 1,
				"method": "worker.print.efficiencies",
				"params": []
			}]
	}, {
		"time": 1,
		"loop": 4,
		"commands": [{
				"id": 1,
				"method": "devices.smartfan.exec",
				"params": []
			}]
	}, {
		"event": "on_quit",
		"commands": [{
				"id": 1,
				"method": "devices.smartfan.reset",
				"params": []
			}]
	}, {
		"event": "on_quickminer.start",
		"commands": []
	}, {
		"event": "on_quickminer.stop",
		"commands": []
	}
]
```

**Comment by nicehashdev** [comment]
You need to enable logging first, right click and settings -> enable full logging.

**Comment by LanceMcCarthy** [comment]
Ah, okay then I'd need to recreate the conditions that hard crashed the system (I didn't even get a bug check BSOD, it just hard crashed to no power). so you can imagine why I'd rather not do that 😁 

I have several important servers running on this box in many VMs, so intentionally crashing it has bad downstream side effects. However, I will enable logging for the next couple weeks, just in case it happens again.

Thanks for the insights and super-fast follow up.

**Comment by Astrarog** [comment]
Hi there!
I've observed the same issue on GeForce RTX 2070 and followed the instructions about enabling the loggin.
So, while setting medium optimizations, the initial behaviour was the black screening monitor and not responing system.
An interesting is that having enabled full loggin the screen now switches off only for a periond of time and the windows after that acts and responds normally.

In the event viewer there are many errors like:
`\Device\0000007a Graphics SM Warp Exception on (GPC 0, TPC 5, SM 1): Out Of Range Register`
`\Device\0000007a Graphics SM Global Exception on (GPC 0, TPC 5, SM 1): Multiple Warp Errors`
or like:
`\Device\0000007a Graphics Exception: ESR 0x506fb0=0x6000d 0x506fb4=0x4 0x506fa8=0x4c1eb72 0x506fac=0x174`

I have the same driver version as was presented in this issue.

Here is the logs and commands.json that I've collected.
[log_2021-02-24_08-01-08.002.log](https://github.com/nicehash/NiceHashQuickMiner/files/6033545/log_2021-02-24_08-01-08.002.log)
[commands.json.txt](https://github.com/nicehash/NiceHashQuickMiner/files/6033554/commands.json.txt)

**Comment by nicehashdev** [comment]
This log does not tell me much but just that your system probably crashed because of too intensive clocks. If Lite mode works for you, just use that. Perhaps you were unlucky and got bad chip that cannot handle higher frequencies.

**Comment by LanceMcCarthy** [comment]
@nicehashdev I'm not sure if I should open another issue for this, but it seems the reason for the original crash might be connected to the same error I am getting when I try to edit Game mode settings:

![image](https://user-images.githubusercontent.com/3520532/109299892-caf1a080-7803-11eb-8ea2-fde4cb20da9e.png)

**Comment by nicehashdev** [comment]
Please, open a new ticket if not being related to this issue, because I am closing this issue.
