### ISSUE TITLE
CUDA error while using the new function "optmizer"

### ISSUE THREAD

**Issue by alanceloth** [nicehash/NiceHashQuickMiner#97]
Hi there, I'm getting an error while I use the optmizer Medium preset.

My rig: RTX 2060 Super Asus Rog Strix.
16GB Ram
Ryzen 7 2700

I only use the Excavator miner, version 1.6.3.g (the new one released today)

error: CUDA error 'an illegal memory access was encountered' in func 'cuda_daggerhashimoto::run' line 1197

print:
https://imgur.com/a/An3eXZ5

**Comment by nicehashdev** [comment]
You clicked button Optimize and chose a Lite or Medium? If you did Medium, try Lite. Looks like your card cannot handle so high memory overclock.

**Comment by alanceloth** [comment]
Well, I've check the memory delta, and the Medium preset set my delta to 900, and I was using 950 of mem clock delta in my previous presets. I don't think that my card do not support.. Could you check this line (1197) on your code to get more details?

**Comment by nicehashdev** [comment]
Crash happens inside kernel that does hashing which indicates too high memory OC. You will not be able to compare this OC with the classic one, because this one does not modify TDP and core clock delta, but rather limit max core clock so the power distribution is a bit different.

**Comment by alanceloth** [comment]
I see, thanks for the info. I hope that my card support the medium preset soon if you guys apply some tweaks :D

**Comment by nicehashdev** [comment]
Lite works for you? If yes, you can help us by supplying information about clocks that you can reach with alternative OC and what kind of speeds/efficiencies you get for that.

**Comment by alanceloth** [comment]
Full Rig Specs:

- Asus Rog Strix RTX 2060 Super 8GB
- Ryzen 7 2700
- 16 GB Ram
- GPUZ print: https://imgur.com/a/Tou9jXE

Alternative OC specs:

- Software: Asus GPU Tweak II
- Core Clock: -48 (1632 MHz on GPU Tweak and 1020 MHz fixed on GPUz sensor, sometimes this value drops to 900MHz-800MHz)
- Mem Clock: +950 (14952 MHz on GPU Tweak and 1850.2 MHz on GPUz sensor)
- GPU Voltage %: 100% (idk how this impacts my perf, I've changed this value to 0% and my eff has no effect.
- Power Target %, TDP: 65 (-35 on GPU Tweak and my Board Power Draw stays with 110-115W)
- GPU Temp Target: 65ºC
- My GPU fans (left, right and middle fans): I've created a curve to controll my temp, and it's working fine, the max temp it's around 53 ºC

-Server location: USA
-Rig Location: Brazil

My eff stays aroung 320-340 kH/J

![Captura de tela 2021-02-23 194603](https://user-images.githubusercontent.com/11635850/108919336-9a4a1500-7611-11eb-9d9d-e363728a395c.jpg)
![Captura de tela 2021-02-23 195225](https://user-images.githubusercontent.com/11635850/108919339-9a4a1500-7611-11eb-9738-0fcebba73c89.jpg)
![Captura de tela 2021-02-23 195725](https://user-images.githubusercontent.com/11635850/108919342-9ae2ab80-7611-11eb-9bfd-b5cceaa74c09.jpg)
![Captura de tela 2021-02-23 195738](https://user-images.githubusercontent.com/11635850/108919344-9ae2ab80-7611-11eb-90f2-6a8e65d8fe7b.jpg)

This link have my results and presets prints: https://imgur.com/a/Tou9jXE

**Comment by nicehashdev** [comment]
The big problem that I see is you are using other tools for overclocking. Reset all to 0 and turn them off. Then let the QuickMiner do it's magic. Your card should go over 40 MH/s with max 110 W. The crash that you get is probably because you limited TDP and there was not enough power for VRAM then so it crashed.

**Comment by alanceloth** [comment]
I will run some test and keep you updated. Thanks for the help!

**Comment by alanceloth** [comment]
I've run some tests here, using the Medium profile with my Alternative OC software with a reseted profile and turned off. The same error has show up.

Also, I've checked with the OC Tune tool, and if i set the settings with 900 delta mem and core clock it's works fine. But when I reset the OC and apply the medium profile the same error show up.

print below:

![erro2](https://user-images.githubusercontent.com/11635850/108923095-f82d2b80-7616-11eb-9350-964a2ed0a052.jpg)
![erro1](https://user-images.githubusercontent.com/11635850/108923094-f6fbfe80-7616-11eb-845f-0a95747d65bd.jpg)

**Comment by alanceloth** [comment]
I will use the Lite Profile for now because it's maintains my eff around 340

**Comment by alanceloth** [comment]
I found something. When I change the TDP High Option, even when the Lite is selected, I've got the same error. But when I choose the Medium, it's works fine.

This option uses some default value? Idk but, maybe the RTX 2060S preset value is not matching the board limit?  

![tdp](https://user-images.githubusercontent.com/11635850/108923901-658d8c00-7618-11eb-9ff4-32f83bf3f3fe.jpg)

**Comment by nicehashdev** [comment]
Shut QuickMiner down completely and turn it on and try Medium now. What happens? Also make sure that you do not have any other overclocks set, TDP MUST BE 100% and core delta must be 0.

**Comment by alanceloth** [comment]
First, I've checked my Alternative OC software, and it was been closed.
Second, I've used the OC Scanner tool for reset to default stock values.
![step 1](https://user-images.githubusercontent.com/11635850/108929019-07fe3d00-7622-11eb-9961-36e745dd68b8.jpg)

Then, I've restarted completely the QuickMiner closing everything and opening again.

After some minutes mining with the Medium profile set, in the Share#16 crashes.
![step2](https://user-images.githubusercontent.com/11635850/108929082-282dfc00-7622-11eb-8754-67e01222d977.jpg)

When it crashes, the miner restart auto, and the Medium preset was set again. After some minutes crashes again.
![step3](https://user-images.githubusercontent.com/11635850/108929178-50b5f600-7622-11eb-9354-f07631e82d74.jpg)

**Comment by nicehashdev** [comment]
I think you have enabled Force P0 for Cuda

Disable that. Otherwise, just use Lite profile.

**Comment by nicehashdev** [comment]
Looks like the issue has been fixed. Closing.

**Comment by alanceloth** [comment]
> I think you have enabled Force P0 for Cuda
> 
> Disable that. Otherwise, just use Lite profile.

How do I disable this? I think I have clicked on this option in the past using the previous NiceHash Miner..

**Comment by nicehashdev** [comment]
There are some tools such as nvidia inspector. If nothing else, a reinstallation of drivers with clean (delete all profiles) should work too I guess.

**Comment by alanceloth** [comment]
I have some news, I set up to log the error and found this:
![image](https://user-images.githubusercontent.com/11635850/109407625-1f5e6280-7961-11eb-9520-3f89326db8f6.png)
![image](https://user-images.githubusercontent.com/11635850/109407632-271e0700-7961-11eb-82ea-2ec50689aa56.png)
[log_2021-02-28_00-56-35.006.log](https://github.com/nicehash/NiceHashQuickMiner/files/6056256/log_2021-02-28_00-56-35.006.log)

The log is attached in the message.


First I've checked if my GPU was in some exclusive computing mode:
![image](https://user-images.githubusercontent.com/11635850/109407585-bd056200-7960-11eb-95cf-ba41e86556a0.png)

nvidia-smi while the miner is off:
![image](https://user-images.githubusercontent.com/11635850/109407653-4d43a700-7961-11eb-9777-2aa2092ccd3c.png)

nvidia-smi while the miner is on:
![image](https://user-images.githubusercontent.com/11635850/109407658-5c2a5980-7961-11eb-8f79-c7dba8573fe5.png)

I'll try the nvidia inspector to check it ou if my GPU is in p0 state.

**Comment by alanceloth** [comment]
Which Performance Level are recommended? It was on P0, and I've clicked on the "Apply Defaults" and "Apply Clocks & Voltage".

![image](https://user-images.githubusercontent.com/11635850/109407806-c263ac00-7962-11eb-8b29-5c1a0a2c571c.png)

Now I'm running the Medium Preset to check it out if I get some error. (actually 5 min running and still no errors)

![image](https://user-images.githubusercontent.com/11635850/109407898-7c5b1800-7963-11eb-96c0-70bd12fb9f26.png)
(but I found my speed and eff a little bit low..)

**Comment by alanceloth** [comment]
Again :(

![image](https://user-images.githubusercontent.com/11635850/109408065-cd1f4080-7964-11eb-8f7f-8592d84090a5.png)
![image](https://user-images.githubusercontent.com/11635850/109408069-d5777b80-7964-11eb-813f-69f5a217b97e.png)
[log_2021-02-28_01-25-58.009.log](https://github.com/nicehash/NiceHashQuickMiner/files/6056267/log_2021-02-28_01-25-58.009.log)

Log attached below.

**Comment by alanceloth** [comment]
Tomorrow I'll do a clean driver reinstall, and reinstall the CUDA package too. Now I'm tired af and can't think clearly. Thx for the help

**Comment by nicehashdev** [comment]
The error you got means that your OC is unstable - memory OC in particular is clocked too high thus being unstable crashing the miner. After each such crash, you need to restart the PC, because driver is unable to make full recovery. If it crashes again after restart, then unfortunately, you just have a bad example and the memory OC is simply too high. At least the one from Optimize preset. You should play on your own using OCTune, setting various memory clocks and see what happens. Also try negative memory delta clock - on some cards, negative memory delta clock actually gives you way more speed (such example is GTX 1660 Super).

**Comment by alanceloth** [comment]
I've found a stable value for a while, I didn't try any negative mem clock yet, but this one is ok for eff and speed I think. (Idk if this speed and eff is good for my GPU, is it?)

Steps that I've done:

1. Apply the Lite optimization on the NiceHash Dashboard
2. Start the NH Quick Miner
3. Start the OCTune, and changed in the Classic Method Overclocking the Mem Clock from 600 to 750.
4. Changed the Temp Target on Fan settings to 55 ºC too (I think that 90 ºC is too high for 24/7)
5. Saved the settings

![image](https://user-images.githubusercontent.com/11635850/109418751-b569ab80-79a8-11eb-9ccd-5d0bcaf37d16.png)

**Comment by nicehashdev** [comment]
You do not have fully utilized memory controller (check, it is 85% only). You should `Core clock limit` to at least 1200 I would say, but probably more, somewhere around 1300.

**Comment by alanceloth** [comment]
![image](https://user-images.githubusercontent.com/11635850/109797391-2a7ef000-7bf8-11eb-9e7d-4dcac3a1c6aa.png)
I've increased my Core clock to almost 1600 and my Memory Controller Load didn't move. 

I've tried 1100, 1200, 1300, 1500, 1605. And the values for the Mem Controller Load was the same (86-87%)

**Comment by nicehashdev** [comment]
You need to do small steps, not so big ones. Test 15 by 15, just like Autotuner does. Then you will find the best clock for that ram freq.

I am closing this issue - considering solved.
